### ISSUE TITLE
Unlock with Passcode

### ISSUE THREAD

**Issue by X-n1nj4** [Vencord/plugin-requests#10]
### Plugin Description

Locks discord with a passcode upon launch/set amount of inactivity

### Existing Plugin for other mod

https://betterdiscord.app/plugin/PasscodeLock

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by lewisakura** [comment]
I do not think plugins that give a false sense of security should be in the mod; the idea of PasscodeLock as an actual lock is misleading at best and dangerous at worst.

> [...]  if anyone has access to the computer with Discord logged in and is actually determined to get access to it, **there's nothing PasscodeLock can do** [...]
