### ISSUE TITLE
Stero plugin 

### ISSUE THREAD

**Issue by mantikafasi** [Vencord/plugin-requests#1000]
### Plugin Description

stero plugin

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
this is why we should take away your computer access until end of time

**Comment by Vendicated** [comment]
bad things will happen tomorrow
