### ISSUE TITLE
Bypass UMG blocks in youtube watch together.

### ISSUE THREAD

**Issue by Aubdaman** [Vencord/plugin-requests#1001]
### Plugin Description

A plugin that bypasses the umg block in discord watch together. (:👍 

### Request Agreement

- [ ] I read the above and made sure my plugin is possible and allowed
- [ ] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
me when
![image](https://github.com/user-attachments/assets/738a25b3-f38c-41a7-99ad-0dcdc135413b)

**Comment by maddie480** [comment]
hey, no box was checked :shrug:
