### ISSUE TITLE
Animated Status

### ISSUE THREAD

**Issue by sHsWeLk** [Vencord/plugin-requests#1002]
### Plugin Description

To prevent the discord server from being spammed with requests, the minimum allowed timeout is hardcoded to be 2.9 seconds.
Logically, the animation timeout should be at least 2900. At best, it should be roughly 10000 milliseconds (10 seconds) for the animation to look smooth on other clients.

### Existing Plugin for other mod

https://github.com/toluschr/BetterDiscord-Animated-Status

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sHsWeLk** [comment]
i use it in discord better for 5 mouth and i don`t have ban

**Comment by sadan4** [comment]
😭

**Comment by Krammeth** [comment]
Deliberately ignoring request guidelines 😔
