### ISSUE TITLE
Personal Pins

### ISSUE THREAD

**Issue by Sharkacuga** [Vencord/plugin-requests#1003]
### Plugin Description

On better discord i had this plugin called personal pins and i used it because i want to remember things like a game came out and it has the link i need to remember or a game code ect it helped me remember things since i have adhd 

### Existing Plugin for other mod

https://github.com/mwittrien/BetterDiscordAddons/tree/8353a951416397a0f39afaaac68c52ce2c9bf72b/Plugins/PersonalPins

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sadan4** [comment]
Me when I lie
![IMG_0953](https://github.com/user-attachments/assets/26d453e0-38e7-4a46-825e-fd702b69a6a9)

**Comment by Krammeth** [comment]
> I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

#75

**Comment by mynameisbob1928** [comment]
Not exactly personal pins but close enough https://discord.com/channels/1015060230222131221/1032200195582197831/1221542573089226802

**Comment by Sharkacuga** [comment]
HA ok brain cells were synced
