### ISSUE TITLE
[BUG] SpotifyControls plugin lacks the ability to see when shuffle state is changed outside of discord app.

### ISSUE THREAD

**Issue by Floyddo** [Vencord/plugin-requests#1006]
### Plugin Description

**Was told to post here by [a mod](https://discord.com/channels/1015060230222131221/1026515880080842772/1270764382250471517)**

### **How to reproduce:**
1. Enable shuffle while playing music on the spotify app (with or without discord started up)
2. Check the spotifycontrols plugin, the icon will not be green 
Spotify: ![image](https://github.com/user-attachments/assets/eeb3c25b-b38b-4327-8dda-6b9b865b3f40)
Discord: 
![image](https://github.com/user-attachments/assets/7ed69af9-98bd-4a7a-8d78-5e10855ef71b)

### **Fix?**
What I think is missing _(don't know exactly how it works, but it's an educated guess)_ is that it's not reading the shuffle value and putting in the store at [SpotifyStore.ts lines 178-188:](https://github.com/Vendicated/Vencord/blob/main/src/plugins/spotifyControls/SpotifyStore.ts#L178C5-L188C11)
```ts
 const store = new SpotifyStore(FluxDispatcher, {
        SPOTIFY_PLAYER_STATE(e: PlayerState) {
            store.track = e.track;
            store.device = e.device ?? null;
            store.isPlaying = e.isPlaying ?? false;
            store.volume = e.volumePercent ?? 0;
            store.repeat = e.actual_repeat || "off";
            store.position = e.position ?? 0;
            store.isSettingPosition = false;
            store.emitChange();
        },
```

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
This is simply an oversight because Discord doesn't have this data at all. But spotify does send it, so we'll need to patch the Spotify websocket event handler to grab the data
