### ISSUE TITLE
owner

### ISSUE THREAD

**Issue by FSFDGF** [Vencord/plugin-requests#1009]
### Plugin Description

make you the srver owner by f4

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
Okay, making this now./s

**Comment by nin0-dev** [comment]
not possible, stop trying to look cool in front of your friends

**Comment by korbosoft** [comment]
an alternative is to close your eyes and hallucinate being owner
