### ISSUE TITLE
Obsidian URIs clickable

### ISSUE THREAD

**Issue by HaipaDev** [Vencord/plugin-requests#101]
### Plugin Description

Hey, was wondering how easy it would be to make obsidian URI links for ex ` obsidian://open?vault=Obsidian%20Vault&file=Untitled ` clickable in Discord? AFAIK they cannot be turned into like markdown links or anything because they are URIs registered by the Desktop (for like shortcut support etc)
I would like to make myself a bot that will be able to send me these links

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by zwinplayer64** [comment]
You can already do that with `<protocol://path>`

**Comment by Divy1211** [comment]
> You can already do that with `<protocol://path>`

For a while now, discord has stopped making links for protocols other than http, https, and discord itself clickable.... `< >` used to work, but it no longer does

**Comment by sadan4** [comment]
this seems too niche
