### ISSUE TITLE
Plugin Request

### ISSUE THREAD

**Issue by yarross** [Vencord/plugin-requests#1011]
### Plugin Description

we need a plugin that will show all members of a specific role such as RoleMembers for BetterDiscord 
![image](https://github.com/user-attachments/assets/1326fec9-ac04-4c3a-b98c-044f3368ddab)

### Existing Plugin for other mod

https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/RoleMembers

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AushevAhmad** [comment]
> I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=sort%3Aupdated-desc+is%3Aissue) and made sure a similar request doesn't already exist

Cap

**Comment by AushevAhmad** [comment]
#493 #359
