### ISSUE TITLE
Custom Ringtone Sound

### ISSUE THREAD

**Issue by ArtemGT69** [Vencord/plugin-requests#1013]
### Plugin Description

Custom Ringtone that allows to change ringtone sound when you get call in discord

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
>     * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

_Lie Sound Effect_
![dupe](https://github.com/user-attachments/assets/07cfc227-a31a-4799-a317-dd6363f4cd47)

**Comment by ArtemGT69** [comment]
> > ```
> > * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist
> > ```
> 
> _Lie Sound Effect_ ![dupe](https://private-user-images.githubusercontent.com/150982280/356327081-07cfc227-a31a-4799-a317-dd6363f4cd47.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzk1NTEsIm5iZiI6MTcyMzEzOTI1MSwicGF0aCI6Ii8xNTA5ODIyODAvMzU2MzI3MDgxLTA3Y2ZjMjI3LWEzMWEtNDc5OS1hMzE3LWRkNjM2M2Y0Y2Q0Ny5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNzQ3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWVjYTc2NzE4ZTA2MWE3NDQzODA0NDU4NzM0ZTU1NWI5YjYwNDFmODYxZjZmMDgwOWE5Zjk3ZjdjY2U0YmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._hmrXEosmRCOQuxqa_TLDZyVPN2IxE2S3GnDS6zwxNk)

I mean custom ringtone not discord ringtone one

**Comment by KrstlSkll69** [comment]
> > > ```
> > > * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist
> > > ```
> > 
> > 
> > _Lie Sound Effect_ ![dupe](https://private-user-images.githubusercontent.com/150982280/356327081-07cfc227-a31a-4799-a317-dd6363f4cd47.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzk1NTEsIm5iZiI6MTcyMzEzOTI1MSwicGF0aCI6Ii8xNTA5ODIyODAvMzU2MzI3MDgxLTA3Y2ZjMjI3LWEzMWEtNDc5OS1hMzE3LWRkNjM2M2Y0Y2Q0Ny5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNzQ3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWVjYTc2NzE4ZTA2MWE3NDQzODA0NDU4NzM0ZTU1NWI5YjYwNDFmODYxZjZmMDgwOWE5Zjk3ZjdjY2U0YmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._hmrXEosmRCOQuxqa_TLDZyVPN2IxE2S3GnDS6zwxNk)
> 
> I mean custom ringtone not discord ringtone one

Bruh... thats what those other requests are also asking for

**Comment by ArtemGT69** [comment]
oh sorry i just completely misunderstood
