### ISSUE TITLE
Add OpenAsar settings similar to the Vencord settings

### ISSUE THREAD

**Issue by Julienraptor02** [Vencord/plugin-requests#1017]
### Plugin Description

Currently OpenAsar settings can only be open by clicking this text
![image](https://github.com/user-attachments/assets/39284f81-5906-40c8-a069-37b778f341a1)
However by doing so, it will also copy stuff into your clipboard
It's also not easy to find for a newcomer
The idea would be to make it appear like Vencord
![image](https://github.com/user-attachments/assets/ae205b67-161e-4632-855d-e355f5d66cc4)
If it had integration to open the settings like Vencord or Discord settings, it would be nice, but if it just open the OpenAsar config popup it's nice and would alr be better than the current situation

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Julienraptor02** [comment]
> OpenAsar is a completely different project unrelated to Vencord.

I know indeed, however as Vencord offer the option to install OpenAsar in its installer, i think it could make sense

**Comment by KrstlSkll69** [comment]
Also it already does _U might have to reinstall openasar with the installer but that normal with it_
![OpenAsar](https://cdn.nest.rip/uploads/7c41c7bb-5fd6-45de-ba66-5cbbb9aa0ce3.PNG)

**Comment by Julienraptor02** [comment]
> Also it already does _U might have to reinstall openasar with the installer but that normal with it_ ![OpenAsar](https://camo.githubusercontent.com/cfc7c653fe400c8a96a6ea1956f66a89840aee312a1c49e906fe9ad22ba97b33/68747470733a2f2f63646e2e6e6573742e7269702f75706c6f6164732f37633431633762622d356664362d343564652d626136362d3563626262396161306365332e504e47)

i've tried reinstalling openasar in multiple ways, with / without vencord and there isn't any menu
i believe that what you see is implemented by your theme / custom css
i'm interested to know what theme / custom css you use, i'll probably be able to grab that feature from it

**Comment by KrstlSkll69** [comment]
> i've tried reinstalling openasar in multiple ways, with / without vencord and there isn't any menu i believe that what you see is implemented by your theme / custom css i'm interested to know what theme / custom css you use, i'll probably be able to grab that feature from it

i don't use CSS other then stuff i created which can found on my GitHub
_tldr; they only recolor icons_

**Comment by KrstlSkll69** [comment]
wait

**Comment by KrstlSkll69** [comment]
yea im not crazy, it does that already

![Asar](https://cdn.nest.rip/uploads/fb723350-7bb4-433e-b6b0-0f5a52124f1a.PNG)
![imnotcrazy](https://cdn.nest.rip/uploads/80aae076-c4c2-4ffe-9c74-f6a550ad6ea0.PNG)

**Comment by Julienraptor02** [comment]
> yea im not crazy, it does that already
> 
> ![Asar](https://camo.githubusercontent.com/7ed62fa3e1fd38617e921279e1be103d45856808151ac4f494cefa24dee1f669/68747470733a2f2f63646e2e6e6573742e7269702f75706c6f6164732f66623732333335302d376262342d343333652d623662302d3066356135323132346631612e504e47) ![imnotcrazy](https://camo.githubusercontent.com/faf71fe495659680cd66ad6c83c132ac7bb6d08a85f5a3f7e44a88a9e9bf87a8/68747470733a2f2f63646e2e6e6573742e7269702f75706c6f6164732f38306161653037362d633463322d346666652d396337342d6636613535306164366561302e504e47)

i swear i'm never getting that
and i know why
it's made in a bad way rn and only appear when using en us...
i guess i'm making an issue in the openasar repo instead
