### ISSUE TITLE
Follow text channel plugin

### ISSUE THREAD

**Issue by yp-coding** [Vencord/plugin-requests#1023]
### Plugin Description

I making a Discord server for a study purpose, is it possible to add a plugin that sends all messages through a webhook? ( What I wanted to do originally was send all AP study server messages from #daily questions channel to my server )

### Request Agreement

- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I read the above and made sure my plugin is possible and allowed
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
Prolly possible with selfbotting, but thats not allowed
![Capture](https://github.com/user-attachments/assets/880147cf-2fa2-46cd-85a0-9d191fe58e3e)
![Capture](https://github.com/user-attachments/assets/e1cf9858-58d4-414a-a146-344157064872)

**Comment by yp-coding** [comment]
Thanks for support!

**Comment by Vendicated** [comment]
can be done easily but it won't work while Discord isn't running which limits use and really it's just too niche

you're better off asking the server owner to turn it into an announcement channel, or making a selfbot outside of vencord that mirrors all messages
