### ISSUE TITLE
toggle default keybinds

### ISSUE THREAD

**Issue by epaluy** [Vencord/plugin-requests#1024]
### Plugin Description

a plugin to toggle default keybinds
![image](https://github.com/user-attachments/assets/de308dfd-90c2-4723-ba2e-28f4186e615b)

game overlays section "toggle overlay lock"
instead of putting a bunch of random buttons so that i don't accidently press it, it's better if i was able to disable it
![image](https://github.com/user-attachments/assets/1426e79d-8ab7-443b-8f79-a1f5a783c323)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
you can already do this by adding a new keybind with the key combo you want to disable and no action
