### ISSUE TITLE
E2E Encryption End-To-End Message Encryption

### ISSUE THREAD

**Issue by multicody10** [Vencord/plugin-requests#1025]
### Plugin Description

Opening a similar request for this as #919 for E2E PGP was rejected and locked without ability to discuss or thumbs up. I disagree with the decision and know many people who would enjoy this feature if added.
DiscordCrypt, for betterdiscord, used AES-256 and Camellia-256 encryption with public/private keys and keyring to encode/decrypt messages, then sent the encoded message. It automatically decrypted encrypted messages if you had the public key for them.
It saw who else used the plugin and sent a public key request to the other person which they could accept.[^1]
It is not stenography like the current InvisibleChat plugin which still requires some way of the other person getting the password.

[^1]: Might fall under selfbot.

### Existing Plugin for other mod

https://github.com/leogx9r/DiscordCrypt/

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
this will never be added as said multiple times by vee. if you want an encrypted messenger, don't use discord
