### ISSUE TITLE
Sound that plays whenever someone turns on their webcam

### ISSUE THREAD

**Issue by MarOnic12345** [Vencord/plugin-requests#1026]
### Plugin Description

Similar to when someone starts streaming, I would like to know when someone turns on their webcam via a sound notification.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by redbaron2k7** [comment]
Love this idea, made it here: https://github.com/redbaron2k7/videoStartNotifier

**Comment by MarOnic12345** [comment]
Works great. Thank you so much!

**Comment by KrstlSkll69** [comment]
bro just got token stolen
