### ISSUE TITLE
Plugin Request

### ISSUE THREAD

**Issue by MANGNAN1** [Vencord/plugin-requests#1028]
### Plugin Description

It would be nice if there was a plugin that allows me to set a desired nickname and have it displayed as that nickname.

For example, if a person with the nickname 'Jake' sets their nickname to 'Zake,' then this person will appear as 'Zake' on my computer from now on.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
> I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

me when I lie
#102 #384 #389 #476 #597 #609 #719

**Comment by mynameisbob1928** [comment]
Also this already exists in the form of friend nicknames, it requires you to be friended to that person but it does what you want ( i think so anyway)
