### ISSUE TITLE
autosuggestion like in zsh

### ISSUE THREAD

**Issue by moonfight1** [Vencord/plugin-requests#1029]
### Plugin Description

you know the [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) plugin? that but for discord

as you are typing, it auto suggests words/sentences that you commonly type, and you can click a keybind to accept the suggestion

customization may include:
- the keybind to accept a suggestion
- manually adding words to the list

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
this is better done on an OS level. I'm sure there are apps for it
