### ISSUE TITLE
LaTeX Renderer 

### ISSUE THREAD

**Issue by Mathias-L456** [Vencord/plugin-requests#103]
### Plugin Description

plugin that can render LaTeX equation with MathJax like this plugin for better discord (see the link below).

https://github.com/BinaryQuantumSoul/discord-latex

### Existing Plugin for other mod

https://github.com/BinaryQuantumSoul/discord-latex

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Kyuuhachi** [comment]
Sounds fun, will make this. Requires CSP mitigation, so desktop only.

**Comment by Kyuuhachi** [comment]
Forgot to report back — got the plugin working: [link](https://github.com/Kyuuhachi/VencordPlugins/tree/main/TeX). Might try to get it upstreamed later, but it's not a priority.

**Comment by Mathias-L456** [comment]
ok ok cool and np

**Comment by supern64** [comment]
Will this ever be upstreamed? This would be quite useful not having to rely on a bot like TeXiT

**Comment by Vendicated** [comment]
no. use a bot

**Comment by Feathers8** [comment]
Seems like it got rejected because it can be done with a user app.

**Comment by Mathias-L456** [comment]
sad

**Comment by row454** [comment]
bots don't work in dms, which is where most of my maths conversations happen

**Comment by Vendicated** [comment]
false. you can install bots that support it to your account and use them anywhere
