### ISSUE TITLE
Raise GC limit

### ISSUE THREAD

**Issue by MattLee100** [Vencord/plugin-requests#1031]
### Plugin Description

Way to raise group limit
https://www.reddit.com/r/discordapp/comments/as4ddj/my_friends_and_i_managed_to_get_15_members_in_a/
this (admittedly) old post showed how simple it was to raise a group chat limit, so I was wondering if there was an easy way to do that via vencord plugins? Groups seem to be client side (?)

![image](https://github.com/user-attachments/assets/99890b38-7283-4fda-9545-7e8c82e2ef35)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
Not Possible GC limit is server side on discord
