### ISSUE TITLE
Role filter

### ISSUE THREAD

**Issue by Kollixer** [Vencord/plugin-requests#1032]
### Plugin Description

Role Filter: shows anyone who has this role in the server

### Existing Plugin for other mod

Not really

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
> I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

me when I lie
#213 #359 #615 #770 #885 #1011
