### ISSUE TITLE
always online

### ISSUE THREAD

**Issue by midiatico** [Vencord/plugin-requests#1035]
### Plugin Description

After a certain amount of time without using discord, the online status (green) automatically changes to away (yellow), I would like there to be a plugin that always leaves the profile online (green).
![status](https://github.com/user-attachments/assets/c731308d-a56a-4b52-ba54-5019ed49c999)

### Existing Plugin for other mod

Vencord has a similar plugin for calls called DisableCallIdle, but I wanted this one for status

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by skullriot** [comment]
https://vencord.dev/plugins/CustomIdle

#199, #316
