### ISSUE TITLE
Nitro reactions

### ISSUE THREAD

**Issue by doejohn126** [Vencord/plugin-requests#1036]
### Plugin Description

I know it said "Nitro features not already provided by [FakeNitro](https://vencord.dev/plugins/FakeNitro) or other existing plugins (e.g. free animated pfp, higher upload limit)"  but maybe if there was a way could u make it so you could react using nitro emojis?

### Existing Plugin for other mod

https://vencord.dev/plugins/FakeNitro

### Request Agreement

- [ ] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
not possible reactions are server side
