### ISSUE TITLE
Reload Commands

### ISSUE THREAD

**Issue by CoasterFreakDE** [Vencord/plugin-requests#1038]
### Plugin Description

I would love to see a simple refresh button in the `/` command popup, that refreshes your commands without the need of restarting your whole discord client.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Masterjoona** [comment]
#879

**Comment by CoasterFreakDE** [comment]
@Masterjoona Whops. Didn't get that when searching. Thanks for linking it. I guess I need to implement it myself. :/
