### ISSUE TITLE
Bulk delete user's messages from a whole server

### ISSUE THREAD

**Issue by notKnownn** [Vencord/plugin-requests#1039]
### Plugin Description

a plugin to delete all messages that the user sent in a server, allowing him to decide if deleting just from a channel, or the whole server. To bypass discord's ratelimit its possible to set a delay between message deletion (also warn the user to not do anything on discord when the deletion process is in progress).

### Existing Plugin for other mod

it's not a plugin for a mod but it's a script that does the same thing: https://github.com/victornpb/undiscord

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
This kind of thing would be better done with a bot

**Comment by sunnniee** [comment]
blatant selfbotting
