### ISSUE TITLE
A plugin blocks you from sending messages with certain words

### ISSUE THREAD

**Issue by RoseHobgoblin** [Vencord/plugin-requests#104]
### Plugin Description

I'm trying to quit saying the F-word, and I think a plugin that prevents messages being send with whatever words the user sets would be helpful.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by exhq** [comment]
you fucking stupid imbecile, you can fucking do that shit using fucking textreplace. please fucking educate yourself. /j
