### ISSUE TITLE
Speech bubble maker

### ISSUE THREAD

**Issue by lephiz69** [Vencord/plugin-requests#1040]
### Plugin Description

Sort of like the petpet but instead add a speech bubble on the top of the attached photo
discord mod EsmBot already has this, but in-built would be better

### Existing Plugin for other mod

https://discord.com/application-directory/429305856241172480

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
if it can be done with a userapp it won't be added, patpat only exists because it was made before userapps

**Comment by Sqaaakoi** [comment]
esmBot as a plugin isn't a bad idea on its own; though I doubt it will be implemented due to the amount of things it implements. The userapp works fine
