### ISSUE TITLE
Font overwrite or fallback

### ISSUE THREAD

**Issue by YAR-Oracool** [Vencord/plugin-requests#1042]
![Screenshot_20240815_132451](https://github.com/user-attachments/assets/c5d02d8d-b605-4f57-9156-d2bffe035f55)
### Plugin Description

So have been on some discords that use custom fonts for their channel names, but the problem is that I'm on Linux and I don't have those fonts, so I just see squares.

I would like a plugin that overwrites certain fonts or all fonts in the interface. Or use a different font if the used font isn't present by force to bypass this issue.

### Existing Plugin for other mod

NA

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
1. css
2. just install more fonts to ur system
