### ISSUE TITLE
FriendNotifications plugin

### ISSUE THREAD

**Issue by ExileWind** [Vencord/plugin-requests#1044]
### Plugin Description

this is soo good https://betterdiscord.app/plugin/FriendNotifications

### Existing Plugin for other mod

https://betterdiscord.app/plugin/FriendNotifications

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Stasai** [comment]
#12
