### ISSUE TITLE
Feature Request: Integrate SponsorBlock with YouTubeAdblock plugin

### ISSUE THREAD

**Issue by madman38** [Vencord/plugin-requests#1045]
### Plugin Description

Could you integrate SponsorBlock into the YouTubeAdblock plugin? This feature would significantly enhance the user experience by allowing us to skip sponsored segments and more. SponsorBlock should work on both embeds and WatchTogether.

note: i searched the existing issues and i found this https://github.com/Vencord/plugin-requests/issues/675#issue-2337103172 but I believe extending the functionality to include embedded videos as well would be better.

Thank you!

message for mods: I accidentally clicked the close issue button on my previous issue - sorry guys. (here is the previous issue https://github.com/Vencord/plugin-requests/issues/1043) Can you please delete that?

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nekohaxx** [comment]
[YouTube.com](https://youtube.com)

**Comment by Vendicated** [comment]
you can just comment on the existing issue
