### ISSUE TITLE
Account-token Switcher/manager

### ISSUE THREAD

**Issue by Yasodzc9** [Vencord/plugin-requests#1049]
### Plugin Description

Tokens manager, allowing users to get their account tokens instantly and login with tokens and having alot of accounts without logging in one by one when they randomly logout and to not be limited by the number of accounts we can save + to avoid email verifications too
note (its not multi requests this old plugin had all of this)

### Existing Plugin for other mod

https://github.com/aarondoet/AccountSwitcher

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
I cannot think of a single ethical reason to have this

**Comment by KrystalSkullOfficial** [comment]
> I cannot think of a single ethical reason to have this

Because there isnt one

**Comment by Sqaaakoi** [comment]
Also, Heads up; It was already decided that a >5 account switcher plugin is not going to be added.

> I do not see the need for anyone to have >5 accounts in a single client, let alone own >5 accounts in general (except for plurality), and encouraging collectors with this sort of plugin means less usernames that people would like to use; genuinely good pomelo usernames have already been sniped and they will never get used or they will be resold for extortionate prices. I'm not sure if this is a good idea to put in the mod.

https://github.com/Vendicated/Vencord/pull/1353#issuecomment-1609889322

Regarding token login, there are legitimate use-cases but most of the time it's either stolen account tokens or bot tokens (which there are dedicated tools for dealing with these).

My thoughts? If anyone wants to improve the (multi) account login experience, add the QR login everywhere, such as the account switcher and to the mobile web login page. This gets rid of the "email verification" problem whilst not blatantly supporting stolen accounts or username squatting.

**Comment by KrystalSkullOfficial** [comment]
> ...add the QR login everywhere...

This Already Exists
https://canary.discord.com/channels/1015060230222131221/1264697709432934526

**Comment by Sqaaakoi** [comment]
> > ...add the QR login everywhere...
> 
> This Already Exists https://canary.discord.com/channels/1015060230222131221/1264697709432934526

Literally no. This just lets you scan QR codes, it doesn't inject QR codes to the add account or mobile web login page.

**Comment by Vendicated** [comment]
no
