### ISSUE TITLE
Friend nickname show in servers

### ISSUE THREAD

**Issue by TAKOMAN1** [Vencord/plugin-requests#1050]
### Plugin Description

For some reason, the "friend nickname" feature doesn't show the nickname you made for your friend in servers. It only shows you it in the DMs section.

Just make a plugin that fixes this issue and you can view the friend nickname anywhere.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
can be solved by EditUsers plugin so I'll be closing this in favour of that request
