### ISSUE TITLE
Command to generate server invite link

### ISSUE THREAD

**Issue by MR-SALEH1** [Vencord/plugin-requests#1051]
### Plugin Description

Basically a command like /invite and when you type the command it will populate/autofill with a list of servers then you can select one, and it will send an invite to that server. This will make it more convenient to invite someone to a server without having to dig through many of your servers

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrystalSkullOfficial** [comment]
Me when clicking a single button

![InviteButton](https://cdn.nest.rip/uploads/be3e469c-1dd3-406f-9ac6-73865b83da3b.png)
