### ISSUE TITLE
A plugin that allows you to connect more than 5 accounts at the same time

### ISSUE THREAD

**Issue by shalevc1098** [Vencord/plugin-requests#1052]
### Plugin Description

I would like to login with more than 5 accounts at the same time. Is there any plugin that can increate the limit or completely disable it? thanks

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
#80 #742 #35
