### ISSUE TITLE
An Animated Status for better communication (professional or other)

### ISSUE THREAD

**Issue by g0shtj0sh** [Vencord/plugin-requests#1054]
### Plugin Description

The purpose of the plugin would be to be able to set different statuses that change every 30 seconds, for example, but you can change it to 5s, 10s, 20s, etc...
This plugin could allow you to set different statuses that change and not just have 1 single status where you're limited.

### Existing Plugin for other mod

https://github.com/toluschr/BetterDiscord-Animated-Status

### Request Agreement

- [ ] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Kyuuhachi** [comment]
> I read the above and made sure my plugin is possible and allowed
![image](https://github.com/user-attachments/assets/03abdba0-218a-4322-8ecf-d84ca50e32ef)

**Comment by g0shtj0sh** [comment]
opps sry
