### ISSUE TITLE
Advanced Discord Lock System

### ISSUE THREAD

**Issue by Rotxeein** [Vencord/plugin-requests#1056]
### Plugin Description

**I want a special button called "Discord Lock" to come to Discord. I want discord to be unusable when this button is clicked. I want the password panel to appear on the screen. I want Discord to be active again if the password that the user has previously determined is entered into this password panel.**

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
https://github.com/Vencord/plugin-requests/issues/968 https://github.com/Vencord/plugin-requests/issues/602 https://github.com/Vencord/plugin-requests/issues/375 https://github.com/Vencord/plugin-requests/issues/360 https://github.com/Vencord/plugin-requests/issues/245 https://github.com/Vencord/plugin-requests/issues/211 https://github.com/Vencord/plugin-requests/issues/54 https://github.com/Vencord/plugin-requests/issues/10

blatant dupe.
![image](https://github.com/user-attachments/assets/0fb64880-2daf-4cbc-9cbc-3677f055cb0a)
