### ISSUE TITLE
Set the target language for the translation plugin.

### ISSUE THREAD

**Issue by koi646** [Vencord/plugin-requests#1058]
### Plugin Description

The translation plugin looks pretty good, but after setting it up, it doesn't seem to work properly. Can I set the target language for the translation results?
English -> English...
![image](https://github.com/user-attachments/assets/56971c8b-6eed-43d3-9099-0281403d6775)

### Existing Plugin for other mod

https://vencord.dev/plugins/Translate

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Stasai** [comment]
Already is possible, open the Translate modal in the chat bar to adjust the language for received messages to be translated to.

![image](https://github.com/user-attachments/assets/ebde8e13-224f-43f0-a8c3-a33d468b41f0)

**Comment by koi646** [comment]
Sorry, newcomer. could you be more specific? I couldn't find where the option button is...

**Comment by rozbrajaczpoziomow** [comment]
Hop onto the [vencord-support](https://discord.com/channels/1015060230222131221/1026515880080842772) channel in the vencord discord server if you want to get support
