### ISSUE TITLE
Always view as role

### ISSUE THREAD

**Issue by jamesbt365** [Vencord/plugin-requests#1061]
### Plugin Description

A plugin for perpetually previewing a server as a role(s) that automatically is applied on startup and doesn't have a gross banner at the top of your screen.

Bonus points if it also respects the allowed mentions of those roles which the stock client does not. Being picky now but if previewing as a user and or disabling the user permission overwrites additionally becomes a thing (currently, its just *you* with only the roles you selected, meaning that you can access channels you have permission overwrites too)

Generally just useful for server owners that are absolutely forced to be have Administrator and would rather go around not having to worry about moving channels accidentally, or playing events that revolve around channel permissions without breaking the flow.

I'm not sure if this is API locked as I have not tested what my client sends but would unlocking this to users regardless of permissions on a server also be viable, I'm aware that it doesn't let you read channel messages, but without Administrator, you currently cannot preview as role.

I apologise if this is not possible or a duplicate, but this may be too niche?

Discord FAQ for anybody who forgot this was a feature: https://support.discord.com/hc/en-us/articles/360055709773-View-as-Role-FAQ

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
this is way too niche and just generally not very useful

if you're worried about
- moving channels: disable "show all channels" and discord will disable drag and drop
- misclicking ui elements: hide them with css and disable the css when you do need to click them
