### ISSUE TITLE
Download media from links

### ISSUE THREAD

**Issue by FoxFil** [Vencord/plugin-requests#1070]
### Plugin Description

The plugin will allow users to download media by tapping on a "download" button when hovering on the link. The download process will happen using [cobalt.tools](https://cobalt.tools) API.

[cobalt.tools github →](https://github.com/imputnet/cobalt)

Supported services:
• bilibili.com & bilibili.tv
• dailymotion videos
• facebook videos
• instagram posts & reels
• loom videos
• ok video
• pinterest (all media)
• reddit videos & gifs
• rutube videos
• snapchat stories & spotlights
• soundcloud
• streamable.com
• tiktok videos, photos & audio
• tumblr video & audio
• twitch clips
• twitter videos & voice
• vimeo
• vine archive
• vk video & clips
• youtube videos, shorts & music

**If this gets accepted, I would like to work on this plugin myself, thanks.**

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
use a bot or manually visit the website
