### ISSUE TITLE
Bedtime reminders

### ISSUE THREAD

**Issue by FoxFil** [Vencord/plugin-requests#1071]
### Plugin Description

The plugin will create a pop-up with something like “It’s bedtime!” and 2 buttons:
- Remind me later (in 10 mins for example)
- Dismiss (the reminder will disappear until the next day)

The bedtime and “remind me later” time are customizable. 

If this gets accepted, I’d like to create the plugin myself, thanks. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
> If this gets accepted, I’d like to create the plugin myself, thanks.

yk you can just make it and use it as a third party plugin whether this is added or not.

**Comment by FoxFil** [comment]
> yk you can just make it and use it as a third party plugin whether this is added or not.

I know, it just says this in CONTRIBUTING.md "If there isn't an existing request, open one yourself and include that you'd like to work on this yourself." So I thought I better include this haha 😁

**Comment by Vendicated** [comment]
use an external app 😭 we don't need DiscordOS
