### ISSUE TITLE
top 3 discord plugins 

### ISSUE THREAD

**Issue by Cynaare** [Vencord/plugin-requests#1077]
### ****Vencord Users and officials****

Hello my dear friends today I want to touch on a very nice topic I think you will all like it, as you know deleting messages on discord is really troublesome or finding a dm you have closed is the same I can say I thought of a solution for this First of all if we touch on the subject of deleting messages there is a Chrome web store extension that I actively use but I can say it would be better if it was in Vencord, the name of the extension is "Discrub" you can find it by searching for it YouTube video is "Delete ALL Your Own DMs In Discord" you can find this video by searching on YouTube this extension does the following for you like undiscord you can delete your dms without getting stuck you can download them (html, json, csv or media only) it is also valid on servers you can do most things 1. This was the plugin I wanted to add and I have been using it for years I have never had any problems with my discord account 2. As for my plugin suggestion just think about it you have closed your dm with an old friend and your friend changed his username you do not have his user id or you are not a shared server with this friend It makes it impossible to reopen your dm. Let's say you only remember your friend's username. Other than that, you don't have the shared server or user id. In this case, I thought like this. We can write your friend's username in the Discord add friend section. Yes, that's true, but the more friends you add in succession, Discord times out this after a while and this can be a problem. There can be an additional dm search section for this. I mean, it's like adding your friend's username on Discord, but instead of sending a friend request, you can only see your friend's profile. I think this would be very useful for everyone, wouldn't it? Finally, let's come to my 3rd suggestion. As I mentioned at the beginning, if the 1st plugin is added, I will say something you can code yourself. There is a mass message deletion section in undiscord, but I don't think it works very well. When I did some research, most people said they got an error, but the way it works is as follows: You open discord in your browser. You open undiscord from the top right and there is a wipe archive section. From there, you open the data you downloaded from discord's settings, that is, the data you requested. And in your discord data package, there will be a file called index.js at the bottom of the messages folder. This contains the current usernames of the people you've talked to so far (if your data package is up to date). When you put this index file in undiscord's wipe archive section, it should delete all the messages in bulk. The dms of everyone you've talked to so far (this may take a few days, I'm talking about deleting messages, but I think it's very useful). I don't know how correctly I explained it, but I think everyone will love these 3 plugins I've explained. If you like it, valuable vencord officials and users, I'd be very happy if you support my message and leave an emoji. I wish you a good day. -Rath Hiroshi

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by PoolloverNathan** [comment]
one plugin per post, also please be more direct

**Comment by Cynaare** [comment]
> one plugin per post, also please be more direct

I'm sorry, but I wrote it like this because they almost all look alike :(

**Comment by PoolloverNathan** [comment]
> > one plugin per post, also please be more direct
> 
> I'm sorry, but I wrote it like this because they almost all look alike :(

that's the point

**Comment by Cynaare** [comment]
> > > one plugin per post, also please be more direct
> > 
> > 
> > I'm sorry, but I wrote it like this because they almost all look alike :(
> 
> that's the point

If it is done, it can all be done in a single plugin, but it is a bit detailed.
