### ISSUE TITLE
PLugin

### ISSUE THREAD

**Issue by kapiokarpii11** [Vencord/plugin-requests#1078]
### Plugin Description

make a plugin that will play different notification sounds, for example, channel notifications will have one sound and notifications from the user will have a different sound

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by schoeneBiene** [comment]
https://github.com/Vencord/plugin-requests/issues/575
https://github.com/Vencord/plugin-requests/issues/507
https://github.com/Vencord/plugin-requests/issues/374
https://github.com/Vencord/plugin-requests/issues/407
https://github.com/Vencord/plugin-requests/issues/83
https://github.com/Vencord/plugin-requests/issues/21
https://github.com/Vencord/plugin-requests/issues/1022
https://github.com/Vencord/plugin-requests/issues/1013
https://github.com/Vencord/plugin-requests/issues/997
https://github.com/Vencord/plugin-requests/issues/944
https://github.com/Vencord/plugin-requests/issues/849
https://github.com/Vencord/plugin-requests/issues/832
https://github.com/Vencord/plugin-requests/issues/764
https://github.com/Vencord/plugin-requests/issues/783
