### ISSUE TITLE
3rd party service image/video upload option

### ISSUE THREAD

**Issue by reecebunny** [Vencord/plugin-requests#1080]
### Plugin Description

It would be wonderful if there was a plugin that added an option to discords file upload button (The '+' icon next to the message box) that allows you to easily upload a image/video to a 3rd party service (imgur, streamable, ect) and automatically send it as a link with an embed to watch/view the uploaded image/video. 

This would allow for sending short videos like video game clips to your friends that exceed discord's file size limit

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
Third party plugin btw https://ptb.discord.com/channels/1015060230222131221/1272186590214619281
