### ISSUE TITLE
please add elapsed time for lastfm rich presence

### ISSUE THREAD

**Issue by Soyjak99** [Vencord/plugin-requests#1081]
### Plugin Description

Last fm rich presence is my most used plugin with vencord, I just wanna request a feature of adding elapsed time to it. i think it would be possible adding elapsed time whenever a song changed/started. it would be perfect!

thank you for this plugin such a blessing :)

### Existing Plugin for other mod

https://github.com/Vendicated/Vencord/blob/main/src/plugins/lastfm/index.tsx

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
not possible because lastfm doesn't provide or even have this information
