### ISSUE TITLE
unhide channels

### ISSUE THREAD

**Issue by basicallybored** [Vencord/plugin-requests#1083]
### Plugin Description

this could be an extra feature in showhiddenchannels or another plugin entirely.

when new channels are created, they are hidden by default and you have to show them through "channels & roles" (i think thats how it works, idk)

i am requesting for a new plugin or a showhiddenchannels update to make discord show said hidden channels

### Existing Plugin for other mod

https://github.com/Vendicated/Vencord/tree/main/src/plugins/showHiddenChannels

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
Me when show all channels

**Comment by Scyye** [comment]
![image](https://github.com/user-attachments/assets/60a5d92e-6e5b-4c8e-a40a-db23e656b24d)

**Comment by basicallybored** [comment]
never noticed the show all channels toggle lmao, still think it would be a good plugin

**Comment by Scyye** [comment]
> never noticed the show all channels toggle lmao, still think it would be a good plugin or update

what??
