### ISSUE TITLE
a plugin similar to xsoverlay notifications

### ISSUE THREAD

**Issue by V0idKing** [Vencord/plugin-requests#1088]
### Plugin Description

Well, I really wanted compatibility with the xs overlay plugin, because I use the vr toolkit, and I simply miss not seeing notifications from discord.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
dupe i think https://github.com/Vencord/plugin-requests/issues/551
