### ISSUE TITLE
Open mic/mic always on/continuous transmission

### ISSUE THREAD

**Issue by Lernos** [Vencord/plugin-requests#1089]
### Plugin Description

I would like to have an option for open mic, if at all possible. That's what I'd been using with my friends all the time on Teamspeak before Discord started dominating the scene. It's simply an option to always transmit everything your mic is picking up, no decibel gate, no push-to-talk.

Reasons why automatic voice activation doesn't work for me: it works poorly. Even when set to lowest sensitivity, it can chop up your transmission (mute random parts of it), and it's terrible for sending audio/soundboarding externally.

Reasons why push-to-talk doesn't work for me: well, I don't want to hold a key all the time. I did jury rig an external solution: wrote an AHK script that utilizes an "unused" function key F13 and keeps it held or releases it by clicking on buttons in a script-generated GUI window. But a) it's annoying to always have to remember to launch that script and rely on an external solution, and b) several games I often play with my friends do something that causes all pressed keys to release on startup, and my mic turns off. I don't remember/notice it every time, and then it turns out mid-session that I've been silent all the time, and my friends saw nothing out of the ordinary in it. And it's annoying to go turn it back on every time.

Is there a way to perhaps trick Discord into thinking you're using push-to-talk and your mic is on, but without any key being actually held down?

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
not so sure if this will actually be made, however in the mean time, I'd recommend turning off all the audio processing options to stop it being cut out

**Comment by Vendicated** [comment]
this makes no sense. just disable push to talk and if part of your sound is being filtered out disable noise suppression / krisp
