### ISSUE TITLE
Deyapiffier

### ISSUE THREAD

**Issue by froginalog** [Vencord/plugin-requests#1090]
### Plugin Description

This is a plugin that adds a cap to messages, if the user sends more than 10 messages a minute, the extra messages will be auto deleted. https://github.com/froginalog/deyappifier/tree/main

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
***what***

**Comment by Sqaaakoi** [comment]
This is your own plugin, you can make a PR for this.

**Comment by Scyye** [comment]
what is the point of this though

**Comment by Scyye** [comment]
Whats the point of this though?
if anything, https://discord.com/channels/1015060230222131221/1206953288537210890
