### ISSUE TITLE
Copy the name of the channels and categories

### ISSUE THREAD

**Issue by yTheuUuzX** [Vencord/plugin-requests#1091]
### Plugin Description

Create a plugin where you can copy the names of channels and categories, whether they are private or public. I press **`Alt + Left Button`** and the name of the channel/category is in the clipboard. Sometimes I want to “clone” a server, and this plugin would help, not only in this case, but it could help with several things. Please think about it!

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by jamesbt365** [comment]
Seems niche and can technically be done (though the UX is worse) with ViewRaw.

**Comment by mynameisbob1928** [comment]
There are bots that can clone servers such as xenon, they do require you to have administrator on that server though

**Comment by Vendicated** [comment]
ViewRaw
