### ISSUE TITLE
Easy to use status

### ISSUE THREAD

**Issue by Beelijah** [Vencord/plugin-requests#1092]
### Plugin Description

Look at your discord right now, lets say you wanted to change your status for some reason.
Of course, you head to the bottom left where it usually is, and click on your profile.
yeah its not there anymore
basically, you guys should add a plugin where it changes the location for the change status button from the profile editor, back to where it originally was, under "Edit Profile".
![brororor](https://github.com/user-attachments/assets/1778ed11-c372-425c-a76b-908a43dbbd38)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Beelijah** [comment]
wait sorry for sending another but heres a better screenshot that's more clear
![brobrorborb](https://github.com/user-attachments/assets/8bee43e1-0433-43d5-9432-48973c815bcc)

**Comment by Scyye** [comment]
Its just a slight move, imo ya should just try to get used to it.

seems a little niche for a plugin :shrug:

**Comment by Kyuuhachi** [comment]
You mean maybe put an edit button around here? ![image](https://github.com/user-attachments/assets/7ca35347-80d6-4ad5-80ec-70856cd656a6)
