### ISSUE TITLE
Local Friend Nickname like feature for Server names

### ISSUE THREAD

**Issue by PeaceDevWasTaken** [Vencord/plugin-requests#1095]
### Plugin Description

This plugin lets users locally rename servers similar to Discord's friend nicknames feature by using the existing friend nicknames feature as a base for the server one. That way, changing obscure server names (i.e., ones using unicodes) can be found easier, (if this isn't possible it's not a deal breaker) and names for servers can be censored if someone is on a server they don't want to be shown for any kind of reason; they'd want to hide a server's name, and allowing people to organize and customize their server list however they like it just that little bit better.

it also just sounds like something discord would natively add

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
> I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

me when I lie
#102 #384 #389 #476 #597 #609 #719 #1028 #1050
