### ISSUE TITLE
let us have a custom discord notification sound pls

### ISSUE THREAD

**Issue by hashimm2345** [Vencord/plugin-requests#1096]
### Plugin Description

a custom discord notification sound

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
>     * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

me when i lie
![custom discord notification sound](https://cdn.nest.rip/uploads/bb0db1a8-7b33-4cb6-895e-a3e98ab21773.JPG)

**Comment by nin0-dev** [comment]
https://github.com/Vencord/plugin-requests/issues/575
https://github.com/Vencord/plugin-requests/issues/507
https://github.com/Vencord/plugin-requests/issues/374
https://github.com/Vencord/plugin-requests/issues/407
https://github.com/Vencord/plugin-requests/issues/83
https://github.com/Vencord/plugin-requests/issues/21
https://github.com/Vencord/plugin-requests/issues/1022
https://github.com/Vencord/plugin-requests/issues/1013
https://github.com/Vencord/plugin-requests/issues/997
https://github.com/Vencord/plugin-requests/issues/944
https://github.com/Vencord/plugin-requests/issues/849
https://github.com/Vencord/plugin-requests/issues/832
https://github.com/Vencord/plugin-requests/issues/764
https://github.com/Vencord/plugin-requests/issues/783
#1078
