### ISSUE TITLE
Bold messages

### ISSUE THREAD

**Issue by HydroHimself2** [Vencord/plugin-requests#1098]
### Plugin Description

A plugin that makes any message you send bold, example: *message*.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
we had a thing for that: textreplace
