### ISSUE TITLE
Profile effects darken

### ISSUE THREAD

**Issue by Oi-jojo** [Vencord/plugin-requests#110]
### Plugin Description

Hello, I was thinking about a plugin that can somehow darken the color of people that have nitro profile effects when opening their profile. I hate getting blinded by it. I don't know if it exists for another mod.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Kyuuhachi** [comment]
Pretty sure you can do that with just css. `opacity` or `filter` would be the most relevant.

**Comment by Oi-jojo** [comment]
> Pretty sure you can do that with just css. `opacity` or `filter` would be the most relevant.

Does a css snippet already exist for that. I don't really know css

**Comment by nin0-dev** [comment]
```
[class^="profileEffects"]
{
  opacity: 70%;
  filter:brightness(50%);
}
```
this should do the job, feel free to adjust the values if needed

**Comment by Oi-jojo** [comment]
> ```
> [class^="profileEffects"]
> {
>   opacity: 70%;
>   filter:brightness(50%);
> }
> ```
> this should do the job, feel free to adjust the values if needed

Thank you very nuch
