### ISSUE TITLE
[FEATURE REQUEST - MessageLogger] - ignore all muted servers/guilds and/or channels

### ISSUE THREAD

**Issue by biast12** [Vencord/plugin-requests#1100]
### Plugin Description

This is a feature request for the MessageLogger plugin

I would love if it had an option to just ignore all muted servers/guilds (and maybe also an option for channels too)

The MessageLogger can end up taking quite a lot of memory after some time if you're on a good handful of servers and i think a feature like this would make it a lot easier for people to ignore those servers they aren't really active in which would mean saving more memory in the long run

it is *technically* possible to do by adding all the server ids manually but again if you're in many servers can that be a ton of work to do, which i know the majority of people won't do (me included)

But yeah i really hope this can be added as it would be really useful for not only me but for others too
Have a good day :3

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sadan4** [comment]
seems too niche

**Comment by biast12** [comment]
i don't think it's niche at all, i'll honestly say it's a really common thing to have, especially for things that takes a lot of resources

**Comment by Vendicated** [comment]
> The MessageLogger can end up taking quite a lot of memory after some time if you're on a good handful of servers

this is just false. it doesn't have any relevant resource usage and doesn't even log deletes in servers you haven't loaded. and this feature is not particularly useful
