### ISSUE TITLE
Deleted Message Ghost Ping Remover

### ISSUE THREAD

**Issue by Fogest** [Vencord/plugin-requests#1101]
### Plugin Description

Many servers I am in related to a game make use of a feature to "request" certain services in game. These requests appear via a Discord message from a bot that pings anybody who opts in for such requests. Once the request is filled the message is deleted. The problem here is with the way Discord handles deleted messages. The indicator of there being an unread message or mention is still present even though the message itself is there and the channel is empty. 

It would be nice to have a plugin that could automatically mark a channel as read if the message no longer exists. This potentially may not be possible to do without too many requests to Discord. So an alternative option would be an ability to mark specific channels as "read" after x seconds/minutes delay since a message is sent. 

There are plugins like "ReadAllNotificationsButton" that can kinda help with this problem. However it's a bit overkill as you may end up clearing notifications you do care about. 

**To be clear:** I do not care _what_ the deleted message is. I do not want to log the contents of it, I do not want to do anything of that nature that would violate Discord TOS. In fact the bot posting these requests already archives the message in a separate channel when the requests are filled. 

### Existing Plugin for other mod

https://github.com/Vendicated/Vencord/tree/main/src/plugins/readAllNotificationsButton

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sadan4** [comment]
Not sure if this is possible without sending api requests

**Comment by Fogest** [comment]
> Not sure if this is possible without sending api requests

Yeah that was my worry about this request. I had a feeling it may not be entirely possible. I wonder if the alternative option I proposed would be possible without this? I assume the client knows when a message is received for a channel. If it would be possible to send a "mark as read" request to that channel X seconds after receiving a message in specific channels? Regardless of whether or not the message still exists or not. That way eliminating the need to query Discord on whether a message still exists or not.

**Comment by Scyye** [comment]
> Not sure if this is possible without sending api requests

i mean, ReadAllNotifications exists, so i dont see why this couldnt.
