### ISSUE TITLE
Sticker Autocomplete

### ISSUE THREAD

**Issue by waterbufalowalking** [Vencord/plugin-requests#1102]
### Plugin Description

Like emoji autocomplete, but for stickers. 
Search using %stickername% instead of :emojiname:
Maybe have an option for favorites only/first(?)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by surgedevs** [comment]
![image](https://github.com/user-attachments/assets/373d6885-73fe-44be-b52b-10b8175cdedc)
![image](https://github.com/user-attachments/assets/e6716cb1-3fd3-4b1d-8cd0-c6630b1d2197)
(this is a vanilla feature)
