### ISSUE TITLE
pluralchum for vencord

### ISSUE THREAD

**Issue by rings2006** [Vencord/plugin-requests#1106]
### Plugin Description

the plugin adds better integrations with [pluralkit](https://pluralkit.me/) letting you vew the messages as though they were from real users, edit them with the edit them with a button, etc.

### Existing Plugin for other mod

https://github.com/estroBiologist/pluralchum

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
blatant dupe.

also, https://github.com/ScyyeCord
