### ISSUE TITLE
UrbanDictionary

### ISSUE THREAD

**Issue by WhateverLime408** [Vencord/plugin-requests#1110]
### Plugin Description

Right-click on any selected word and choose "Urban Dictionary" to view its definition from Urban Dictionary 

### Existing Plugin for other mod

https://betterdiscord.app/plugin/UrbanDictionary

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
we had a thing for that: user apps

look for some urban dictionary bot in the app directory and add to ur account

**Comment by sadan4** [comment]
> we had a thing for that: user apps
> 
> look for some urban dictionary bot in the app directory and add to ur account

As neat as userapps are, they kinda suck
A plugin is better imo

**Comment by Vendicated** [comment]
bots are objectively better for this because they can send proper embeds and work on all your devices. pick your poison and install it to your account https://discord.com/application-directory/search?q=urban
