### ISSUE TITLE
Search in server list

### ISSUE THREAD

**Issue by xKony** [Vencord/plugin-requests#1111]
### Plugin Description

bro please all i want for christmas is a plugin that allows me to search in my discord server list, to easily find the one i search for i know folders are fine and all, but i have 100 servers, some of them change profile icon, do random funny business and i waste time searching for the ones i need at the moment, pleeeaasseeeee 🙏🙏🙏🙏🙏🙏

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
ctrl + k
happy early christmas

**Comment by xKony** [comment]
Scyye goat
