### ISSUE TITLE
Add a Split Large Messages plugin

### ISSUE THREAD

**Issue by mikeeeeeeeer1** [Vencord/plugin-requests#1112]
### Plugin Description

I feel like vencord should add a plugin that automatically splits large messages. FakeNitro does not bypass the character limit and I feel like it would be nice and a hell of a lot easier.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/SplitLargeMessages

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
#1079 #948 #494 #362 #151
