### ISSUE TITLE
Resizable Modals

### ISSUE THREAD

**Issue by ArchiDog1998** [Vencord/plugin-requests#1113]
### Plugin Description

https://github.com/discord/discord-api-docs/discussions/5196

For the case where I want to write a wall of text, it is very hard to see all the texts at the same time.
Shall we make it bigger?

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
can be done with css
