### ISSUE TITLE
View previous server owners

### ISSUE THREAD

**Issue by ssamerop** [Vencord/plugin-requests#1116]
### Plugin Description

ServerInfo plugin shows server owner, but the owner can be transferred to someone else. Make a plugin that shows all previous server owners

### Existing Plugin for other mod

https://vencord.dev/plugins/ServerInfo

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by jamesbt365** [comment]
The API does not provide such information.
