### ISSUE TITLE
Badges Plugin

### ISSUE THREAD

**Issue by D33pWar** [Vencord/plugin-requests#1117]
### Plugin Description

All badges Plugin. We can click and select what badges we want to have on our profile. It's only local, so only the user will see these badges

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by jamesbt365** [comment]
Duplicate of #821, #579, #444, #395, #318, #194.

I can search "Badge" and it shows all of these.
