### ISSUE TITLE
Get notified when a user reacts to your message

### ISSUE THREAD

**Issue by ssamerop** [Vencord/plugin-requests#1119]
### Plugin Description

Simply, if someone reacts to your message, you get a ping. (or a similar sound effect)

Plugin Name: WhoReact (or whatever u want)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sadan4** [comment]
duplicate
https://github.com/Vencord/plugin-requests/issues/96
