### ISSUE TITLE
Greentext Plugin

### ISSUE THREAD

**Issue by CynicalSinz** [Vencord/plugin-requests#112]
### Plugin Description

It detects ">be me" and applies a CSS style to the message. 
It is important to note that there are multiple Styles for 4chan, all colors that I mention will be in regards to the default Yotsuba. I would highly recommend making each Style an option in the plugin settings.

An additional feature I'd like to recommend is adding the red ">>message link" to the top of every reply message (would be interesting if the numbers were the messageID. And since this is client-side, hyperlinking shouldn't flag automodded servers 😉 ). Highlighting and original message popouts are weird imo, but ig they could also be optional functions.
It would also be cool if the vencord implementation included the option to apply it to any message with unindented ">" messages. 
And it would be even cooler if attachments were wrapped inline with the message, with the image/video viewer modal also expanding above the post, just like in 4chan.

\
\
\

Replugged refuses to work on my MacBook, so I added a quick video of 4chan for reference. 

https://github.com/Vencord/plugin-requests/assets/157345374/95cc0eba-4d2c-44fd-a85d-aefcd0b86d5c

Transcript:
Starts with showcasing greentext posts. (none are >be me's, but it should suffice)
Then displays inline images and expanding the image viewer above the post.
Ends with focusing on "red reply text."

### Existing Plugin for other mod

https://github.com/lexisother/replugged-plugins/tree/master/plugins/greentext

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
This is either:
A: Doable with CSS
B: Too low quality to be an actual plugin

**Comment by TheKodeToad** [comment]
It's impossible to do `>text` with just CSS

**Comment by MrDiamondDog** [comment]
This is low quality but it's funny so I made it a third party plugin:

https://discord.com/channels/1015060230222131221/1032200195582197831/1211412605277569105
