### ISSUE TITLE
Disable the "Activity" page on discord servers.

### ISSUE THREAD

**Issue by quelziz** [Vencord/plugin-requests#1120]
### Plugin Description

Disable the "Activity" page on discord servers. I can't find any settings, nor a plugin to disable it, and its kinda annoying.

![image](https://github.com/user-attachments/assets/c686a874-5861-45be-8f86-b4ed21a078bb)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by GrayLanterns** [comment]
A plugin for this is not yet available, but you can paste this lil bad boy in your QuickCSS and it does pretty much suffice. Kudos to @krystalskullofficial on Discord for lighting up the road.

```
/* remove activities from memberlist */
[class^=membersGroup_]:has([d^="M10.56 1.1c-.46.05-.7.53-.64.98.18"]),
div:not([class]):has([class^=facePile_]) { 
  display: none; 
}
```

**Comment by KrystalSkullOfficial** [comment]
thank you but it wasn't actually made by me it made by an `@krammeth` on discord :3 
_I'm just trying to spread it around because it was buried in the sea that is the theme-development channel_

**Comment by GrayLanterns** [comment]
Oh I didn't know, thanks for the heads up. Perhaps Krammeth lit up your road and you lit up mine. And I guess I poured some of the stardust left for OP to follow along. Cheers to the lil north stars of the Vencordverse, haha ✨

**Comment by GrayLanterns** [comment]
You're awesome! Have a great rest of the day! @Krammeth

**Comment by Krammeth** [comment]
You too!
