### ISSUE TITLE
Server Rename plugin

### ISSUE THREAD

**Issue by PovilasLT** [Vencord/plugin-requests#113]
### Plugin Description

Hi,
Plugin should let user to client-side rename servers. It would be useful for developers, i.e. I'm in lot of plugin support servers that are named like "xxxx development", and I would love to be able to rename them to "yyyy plugin" instead of trying to remember every server name.
These renamed servers should be also searchable by ctrl+k.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
not useful enough to be a stock feature. Also doable with css most likely

**Comment by Sqaaakoi** [comment]
doing this with CSS would probably be horribly painful, also the example given is a bad example that doesnt show how this could be useful
i know some servers like to just be renamed as a joke, thats why this would be useful
