### ISSUE TITLE
NoInlineLinks

### ISSUE THREAD

**Issue by OIRNOIR** [Vencord/plugin-requests#115]
### Plugin Description

This potential plugin would disable the new inline links from being rendered, instead showing as `[title](link)` when sent by users (not affecting bot embeds). This is useful for everyone who agrees that allowing regular users to send inline links is a bad idea.

### Existing Plugin for other mod

https://github.com/lexisother/replugged-plugins/tree/master/plugins/noInlineLinks

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
You can use css to change the appearance of those links
