### ISSUE TITLE
ReplaceGoogleSearch

### ISSUE THREAD

**Issue by OIRNOIR** [Vencord/plugin-requests#117]
### Plugin Description

Allows using search engines other than google to be used when searching for phrases from within Discord.

### Existing Plugin for other mod

https://github.com/GriefMoDz/replace-google-search

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by ImpishMoxxie** [comment]
Me and Ethan are working on it :3

**Comment by ImpishMoxxie** [comment]
its made!
https://github.com/Vendicated/Vencord/pull/2217

**Comment by OIRNOIR** [comment]
Awesome, thanks!

**Comment by ImpishMoxxie** [comment]
> Awesome, thanks!

np it was fun working on it

**Comment by BaconCatBug** [comment]
@ImpishMoxxie Any luck with making the changes noted in the failed PR? I'd love for this plugin to be a thing.

**Comment by ImpishMoxxie** [comment]
Didn't have to much time to work on it cuz of school stuff but I will prob start working on it again today or in the close week
