### ISSUE TITLE
ShowAllRoleMembers

### ISSUE THREAD

**Issue by tomodachi94** [Vencord/plugin-requests#118]
### Plugin Description

Shows all roles _and_ the members of each role.

### Searched terms

I searched for:
* `role members`
* `role`
* `ShowAllRoleMembers`
* `ShowRoleMembers`

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Kyuuhachi** [comment]
Pretty sure this is not possible.

**Comment by tomodachi94** [comment]
That's unfortunate. Closing...

**Comment by Grafaffel** [comment]
> Pretty sure this is not possible.

there is an experiment for that, I think it called role pop out (adds an pop out showing all members of an role, when clicking the appropriate role mention) or smth. But afaik it only shows cached users

**Comment by mynameisbob1928** [comment]
> Pretty sure this is not possible.

me when i say no: https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/RoleMembers

**Comment by mynameisbob1928** [comment]
currently for viewing all roles i use permissionsViewer which displays all roles

**Comment by Sqaaakoi** [comment]
> > Pretty sure this is not possible.
> 
> me when i say no: https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/RoleMembers

i cant read devilbro code :husk:
can i go back to looking for some jank code to force client side permission to view roles menu?
