### ISSUE TITLE
Delete all message history

### ISSUE THREAD

**Issue by joutico777** [Vencord/plugin-requests#126]
### Plugin Description

A button to delete all message history (for message logger). That would be cool

### Existing Plugin for other mod

No

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by gllxflr** [comment]
ctrl+r

**Comment by cheesesamwich** [comment]
😭

**Comment by MadelineMaid** [comment]
https://github.com/Vencord/plugin-requests/assets/143292746/480c39e7-490b-4439-b02f-6f8544f55645
