### ISSUE TITLE
Mod view without mod permissions

### ISSUE THREAD

**Issue by MrBossy** [Vencord/plugin-requests#134]
### Plugin Description

Discord released a new feature called "Mod view" where it shows you more detailed user information such as amount of messages sent, if they passed the verification level, join method, mod permissions and more. Would be good if you could install a plugin and have it available on all servers without needing to have mod permissions. This is currently possible by modifying Discord server responses but it's incredibly unreliable and the pop ups as well as the button to open it disappear after a minute or two.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
I have already made this plugin, I just haven't submitted the PR yet. Will do so now.

**Comment by Sqaaakoi** [comment]
https://github.com/Vendicated/Vencord/pull/2220
