### ISSUE TITLE
Server details

### ISSUE THREAD

**Issue by DexType** [Vencord/plugin-requests#135]
### Plugin Description

A plugin which shows information about the server that you've joined. A good example is server details by devilbro for better edit :)

### Existing Plugin for other mod

https://betterdiscord.app/plugin/ServerDetails

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by ImpishMoxxie** [comment]
It is already a thing
https://vencord.dev/plugins/ServerProfile
