### ISSUE TITLE
[Updating the plugin] FakeNitro

### ISSUE THREAD

**Issue by AlexxIsHere** [Vencord/plugin-requests#139]
### Plugin Description

1. Give the plugin an option to toggle whether to send with or without the name of the emoji as it works without it too.

-  Reason 

 

- The plugin is sending the emotes along with the name, which bots like Mee6 or the autmod would filter it which makes it harder to send them, having to go to a different DM to send it and remove the name. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
There is an option to disable it.

**Comment by AlexxIsHere** [comment]
Where? I have checked each and every option, but none does it

**Comment by AlexxIsHere** [comment]
Unless it has gotten updated without me knowing

**Comment by MrDiamondDog** [comment]
FakeNitro settings > Use Hyperlinks

**Comment by AlexxIsHere** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/78157101/dd8de035-b101-4d71-bded-bacd36204d93)

**Comment by AlexxIsHere** [comment]
Yes, but the name is still there, it will still filter it out

**Comment by MrDiamondDog** [comment]
There is no way to get around that. FakeNitro sends an image link that shows the emoji, and if the server blocks that, you cant use the links.

**Comment by AlexxIsHere** [comment]
I am talking about the last part, the "name=ASC_ze_stare" The last part will make it be filtered due to the name of it (if it contains something that will filter the message).

**Comment by AlexxIsHere** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/78157101/d14a76a6-3aa6-4ea4-b854-fcd0cbe25703)

**Comment by AlexxIsHere** [comment]
By removing the last part of it, it still embeds, but there's no option for me to stop sending them without the name, which is unnecessary

**Comment by nin0-dev** [comment]
as far as i know the name is used so that you and other fakenitro users see the actual emoji name instead of `FakeNitroEmoji`.
also if your emoji name gets automodded it means its definitely not appropriate for the server you're in imo

**Comment by AlexxIsHere** [comment]
I see, no, sometimes it is not much of a deal and has nothing inappropriate, talking about the emoji itself, there's some emotes that do have an inappropriate name in them, but do not have anything inappropriate whatsoever. 

Cloning them sounds like a way out of it, but that would give a bit of a hassle. I am not asking much, but just one part to not be present in the message itself. Seems a lot easier this way, would've been easier if it was possible to do the job yourself like in betterdiscord, yet the performance seems a little sluggish for me compared to vencord

**Comment by MrDiamondDog** [comment]
It gets blocked because the name of the emoji is blocked in the server. It should just be that specific emoji, other ones should be fine.

**Comment by sunnniee** [comment]
you can do this with a TextReplace rule

as regex
match: `(cdn.discordapp.com/emojis/\d{17,20}.{0,50})&name=\w+`
replace: `$1`
