### ISSUE TITLE
Favorite Any Media

### ISSUE THREAD

**Issue by Flumpledorf** [Vencord/plugin-requests#14]
### Plugin Description

The ability to favorite any embedded Image or Video and add it to the favorite gifs section.
Add a warning to videos since those have issues on mobile.

### Existing Plugin for other mod

Vendetta: https://vd-plugins.github.io/proxy/castdrian.github.io/vendetta-plugins/favorite-gifs/   BetterDiscord: https://betterdiscord.app/plugin/FavoriteMedia 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by cheesesamwich** [comment]
duplicate

**Comment by YahBoiiJose** [comment]
> duplicate

what is this a duplicate of?

**Comment by Slimemaster0** [comment]
Where is the original?

**Comment by Flumpledorf** [comment]
https://github.com/Vencord/plugin-requests/issues/13
It was originally titled differently and didn’t exist when I originally wrote the request.
The creator didn’t say “favorite” or in it at all making it harder to search for.
