### ISSUE TITLE
Read Full User Bio

### ISSUE THREAD

**Issue by wolfieboy09** [Vencord/plugin-requests#142]
### Plugin Description

When some bios are long, discord will show a `...` at the bottom of it.

For example:
```
blah blah blah blah blah 
blah blah blah blah 
blah blah 
blah blah blah blah blah 
blah blah 



blah blah blah blah blah blah blah 
blah blah blah blah 
Fun fact below:
...
```

So, this plugin would just display the entire thing like:
```
blah blah blah blah blah 
blah blah blah blah 
blah blah 
blah blah blah blah blah 
blah blah 



blah blah blah blah blah blah blah 
blah blah blah blah 
Fun fact below:
Hot water freezes faster then normal room-temperature water



*Air conditioning is just domesticated wind...*
```

It makes it super useful to read the entire thing

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AftmostSeeker80** [comment]
This can be done through css
https://discord.com/channels/1015060230222131221/1028106818368589824/1174045822858559519

**Comment by KrstlSkll69** [comment]
> This can be done via css
> https://discord.com/channels/1015060230222131221/1028106818368589824/1174045822858559519

That CSS doesn't work anymore someone will have to remake it

**Comment by AftmostSeeker80** [comment]
This one should work
https://discord.com/channels/1015060230222131221/1028106818368589824/1121106047654961253

**Comment by EdVraz** [comment]
> This one should work https://discord.com/channels/1015060230222131221/1028106818368589824/1121106047654961253
> 
> edit: sorry, I should've checked the old one first

Yop that one works
