### ISSUE TITLE
3 plugins that not exist in vencord

### ISSUE THREAD

**Issue by Soulivan71** [Vencord/plugin-requests#144]
### Plugin Description

Maybe something better than an explication : 
Link below, could be cool on vencord :3

### Existing Plugin for other mod

https://betterdiscord.app/plugin?id=1067 / https://betterdiscord.app/plugin?id=1066 / https://betterdiscord.app/plugin/ShowBadgesInChat

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by InfectedGriffon** [comment]
The functionality of the first plugin is pretty easy to achieve in vanilla Discord. In the search bar for a server, search for "in:<channel name>" (or hit ctrl+f while in the channel) to get only messages in a channel, then click the "Old" button next to the result count. This will give you a list of the messages in the channel in reverse chronological order. Clicking on the first message in the list will jump you to the top of the channel.

**Comment by Soulivan71** [comment]
> The functionality of the first plugin is pretty easy to achieve in vanilla Discord. In the search bar for a server, search for "in:" (or hit ctrl+f while in the channel) to get only messages in a channel, then click the "Old" button next to the result count. This will give you a list of the messages in the channel in reverse chronological order. Clicking on the first message in the list will jump you to the top of the channel.

Sure but a button, its easier too x)

**Comment by EdVraz** [comment]
You have not checked for duplicate requests. Please open a separate request for every plugin that you want so its easier to keep track of them. Also use an appropriate title the next time (look at other issues for example).
