### ISSUE TITLE
Non-friend nicknames

### ISSUE THREAD

**Issue by mommyissues** [Vencord/plugin-requests#147]
### Plugin Description

I don't understand why discord won't let us add nicknames for non-friends, but I guess it needs to be added as a custom functionality on vencord...

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by InfectedGriffon** [comment]
duplicate of #145 from two hours ago
