### ISSUE TITLE
WebKeybinds - MacOS Keyboard Layout support?

### ISSUE THREAD

**Issue by LukeGotBored** [Vencord/plugin-requests#149]
### Plugin Description

I have been using Vencord on Web due to battery life concerns with the desktop application. Right now, the WebKeybinds plugin adds Windows-specific keyboard shortcuts (utilizing the CTRL key), but I would find it much more straightforward to have an option in the plugin settings to replace CTRL with the Mac CMD (⌘) key instead. After becoming accustomed to using CMD key shortcuts on MacOS, re-training my muscle memory for the CTRL combination shortcuts feels rather awkward.

Would it be possible to add such option to the plugin?

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
https://github.com/Vendicated/Vencord/blob/main/src/plugins/webKeybinds.web/index.ts#L33 ???????

**Comment by LukeGotBored** [comment]
> https://github.com/Vendicated/Vencord/blob/main/src/plugins/webKeybinds.web/index.ts#L33 ???????

That's quite weird, I've tried using the CMD key, on both Chrome and Arc, and it definitely doesn't work on my end, I'm not quite sure why

**Comment by EdVraz** [comment]
> > https://github.com/Vendicated/Vencord/blob/main/src/plugins/webKeybinds.web/index.ts#L33 ???????
> 
> That's quite weird, I've tried using the CMD key, on both Chrome and Arc, and it definitely doesn't work on my end, I'm not quite sure why

```
description: "Re-adds keybinds missing in the web version of Discord: ctrl+t, ctrl+shift+t, ctrl+tab, ctrl+shift+tab, ctrl+1-9, ctrl+,. Only works fully on Vesktop/ArmCord, not inside your browser",
```

Maybe you should try using [Vesktop](https://github.com/Vencord/Vesktop).
