### ISSUE TITLE
Read/Seen

### ISSUE THREAD

**Issue by Oi-jojo** [Vencord/plugin-requests#15]
### Plugin Description

I dont think this falls as a creepy plugin but i do understand if it does. we all know the instagram read/seen feature if another person had seen your message. is it poosible to make some similar mechanism for discord in dms. (i dont know if this plugin was made for other mod clients.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by cheesesamwich** [comment]
not possible and just weird. Discord didnt add that feature for a reason
