### ISSUE TITLE
luh calm plugin 😹

### ISSUE THREAD

**Issue by MoronDev** [Vencord/plugin-requests#150]
### Plugin Description

luh plug 😹

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MadelineMaid** [comment]
i sure wish i knew at all what this was

**Comment by 42chompii** [comment]
Very fitting username

**Comment by Sqaaakoi** [comment]
Your username is very accurate indeed

**Comment by MadelineMaid** [comment]
ok

**Comment by toasterw** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/71234319/85a2507a-12f2-4eaf-92ae-6e81e8e279d8)
