### ISSUE TITLE
SplitLargeMessages

### ISSUE THREAD

**Issue by Rando213** [Vencord/plugin-requests#151]
### Plugin Description

Splits messages that go over the Discord character count into smaller ones. A 4000 character message would be split into 2 messages, a 5678 character message into 3, so on and so forth. This also avoids the "message.txt" file getting created, when pasting a large message into the Discord message box.

### Existing Plugin for other mod

https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/SplitLargeMessages

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Rando213** [comment]
Ah sorry missed that one

**Comment by TrueReplayJay** [comment]
> You're not the first person to suggest this: #77
> 
> Quoting the last time this happened:
> 
> > This would technically be API spam/selfbotting and thus is not allowed

Aw man, that's so annoying. I love that plugin. Major thing I miss from Betterdiscord.
