### ISSUE TITLE
dangercord implomentation

### ISSUE THREAD

**Issue by dropalways** [Vencord/plugin-requests#152]
### Plugin Description

https://dangercord.com/
kinda like review db(not really) idk what to say here but yeah
u can click on someones profile to see any reports
add reports

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/129603125/f5c2118e-1e1e-47f0-9409-d99bd482847e)

**Comment by TheKodeToad** [comment]
This is pretty much reviewdb but worse - especially in terms of safety and privacy - you can't opt-out, block people or delete your own reviews, and all recent reports are visible on the front page.

**Comment by mantikafasi** [comment]
so baddd
