### ISSUE TITLE
Friends since plugin

### ISSUE THREAD

**Issue by Roki100** [Vencord/plugin-requests#157]
### Plugin Description

Plugin that shows a date when you and your friend became friends at

### Existing Plugin for other mod

https://betterdiscord.app/plugin?id=1080

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
https://github.com/Vendicated/Vencord/pull/2240
