### ISSUE TITLE
Disable Shift+Ctrl+N keybind

### ISSUE THREAD

**Issue by wojpawlik** [Vencord/plugin-requests#165]
### Plugin Description

Having to close "Create own guild" modal after opening an Incognito window in Chromium-based browsers is annoying.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
disable the webkeybinds plugin

**Comment by wojpawlik** [comment]
I have never used it: ![Nagranie ekranu z 2024-03-09 10-30-12.webm](https://github.com/Vencord/plugin-requests/assets/23058303/88ef6cac-41d9-422d-963c-76596d398b97)

**Comment by wojpawlik** [comment]
So I disagree with closing the issue @Vendicated
