### ISSUE TITLE
Disable notification count in favicon

### ISSUE THREAD

**Issue by wojpawlik** [Vencord/plugin-requests#166]
### Plugin Description

I already use Vivaldi's (for Microsoft Teams): ![](https://cdn.discordapp.com/attachments/170121320825225218/1215659123669213194/image.png?ex=65fd8dc8&is=65eb18c8&hm=4343c49d1f5f84d5939c5035cc94169a234bde19443119cc53972daa5b460dd9)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MadelineMaid** [comment]
doesn’t this already exist in notification settings

**Comment by Inbestigator** [comment]
> doesn’t this already exist in notification settings

Affirmative, if it’s not in notification settings, I’ve definitely seen a built in plugin that fixes it

**Comment by wojpawlik** [comment]
It does not affect pings. But I no longer need it, since I moved Vivaldi's badge with a little bit of CSS: ![image](https://github.com/Vencord/plugin-requests/assets/23058303/088d56eb-ea60-4802-969b-ac83058bf8cb)

```css
/* cover Discord's notification badge with Vivaldi's */
.tab span.button-badge {
    left: 11px;
    top: 13px;
}
```
