### ISSUE TITLE
Soundboardless

### ISSUE THREAD

**Issue by nixklolwastaken** [Vencord/plugin-requests#169]
### Plugin Description

a plugin that automatically mutes people's soundboards in the voice channel you're in, if they aren't muted already.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
set this to zero

![soundboard volume slider in discord voice settings](https://github.com/Vencord/plugin-requests/assets/45497981/90da0935-ef3c-4c66-bfef-5c2d1de208dc)
