### ISSUE TITLE
UwUfier Plugin

### ISSUE THREAD

**Issue by xan1ety** [Vencord/plugin-requests#17]
### Plugin Description

A UwUfy plug-in that converts messages to UwU language before sending them.
I've listed below a link of something similar. It would be nice to see a slightly enhanced version of it.

### Existing Plugin for other mod

https://github.com/SMC242/UwUfy

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by lewisakura** [comment]
TextReplace & [this config](https://discord.com/channels/1015060230222131221/1102784112584040479/1134830169396367540)
