### ISSUE TITLE
Auto-capitalize/Auto-uppercase 

### ISSUE THREAD

**Issue by feliximio** [Vencord/plugin-requests#170]
### Plugin Description

This plugin would allow the starting letter of each sentence to be automatically capitalized. 

### Existing Plugin for other mod

https://betterdiscord.app/plugin/WriteUppercase

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Roki100** [comment]
https://discord.com/channels/1015060230222131221/1032200195582197831/1196176143649349863
