### ISSUE TITLE
Status Customization

### ISSUE THREAD

**Issue by Martoona** [Vencord/plugin-requests#171]
### Plugin Description

It would be cool if i can make it so that my status aren't seen be certain selected people.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
not possible

if you share a server or have someone friended they'll be able to view your status, even if you have them blocked
