### ISSUE TITLE
Dank Memer Support

### ISSUE THREAD

**Issue by OzzyCoder11** [Vencord/plugin-requests#175]
### Plugin Description

This plugin would help you do things in Dank Memer (e.g: automatically claim /daily). I could also help you will jobs, fishing, fighting (best moves to go). This would all be client side. So if the bot helped you with tic tac toe, it would only show the best move in kinda transparent pictures.

The daily thing would pretty must just send a POST request to send a message to a channel that uses a command.

Idc about the other stuff, just plz auto daily.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
Well done you just described a selfbot
