### ISSUE TITLE
FakeNitro Suggestion

### ISSUE THREAD

**Issue by Luminityq** [Vencord/plugin-requests#176]
### Plugin Description

Allowed to have super react with FakeNitro (If Possible)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
not possible

**Comment by Vendicated** [comment]
It is quite rude to request a feature without reading the rules

![](https://github.com/Vencord/plugin-requests/assets/45497981/cd069b49-8cad-4034-a8d9-08da54ff723d)
