### ISSUE TITLE
Download as __ plugin

### ISSUE THREAD

**Issue by cheesesamwich** [Vencord/plugin-requests#177]
### Plugin Description

Adds a context menu option on attachments and other files to download as a specific file type- mp3 and wav for audio, png, jpg, and webp for image, etc 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
not really possible without including massive libraries for converting files

just use a proper app for this, there are many out there
