### ISSUE TITLE
Spotify Controls But For Music Bee

### ISSUE THREAD

**Issue by Benzeel** [Vencord/plugin-requests#178]
### Plugin Description

A plugin that functions almost the same as the Spotify player controls but for [Music Bee](https://www.getmusicbee.com/) (a music player / music library app) 

this may just be an annoyance to make, as it is probably not JUST a discord plugin you would have to make,
unless there is some way to hook into music bee already, 
a separate plugin for music bee may need to be made for this to function

i know this probably will never be a plugin due to how specific it is / possibly requiring a plugin for the program itself, 
but i thought id create a plugin request for it nonetheless, just in case it ever becomes a possibility.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
closing in favour of of #198
