### ISSUE TITLE
Cloning emotes straight from reactions

### ISSUE THREAD

**Issue by YackovFx** [Vencord/plugin-requests#179]
### Plugin Description

As an upgrade to the EmoteCloner plugin, adds a button when checking an emote from a reaction that allows the user to clone said emote to a server they're in.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
https://github.com/Vencord/plugin-requests/assets/129603125/20299fe4-d808-494b-bfb9-e9ab9853eb95
its really not that hard

**Comment by Shavixinio** [comment]
What if the reaction is an emoji outside of the servers you are in, then they won't show up in the reaction menu
