### ISSUE TITLE
Current File Upload Count

### ISSUE THREAD

**Issue by alexworrell16** [Vencord/plugin-requests#18]
### Plugin Description

A plugin that shows the number of files currently uploading in a channel (When the channel is open). Maybe the number could float above the Gif/Sticker/Emote buttons on the right?

I am often uploading large files to channels and it would be nice to know the number that are simultaneously uploading so that I can know if it's time to add another upload or not.

Edit: I'm referring to the number of currently uploading files on the client, not other people who may also be uploading files to a channel

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
why? why do you need to know? why does it matter?

**Comment by alexworrell16** [comment]
> why? why do you need to know? why does it matter?

Let me clarify why since I don't think I was clear enough. 

Since you cannot just drag 30 files at once into Discord and have it reliably upload all of them, I have to upload them in smaller batches. 

When uploading larger files in bulk, I can upload (For example) 15 or so files of a similar size, walk away and maybe 3-4 of them will be uploaded. 

I'd like to know exactly how many were uploaded at a glance rather than having to manually recount things. That way I can more easily queue up more files for upload. 

![Discord_PFTqVsDmOa](https://github.com/Vencord/plugin-requests/assets/80132604/25772ab1-a0f2-46c2-a1f9-81eb06680628)

It's a pretty niche thing that may not even seem that useful to 99% of users, but it'd be nice for to have since I upload pretty frequently in bulk.

**Comment by Vendicated** [comment]
why are you uploading so many large files, that seems like you're either abusing discords cdn or should just use a proper discord bot that can better automate uploading

**Comment by alexworrell16** [comment]
I've already got a Discord bot that can upload files, but it's limited to the max upload file size of the server. 

Obviously with Nitro the client can upload up to 500MB files.

If you know of a bot that can automate uploads larger than the server limit, I'm all ears.
