### ISSUE TITLE
Tell if someone has read it

### ISSUE THREAD

**Issue by OzzyCoder11** [Vencord/plugin-requests#180]
### Plugin Description

Just like [this](https://www.youtube.com/watch?v=DOvbXgHWgHc) but without the long tutorial. Just a little thing that says 'Unread' or 'Read' on DM (or channels).

Settings would be like 'Enabled in channels' and dms.

sorry abt my last suggestion :(

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
Stalking is something we do not appreciate here.
