### ISSUE TITLE
Download Voice Messages

### ISSUE THREAD

**Issue by MrRich4617** [Vencord/plugin-requests#184]
### Plugin Description

Basicly i would like to be able to download voice messages that i send or some people send me. As a voice actor this would help me GREATLY to download my voice messages and send it to the other people.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
As a workaround: enable ViewRaw plugin, hit the button on the message containing the voice message, copypaste the url to your browser.

**Comment by MrRich4617** [comment]
> copypaste the url to your browser.
   what url?

**Comment by MrRich4617** [comment]
> > copypaste the url to your browser.
> > what url?

IT WORKED THANK YOU SO MUCH
