### ISSUE TITLE
Custom quotes for LoadingQuotes Plugin

### ISSUE THREAD

**Issue by Naxy21** [Vencord/plugin-requests#185]
### Plugin Description

i like the LoadingQuotes plugin a lot, but it would be pretty cool to be able to use your own custom quotes as well in the plugin's options.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
PR already opened at Vendicated/Vencord#1795
