### ISSUE TITLE
Theme Manager

### ISSUE THREAD

**Issue by Tr0llie** [Vencord/plugin-requests#190]
### Plugin Description

A Theme manager ( with links) in which manages themes via UI

## Note
this Ui change may not be needed for many people and It is abit stupid in my opinion but is a nice thing to have if u want to switch themes quickly and not search for it for a long time. 

# Visual UI Design (example)
### Design 1 
![image](https://github.com/Vencord/plugin-requests/assets/92353690/7873847f-7daf-4cf5-8692-444343afd715))

i couldn't think of more design

* ps i couldn't find any similar plugins, i did search it for a long time and couldn't find any similar ones *

### Existing Plugin for other mod

Can't find 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by TheKodeToad** [comment]
This already exists xD
I like the drawing though

Just press Upload theme and select the CSS file.

**Comment by Tr0llie** [comment]
> This already exists xD I like the drawing though
> 
> Just press Upload theme and select the CSS file.

Im sorry, i haven't ever use that feature b4 since i didn't want to download any file and instead used the link. 
Maybe it should also have a button for uploading css via links.

**Comment by Tr0llie** [comment]
> It literally does though, in the online themes tab.

im trying to imply that 
you can save it with link **and** with files since people might not want to download themes. I know the online themes tab exist but if i want to switch a theme i need to go find looking for it in better discord website or other external links
but with this feature i can input a link and it can be saved until deleted or until not used for x amount of days

**Comment by Vendicated** [comment]
> Im sorry, i haven't ever use that feature b4 since i didn't want to download any file and instead used the link.
> Maybe it should also have a button for uploading css via links.

unfortunately users are stupid and paste the wrong link. that's why we moved away from using links as the main method. the online themes tab still exists for advanced users but we don't plan any new changes to it
