### ISSUE TITLE
Allbadges

### ISSUE THREAD

**Issue by TNTISGOOD** [Vencord/plugin-requests#194]
### Plugin Description

This is a plugin that is written in javascript which I found here: https://discord.com/channels/603970300668805120/1112823600634925147/1112823600634925147

the file which contains the code can be downloaded from the message. It is a plugin which allows you get to get all the badges ( client side ) on your profile!

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
This is useless

**Comment by cheesesamwich** [comment]
yeah why would you even want this?

**Comment by byeoon** [comment]
I like this, even though it's only cosmetic and may not have a purpose.
*In fact I was thinking about making a (prob 3rd party vencord) plugin that works similar to this.*

**Comment by MrDiamondDog** [comment]
This was a pr that got rejected, so no, this will not become a plugin. https://github.com/Vendicated/Vencord/pull/2068
