### ISSUE TITLE
Set default view mode of Forum

### ISSUE THREAD

**Issue by TetraTheta** [Vencord/plugin-requests#195]
### Plugin Description

Discord has Forum feature. It provides two view mode: Gallery, List.

Gallery view:
![Gallery](https://github.com/Vencord/plugin-requests/assets/37061801/b8fa5a1b-4b19-4709-b9ed-1800f65e5e64)

List view:
![List](https://github.com/Vencord/plugin-requests/assets/37061801/89f9a80e-cc62-4cd7-933b-9b8503c44ec2)

Server moderator can set default view of Forum, but user can't set default view of Forum. This really annoys me. I wish I can set default view of Forum, regardless of how server moderator set it as.

For example, I want to force every Forum on server I've joined to be displayed as List view even though the server moderators set it as Gallaery view.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Inbestigator** [comment]
Here's the PR: https://github.com/Vendicated/Vencord/pull/2272
