### ISSUE TITLE
AutoIdle-Disable

### ISSUE THREAD

**Issue by ItsDrike** [Vencord/plugin-requests#199]
### Plugin Description

A very simple plugin that would disable discord from automatically changing my status from "online" to "idle" if I haven't interacted with the client for a while.

This is useful if you want to look at a message you just received, which means interacting with the client, but without giving away that you've actually looked at the message, by your status changing from idle back to online. You could also hide this by setting yourself to "idle" or "offline" too, but I don't like having my status at either of those options.

For whatever reason, when I was using the proprietary client on my linux (wayland) machine, with the status set to "online", I actually never automatically went idle. I'm not sure if this was a bug in the official app, but I liked this behavior, and with vesktop, I no longer get it.

Edit: Upon receiving a suggestion from @UglukOrc, I also think that this plugin should also include a way to control the amount of time it takes until you become idle, not just a way to simply disable the auto-idle behavior. With that, this request becomes similar to the existing: <https://betterdiscord.app/plugin/AutoIdleOnAFK> plugin. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by waresnew** [comment]
I can work on this
