### ISSUE TITLE
Search filter for threads

### ISSUE THREAD

**Issue by Had781795** [Vencord/plugin-requests#20]
### Plugin Description

There is currently no way to search for messages within threads on discord.
currently they're mixed in with the channel the thread was made in.

#General
|--thread01
|--thread02

something like: `channel:#General#thread01`

Would it be possible to add a filter?
Maybe just search everything in #General but only show the ones from the thread?

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
search changes are not possible
