### ISSUE TITLE
AuditLogVis

### ISSUE THREAD

**Issue by DeffQ** [Vencord/plugin-requests#201]
### Plugin Description

make a plugin that lets the user see audit log without perms

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by byeoon** [comment]
This is literally impossible. The audit log is locked behind the API
and trying to access it if you don't have the right server permissions will give you a 403 error.
