### ISSUE TITLE
Base64

### ISSUE THREAD

**Issue by Eve9181** [Vencord/plugin-requests#202]
### Plugin Description

A plugin that allows decoding/encoding of base64 texts, if possible add the decoding option to context menu as well 

### Existing Plugin for other mod

https://github.com/mantikafasi/AliucordPlugins/tree/main/Base64

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
why was this rejected? with some work to find base64 strings in messages, something like could actually be a useful feature

**Comment by Vendicated** [comment]
because it's useless. why would one ever want to send or receive base64 text on discord? it's nonsense.

**Comment by apprehensions** [comment]
`printf 'text to send' | base64 | wl-copy`
