### ISSUE TITLE
Online friend notification 

### ISSUE THREAD

**Issue by jakuza622** [Vencord/plugin-requests#205]
### Plugin Description

you got message or notification when selected people online

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
#12
