### ISSUE TITLE
Read Receipts

### ISSUE THREAD

**Issue by tjxzz** [Vencord/plugin-requests#207]
### Plugin Description

It's basically how Instagram, Twitter. and Snapchat have a read receipt where whenever someone reads the other persons message, it'll say it's read. That way so we know when people on Discord are just blatantly ignoring us. It'd be a great thing to add and lots of people want it. Please add this, trust 🙏 Don't know if it's possible with the other user not having Vencord though.

### Existing Plugin for other mod

Not sure sadly. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by cheesesamwich** [comment]
creepy as shit

**Comment by KrstlSkll69** [comment]
frfr super creepy, as someone who has a lot of creeps as in her DMs i don't think it's a safe thing for them to be able to see if someone as actually read their DMs

**Comment by Sqaaakoi** [comment]
not (reasonably) possible and extremely creepy

**Comment by fily-gif** [comment]
I really hope that there will be a bot that will close these issues.

1. This is creepy.
2. Not possible.
3. Duplicate.

**Comment by AftmostSeeker80** [comment]
:husk:

**Comment by Inbestigator** [comment]
Bro just watched the NTTS video and thought that it would be a perfect system and not annoying at all.

**Comment by Roki100** [comment]
lil bros dont know what "creepy" stuff really is

**Comment by KrstlSkll69** [comment]
> lil bros dont know what "creepy" stuff really is

Don't care didn't ask cope

**Comment by nin0-dev** [comment]
> lil bros dont know what "creepy" stuff really is

honestly if you don't like the decision that's taken fork vencord, learn ts, and make your own plugin <:husk:1026532993923293184>

**Comment by Roki100** [comment]
> > lil bros dont know what "creepy" stuff really is
> 
> honestly if you don't like the decision that's taken fork vencord, learn ts, and make your own plugin <:husk:1026532993923293184>

where did i say such thing?

**Comment by MrDiamondDog** [comment]
> > > lil bros dont know what "creepy" stuff really is
> 
> > 
> 
> > honestly if you don't like the decision that's taken fork vencord, learn ts, and make your own plugin <:husk:1026532993923293184>
> 
> 
> 
> where did i say such thing?

![image](https://github.com/Vencord/plugin-requests/assets/84212701/8128914b-3b8d-4e21-9c0c-564a90ea87e9)

**Comment by Vendicated** [comment]
ladies please keep it on topic. rejections are final please do not pollute the suggestions channel with needless arguing
