### ISSUE TITLE
dm's protection

### ISSUE THREAD

**Issue by Martoona** [Vencord/plugin-requests#211]
### Plugin Description

maybe add a button that allows me to make a password for a private dm? betterdiscord did something similar but not quite, pretty sure it's possible and if it is that would be an amazing feature.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
#10 #54 - passwords to lock down the app/parts of the app are not useful; just lock your system or log out of discord, theres nothing we can do to offer more protection than that.

**Comment by nin0-dev** [comment]
also this gives a huge false sense of security- since you can just use js console to disable the plugin, or even better, just uninstall vencord

@Vendicated you should add that passwordlock plugins won't be added in the request agreement thing
