### ISSUE TITLE
Twemoji plugin for channel names, usernames, and role names

### ISSUE THREAD

**Issue by innosflew** [Vencord/plugin-requests#215]
### Plugin Description

I would like to request a plugin that would replace the system default emojis in channel names, usernames, and role names with Twemojis. I think it's very inconsistent that Discord uses Twemojis for their messages, but for everything else it uses the system default emojis, which on Windows are the Segoe UI emojis. These Segoe UI emojis not only look worse in my opinion than Twemojis, but they also don't support country flags.

Here is an example with default Segoe UI emojis:
![](https://i.imgur.com/x04d2s4.png)

And here is an example if Discord used Twemojis in the channel names:
![](https://i.imgur.com/OQmIBN6.png)

### Existing Plugin for other mod

I'm only aware of this Chrome extension, but sadly you can't use Chrome extensions with the desktop app: https://chromewebstore.google.com/detail/twemoji-for-chrome/fopgafjdjlongoeblobbafbnapafcicg

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
This is easily achieved with css.
To give you an example, here's a snippet for channel names using Twemoji for flags and a blank 'dashless' font for the "-":
https://discord.com/channels/1015060230222131221/1028106818368589824/1199849292853157888

That doesn't apply to threads, roles or usernames though, it's just to give you an idea.
Modifying that to do what you described is easy to do if you're at all familiar with css and devtools (ctrl+shift+i).
Ask on the theme development channel if you need help.
