### ISSUE TITLE
Amazon Music Rich Presence!

### ISSUE THREAD

**Issue by TheRealFynn07** [Vencord/plugin-requests#217]
### Plugin Description

Something similar to the already integrated Spotify Rich Presence this could also be interesting!

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
I don't believe that amazon music has a spotify-like API to control playback, so picking it up directly from vencord in a reliable way would be hard

you can use [PreMID](https://premid.app/) though, it has amazon music presence.
