### ISSUE TITLE
Become MOD

### ISSUE THREAD

**Issue by ayakgurmesi** [Vencord/plugin-requests#218]
### Plugin Description

I had used another software before and it had the "become a mod" option. It seemed like I could do everything the server owner could do. It would be nice if you bring a nice plugin to troll my friends.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
if you mean the view server as role plugin, its a native discord feature that you can access by having the manage roles permission.

aliucord never had become mod plugin

**Comment by ayakgurmesi** [comment]
> if you mean the view server as role plugin, its a native discord feature that you can access by having the manage roles permission.
> 
> aliucord never had become mod plugin

I couldn't find the link to the plugin in the program called Acord of the developer named TheArmagan. The developer's discord server = https://discord.gg/armagan-nin-projeleri-1078486841688342568

**Comment by Koishukaze** [comment]
> > if you mean the view server as role plugin, its a native discord feature that you can access by having the manage roles permission.
> > aliucord never had become mod plugin
> 
> I couldn't find the link to the plugin in the program called Acord of the developer named TheArmagan. The developer's discord server = https://discord.gg/armagan-nin-projeleri-1078486841688342568

Its simply impossible to become an admin in any server

**Comment by ayakgurmesi** [comment]
> > > if you mean the view server as role plugin, its a native discord feature that you can access by having the manage roles permission.
> > > aliucord never had become mod plugin
> > 
> > 
> > I couldn't find the link to the plugin in the program called Acord of the developer named TheArmagan. The developer's discord server = https://discord.gg/armagan-nin-projeleri-1078486841688342568
> 
> Its simply impossible to become an admin in any server

You misunderstood, I am only talking about appearing as an administrator on my own screen. Those on the server will not see me as an administrator. I will not be able to do anything related to the server. I am only talking about being able to enter the server settings on my own screen.

**Comment by MrDiamondDog** [comment]
> > > > if you mean the view server as role plugin, its a native discord feature that you can access by having the manage roles permission.
> > > > aliucord never had become mod plugin
> > > 
> > > 
> > > I couldn't find the link to the plugin in the program called Acord of the developer named TheArmagan. The developer's discord server = https://discord.gg/armagan-nin-projeleri-1078486841688342568
> > 
> > 
> > Its simply impossible to become an admin in any server
> 
> You misunderstood, I am only talking about appearing as an administrator on my own screen. Those on the server will not see me as an administrator. I will not be able to do anything related to the server. I am only talking about being able to enter the server settings on my own screen.

This is entirely useless. You won't be able to even *see* most of the settings.

**Comment by ayakgurmesi** [comment]
> > > > > if you mean the view server as role plugin, its a native discord feature that you can access by having the manage roles permission.
> > > > > aliucord never had become mod plugin
> > > > 
> > > > 
> > > > I couldn't find the link to the plugin in the program called Acord of the developer named TheArmagan. The developer's discord server = https://discord.gg/armagan-nin-projeleri-1078486841688342568
> > > 
> > > 
> > > Its simply impossible to become an admin in any server
> > 
> > 
> > You misunderstood, I am only talking about appearing as an administrator on my own screen. Those on the server will not see me as an administrator. I will not be able to do anything related to the server. I am only talking about being able to enter the server settings on my own screen.
> 
> This is entirely useless. You won't be able to even _see_ most of the settings.

For example, by right-clicking on the user, the options of ban, disconnect, assign a role, move the person to the channel appear, only the special URL location does not appear, but of course, you know, I was just offering an idea.-I'm sorry for my bad english...

**Comment by Kyuuhachi** [comment]
What, you want to see a bunch of right click menu items that don't work?

**Comment by ayakgurmesi** [comment]
> What, you want to see a bunch of right click menu items that don't work?

I like trolling my friends.

**Comment by Vendicated** [comment]
stupid/useless + acord is malware, do not bring it up
