### ISSUE TITLE
Bypass Plugins Button (BPB)

### ISSUE THREAD

**Issue by HeartX94** [Vencord/plugin-requests#221]
### Plugin Description

Dear Developers,

As someone who relies on plugins to enhance my _Vencord_ experience, I wanted to share an idea with you for a new feature that could make managing those plugins even simpler. Essentially, I suggest adding a bypass plugin button within the Vencord control panel.

Here's how it would work: When you click the button, all of your current plugins would be temporarily disabled. **But don't worry** – the system would remember which plugins were active beforehand. Then, once you click the button again, everything would snap back into place exactly as it was before.

This feature would come in handy for situations like debugging technical issues or comparing different combinations of plugins. Instead of manually enabling and disabling one plugin at a time, you could quickly and easily rule out entire groups of them with the push of a single button. Plus, since optimizing Discord performance is critical for user satisfaction, this feature could help identify bottlenecks caused by conflicting plugins.

Adding a bypass plugin button would fit well with Vencord's commitment to simplicity and ease of use.
Thanks for considering my suggestion!

Best regards,
Yan

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by fily-gif** [comment]
thanks Mr. GPT.
i dont really see a reason for this to exist, its not that hard to press 1 button, scroll and press another button to then filter by "active" and disable everything there imo.

**Comment by EdVraz** [comment]
> Instead of manually enabling and disabling one plugin at a time, you could quickly and easily rule out entire groups of them with the push of a single button

You know you can just select and deselect multiple plugins at the same time and then reload, works just fine.

Also this seems a lot like being Ai-written and a lot of it doesn't really make sense, please don't do that if you request a plugin again.

**Comment by HeartX94** [comment]
Here is the original text:

Hi everyone,

here is my idea. A bypass plugins button. What would it do and why have a bypass plugins button ?

If you have let's say 18 plugins activated and checked for example. And you want to disable all plugins to test something, but remember all the plugins you had before, so you could just press the PBB and it will "temporarlyx" shut it down.

When you're happy with your investigation or what you had to do, you can simply reactivate the PBB. Could be a toggle also doesn't really matter. You got the idea. 

We can see this often in audio production. You have always a bypass button.

I hope this idea haven't got sumbit before.



Here is what I asked: correct me that text above, check all the mistakes, you can also re-formulate if you wish.




Should had go with the fucking mistake. anyway.

**Comment by fily-gif** [comment]
featurecreepcord.

**Comment by Inbestigator** [comment]
Just make it yourself if you really want it
