### ISSUE TITLE
See who viewed message

### ISSUE THREAD

**Issue by Luminityq** [Vencord/plugin-requests#223]
### Plugin Description

The ability to see who viewed your message/forum/image/thread.. I'm sure you get the idea

This will be pretty useful

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
Creepy (Stalking).

**Comment by Luminityq** [comment]
> Creepy (Stalking).

How is this creepy?

**Comment by EdVraz** [comment]
> > Creepy (Stalking).
> 
> How is this creepy?

... Monitoring the actions of other users at all times so you know if they read your messages does NOT seem creepy to you? I would suggest seeking out professional help.

**Comment by Roki100** [comment]
> > > Creepy (Stalking).
> > 
> > 
> > How is this creepy?
> 
> ... Monitoring the actions of other users at all times so you know if they read your messages does NOT seem creepy to you? I would suggest seeking out professional help.

email entire meta, matrix, telegram, signal and others that their features are creepy to you then...

im not defending this suggestion as it makes no sense as a plugin but also calling such functionality creepy is weird

**Comment by EdVraz** [comment]
> > > > Creepy (Stalking).
> > > 
> > > 
> > > How is this creepy?
> > 
> > 
> > ... Monitoring the actions of other users at all times so you know if they read your messages does NOT seem creepy to you? I would suggest seeking out professional help.
> 
> email entire meta, matrix, telegram, signal and others that their features are creepy to you then...
> 
> im not defending this suggestion as it makes no sense as a plugin but also calling such functionality creepy is weird

In the context of Vencord (or rather Discord client modifications in general) and according to our ethos such a feature is considered creepy. I know your opinion might differ, but there's no reason for you to comment on every request of this kind that it "isn't creepy". It is annoying, spam and you do not contribute to the topic in any way. The same thing Vee mentioned [here](https://github.com/Vencord/plugin-requests/issues/207#issuecomment-2010888608) also applies in this case. I kindly ask you to refrain from commenting in these ways in the future. Any  sort of "message read confirmation" will not be accepted into Vencord and this is a final statement.

**Comment by Luminityq** [comment]
> > > > Creepy (Stalking).
> > > 
> > > 
> > > How is this creepy?
> > 
> > 
> > ... Monitoring the actions of other users at all times so you know if they read your messages does NOT seem creepy to you? I would suggest seeking out professional help.
> 
> email entire meta, matrix, telegram, signal and others that their features are creepy to you then...
> 
> im not defending this suggestion as it makes no sense as a plugin but also calling such functionality creepy is weird

Yeah.. Also TikTok allows you to see who viewed your video and usually profile

**Comment by EdVraz** [comment]
> > > > > Creepy (Stalking).
> > > > 
> > > > 
> > > > How is this creepy?
> > > 
> > > 
> > > ... Monitoring the actions of other users at all times so you know if they read your messages does NOT seem creepy to you? I would suggest seeking out professional help.
> > 
> > 
> > email entire meta, matrix, telegram, signal and others that their features are creepy to you then...
> > im not defending this suggestion as it makes no sense as a plugin but also calling such functionality creepy is weird
> 
> Yeah.. Also TikTok allows you to see who viewed your video and usually profile

Yeah.. Also TikTok is owned by a Chinese company that eats your data! Vencord in fact, is not owned by a Chinese company and also does not spy on you or collect your data.

Please use your brain.
