### ISSUE TITLE
Discord Password Plugin

### ISSUE THREAD

**Issue by catluizfilipi** [Vencord/plugin-requests#226]
### Plugin Description

I want a plugin that when discord is open, instead of simply opening it and leaving you free to do whatever you want, it shows a "Enter the password to access discord" because I think I'm not the only one who uses the same PC in the house and if you can make the password it can be numbers and letters for example: ILoveVencord2018.2024.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
#10 #54 #211
