### ISSUE TITLE
Disable "View Song" button on LastFMRichPresence

### ISSUE THREAD

**Issue by ayunami2000** [Vencord/plugin-requests#227]
### Plugin Description

Disable the "View Song" button on LastFMRichPresence plugin. I would like this because on mobile, the buttons do not work. There is already a toggle for the second button, so I only request one toggle for the "View Song" button. It would also make it look cleaner imo.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Yumiro** [comment]
i've opened up a PR that adds a toggle for this button: https://github.com/Vendicated/Vencord/pull/2292
