### ISSUE TITLE
mutual servers enhanced

### ISSUE THREAD

**Issue by justmohamedd** [Vencord/plugin-requests#230]
### Plugin Description

right click on any server and see who on your friend list is in it

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AftmostSeeker80** [comment]
1. Enable "Server Info" plugin
2. Restart Vencord
3. Open a server/right click on the icon
4. Select "Server info"
5. Click on the friends panel
