### ISSUE TITLE
Server searchbar

### ISSUE THREAD

**Issue by 8e3** [Vencord/plugin-requests#231]
### Plugin Description

A simple plugin, adding e.g. a magnifying glass in between the "direct messages" button and a users top server.
Upon interacting with the icon, a searchbar pops up, which can be used to find the server you are looking for. Matching servers will be listed below the searchbar. (Most stuff is very variable, just using my imagination lol)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Inbestigator** [comment]
Literally already a feature, just press ctrl+k

**Comment by katlyn** [comment]
To expand on the last comment: type `*` before your search to filter for just guilds, `#` for text channels, `!` for voice channels, and `@` for users. Discord support reference: https://support.discord.com/hc/en-us/articles/115000070311-Quick-Switcher

**Comment by 8e3** [comment]
> To expand on the last comment: type `*` before your search to filter for just guilds, `#` for text channels, `!` for voice channels, and `@` for users. Discord support reference: https://support.discord.com/hc/en-us/articles/115000070311-Quick-Switcher

Thanks, I wasn't familiar with this
