### ISSUE TITLE
Pin Servers

### ISSUE THREAD

**Issue by 8e3** [Vencord/plugin-requests#232]
### Plugin Description

This plugin is meant to be similar to the "pin dms" plugin. The title states it all, upon rightclicking a server, a new option to pin selected server shall show up.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by cheesesamwich** [comment]
what would this even do, couldnt you just move the servers to the top

**Comment by 8e3** [comment]
> what would this even do, couldnt you just move the servers to the top

if you join new servers a lot, you'd always have to sort them again

**Comment by trwy7** [comment]
> > what would this even do, couldnt you just move the servers to the top
> 
> if you join new servers a lot, you'd always have to sort them again

You just need to move a single item, you can do that, you can even put them in a folder.
