### ISSUE TITLE
Block Groupchat invites from forcing you into a groupchat

### ISSUE THREAD

**Issue by Crazycatwantsrtx** [Vencord/plugin-requests#239]
### Plugin Description

A plugin that lets you prevent being put in groups and keep friends, genius idea.
Its really awkward getting added to a groupchat right?

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
to prevent it entirely would require serverside changes (not possible)
automatically leaving group chats you get added to would be considered selfbotting (automating actions on your account that are very clearly being automsted is too risky, especially for something potentially "destructive")

also have you tried... Asking your friends to not do this? Your friends could DM you an invite link to the group instead

**Comment by Sqaaakoi** [comment]
> to prevent it entirely would require serverside changes (not possible) automatically leaving group chats you get added to would be considered selfbotting (automating actions on your account that are very clearly being automsted is too risky, especially for something potentially "destructive")
> 
> also have you tried... Asking your friends to not do this? Your friends could DM you an invite link to the group instead

I AM SO SORRY FOR WHAT I SAID LAST MONTH I TAKE IT ALL BACK I THINK I NEED THIS MAYBE ACTUALLY
