### ISSUE TITLE
Auto Idle. Like BetterDiscords AutoIdleAFK.

### ISSUE THREAD

**Issue by UglukOrc** [Vencord/plugin-requests#240]
### Plugin Description

I'd like to be able to control the settings of Idling, not just disable it. Like, BetterDiscord has AutoIdleAFK, Which lets you control the idling settings. Any way we can have this in Vencord? This is Better Discords Mod, https://betterdiscord.app/plugin/AutoIdleOnAFK Any way Vencord can add a mod like this? With Possibly more settings?
![image](https://github.com/Vencord/plugin-requests/assets/103696326/89b5544b-2b9f-46df-bd9c-7e82d9eef2f9)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by ItsDrike** [comment]
Just noting the similarity to #199 here, it's not the same request, it's more of an extension of my original issue, but I think these should be merged into a single issue, either this one, or my original one. I agree that being able to control the time it takes until you become idle would be a nice feature, not just the ability to disable auto-idle entirely.

**Comment by nvhhr** [comment]
yeah this should fall under #199
