### ISSUE TITLE
Netflix Discord RPC

### ISSUE THREAD

**Issue by szumi6760** [Vencord/plugin-requests#243]
### Plugin Description

So the plugin will display the  series/movie you are currently watching on netflix.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
https://premid.app/ does what you want
