### ISSUE TITLE
Channel locker - Client sided

### ISSUE THREAD

**Issue by xRedCrystalx** [Vencord/plugin-requests#245]
### Plugin Description

I couldn't find any similar request, so here is my idea.

### Explaination:
Client-sided plugin that can lock any text channel under password. Basically plugin would "lock" the channel on the client and whoever wanted to access it, they would need to write password. Something like current private/locked channel screen, just instead of "who can access it", there would be input password field. Something like this:

![image](https://github.com/Vencord/plugin-requests/assets/118546534/a54ca6c8-b348-45ea-9782-bfbcb629fd78)

### Why?
Security/privacy purposes. Especially for annoying brothers, sisters and friends. Sometimes I and maybe others don't really want xyz person to write and read to some people dms/channels.

Apologies for my bad English.

### Existing Plugin for other mod

Not that I'm aware of.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
https://github.com/Vencord/plugin-requests/issues/10 https://github.com/Vencord/plugin-requests/issues/54 https://github.com/Vencord/plugin-requests/issues/211

**Comment by 1price** [comment]
This is great!
