### ISSUE TITLE
Call audio compressor/limiter

### ISSUE THREAD

**Issue by liliantdn** [Vencord/plugin-requests#247]
### Plugin Description

An audio compressor/limiter plugin for discord calls, I'm not sure how calls work internally but either on the global audio output, or individual limiters per voices. This would prevent having to change everyone's volume so frequently, and reduce/remove clipping whenever people scream. I tried making this plugin myself a while ago using [DynamicsCompressorNode()](https://developer.mozilla.org/en-US/docs/Web/API/DynamicsCompressorNode) but I couldn't figure out out as I'm not knowledgeable enough on how audio works in discord.

IMO a plugin like this would greatly improve the experience of being in discord calls and could replace having to use VolumeBooster in a lot of cases. However it would probably need to be implemented in an easy-to-use way, because I'm assuming average people
don't know how to/want to spend time tweaking ratios, attack, release, etc. If needed I can 100% help with prototyping and choosing the right values for the "default" setup!

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
not possible because calls are handled by the discord_voice native module which plugins have 0 control over

**Comment by Kerman-ap** [comment]
which part of it isn't possible? the data capture part or the 'volume changing' part
