### ISSUE TITLE
Auto convert twitter and x links to fxtwitter and fixupx links

### ISSUE THREAD

**Issue by Nailington** [Vencord/plugin-requests#25]
### Plugin Description

https://twitter.com and https://x.com links embed poorly (or not at all) on discord. A common alternative is https://fxtwitter.com and https://fixupx.com that embed prettily, with more functionality (such as multi image tweets and video tweets embedding properly, and pretty much always works. I often manually convert links before sending a message (or editing the message because I forgot). A plugin that would change the url from either base domain to the fx ones would be convenient.

If you want to know more information on the "service", check out https://github.com/FixTweet/FxTwitter (I am not in any way affiliated with the repo)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
Can be done with TextReplace

**Comment by Nailington** [comment]
I had no idea that plug existed! Thanks for pointing that out. Sorry for making the issue without better research….
