### ISSUE TITLE
Mutual Count in Profile

### ISSUE THREAD

**Issue by Obsidianninja11** [Vencord/plugin-requests#250]
### Plugin Description

Add mutual counts in the profile (this exists in dms already, but when viewing someone's profile, you have to manually count mutual servers/friends/etc.).
This could be done by adding the count to the mutual tab name, or it could be done by adding it as an entry in the tab (see image).
<details>
<summary>Example Image</summary>

![image](https://github.com/Vencord/plugin-requests/assets/108832807/0efa1a3e-9f52-4b44-a4e9-9e0763771ada)

</details>

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
discord themselves are working on this
https://github.com/Discord-Datamining/Discord-Datamining/commit/89bb5956420ee14cf0227614a31a8042493f50d5#commitcomment-139526561
https://github.com/Discord-Datamining/Discord-Datamining/commit/23b826e3a363ed34508c2cb0369f44190187eae2#commitcomment-140268405
