### ISSUE TITLE
Force a server nickname

### ISSUE THREAD

**Issue by Katranune** [Vencord/plugin-requests#252]
### Plugin Description

Plugin that automatically changes a nickname in a server back to what the user themself set it as (if they have nickname perms).

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
selfbotting
