### ISSUE TITLE
User Volume Boost and Mic boost

### ISSUE THREAD

**Issue by Prianshu1** [Vencord/plugin-requests#254]
### Plugin Description

A plugin that can boost a user volume and we can increase our input sound too.

### Existing Plugin for other mod

https://betterdiscord.app/plugins?filter=better+volume

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
isn't that just this
https://vencord.dev/plugins/VolumeBooster

**Comment by candroid-man** [comment]
Where did this plugin go? It has completely disappeared

![image](https://github.com/Vencord/plugin-requests/assets/51019003/076c9f73-e1b0-4b89-9716-d20a5a5bd63c)

**Comment by nvhhr** [comment]
> Where did this plugin go? It has completely disappeared
If you use any browser version or Vesktop you won't have it due to technical limitations yet to be overcome.
