### ISSUE TITLE
soundboard

### ISSUE THREAD

**Issue by xdleonMC** [Vencord/plugin-requests#256]
### Plugin Description

soundboard working without nitro from every server (not sure if possible)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by xHyroM** [comment]
Duplicate of https://github.com/Vencord/plugin-requests/issues/32
