### ISSUE TITLE
Remove Gift Button

### ISSUE THREAD

**Issue by skylerzap** [Vencord/plugin-requests#26]
### Plugin Description

The title is pretty self explanatory. Please add a plugin that removes the gift button. It's more of a nuisance than anything and all of the time when I click on it, it's by accident. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
This can be done via quickcss
