### ISSUE TITLE
ChatGPT

### ISSUE THREAD

**Issue by NightStar-s** [Vencord/plugin-requests#261]
### Plugin Description

A plugin for ChatGPT by providing a prompt in a prompt box and it will paste the result in the message bar/box, just like how translation plugin works in the result but you get to see the reply of the prompt before sending, you also get to pick models and providing api key in the plugin settings

![image](https://github.com/Vencord/plugin-requests/assets/125619247/6570209f-a381-436d-9d07-66718000d37b)
![image](https://github.com/Vencord/plugin-requests/assets/125619247/afd95471-fee7-4b84-9a68-bd599ac17d89)
![image](https://github.com/Vencord/plugin-requests/assets/125619247/73a937e7-e080-4baa-8c3b-571eb9159970)

### Existing Plugin for other mod

https://github.com/edde746/shelter-plugins

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
Not useful for the general vencord user; maybe someone will make it as 3rd-party plugin
