### ISSUE TITLE
Personal Ai Assistant

### ISSUE THREAD

**Issue by Kraxplorer** [Vencord/plugin-requests#263]
### Plugin Description

A plugin named "Personal AI Assistant". This plugin uses the OpenAI API to provide AI responses to user queries.

The "/assistant" command works as follows:
- It first checks if an API key is defined in the settings. If not, it sends a message notifying the user to set the API key.
- It then checks if a query is defined. If not, it sends a message notifying the user to define a query.
- If both the API key and the query are specified, an AI-generated response will be sent.

## -------------------------------------------------------------------

![Bild 1](https://i.imgur.com/wXypjdz.png)
![Bild 2](https://i.imgur.com/a4Bj4E8.png)
![Bild 3](https://i.imgur.com/iirjJtj.png)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
literally just https://github.com/Vencord/plugin-requests/issues/261
