### ISSUE TITLE
Auto Rejoin

### ISSUE THREAD

**Issue by kazman115** [Vencord/plugin-requests#264]
### Plugin Description

I’m not sure this would be allowed but would an auto reconnect to channel after being kicked be fine? Like someone kicks you from a vc you automatically join back into. Sorry if this has already been suggested, is not allowed, or already suggested.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
I think this is a selfbot

**Comment by EdVraz** [comment]
Selfbot + not really possible (no difference between leaving yourself and being kicked afaik)
