### ISSUE TITLE
[Request] AvatarHover

### ISSUE THREAD

**Issue by ReDarkTechnology** [Vencord/plugin-requests#265]
### Plugin Description
AvatarHover was an old plugin in BetterDiscord but I can't search it up anymore and it's already out of date. So I'm requesting the plugin here.

It'd be nice to have something like this but for use avatars or server profiles, where it shows the image but at a higher resolution on hover. I think this is possible as one plugin? Though if it's too much of a hassle to make it one plugin, I might make another request for it.

It would be something like this:
![hover-example](https://github.com/Vencord/plugin-requests/assets/53262904/c942203e-3331-4436-8e50-7fb1e4077f64)

or maybe on servers (taken from ServerDetails plugin preview):
![image](https://github.com/Vencord/plugin-requests/assets/53262904/4077272d-2036-454c-99f8-dcd78cbd7424)

### Existing Plugin for other mod
BetterDiscord does have some good examples of this but not actually functioning as an avatar hover:
[StickerEmojiPreview (BetterDiscord)](https://betterdiscord.app/plugin/StickerEmojiPreview)
[ServerDetails (BetterDiscord)](https://betterdiscord.app/plugin/ServerDetails) (Might be deprecated)

### Request Agreement
- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
one request per issue please

serverinfo already exists

you might be interested in ViewIcons

**Comment by ReDarkTechnology** [comment]
Yeah I've had ViewIcons and ServerProfile turned on but it requires clicks to see the actual full avatar, a little inconvenient.
On this request I kind of just wanted to focus on the avatars, both of the plugins doesn't show the images "on hover" which is the point I'm trying to make here. Sorry if this is too much to ask for

**Comment by ReDarkTechnology** [comment]
This, kind of worked? Well, except that it doesn't actually show the higher resolution of the image. Will be using this until the request got reopened if that's even possible. Thank you for the QuickCSS though

AvatarHover basically made another popup on hover like what I did on the preview image there, getting the source url and then run it through a function that basically adds `?size=4096` at the end of it and then putting it as the popup image source, so I don't think this is possible with just css?

Maybe if ViewIcons have an option to do that (show higher res image on hover) in settings that could also work
