### ISSUE TITLE
Send Audio File As Voice Message

### ISSUE THREAD

**Issue by sang765** [Vencord/plugin-requests#269]
### Plugin Description

Allows automatic conversion of audio files such as **mp3, wav, m4a, ...** into `voice messages` allowing users (including mobile) to listen to that audio file on Discord without downloading the audio file.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
Exists
