### ISSUE TITLE
GifCaptioner

### ISSUE THREAD

**Issue by harukadotfr** [Vencord/plugin-requests#272]
### Plugin Description

**GifCaptioner**
This is a [BetterDiscord](https://betterdiscord.app/) plugin that adds a way to add a custom caption to a tenor gif from directly within discord. Gifs inside the gif picker will have a new button at the top left that will open a dialog to create a custom caption.

### Existing Plugin for other mod

Yes, here : https://betterdiscord.app/plugin/GifCaptioner

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by HenriqueRadical** [comment]
This would be sick

**Comment by Domicele** [comment]
hoping they will add this

**Comment by Sqaaakoi** [comment]
esmBot works as a user app now and can do so much more

**Comment by Domicele** [comment]
> esmBot works as a user app now and can do so much more

yea but the plugin kinda easier and a bit faster and i think It wouldn't hurt to add it
