### ISSUE TITLE
PlatformEmulator

### ISSUE THREAD

**Issue by DarknessSmile** [Vencord/plugin-requests#273]
### Plugin Description

A plugin that lets you trick Discord into thinking you're running on a different operating system.
example: https://github.com/Kyza/BetterDiscordPlugins , https://betterdiscord.app/plugin/PlatformEmulator

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by zymcs** [comment]
Plugin already exists, it is a third party one.
There are 2 versions. one made by a person who forked vencord and another made by someone else.
I don't think I can help you any further about third party plugins so I'd safely assume this should be closed.

**Comment by Vendicated** [comment]
not useful. potential risk to account

**Comment by FireStacks** [comment]
> not useful. potential risk to account

It is it is very useful ask me
