### ISSUE TITLE
"Fast Reading"

### ISSUE THREAD

**Issue by Dreadrith** [Vencord/plugin-requests#274]
### Plugin Description

Basically [this](https://github.com/ansh/jiffyreader.com) but for Discord. The "similar term" for it is Bionic Reading. 
Doesn't actually modify your own text when sending it but rather modifies everyone's message locally to look like the examples in that repository.
A personal suggestion is to also add an option for it to capitalize the first letter of every word and to have an easy way to toggle it off and on without going to plugins as it may get overwhelming sometimes.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Dreadrith** [comment]
I apologize. It turns out this feature request was [already made](https://github.com/Vencord/plugin-requests/issues/62). It seems like I looked at the wrong issues when searching for similar ones.

**Comment by nvhhr** [comment]
Check out my comment in the other issue
