### ISSUE TITLE
Button to clear all message history

### ISSUE THREAD

**Issue by Luminityq** [Vencord/plugin-requests#276]
### Plugin Description

A button to clear all message history to save time so you don‘t have to do it one by one 

### Existing Plugin for other mod

MessageLogger

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
just restart discord

**Comment by Luminityq** [comment]
ok, I searched for issues like this first time and didnt see it and then just seen it after posting this

**Comment by nvhhr** [comment]
Ctrl+R is a quick way to clear out all edits/deletions.
