### ISSUE TITLE
PlatformEmulator/WebSocket Spoofer

### ISSUE THREAD

**Issue by NotOnii** [Vencord/plugin-requests#280]
### Plugin Description

PlatformEmulator is a plugin that has previously existed for BetterDiscord and hasn't worked for nearly 4 years as the developer stopped maintaining it. I've linked the compiled copy below, which is in a master folder which also contains the complete source of the plugin.

PlatformEmulator is useful for a lot of development debugging as it allows you to spoof your websocket and desired UI specifications (Discord auto-updates as soon as this happens). I'm personally requesting this as I'm currently in the works of developing a mobile app with Discord integration that detects user platforms which would go so much smoother with this plugin. I don't believe this could be used in any malicious way that would have a big impact, and I couldn't find any other request regarding this plugin. I've also reached out to the developer who said they were not ever planning on updating it or remaking it.

Thank you.

### Existing Plugin for other mod

https://github.com/Kyza/BetterDiscordPlugins/blob/master/builds/PlatformEmulator.plugin.js

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
#273
