### ISSUE TITLE
jumptotop

### ISSUE THREAD

**Issue by sightie** [Vencord/plugin-requests#282]
### Plugin Description

go to top message of the channel you're viewing

### Existing Plugin for other mod

https://betterdiscord.app/plugin/JumpToTop

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
https://github.com/Vencord/plugin-requests/issues/4
