### ISSUE TITLE
favorite videos and images like gifs

### ISSUE THREAD

**Issue by MonsterHat** [Vencord/plugin-requests#284]
### Plugin Description

you can favorite videos and images like gifs and theres a section next to gifs that shows the favorited medias and u can send them like a gif.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/FavoriteMedia

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment]
already exists `FavoriteAnything`

**Comment by nvhhr** [comment]
https://github.com/Vencord/plugin-requests/issues/13
