### ISSUE TITLE
[Plugin Request] Increase allowed soundboard duration.

### ISSUE THREAD

**Issue by KronosThanato** [Vencord/plugin-requests#285]
### Plugin Description

I looked through the other open issues and other plugins, and didn't see anything else like this (if it is there I must be blind and apologize), I'm not sure if it is even possible, but can the allowed audio file duration for the soundboard be increased from 5 seconds to 10 seconds? or be removed entirely?

### Existing Plugin for other mod

I don't know of one.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
The soundboard sounds are saved on discords servers, they have a server sided check of how long a sound is and we cannot stop it or change it
