### ISSUE TITLE
BetterPingViewer

### ISSUE THREAD

**Issue by Spiderfffun** [Vencord/plugin-requests#287]
### Plugin Description

A better way to view all the pings you got.
Say you went to touch grass for a while, and you got a ton of pings from a ton of servers (help I'm at my limit), and you want to see each one of those pings without going thru the janky CTRL + K menu or the painfully scrolled serverlist, you would have no way to do it well.

What if there was a plugin that introduced a hotkey, which when pressed, will instantly lead you to one of the pings. These could be sorted by time, order, and could even have a whitelist/blacklist for specific channels and servers.

This could also be a menu that has a small preview of every message and a couple of quick shortcuts (middle click to mark as read, right click for extra stuff, left click to go to the full message)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
![Sqaaakoi-03-04-2024-00-00-35](https://github.com/Vencord/plugin-requests/assets/37475903/51ede37a-21cd-46ae-ad75-149c9c26e872)

**Comment by Sqaaakoi** [comment]
although, a "next ping" button or hotkey could be useful

**Comment by Spiderfffun** [comment]
> Did you try the inbox button in the top right toolbar?

I did not know that existed. Why is it so hidden away?? On mobile it used to have a whole menu

**Comment by Kyuuhachi** [comment]
> although, a "next ping" button or hotkey could be useful

[Ctrl+alt+shift+↑↓](https://support.discord.com/hc/en-us/articles/225977308--Windows-Discord-Hotkeys)

**Comment by Sqaaakoi** [comment]
> > although, a "next ping" button or hotkey could be useful
> 
> [Ctrl+alt+shift+↑↓](https://support.discord.com/hc/en-us/articles/225977308--Windows-Discord-Hotkeys)

oh yeah thats right
