### ISSUE TITLE
Chat Filter Bypass

### ISSUE THREAD

**Issue by TheGithubJoshua** [Vencord/plugin-requests#288]
### Plugin Description

A Plugin to bypass the built-in chat filter.

### Existing Plugin for other mod

BetterDiscord - https://github.com/danik4985/bd-chatfilterbypass

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
use textreplace

**Comment by KrstlSkll69** [comment]
Also this is just extremely bad, since it just gives a way for people to bypass automod or discord moderation bots.

**Comment by nin0-dev** [comment]
+ these days most servers block cyrillic letters/blank chars so that would just be useless and stupid

**Comment by TheGithubJoshua** [comment]
> use textreplace

Would be better to have it replace any words with a prefix with look-alike Unicode characters automatically like the BD plugin I referenced though.

**Comment by TheGithubJoshua** [comment]
> Also this is just extremely bad, since it just gives a way for people to bypass automod or discord moderation bots.

That's the point :trollface:

**Comment by nin0-dev** [comment]
> referenced

that's also possible with textreplace

**Comment by KrstlSkll69** [comment]
> > Would be better to have it replace any words with a prefix with look-alike Unicode characters automatically like the BD plugin I referenced though.
> 
> that's also possible with textreplace

Y'all need to just stop having this convo and close this request, this is extremely dangerous and not allow
