### ISSUE TITLE
Notification Reader Button

### ISSUE THREAD

**Issue by BoxEpicYT** [Vencord/plugin-requests#289]
### Plugin Description

Adds a Clear Button to the Server List and the Mentions Popout

### Existing Plugin for other mod

https://betterdiscord.app/plugin/ReadAllNotificationsButton

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
> [*] I checked the existing plugins and made sure my plugin doesn't already exist

**Comment by fily-gif** [comment]
[exists.](https://vencord.dev/plugins/ReadAllNotificationsButton)
