### ISSUE TITLE
Adblock / Questblock

### ISSUE THREAD

**Issue by Blazzycrafter** [Vencord/plugin-requests#290]
### Plugin Description

The simplest description?
ADBLOCK
or for now QuestBlock
yeah its an request to block an future annoying thing...

more explenation? an code that kills all running quest loggers... or just hides them permanently... (auto css for possible random id systens)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
css allows to target IDs that start with a specific string

+ you can just turn off quests in privacy settings
