### ISSUE TITLE
ReadAllNotificationsButton per folder

### ISSUE THREAD

**Issue by DovidP** [Vencord/plugin-requests#292]
### Plugin Description

A plugin to add a button to read all notifications in a specific folder.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by fres621** [comment]
builtin
1. right click folder
2. mark as read

**Comment by TetraTheta** [comment]
> builtin
> 
> 1. right click folder
> 2. mark as read

This depends on client's language and platform.  
In my language, I can only use that feature in Mobile version. In PC version, that button exists, but I can't click it because it is disabled.

For people like me, this feature request would be still useful.

**Comment by fily-gif** [comment]
> > builtin
> > 
> > 1. right click folder
> > 2. mark as read
> 
> This depends on client's language and platform.  
> In my language, I can only use that feature in Mobile version. In PC version, that button exists, but I can't click it because it is disabled.
> 
> For people like me, this feature request would be still useful.

I have never heard of that. You can also just change your language to English.

**Comment by TetraTheta** [comment]
> I have never heard of that. You can also just change your language to English.

Change Discord language from my language to English only to use 'Mark as read'? I don't think that's good idea. To me, that looks like "Ils n'ont pas de pain? Qu'ils mangent de la brioche!"

**Comment by AftmostSeeker80** [comment]
if you're French, the button works
![image](https://github.com/Vencord/plugin-requests/assets/55350217/58c95004-3454-48e6-97b3-020a87156697)

**Comment by AftmostSeeker80** [comment]
try this, sauce is a Reddit post
![image](https://github.com/Vencord/plugin-requests/assets/55350217/42a2a348-63e8-442d-9867-8ebd9fa35e5e)

**Comment by TetraTheta** [comment]
> try this, sauce is a Reddit post

Thank you, that worked!

But since I want to mute all those servers in that folder, I think I must accept current behavior. I really wonder why Discord decided to make things like this...

**Comment by Vendicated** [comment]
if all servers are muted, then what's the point of marking them as read? they don't show unreads anyway don't they?
