### ISSUE TITLE
Add volume control to SpotifyControls

### ISSUE THREAD

**Issue by Lightning-isnt-a-dev** [Vencord/plugin-requests#293]
### Plugin Description

Just an addition to SpotifyControls, an integrated volume slider.

### Existing Plugin for other mod

https://github.com/mwittrien/BetterDiscordAddons/blob/master/Plugins/SpotifyControls/SpotifyControls.plugin.js

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
already a thing. right click the album art

**Comment by Lightning-isnt-a-dev** [comment]
i feel like that should be said in the plugin description/settings lol
