### ISSUE TITLE
Client side profile picture changer

### ISSUE THREAD

**Issue by kavkaz1** [Vencord/plugin-requests#294]
### Plugin Description

Some people have the dumbest profile pictures I have ever seen that make me want to to pour bleach inside my eyes. It would be SO GOOD if a plugin existed that would make it so you could change the profile picture of someone clientside (only seen by you). I'm not sure if that's legally allowed but hey, that would be neat.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AftmostSeeker80** [comment]
Doable with css

```css
[src^="https://cdn.discordapp.com/avatars/USERID/"] {
    content: url(LINK);
}```
just replace USERID with their ID and LINK with the image link (might need some tinkering)

**Comment by Vendicated** [comment]
Also duplicate of https://github.com/Vencord/plugin-requests/issues/102
