### ISSUE TITLE
Resize channel list section

### ISSUE THREAD

**Issue by Renmw** [Vencord/plugin-requests#296]
### Plugin Description

ability to resize/collapse the "channel list" section on discord
![cccccccc](https://github.com/Vencord/plugin-requests/assets/69709899/bd64c9ca-0ab4-4698-b1d1-a82acb904692)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
css
