### ISSUE TITLE
Quick Leave/Server Actions

### ISSUE THREAD

**Issue by 1price** [Vencord/plugin-requests#297]
## Quick server actions | Requested by 1price

- Removes the pesky confirmation box when leaving a server.
- Adds other small tweaks to the server options menu
- Allows you to mass purge selected servers

Super useful if you've been bot added to unwanted servers - or you just want more organisation of your server assortment. I also know that this has been a heavily requested feature throughout discord's history.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
Leaving multiple servers at once is api abuse/self botting and therefore not possible.

If you've been bot added, that's a skill issue on your end for allowing an app to add you to servers tbh.
