### ISSUE TITLE
Shared servers (MutualServers) in member list

### ISSUE THREAD

**Issue by Nieme** [Vencord/plugin-requests#298]
### Plugin Description

Show a icon next to the user if the user has a shared server.
With mouse over this icon (or click) you see all the shared servers with this user.
Maybe having the icon show the number (How many servers you share with the user).

### Existing Plugin for other mod

https://vencord.dev/plugins/MutualGroupDMs

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
Server Profile does this
