### ISSUE TITLE
Display Last Seen Status Date

### ISSUE THREAD

**Issue by triple7inc** [Vencord/plugin-requests#300]
### Plugin Description

Display the LAST SEEN date for users in the DM and on their profile for when they were as last online (any other than offline), with different examples depending on the time range.
![image](https://github.com/Vencord/plugin-requests/assets/34259253/2410ce9a-b4b0-4971-9d7a-8537da2621dc)
![image](https://github.com/Vencord/plugin-requests/assets/34259253/c7307aec-3cec-41fc-919c-943611ee94d0)
![image](https://github.com/Vencord/plugin-requests/assets/34259253/8dec1d33-4ea5-4c93-ae38-55c25739d955)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Inbestigator** [comment]
Wouldn’t that require tracking all of your friends? I’m sure Discord doesn’t just give out info like that.

And what happens if they log off while you’re offline?

**Comment by triple7inc** [comment]
> Wouldn’t that require tracking all of your friends? I’m sure Discord doesn’t just give out info like that.
> 
> And what happens if they log off while you’re offline?

This will only work whenever you are _online_ and store it locally by checking changes in their online indicator, even invisible would act as if they are offline unless you receive a message from them (or any other activity) while invisible which indicates that they are online.

**Comment by triple7inc** [comment]
> You could hypothetically do that by tracking status changes, but that would be insanely creepy, especially if you do that without your friends knowing

I require this to track the last online time of my customers to provide better support, and, yes, on many messaging apps this is enabled by default.
