### ISSUE TITLE
Steam friend list with games friends are playing

### ISSUE THREAD

**Issue by benni2250** [Vencord/plugin-requests#301]
### Plugin Description

Similar to the spotify player above account panel, but with steam friend list. 

### Existing Plugin for other mod

https://vencord.dev/plugins/SpotifyControls

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment]
this is probably not possible
