### ISSUE TITLE
SpotifyControls

### ISSUE THREAD

**Issue by hanahcom** [Vencord/plugin-requests#303]
### Plugin Description

Spotify controls that looks like the BetterDiscord one (has an image of the song that is playing)
<img width="168" alt="Screenshot 2024-04-06 at 3 11 24 pm" src="https://github.com/Vencord/plugin-requests/assets/155699910/b64e151c-33c0-42a0-bcfa-0a46d139681e">

### Existing Plugin for other mod

https://betterdiscord.app/plugin/SpotifyControls

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AftmostSeeker80** [comment]
Already a thing and it can be done with css
The https://discord.com/channels/1015060230222131221/1028106818368589824 channel has plenty of styles for it
