### ISSUE TITLE
Disable selected activities on specific servers

### ISSUE THREAD

**Issue by krisoguild** [Vencord/plugin-requests#304]
### Plugin Description

I would love to see a plugin that allows you to disable selected activities shown in servers.

For example I have a server for friends we usually play in, and i want them to be able to see I am currently listening to spotify or playing some game.

BUT I have a server for my job that I do and write work stuff for my co-workers and I DO NOT want them to see if I am playing a game or listening to spotify or doing any activity that is shown in the member bar

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
already exists in stock, go to the server name > privacy settings
![image](https://github.com/Vencord/plugin-requests/assets/75569739/fc269647-b856-4d9b-b9e3-2b1e1420e742)

**Comment by krisoguild** [comment]
This does not work properly for a long time hence thats why I requested this plugin

**Comment by nin0-dev** [comment]
If you have the person friended or have a mutual server where presence is allowed then ofc it won't work

also that is impossible for Vencord to control
