### ISSUE TITLE
Spotify Lyrics

### ISSUE THREAD

**Issue by DomenicUrso** [Vencord/plugin-requests#306]
### Plugin Description

A plugin that shows lyrics when the spotify controls are hovered. Something like [/akashrchandran/spotify-lyrics-api](https://github.com/akashrchandran/spotify-lyrics-api) could be used to fetch the lyrics.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
This is a textbook example of feature creep / bloat, no offense. If someone makes a third party plugin for this, that's fine, but something like this should not belong into Vencord. It would be a pain to make it fit nicely, and a nightmare to support and maintain.

**Comment by DomBom16** [comment]
Sorry :(
