### ISSUE TITLE
[Request] ScrollToLast

### ISSUE THREAD

**Issue by icrazykola** [Vencord/plugin-requests#307]
### Plugin Description

Automatically opens to the last message sent when you open a channel.
Please save my fingers from endless scrolling and mashing the escape button 🙏🙏

### Existing Plugin for other mod

BD used to have one, might be extremely outdated but I found the plugin on here - https://github.com/Inve1951/BetterDiscordStuff

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
I dont think this is really useful; escape button is not much effort to press
