### ISSUE TITLE
Plugin for emotes selection no bugged

### ISSUE THREAD

**Issue by harukadotfr** [Vencord/plugin-requests#309]
### Plugin Description

Make a plugin that displays the FULL list when you type :emote in the list of emojis that appears (without bug)
![Discord_YFtPKwH2L8](https://github.com/Vencord/plugin-requests/assets/143806235/31d77827-b741-4539-9a89-fc254b5b0d24)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Faf4a** [comment]
(with bug)

![trolley](https://cdn.discordapp.com/emojis/1223962219247833158.webp?size=44&quality=lossless)

**Comment by harukadotfr** [comment]
?

**Comment by Faf4a** [comment]
Jokes aside, I'm pretty sure Discord already does this unless I'm tripping (correct me if so).

They already show all matches for they keyword you're typing.

**Comment by Vendicated** [comment]
this is a favouriteemojifirst bug
