### ISSUE TITLE
More files uploader

### ISSUE THREAD

**Issue by OlegSavitskiy** [Vencord/plugin-requests#311]
### Plugin Description

When trying to upload more than 10 files plugin automatically sends several messages instead of popping out window that you cant upload more than 10 files (images for example)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
First why would you need to upload so many files

Second that's selfbotting

**Comment by MrDiamondDog** [comment]
This is very similar to a message splitter plugin, which is self botting.

**Comment by Vendicated** [comment]
For future reference, there's nothing selfbotty about it as long as it has a sanity limit to prevent people from sending 1 morbillion messages at once

but also why would you need this? way too niche and just not very useful

**Comment by Sqaaakoi** [comment]
1. if this isnt selflbotting, can we get a split messages plugin?
2. discord is not a reliable file host. what do you need loads of small individual files for? just use an archive format and upload that (hmmmm, this could be a plugin?)

**Comment by OlegSavitskiy** [comment]
> 1. if this isnt selflbotting, can we get a split messages plugin?
> 2. discord is not a reliable file host. what do you need loads of small individual files for? just use an archive format and upload that (hmmmm, this could be a plugin?)

I often send lots of screenshots and dont like counting in folder exactly 10 files every time. And archive format also doesn't suit me

**Comment by Sqaaakoi** [comment]
> > 1. if this isnt selflbotting, can we get a split messages plugin?
> > 2. discord is not a reliable file host. what do you need loads of small individual files for? just use an archive format and upload that (hmmmm, this could be a plugin?)
> 
> I often send lots of screenshots and dont like counting in folder exactly 10 files every time. And archive format also doesn't suit me

okay; this is actually a very good legitimate use case

**Comment by Dynamixus** [comment]
Came here to add my +1's and 2 cents. I am currently using Discord right now as sort of an album, with separate channels for my pictures for each category/event. I have hundreds of photos for each one and drag-and-dropping ten at a time is taking a lot of time and sometimes I miss that it's already finished so I can move on to the next batch.

What I'm thinking of is sort of a Queue-like feature, where I can select a bunch of files that will upload it to the channel 10 at a time before moving on to the next batch.

**Comment by Delta0S** [comment]
> but also why would you need this? way too niche and just not very useful
@Vendicated
 
When I use markdown and emojis to make things look nice, it takes up a lot of space. By breaking up the text, I can make sure everything fits and is easy to read, without losing any important info.
