### ISSUE TITLE
Reaction Logger

### ISSUE THREAD

**Issue by IamChristianS** [Vencord/plugin-requests#312]
### Plugin Description

The same feature-set that MessageLogger has, but applied to reactions. It could have a series of reactions next to the non-deleted ones, with just a red highlight, or maybe an additional menu to the reactions page. Not sure how possible this is, or even how much it could log, but it'd be nice to mess with friends together.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Inbestigator** [comment]
But like, why?
