### ISSUE TITLE
[Request] Custom Stream Preview

### ISSUE THREAD

**Issue by Wikinger8** [Vencord/plugin-requests#315]
### Plugin Description

Lets you use a custom image to render as the stream preview.

### Existing Plugin for other mod

https://github.com/YofukashiNo/BetterDiscordPlugins/blob/master/DiscordBypasses.plugin.js https://github.com/YofukashiNo/DiscordBypasses

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
Sounds like a css thing

**Comment by Kyuuhachi** [comment]
Css can't change what's sent to other people looking at the stream preview.

**Comment by EdVraz** [comment]
> Css can't change what's sent to other people looking at the stream preview.

I would've expected there to be a css class or something, my bad

**Comment by Sqaaakoi** [comment]
Just curious, why do you need to customise this? There is literally no reason to do this other than to bait people into joining your VC and watching your stream

**Comment by Wikinger8** [comment]
I don’t really know I used it in the past on betterdiscord and I thought it was cool to put your own image in their.

**Comment by EdVraz** [comment]
Okay then this is feature creep as closing reason

Also to explain my css closing, I thought this was about changing what you see as preview of other users locally, not what other users see as your preview lol
