### ISSUE TITLE
[Request] No Idle

### ISSUE THREAD

**Issue by Wikinger8** [Vencord/plugin-requests#316]
### Plugin Description

Stops Discord from setting your presence to idle. 
![image](https://github.com/Vencord/plugin-requests/assets/85295145/f53f3def-593b-4ed2-9679-817248adafe3)
I mute myself on my headset and not on Discord and so after about 20 minutes Discord thinks I'm gone, but I'm there and I want other people to know that too.

### Existing Plugin for other mod

https://github.com/YofukashiNo/BetterDiscordPlugins/blob/master/DiscordBypasses.plugin.js

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by waresnew** [comment]
I think this should go under #199
