### ISSUE TITLE
PRIVATE CHAT FOLDERS AND +

### ISSUE THREAD

**Issue by PELLYPELLY** [Vencord/plugin-requests#317]
### Plugin Description

The title says it all, like there are server folders, add **dm folders** to sort your friends and maybe even creating and **adding roles to friends** to sort them (Ex: valorant role: finding people who play valorant). Not that they are automatic but that **the user makes it**. And also maybe being able to have an **extra option on friend requests** to **invite them to a server** **without adding them.** **Thanks for ur time :)**
_-_PELLYPELLY_-_

(Also please specify more for some plugins, just a simple description is enough.

### Existing Plugin for other mod

No

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
There already is pindms, the rest doesn't really seem useful.

**Comment by Sqaaakoi** [comment]
friend roles/tagging is very useful actually

**Comment by KeiBoogie** [comment]
I want DM folders too. I do a lot of business communications and I also use discord personally and want a way to sort my dms

**Comment by Shenlmao** [comment]
i want DM folders. i use the plugin that removes guild pictures from folders because i want a clean discord. now my whole discord is clean but my dms are still messy.

**Comment by lewisakura** [comment]
This is possible with PinDMs' categories. Please do not necro threads.
