### ISSUE TITLE
assign badges

### ISSUE THREAD

**Issue by Xelo2** [Vencord/plugin-requests#318]
### Plugin Description

The plugin will have option to add/remove any badge that is on discord like all boosting badges, nitro badge, active developer badge, announ as and more, On the badge announ as will the user have option to set any username and tag and the other peoples with this plugin will can see other users badges.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
Badges are meant to represent something and shouldn't be faked, this is pretty useless anyway

**Comment by nin0-dev** [comment]
That's honestly stupid, it can easily allow impersonation, and if this was to be added it likely wouldn't support custom badges since these are perks for contributors/donors

**Comment by MrDiamondDog** [comment]
It won't be added. This specific plugin has been discussed many times before, it is not going to be a thing. It is useless and badges are meant to be earned, not cheated
