### ISSUE TITLE
Google Search and Send with command

### ISSUE THREAD

**Issue by Wraient** [Vencord/plugin-requests#319]
### Plugin Description

Google any query within DM or Server, and send the result in the channel. The search engine could be google or any other search engine. This could be done similar to how a cli-search program [Tuxi](https://github.com/Bugswriter/tuxi) works.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
user installable apps can solve this
