### ISSUE TITLE
Nitro soundboard?

### ISSUE THREAD

**Issue by holmat1** [Vencord/plugin-requests#32]
### Plugin Description

Sorry if someone already requested it (or if it isn't possible), I looked everywhere and noone really suggested it. A plugin (or a part of FakeNitro), that gives us access to the full soundboard (using sounds from other servers, no soundboard sounds limit)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
Not possible

**Comment by mynameisbob1928** [comment]
couldn't you like, fetch the sound and then play it through your mic or does that need kernel stuff

**Comment by cheesesamwich** [comment]
at that point just use an actual soundboad software 😭

**Comment by mynameisbob1928** [comment]
aight 💀
