### ISSUE TITLE
Remove embedded for custom domains

### ISSUE THREAD

**Issue by Makishima** [Vencord/plugin-requests#324]
### Plugin Description

Discord often creates previews for links, if it is behind authentication, then only the favicon and a brief description are shown.
It would be nice to have the ability to specify different domains for which the plugin will remove embedded content.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
removing the embed seems like a dumb idea that will only lead to curiosity and disappointment. somehow re-requesting the embed data on the client with authentication would be useful.

**Comment by Makishima** [comment]
> somehow re-requesting the embed data on the client with authentication would be useful.

We have internal tracker like jira.internal.com which discord does not and will not have access to, so I want to remove embedding link to that domain but keep gif and other public links

**Comment by Inbestigator** [comment]
Just don’t specify head data

**Comment by Vendicated** [comment]
you can probably do this with css + not useful
