### ISSUE TITLE
A plugin that allows you to password-protect a channel from local

### ISSUE THREAD

**Issue by Joseleelsuper** [Vencord/plugin-requests#327]
### Plugin Description

# Protected channels
## Description
Password protect text channels.

## Idea
The plugin should be able to add an option to a text channel after right clicking on it which is: "protect with password". The user will type the password in the channel and it will be password protected.

### How should it work?
Once it is password protected, you must go to another server's channel to view the channel so that you have to enter the password again. I would like it to be configurable, but since I'm not going to program it I'm not asking for much.

### What happens if you lose the password?
It would be a lot of work to try to create a system that sends you an email to the email assigned to the discord account, so the only viable option would be to delete the channel.

### What happens if you want to unprotect the channel?
Once protected, there would be the option to "Delete password", where you must enter the password once and then it is deleted.

### Will the password affect all users who can view the channel?
No. The password only works locally. If you want to access that channel, you must enter a password.

## Image
Here is an example image (Yes, is so realistic)
![image](https://github.com/Vencord/plugin-requests/assets/51025490/940cadf6-7a6c-43e8-a4bf-6f6f939ca0fe)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
#245 #226 #211 #54

**Comment by AftmostSeeker80** [comment]
*uninjects Vencord*
oh look, I can see the channel
https://discord.com/channels/1015060230222131221/1026515880080842772/1209103203577110539
