### ISSUE TITLE
ChannelTabs

### ISSUE THREAD

**Issue by Baanner** [Vencord/plugin-requests#328]
### Plugin Description

ChannelTabs

Adds tabs and bookmarks to Discord, just like in a normal web browser.
![favorites](https://github.com/Vencord/plugin-requests/assets/52113189/b0b0dd87-2241-42ed-a4de-d898bf6d3e3d)

### Existing Plugin for other mod

https://betterdiscord.app/plugin/ChannelTabs

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
> [ x ]  I checked the existing plugins and made sure my plugin doesn't already exist

You did not read

#6
