### ISSUE TITLE
A plugin that searches a server's memberlist for people that have mutual servers/friends with you 

### ISSUE THREAD

**Issue by magic-teo** [Vencord/plugin-requests#329]
### Plugin Description

I would like to be able to open a server, and then be able to check if anyone else in that server shares mutual friends or servers with me. I assume that this would only work in servers under 1000 people due to admin perm issues but I honestly have no idea. 

### Existing Plugin for other mod

n/a (remember something similar existed in like late 2021 but I cannot find any trace of it)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
ServerProfiles does this

**Comment by magic-teo** [comment]
> ServerProfiles does this

not quite, that shows you friends in the server, I am looking for people who I am NOT friends with who share mutual friends or servers.

**Comment by Sqaaakoi** [comment]
this will probably result in a lot of api calls and be extremely slow so no

**Comment by MrDiamondDog** [comment]
@Sqaaakoi is right- this would be an insane amount of api calls for large servers, so this is a definite no
