### ISSUE TITLE
QuickDelete Plugin

### ISSUE THREAD

**Issue by BedBug2479** [Vencord/plugin-requests#333]
### Plugin Description

Plugin to remove the confirmation window while deleting a message

### Existing Plugin for other mod

https://actuallythesun.github.io/vendetta-plugins/QuickDelete/

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
#38 also just hold shift while deleting messages
