### ISSUE TITLE
APNG (Animated Portable Network Graphics) Back

### ISSUE THREAD

**Issue by sang765** [Vencord/plugin-requests#335]
### Plugin Description

I don't know how to explain it, but simply put, this required plugin will allow **Vencord & Vesktop** to view messages with images in APNG format without having static frames when sending files like regular PNG. Discord has broken the APNG animation view on messages because there are some Discord users who can use APNG as an animated avatar without needing nitro. I think this is not a difficult thing for plugin makers so I hope it can return. Thank.

![Vesktop_DGEWpO7QkB](https://github.com/Vencord/plugin-requests/assets/80249864/a23295fb-3469-46fc-b5c4-a6d64241c4f9)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
this is not possible because discord strips apng data from pngs
