### ISSUE TITLE
TidalControls

### ISSUE THREAD

**Issue by ItsGfue** [Vencord/plugin-requests#337]
### Plugin Description

The same thing as SpotifyControls but for Tidal i dont know if its possible Tidals API is out so it may be i found one that used neptune for Tidal but Neptune stopped working, ill link the one that uses neptune

### Existing Plugin for other mod

https://github.com/trebor048/TidalControls

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by marie0llie** [comment]
this would be nicer if it was just for *any* media player being used on the system, although i have no clue how possible such a plugin would be. every os (typically) has a media server that can be interfaced with, and can be controlled as well. so. idk?

**Comment by Vendicated** [comment]
> this would be nicer if it was just for any media player being used on the system

i was planning to do this, for linux via mpris

tidal is likely not possible

**Comment by Vendicated** [comment]
closing in favour of of #198
