### ISSUE TITLE
Auto-Capitalisation

### ISSUE THREAD

**Issue by firegink** [Vencord/plugin-requests#338]
### Plugin Description

Make it so that the first letter and the letter 'I' are automatically capitalized when I type on Discord. It would be beneficial for everyone as they wouldn't need to press an extra button or remember to do so themselves. This is an important feature to have.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Inbestigator** [comment]
![dreamstime_l_23226525](https://github.com/Vencord/plugin-requests/assets/119569726/91d39232-a9e7-49c8-a039-82d3c2f41a2c)

**Comment by Kyuuhachi** [comment]
Pretty sure you can do that with textreplace.
