### ISSUE TITLE
Support for Opera GX

### ISSUE THREAD

**Issue by jkadukara** [Vencord/plugin-requests#342]
### Plugin Description

Support for Opera GX so that while screen sharing it won’t display black. Chrome does not have this issue.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
Fuck opera :3

**Comment by Vendicated** [comment]
(not a vencord issue)

**Comment by Grafaffel** [comment]
stop using spyware
