### ISSUE TITLE
Copy Role Icons

### ISSUE THREAD

**Issue by iwokeupinchrisbrownsbody** [Vencord/plugin-requests#346]
### Plugin Description

Plugin that lets you right click (or do some other keybind) on a role icon, giving you the option to copy the image. Some servers directly upload PNGs as role icons, making it to where you can't steal those emojis. (would also work well if incorporated with one of the, already existing, "copy role colors.")

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
As a workaround, you can grab the url to any image including role icons with devtools (ctrl+shift+i); hit the inspect button topleft and then the icon.
