### ISSUE TITLE
Hidden Blocking

### ISSUE THREAD

**Issue by MochyPei** [Vencord/plugin-requests#348]
### Plugin Description

I need plugin what can hide messages from users, without blocking them Discord profiles, especially in servers (not DM's)

### Existing Plugin for other mod

https://github.com/lmharpae/DiscordHiddenBlocking

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
This would be horrible to implement with CSS though

**Comment by Vendicated** [comment]
false. enable the ThemeAttributes plugin, then it's as simple as
```css
[data-author-id="..."] {
    display: none;
}
```

**Comment by Sqaaakoi** [comment]
> false. enable the ThemeAttributes plugin, then it's as simple as
> 
> ```css
> [data-author-id="..."] {
>     display: none;
> }
> ```

i knew this was possible, but wouldnt this be ignored by stuff like Ctrl+up to reply? Also you 100% can't see it, which not everyone would want
