### ISSUE TITLE
[FEATURE REQUEST] Custom notification plugin

### ISSUE THREAD

**Issue by EthanWinters2885** [Vencord/plugin-requests#349]
### Plugin Description

A plugin that allows us to change the notification sounds in Discord.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/NotificationSounds

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by cheesesamwich** [comment]
there was a pr for this already

**Comment by nvhhr** [comment]
dupe https://github.com/Vencord/plugin-requests/issues/21
