### ISSUE TITLE
Friend List

### ISSUE THREAD

**Issue by LUPUF** [Vencord/plugin-requests#351]
### Plugin Description

A way to hide some friends or to separate them.  An example: A new tab on top (where you see online, all friend.....) where it could say "hidden friends". Friends that are hidden will not show on online tab neither at all friends tab.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/BetterFriendList

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment]
`PinDms` already alr does that

**Comment by LiIyKitsune** [comment]
pin dms doesnt do exactly what we're asking, also i already made this request like a week ago, its a mirror of better discord's "better friend list" plugin
