### ISSUE TITLE
(PLUGIN REQUEST) Favourite videos

### ISSUE THREAD

**Issue by pe99992** [Vencord/plugin-requests#353]
### Plugin Description

Basically lets you favourite videos and then post them quicker to someone, just like gifs

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
Also dupe https://github.com/Vencord/plugin-requests/issues/13
