### ISSUE TITLE
Copy AutoModded message

### ISSUE THREAD

**Issue by xparadoxical** [Vencord/plugin-requests#355]
### Plugin Description

A small QoL feature would be to be able to copy raw text of a message deleted by AutoMod. Currently it can only be deleted (with a button) / rejected (it's an ephemeral).
![image](https://github.com/Vencord/plugin-requests/assets/43796685/1ae4b6fe-fc75-4ca9-9ad6-f9e1f474cf66)
An extension of this would be to have more of the usual on-hover message buttons on all ephemeral&automod messages. But for me, `Copy Raw` that's provided by one of the plugins (see below, no clue which plugin it is) would be sufficient.
![image](https://github.com/Vencord/plugin-requests/assets/43796685/05425053-fcbb-4dd0-a642-3a6b1e962cd1)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by WildFyr16** [comment]
Yes! Please! I don't know why Discord does not nativly allow you to copy the text from those messages. You write a huge paragrah and it gets flagged because of one word and your fucked. Esspecally on mobile where you can't just select the text like you can on desktop.

**Comment by Vendicated** [comment]
should already be a stock feature. if not, can be done with css via `user-select: text` property

**Comment by WildFyr16** [comment]
Yes it should be a stock feature. Right after this comment I went to Discord Support and left a feature request for it.
https://support.discord.com/hc/en-us/community/posts/23343196385303-Copy-or-Edit-AutoMod-Flagged-messages

**Comment by xparadoxical** [comment]
It's not a feature on `Stable 291507 (e1c2bf8) Vencord 6ad17ff (Vesktop V1.5.2) Electron 29.1.1 Chromium 122.0.6261.111`, `stable 291507 (e1c2bf8)` (web) and `App: 227.12 (227012) googleRelease` (vanilla android discord).
All `.cozy .messageContent` already has `user-select: text` and it only lets you copy displayed text - copying raw markdown from automodded messages is the request.
