### ISSUE TITLE
UserPFP

### ISSUE THREAD

**Issue by KeiG1999** [Vencord/plugin-requests#358]
### Plugin Description

UserPFP
Animated profile pictures without nitro (Compatible with most client mods)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment]
Couldn't this be done with CSS?

**Comment by KrstlSkll69** [comment]
> Couldn't this be done with CSS?

it can just put 
`@import url(https://userpfp.github.io/UserPFP/import.css);` in quickCSS or put the link your online themes and join their server to request

**Comment by coolesding** [comment]
UserPFP Owner here: This is not official and not from us. We have already made a plugin [#1956 Vendicated/Vencord](https://github.com/Vendicated/Vencord/pull/1956) and are waiting for approval for months now. Do not impersonate us, do not submit requests in our name and inform yourself before you submit legitimate requests. Thank you very much.

If you want to use our UserPFP plugin right now, you can do so in https://github.com/equicord/equicord, which is a fork of Vencord that integrates fixes and requested plugin merges themselves and independent of Vencord.

**Comment by Grafaffel** [comment]
> UserPFP Owner here: This is not official and not from us. We have already made a plugin ( [#1956 Vendicated/Vencord](https://github.com/Vendicated/Vencord/pull/1956) ) and are waiting for approval for months now. Do not impersonate us, do not submit requests in our name and inform yourself before you submit legitimate requests. Thank you very much.

I was looking through the repo and found the link stylesheet for the PFPs (https://raw.githubusercontent.com/UserPFP/UserPFP/main/import.css) couldn't you just use this, or would it have horrible performance?

**Comment by coolesding** [comment]
> > UserPFP Owner here: This is not official and not from us. We have already made a plugin ( [#1956 Vendicated/Vencord](https://github.com/Vendicated/Vencord/pull/1956) ) and are waiting for approval for months now. Do not impersonate us, do not submit requests in our name and inform yourself before you submit legitimate requests. Thank you very much.
> 
> I was looking through the repo and found the link stylesheet for the PFPs (https://raw.githubusercontent.com/UserPFP/UserPFP/main/import.css) couldn't you just use this, or would it have horrible performance?

This is exactly why the plugin exists. Every user in our database generates 4 CSS rules. Since we are currently only about 1200 registered users, the performance impact is minor, but noticeable. If we grew to the size of Decor or UsrBG we wouldn't generate about 4800 rules, we would generate 360000, way more than discord has at the moment (and our rules are less performant than the average discord stock css rule).

**Comment by nin0-dev** [comment]
this should be closed as not planned, since the UserPFP PR got closed
