### ISSUE TITLE
DiscordPIN

### ISSUE THREAD

**Issue by vlocefn** [Vencord/plugin-requests#360]
### Plugin Description

A little plugin that when you open Discord it requests a pin and also has a little button to lock it back up

### Existing Plugin for other mod

BetterDiscord

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
this is like the [17 morbillionth duplicate](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue+sort%3Aupdated-desc+lock+is%3Aclosed+). please stop being lazy and actually check if requests were already made.
