### ISSUE TITLE
split large messages

### ISSUE THREAD

**Issue by Limitrious** [Vencord/plugin-requests#362]
### Plugin Description

something like split large message cuz i dont have nitro

### Existing Plugin for other mod

https://betterdiscord.app/plugin/SplitLargeMessages

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by programminglaboratorys** [comment]
> This would technically be API spam/selfbotting and thus is not allowed
already been requested #151 #77
