### ISSUE TITLE
Make Free Emojis even better!

### ISSUE THREAD

**Issue by Amadace** [Vencord/plugin-requests#363]
### Plugin Description

I recently created a script found here: https://greasyfork.org/en/scripts/492429-discord-keklol-emoji-add-on-without-nitro/code

This hides the text when the gif is embedded.

I have used a combination of invisible characters such that there is no text for the embedded link. Here is an example:

`[‎឴᠍](https://i.imgur.com/0CCc0Yr.png)`

You can inspect the characters within the square brackets here: https://apps.timwhitlock.info/unicode/inspect

Edit: To make it more clear, I know you can change the text manually in Vencord settings, but I suggest making it show it like that by default.

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Amadace** [comment]
Example message:
https://discord.com/channels/1015060230222131221/1026515880080842772/1230510814050521108

**Comment by Grafaffel** [comment]
So this script is just replacing `:keklol:` with an imgur link. Couldn't you just add this emoji to a private server?

**Comment by Amadace** [comment]
That's not the point here. The main part is the use of the combination of certain invisible characters so you don't have the embed text that's currently present.

**Comment by Grafaffel** [comment]
So this script is just replacing `:keklol:` with an imgur link. Couldn't you just add this emoji to a private server, if you're already using `FakeNitor`?

**Comment by Amadace** [comment]
That's not the point here. The main part is the use of the combination of certain invisible characters so you don't have the embed text that's currently present.

**Comment by Amadace** [comment]
No, FakeNitro shows a text with a hyperlink to image's url.

**Comment by Grafaffel** [comment]
> No, FakeNitro shows a text with a hyperlink to image's url.

[1] Shows a FakeNitro emoji
![1](https://github.com/Vencord/plugin-requests/assets/96660820/b6b65272-1393-402e-8558-efeeae192b27)

[2] Shows the supplied example message
![image](https://github.com/Vencord/plugin-requests/assets/96660820/117b8563-8a82-4e1a-ba88-64a329a5e64e)

If you're still encountering that issue, you can just change the contents of the FakeNitro Hyperlink in the Plugins settings.

**Comment by Grafaffel** [comment]
> Type a message and then put an emoji after that, like I did

I kinda feel like there is an issue with your vencord, or you don't have the plugin enabled
![image](https://github.com/Vencord/plugin-requests/assets/96660820/ea5e6772-a4db-4500-b08f-c9cda0d1a906)

**Comment by Amadace** [comment]
Oh... can you please send that in the #support channel so I can see how it's formatted

**Comment by shadowking1443** [comment]
Hey all! I apologize for necroing this thread, but wanted to ask if this was ever solved. Mine does the same thing, so I'm not sure if it's default behavior, or a setting issue.

**Comment by Vendicated** [comment]
as you have said yourself, you can achieve this using the plugin's settings

![image](https://github.com/Vencord/plugin-requests/assets/45497981/eb025196-d885-4415-9403-a64552696205)

as such i'll close this
