### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by fleymv** [Vencord/plugin-requests#364]
### Plugin Description

There is a plugin called "Timezones" on Betterdiscord and it should have a pretty similar use to that
U can right click a user and there should be a option of;
"Timezones"
Add Timezone
Remove Timezone
When pressed Add Timezone it pulls up all timezones from different countries and when u find the right one and u set the timezone to the user everytime they type it should look like this
exampleuser  — Their timezone / ur normal discord timezone
Also if u right click on their profile n select profile it should show their time as well ( betterdiscord has that as well )

### Existing Plugin for other mod

https://betterdiscord.app/plugin/Timezones 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment]
already exists in #third-party-plugins

https://discord.com/channels/1015060230222131221/1032200195582197831/1189470289638207488
