### ISSUE TITLE
Custom Timestamps in chat

### ISSUE THREAD

**Issue by mrnicedonovan** [Vencord/plugin-requests#365]
### Plugin Description

Having the option to fully customize the timestamps (in chat) changing it from being tied to language to making your own (for example 'HH:MM:SS MM:DD:YYY'
This so you can both see when a message is send exactly and change the language to Eng_US without having the US timestamp

### Existing Plugin for other mod

https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/CompleteTimestamps

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
#1
