### ISSUE TITLE
Middle Click Confirmation

### ISSUE THREAD

**Issue by potentialnerd** [Vencord/plugin-requests#37]
### Plugin Description

When you middle-click on an image in discord, it doesn't give you that little popup that asks you if you want to go to that domain. This could be useful for preventing links that try to phish you. This is a relatively small plugin, but I think it could be really useful. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
simply don't middle click
