### ISSUE TITLE
FakeGifPFP

### ISSUE THREAD

**Issue by nayadaa** [Vencord/plugin-requests#370]
### Plugin Description

Make your own, or put in a gif for your profile picture on discord (visible to _EVERYONE_ viewing/looking at you or your profile).

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
#358
