### ISSUE TITLE
Translator - Plugin Request

### ISSUE THREAD

**Issue by aymanbest** [Vencord/plugin-requests#371]
### Plugin Description

A translator make u able to translate messages to other languages
Allows you to translate Messages and your outgoing Messages within Discord

### Existing Plugin for other mod

https://betterdiscord.app/plugin/Translator

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
This exists

use the Translate plugin

**Comment by aymanbest** [comment]
its not perfect we need someone with other translate apis or the possibility to change them google translation is bad


> This exists
> 
> use the Translate plugin

**Comment by nin0-dev** [comment]
Such as? which apis

**Comment by aymanbest** [comment]
> Such as? which apis

Bing Yandex ... or even DeepL for more accurate translate
