### ISSUE TITLE
NotificationSounds - Plugin request

### ISSUE THREAD

**Issue by SniperQuiet** [Vencord/plugin-requests#374]
### Plugin Description

This plugin allows you to change your discord notification sounds to a custom ones, including incoming call, message notification, voice channel connecting, etc.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/NotificationSounds

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment]
discord might already be working on this: [Vencord Discord Server Message](https://discord.com/channels/1015060230222131221/1105582084237570088/1227336801774211164)

**Comment by danielah05** [comment]
the discord one from what i can tell is nitro only and per guild only (people are also speculating itll use the soundboard feature), it also probably doesnt let u set sounds like the calling sound, there is a pull request in vencord that lets u set custom sounds that u might be interested in instead https://github.com/Vendicated/Vencord/pull/1765

**Comment by Grafaffel** [comment]
can someone add pr pending to this?

**Comment by nvhhr** [comment]
This is also a duplicate request: #21
