### ISSUE TITLE
Passcode Lock - Plugin Request

### ISSUE THREAD

**Issue by seifdark12** [Vencord/plugin-requests#375]
### Plugin Description

This plugin does prevent people who are casually snooping. 

### Existing Plugin for other mod

https://github.com/arg0NNY/DiscordPlugins/tree/d6f8903acd8ac18636e6b8a0c83a8306ff0e5e9c/PasscodeLock

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/47912135/c99b0231-b4da-403a-a903-b420a9ece76a)
are you sure about that?

#10  #54 #211 #245 #360

**Comment by seifdark12** [comment]
Sorry i didnt see it on the page i checked.

**Comment by seifdark12** [comment]
i can delete it if u want
