### ISSUE TITLE
Server count

### ISSUE THREAD

**Issue by RunninPigeon** [Vencord/plugin-requests#377]
### Plugin Description

A number that tracks how many servers you're on.
Example: "Servers: 59"
It'll be located below the home button.

### Existing Plugin for other mod

_https://betterdiscord.app/plugin/ServerCounter_

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
Doesn't server list indicators already do this

https://vencord.dev/plugins/ServerListIndicators

**Comment by RunninPigeon** [comment]
ohhhhh i completley forgot about that woops
