### ISSUE TITLE
Channel DMs

### ISSUE THREAD

**Issue by Aang321123** [Vencord/plugin-requests#378]
### Plugin Description

Channel dms. Adds a button that can be clicked form the server list to switch to DMs which prevents as much scrolling 

### Existing Plugin for other mod

https://betterdiscord.app/plugin/ChannelDms

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
Use the quick switcher via ctrl+k to navigate to an unread or type the name of the person you want to navigate to.

**Comment by Vendicated** [comment]
ctrl + 1
