### ISSUE TITLE
Configuration Search (Bar)

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Vencord/plugin-requests#379]
#### **Description**

As https://github.com/Vencord/Vesktop/issues/454#issue-2190643035 states:

<blockQuote>

1.	#### **Is your feature request related to a problem? Please describe.**

	Finding specific configuration toggles can be incredibly difficult without prior knowledge of where they are.

	For instance, locating where the system autostart option was (for https://github.com/Vencord/Vesktop/issues/455#issue-2190649280) was unintuitive.
	
1.	#### **Describe the solution you'd like.**

	Add a search bar to Settings.
	
1.	#### **Describe alternatives you've considered.**

	Better yet, implement this in https://github.com/Vendicated/Vencord.git:

	> https://discord.com/channels/1015060230222131221/1026515880080842772/1218895628365729823
	
1.	#### **Additional context.**

	https://discord.com/channels/1015060230222131221/1026515880080842772/1218897155524268042

</blockQuote>

#### **Relevant**

1.	The query "https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue+search+bar" returned 0 relevant results.
1.	Transferred to here at the recommendation of https://github.com/Vencord/Vesktop/issues/454#issuecomment-2067786731.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by korbosoft** [comment]
it appears discord added this recently in an experiment

**Comment by Vendicated** [comment]
indeed. `2024-05_desktop_user_settings_search` experiment

![image](https://github.com/Vencord/plugin-requests/assets/45497981/2a8b8cc6-374b-4392-a163-30e0fecafad4)

vencord will integrate with it once it is a stable feature
