### ISSUE TITLE
One Click Delete

### ISSUE THREAD

**Issue by ModeratedNickname2-v2** [Vencord/plugin-requests#38]
### Plugin Description

- Removes confirmations for deleting things such as roles, messages and channels.

### Existing Plugin for other mod

https://github.com/rushiiMachine/aliucord-plugins/tree/a3177195b6050e78ac9190d0081f2d8f46ff83a3/1ClickDelete might not count but eh whatever

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by D3SOX** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/24937357/3191a6a9-4072-40b0-8977-9c86dc78f731)

To one-click delete messages you can already hold shift :) Doesn't seem to work for other stuff though

**Comment by Benzeel** [comment]
"no confirm" maybe instead for plugin name?

**Comment by cheesesamwich** [comment]
> "no confirm" maybe instead for plugin name?

that makes it seem like it removes all confirmation. Id suggest noDeleteConfirm but it might be too long

**Comment by nin0-dev** [comment]
vendetta calls it QuickDelete ig

we could use that

**Comment by Vendicated** [comment]
hold shift for messages

everything else is too niche
