### ISSUE TITLE
Spoiler embeds plugin

### ISSUE THREAD

**Issue by BurningButter** [Vencord/plugin-requests#381]
### Plugin Description

I think a good plugin would be a plugin that still shows embeded content but covers it with a spoiler like the ones we have for file uploads this would occur if the link has spoiler tags around it too. So for example if I sent someone a spotify song like so:
`||https://open.spotify.com/track/4PTG3Z6ehGkBFwjybzWkR8||`
It would also spoiler the embed of the track.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by BurningButter** [comment]
I sent a spoiled gif link and it just removed the embed tho.

**Comment by Vendicated** [comment]
put space between || and link.
