### ISSUE TITLE
Add ability to send messages through proxy

### ISSUE THREAD

**Issue by kostya315** [Vencord/plugin-requests#383]
### Plugin Description

For people who banned in Google for any reasons, would be comfortable if files can be sended through proxy. For example, people who live in Crimea, who can use Discord without any issues, but can't send media and files. (Proxy shouldn't be on all discord, only on files, because standard messages, voice calls, video, screenshare and etc works propertly and using proxy on whole app will add huge delay)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
why don't you use a system level split tunnel proxy for this

**Comment by kostya315** [comment]
> Proxy shouldn't be on all discord, only on files, because standard messages, voice calls, video, screenshare and etc works propertly and using proxy on whole app will add huge delay
I can't split proxy to only file sent as a regular user

**Comment by Vendicated** [comment]
just use a system level vpn
