### ISSUE TITLE
Message logger saves deleted messages

### ISSUE THREAD

**Issue by MonasChots** [Vencord/plugin-requests#385]
### Plugin Description

Have the message logger save deleted messages, ghost pings, etc. like 1Lightly's message logger.

### Existing Plugin for other mod

https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/MessageLoggerV2

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
I believe it was decided against, how the message logger is now will be how it is forever

**Comment by mynameisbob1928** [comment]
there is one as a third party plugin
https://discord.com/channels/1015060230222131221/1032200195582197831/1131677805550252092
