### ISSUE TITLE
Middle click scroll on Mac

### ISSUE THREAD

**Issue by Golonchy** [Vencord/plugin-requests#387]
### Plugin Description

as the title suggests, i would like a middle click scroll when pressing dows on the scroll wheel
this but for mac: https://github.com/Vencord/plugin-requests/issues/5
here is a video showing what i mean becuase i do suck at explaining things.
https://github.com/Vencord/plugin-requests/assets/165617563/642a5b1c-7378-42fc-be36-b9dd4f23999d

### Existing Plugin for other mod

i dont know

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
duplicate of the issue you've mentioned

**Comment by Golonchy** [comment]
But the other one was for Linux. 
Anyway stupid explaination, thanks tho
