### ISSUE TITLE
Automatic Folder Sorter

### ISSUE THREAD

**Issue by charlielichterman** [Vencord/plugin-requests#393]
### Plugin Description

Basically it would take info about the servers your in and sort them into respective folders

### Existing Plugin for other mod

No

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
but what would it sort them against
