### ISSUE TITLE
Destiny 2 Join Code Copier

### ISSUE THREAD

**Issue by JacobPlaysGames** [Vencord/plugin-requests#394]
### Plugin Description

Introducing a straightforward plugin designed to enhance your Destiny 2 gaming experience. This plugin automatically converts any Destiny 2 join code within messages into clickable links. Say goodbye to manual copying and pasting! Unlike TextReplace, this plugin exclusively targets join codes from other users' messages, leaving your own text untouched. With its potential for customization, this plugin can easily adapt to other gaming environments or any scenario requiring similar chat functionality.

### Existing Plugin for other mod

https://github.com/bodaay/DestinyLFGJoinInviteCopier

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
this is way too niche, we just need TextReplace for incoming messages

**Comment by JacobPlaysGames** [comment]
I agree I just used this as an example of something that already exists. As I stated this could easily be expanded for other use cases.
