### ISSUE TITLE
FakeBadge

### ISSUE THREAD

**Issue by MrLucaverus** [Vencord/plugin-requests#395]
### Plugin Description

Adds the ability to add discord badges to the profile, which cannot be obtained by ordinary mortals. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
dupe of #318 #194
