### ISSUE TITLE
Timezone Changer

### ISSUE THREAD

**Issue by Damn1611** [Vencord/plugin-requests#401]
### Plugin Description

I've been looking to change the displayed timezone within discord without actually having to change my system timezone. 
this is probably one of the most niche things to ask for and I doubt anyone will use it. essentially I prefer not to leak my time when taking screenshots or screensharing etc, thus being able to change it to a different timezone kind of masks it.
I saw something about changing the format of the timestamps, but I'm too stupid to modify that code to also accommodate for changing timezones.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
way too niche
use system level timezone changing
if you're on linux use the `TZ` environment variable

**Comment by Vendicated** [comment]
you could use css to hide timestamps entirely. or if you really care, change your system time. (fyi, git commits also leak your timezone lol)
