### ISSUE TITLE
Add NotificationSounds and BDFDB(Library)

### ISSUE THREAD

**Issue by errorcat404** [Vencord/plugin-requests#407]
### Plugin Description

Allows you to replace the native Sounds with custom Sounds

### Existing Plugin for other mod

https://betterdiscord.app/plugin/NotificationSounds  https://betterdiscord.app/plugin/BDFDB

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
Vendicated/Vencord#1765 and will also be added as a stock discord feature soon

**Comment by Sqaaakoi** [comment]
bdfdb will never be added to vencord

**Comment by nvhhr** [comment]
#21

**Comment by Grafaffel** [comment]
> ### Plugin Description
> Allows you to replace the native Sounds with custom Sounds
> 
> ### Existing Plugin for other mod
> https://betterdiscord.app/plugin/NotificationSounds https://betterdiscord.app/plugin/BDFDB
> 
> ### Request Agreement
> * [x]  I read the above and made sure my plugin is possible and allowed
> * [x]  I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
> * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

BDFDB is a library **_for better discord_** with utility functions and more and thus it is **not** compatible with Vencord. Vencord has it's own utility functions and stuff, so there is **_no_** need for this to be added.
