### ISSUE TITLE
New chat bubble

### ISSUE THREAD

**Issue by Nzymm** [Vencord/plugin-requests#411]
### Plugin Description

![ASA](https://github.com/Vencord/plugin-requests/assets/142067798/289d51d4-da33-4c2e-9812-75fd0292f973)
Add an pugin that removes the "New" thing when a new chat has been created (need to send a message to desappear and it's verry frustrating)

### Existing Plugin for other mod

.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
this can be done with css

```css
div[class^="newChannel__"] {
    display: none;
}
```

**Comment by HAHALOSAH** [comment]
1. CSS
2. nice job censoring
