### ISSUE TITLE
AD/SPONSORSHIP BLOCKER

### ISSUE THREAD

**Issue by Stigstille** [Vencord/plugin-requests#412]
### Plugin Description

![image](https://github.com/Vencord/plugin-requests/assets/134349048/d6f2c407-9ee3-4be8-bcb2-eb5f4f122003)
Something to remove these dumb things

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
User Settings > Privacy

turn off quests there

**Comment by Stigstille** [comment]
> User Settings > Privacy
> 
> turn off quests there

AAA!! Should have probably checked there first... Sorry
