### ISSUE TITLE
Message Scheduler for Private DMs

### ISSUE THREAD

**Issue by XimplusGG** [Vencord/plugin-requests#42]
### Plugin Description

I want a plugin to schedule messages in dms and not servers so that i can schedule particular messages to my friends in dms making it easier to share info incase i forget it later or if it has a deadline....for example the Schedule message feature available in telegram, ive seen other users wanting them in servers but message scheduler exists for servers for not for dms, a message schedule for such would be incredibly useful, thanks

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
Isn't this just selfbotting

**Comment by XimplusGG** [comment]
Maybe, but is it that risky ? Considering its so useful

**Comment by Koishukaze** [comment]
discord really dislikes selfbotting, you also didn't see this
![image](https://github.com/Vencord/plugin-requests/assets/47912135/c753b265-9ad3-4322-b54c-83895bb96988)

**Comment by XimplusGG** [comment]
oh yeah i totally missed that section....thanks for you help mate

**Comment by Riddim-GLiTCH** [comment]
As a sidenote, Message Schedule in DM's is kinda pointless. The only real world use-case I can imagine is wishing someone a happy birthday. The issue there is forgetting such would make you a not very good friend.



> Isn't this just selfbotting

A very poor selfbot at that. You would have to keep your computer online at all times as you cant send any messages without being logged in on some sort of bot network. Making it kinda impossible to be useful, as in most cases, you already are logged in and active on discord.
