### ISSUE TITLE
Sounds panels

### ISSUE THREAD

**Issue by Proklanyt** [Vencord/plugin-requests#426]
### Plugin Description

Simple plugin, simple request. Please make a plugin, you can call it "Sunds Panel" or add it to the FakeNitro plugin. The operation of the plugin is simple, without having nitro you can use sound panels from other servers. A plugin that has already been added on Better Discord.Thank you in advance for reading and adding it <3

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
me thinks plugin that will cause mods to server mute you is a bad idea

**Comment by MrDiamondDog** [comment]
This isn't possible. You say there is a betterdiscord plugin, but there definitely isn't.

**Comment by Proklanyt** [comment]
My friend said that its mod for Better Discord, if it is impossible to create this plugin, unfortunately there is nothing we can do about it

**Comment by Vendicated** [comment]
not possible. just use a system soundboard and read the instructions next time.
