### ISSUE TITLE
Friend text color changer

### ISSUE THREAD

**Issue by dahkohtah** [Vencord/plugin-requests#427]
### Plugin Description

A plugin that lets you change your friend's text colors with a hex code.
So I could give my friend John green text and my other friend Joe yellow text etc.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
This is possible to do with css, enable themeattributes plugin, copy their userid and put it in this:
``[data-author-id="165098921071345666"] [class*=messageContent_] { color: #00ff00; }``

**Comment by Sqaaakoi** [comment]
> This is possible to do with css, enable themeattributes plugin, copy their userid and put it in this: `[data-author-id="165098921071345666"] [class*=messageContent_] { color: #00ff00; }`

does this only work in the chat box?

**Comment by nvhhr** [comment]
> does this only work in the chat box?
The goal was to color the text of their messages if I understood correctly and that's what it does.

**Comment by Sqaaakoi** [comment]
yeah i mean above messages you know what i mean
nowhere else though

this does remind me someone made a random name color for everyone plugin though
