### ISSUE TITLE
color parts of messages <red> like this </red>

### ISSUE THREAD

**Issue by SeazeIsCool** [Vencord/plugin-requests#43]
### Plugin Description

the ability to color parts of your message (pink) like this (/pink) [just imagine the brackets are angular here] and its visible to all other users with the plugin, you could also put in a hex code <#C02C38> such as this. </#C02C38> (oh my god the html tags dont show in plugin-requests channel lol)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
> wouldnt this become annoying for everyone who doesn't have the plugin? which i guess would be the vast majority of users.

It would be, but you might be able to do it with invisible characters. Not sure how useful/realisable that is though.

**Comment by Vendicated** [comment]
not very useful and way too limited cause people need the plugin to see it

**Comment by mynameisbob1928** [comment]
you could try by using the ansi markdown
![example](https://github.com/Vencord/plugin-requests/assets/129603125/fab97401-85d2-4670-a46b-671ab4c61e1d)
