### ISSUE TITLE
ChannelTabs

### ISSUE THREAD

**Issue by RogalDoe** [Vencord/plugin-requests#433]
### Plugin Description

ChannelTabs Allows you to have multiple tabs and bookmarks channels

https://github.com/samfundev/BetterDiscordStuff/tree/master/Plugins/ChannelTabs

### Existing Plugin for other mod

N/A

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
PR already exists

**Comment by RogalDoe** [comment]
> PR already exists

What the name please :/

**Comment by MrDiamondDog** [comment]
> What the name please :/

you wouldn't believe this

**Comment by Sqaaakoi** [comment]
https://github.com/Vendicated/Vencord/pull/499

it only has over 200 commits waiting to be merged

**Comment by RogalDoe** [comment]
> [Vendicated/Vencord#499](https://github.com/Vendicated/Vencord/pull/499)
> 
> it only has over 200 commits waiting to be merged


That means still in developpement ?

**Comment by Sqaaakoi** [comment]
> > [Vendicated/Vencord#499](https://github.com/Vendicated/Vencord/pull/499)
> > it only has over 200 commits waiting to be merged
> 
> That means still in developpement ?

no it means it is very complicated and will get lost in the sea of hundreds of PRs

**Comment by RogalDoe** [comment]
> > > [Vendicated/Vencord#499](https://github.com/Vendicated/Vencord/pull/499)
> > > it only has over 200 commits waiting to be merged
> > 
> > 
> > That means still in developpement ?
> 
> no it means it is very complicated and will get lost in the sea of hundreds of PRs

Unnnh ??? what thes means PRs

**Comment by RogalDoe** [comment]
they need to verify all commits ?

But this plugins already exist ! but need to be rewrited at zero for Vencord Build ?

**Comment by RogalDoe** [comment]
??? :|

**Comment by nin0-dev** [comment]
No, pull requests are a request for the repo owner (in this case vendicated) to "pull" code from another repo (basically pulling a plugin to vencord for example).

However,
![image](https://github.com/Vencord/plugin-requests/assets/75569739/1dc50852-b19f-4e69-a111-650a505853cc)

vee will get to the pr at some point, and potentially merge it

**Comment by RogalDoe** [comment]
> No, pull requests are a request for the repo owner (in this case vendicated) to "pull" code from another repo (basically pulling a plugin to vencord for example).
> 
> However, ![image](https://private-user-images.githubusercontent.com/75569739/330415036-1dc50852-b19f-4e69-a111-650a505853cc.png?)
> 
> vee will get to the pr at some point, and potentially merge it

Thanks you for your light 


Then Pull requests 150, means 150 plugin awaiting to be merged o_O ?

**Comment by KaKi87** [comment]
No, there still are a lot though :

![42 open `feat(plugin)` PRs](https://i.goopics.net/s6zuj5.jpg)
