### ISSUE TITLE
add proxy in discord 

### ISSUE THREAD

**Issue by amirkma** [Vencord/plugin-requests#437]
### Plugin Description

Hello, can you make a plugin like telegram proxy?
Because the Iranian government has filtered Discord, you are doing a great favor to the Iranian gaming community

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
why not just use a vpn?

**Comment by nin0-dev** [comment]
I don't think an authoritarian government would consider a difference between a HTTP proxy and a VPN

also if you're that willing to use a proxy, just put one system wide
