### ISSUE TITLE
some betterdiscord plugins: SplitLargeMessages, CharacterCounter, KeyboardSounds

### ISSUE THREAD

**Issue by Albert-1645** [Vencord/plugin-requests#441]
### Plugin Description

SplitLargeMessages:
Splits the messages into varius messages if the messages is bigger than the allowed character counter without nitro, bsclly you can "send" +4k large messages.

CharacterCounter:
the names says for is own

KeyboardSounds:
plays some little sounds by pressing keys when you typing

### Existing Plugin for other mod

https://betterdiscord.app/plugin/SplitLargeMessages, https://betterdiscord.app/plugin/CharCounter, https://betterdiscord.app/plugin/KeyboardClick

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
1. SplitLargeMessages isn't possible
2. CharCounter had a pending PR but got exploded
3. Kinda stupid ngl

Also please make separate issues for separate requests
