### ISSUE TITLE
Use Discord's emojis to replace Twemoji (where possible)

### ISSUE THREAD

**Issue by UltraBlackLinux** [Vencord/plugin-requests#443]
### Plugin Description

https://discord.com/assets/1cc4d6bf26f571d0c695.png
https://discord.com/assets/0c81fb35c18e223d2745.png 
These are the emojis used for the emoji picker button. They're so cute and I'd love to use them, but there is no official way to do so (not even a tool to convert this to a font :cry:)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
having this as a plugin doesn't make much sense for multiple reasons

do it yourself, you can do this with css

- use imagemagick to split the spritesheet into individual images
- adapt the https://betterdiscord.app/theme/Emoji Replace theme to use your images
