### ISSUE TITLE
to remove this stuff

### ISSUE THREAD

**Issue by official-notfishvr** [Vencord/plugin-requests#452]
### Plugin Description

![image](https://github.com/Vencord/plugin-requests/assets/124737490/448a092c-e3a0-4db0-9c3c-a42db154776f)
remove all of it

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
BetterGifPicker automatically takes you to your favorites so you dont see this

**Comment by official-notfishvr** [comment]
> BetterGifPicker automatically takes you to your favorites so you dont see this

no i want them to BE REMOVED
