### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by XAVIETHEME** [Vencord/plugin-requests#453]
### Plugin Description

JJJ

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
what are you even saying

**Comment by XAVIETHEME** [comment]
ok sorry so i have been trying to do this vencord and its really not working for me so i need a little help

**Comment by nin0-dev** [comment]
1- close this issue
2- go to https://discord.gg/vencord, then in the support channel
