### ISSUE TITLE
discord video size limit bypass

### ISSUE THREAD

**Issue by Norris-Lee** [Vencord/plugin-requests#455]
### Plugin Description

Program linked below allows large video files to be embeded in discord without quality loss through a bug, would be nice to have as a vencord plugin.

### Existing Plugin for other mod

https://github.com/nekiak/discordclipuploader

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
just do it manually

having abusive stuff like this in the mod is not a good idea
