### ISSUE TITLE
DateFormats

### ISSUE THREAD

**Issue by aubymori** [Vencord/plugin-requests#459]
### Plugin Description

By default, the date and time format in Discord (most notably on messages) is linked to the language. This kind of sucks, because as an English speaker, there's no way for me to use 24-hour time with YYYY/MM/DD format.

This mod would allow you to enter custom date/time formats, so that you can use your preferred date and time formats without switching languages.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
#1
