### ISSUE TITLE
Close a Direct Message Confirmation

### ISSUE THREAD

**Issue by Odonix** [Vencord/plugin-requests#460]
### Plugin Description

**What I'd like:** A plugin that makes a confirmation screen pop up asking if you're sure you want to close out of the DM when clicking the X button next to a user or group.

**Explanation:** I often fear accidentally closing a DM while browsing my messages as there is no confirmation.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
just hide the close button with css:
```css
[class*=channel] [class*=closeButton] {
    display: none !important;
}
```

you can still close with context menu

**Comment by Odonix** [comment]
> just hide the close button with css:
> 
> ```css
> [class*=channel] [class*=closeButton] {
>     display: none !important;
> }
> ```
> 
> you can still close with context menu

Sorry for the late reply!

This works! Thanks!
