### ISSUE TITLE
Space add

### ISSUE THREAD

**Issue by RayPiers** [Vencord/plugin-requests#461]
### Plugin Description

Allows making channels with spaces in them.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
all you can really do is insert invisible unicode characters, not actually adding spaces

simply copy and paste one of those characters in place of spaces
