### ISSUE TITLE
[Feature Request] add the ability to choose language per chat in the translate plugin

### ISSUE THREAD

**Issue by TheLime1** [Vencord/plugin-requests#463]
### Plugin Description

The translate plugin detects the language automatically, and sometimes it's not correct. Is it possible to insert a combo box above the server/DM chat section to choose the source language?
![image](https://github.com/Vencord/plugin-requests/assets/47940043/bce9801c-ceea-40a3-9212-8fec2ba23e0c)

### Existing Plugin for other mod

[translate plugin](https://vencord.dev/plugins/Translate) (itself)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by TheLime1** [comment]
welp this is already implemented

**Comment by Qwertyto** [comment]
How? If you don't mind me asking? How do I use this feature?

**Comment by Qwertyto** [comment]
or what about choosing the language it translates into. I wanna see my friends' messages in my native spanish!

**Comment by TheLime1** [comment]
@Qwertyto 
by clicking here 
![image](https://github.com/Vencord/plugin-requests/assets/47940043/db093ece-2a55-4e31-9924-45f06637d433)
