### ISSUE TITLE
plugin request: hidden edit plugin

### ISSUE THREAD

**Issue by hyperlexus** [Vencord/plugin-requests#465]
### Plugin Description

its possible to hide yourself editing a message. for this however you have to have the network tab in the dev console pulled up before sending the message to obtain the ID. (see ntts vid)
is it possible to make a plugin that stores these ids somewhere so we can edit previous messages in the same session without needing to have f12 open?

### Existing Plugin for other mod

not that I know of

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
dear ntts viewer,

if you had actually watched the entire video you would know that this is just a visual glitch and that you can't just edit without showing the edited mention

**Comment by hyperlexus** [comment]
dear commenter, if you tried it out you would know that it works flawlessly.

**Comment by nin0-dev** [comment]
> dear commenter, if you tried it out you would know that it works flawlessly.

shouldn't even be added in the first place because it can be used to easily ban bait. plus it just sends a 2nd message instead of actually editing the 1st
