### ISSUE TITLE
FakeProfileEffects

### ISSUE THREAD

**Issue by xxxanteria** [Vencord/plugin-requests#470]
### Plugin Description

There might be someone who used this title, but as i see we have the decor plugin, i wonder if we could have a profile effect plugin, that we could be able to make our custom profile effects without buying it from the nitro shop, a custom profile effects not discord ones. I hope i made everything understandable and it would be accepted. I know this is a bit too short, but i was bored and really wanted a custom profile effect.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
#65

**Comment by xxxanteria** [comment]
> #65

but i ddint saw it when i looked for those?
