### ISSUE TITLE
WriteUppercase

### ISSUE THREAD

**Issue by svgszn** [Vencord/plugin-requests#472]
### Plugin Description

Changes the first Letter of each Sentence in Message Inputs to Uppercase

### Existing Plugin for other mod

https://betterdiscord.app/plugin/WriteUppercase

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
#170
