### ISSUE TITLE
Make my status invisible when discord starts

### ISSUE THREAD

**Issue by BIRTAX38** [Vencord/plugin-requests#473]
### Plugin Description

Make my status invisible when discord starts

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by danielah05** [comment]
doesnt discord remember the online status u set, why not just manually go invisible

**Comment by BIRTAX38** [comment]
usually my status is set to online. But I would like it to be set to invisible after entering.
