### ISSUE TITLE
Collapse/Hide Messages 

### ISSUE THREAD

**Issue by PlagueBirb** [Vencord/plugin-requests#474]
### Plugin Description

A simple plugin that allows you to hide messages you don't want to see. Works like blocked messages but only on specific messages the user wants to hide.  There are many messages from my friends that I wouldn't want to report because i don't want them to get in trouble, but i also just don't want to see. If this plugin existed, instead of having to report a message or ask a friend to take their message down, i could simply right-click on the message and press hide, which would collapse it as if it were a blocked message.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Cynosphere** [comment]
#435
