### ISSUE TITLE
FileViewer : This plugin comes from Better Discord and I think it's cool

### ISSUE THREAD

**Issue by Pierre2004** [Vencord/plugin-requests#475]
### Plugin Description

File Viewer lets you view files like pdf, doc, xlsx etc. directly in discord
![FileDemo](https://github.com/Vencord/plugin-requests/assets/79320512/baee49d3-71f1-4874-9093-1450a6507c4f)

### Existing Plugin for other mod

https://betterdiscord.app/plugin/FileViewer

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Golonchy** [comment]
https://github.com/Vencord/plugin-requests/issues/3
#3
lol
