### ISSUE TITLE
Edit Users.

### ISSUE THREAD

**Issue by LFL38** [Vencord/plugin-requests#476]
### Plugin Description

You can edit the profiles of people using this plugin!
https://codeberg.org/Lunaa/userPlugins/src/commit/0f01b42d4395fd6ecfd73272262a95fe533a7d91/editUsers
&
https://betterdiscord.app/plugin/EditUsers

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
duplicate #102
