### ISSUE TITLE
EveryBadge

### ISSUE THREAD

**Issue by gugabugabadabanga** [Vencord/plugin-requests#477]
### Plugin Description

Add a plugin. That gives you every badge in discord, (e.g, active developer) it would be a cool feature to use.

### Existing Plugin for other mod

https://github.com/wtrfl/allbadges

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Cats1337** [comment]
https://github.com/ethan-davies/FakeBadges/
