### ISSUE TITLE
animated discord status

### ISSUE THREAD

**Issue by nieznanyPOLAK** [Vencord/plugin-requests#479]
### Plugin Description

animated discord status

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
>  I read the above and made sure my plugin is possible and allowed

I doubt so

![IMG_2766](https://github.com/Vencord/plugin-requests/assets/47912135/2cf02e16-cd13-4ec6-a519-be75ea18b5a7)
