### ISSUE TITLE
Status blocker/hider

### ISSUE THREAD

**Issue by phant0m2290** [Vencord/plugin-requests#480]
### Plugin Description

This will allow you to block/hide statuses. For example when you dont like a status or its racist or its extremely cringe and you dont want to see it you can hide that users status

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by ImLvna** [comment]
this can be done with css

**Comment by phant0m2290** [comment]
> this can be done with css

yes but i mean specific people. not everyone

**Comment by ImLvna** [comment]
still can be done with css
