### ISSUE TITLE
Be able to copy role ID's (PermissionViewer)

### ISSUE THREAD

**Issue by Error340GTL** [Vencord/plugin-requests#481]
### Plugin Description

Be able to copy role ID from permission viewer by right clicking on it and clicking "Copy role ID" if you don't have "Server settings" button or don't have permission to mention the role.

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
https://github.com/Vendicated/Vencord/pull/2367
