### ISSUE TITLE
Built-in Fancy Text

### ISSUE THREAD

**Issue by geometry-fucking-dash** [Vencord/plugin-requests#483]
### Plugin Description

This is a pretty obscure idea, but I'm sure that people would fuck with it.

I'm just gonna get to the point with this one. Add a button around where the user types a message which brings up a menu adjacent to **this sloppy mockup:**

![image](https://github.com/Vencord/plugin-requests/assets/95655098/cc54b7ac-f65d-421b-9162-b3bc3790685b)

The dropdown menu gives a list of fancy text formats/fonts to choose from, the input is what the user would like to write in that format, and the output is exactly that. This is merely for copy and pasting, and doesn't replace text within messages. 

Fairly simple idea and hopefully not too hard to implement. My apologies if this wasn't a well made request or didn't have enough info, I just think the idea is simple enough to not be necessary.

### Existing Plugin for other mod

Closest would be https://vencord.dev/plugins/TextReplace, but not very similar

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
annoying, useless, and poor/no accessibility
