### ISSUE TITLE
Hide messages from annoying users

### ISSUE THREAD

**Issue by sergiohzph** [Vencord/plugin-requests#484]
### Plugin Description

Many times, we find quite irritating users on any Discord server. But they're not hostile enough to block, and we don't want to do it to avoid those unpleasant situations where people talk about you on that server because you blocked that person.

The plugin would give the option to list a username, and from then on mentions or messages from that user would be hidden, as if they didn't exist. There would be a choice depending on our needs, to hide only their mentions, or to hide all their posts in general.

Yes, I know there is already Discord's own function to block someone. But the thing is that I don't want to block anyone because that can cause controversy on the server as I mentioned at the beginning because when someone blocks you and you try to mention or quote them, a system message appears saying that this user does not share communication with you (or something like that), it has happened to me more than once that I have blocked someone on a server, that person mention me and in front of everyone start a drama because I blocked them... It's best if it's something that the annoying person is not aware of. That's why I'm asking for this and I'm sure many other people will agree with such a plugin.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
#466
