### ISSUE TITLE
RelativeTimestamps

### ISSUE THREAD

**Issue by mn7216** [Vencord/plugin-requests#49]
### Plugin Description

Plugin Description
Adds relative timestamps to messages. I find it really useful for remembering/recognizing timespans & keeping in mind how long ago something happened or I got messaged about. I think it would definitely be a great addition.
Example:
![image](https://github.com/Vencord/plugin-requests/assets/94876457/27bbd550-a3fa-4205-aec6-4c61decab8f4)

### Existing Plugin for other mod

https://betterdiscord.app/plugin/RelativeTimestamps

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
Not really a duplicate, but I'm closing this in favor of https://github.com/Vencord/plugin-requests/issues/1 - all timestamp customization can and should be achieved with one plugin and the discussion for all of it is best to be kept in one place.

**Comment by mn7216** [comment]
> Not really a duplicate, but I'm closing this in favor of #1 - all timestamp customization can and should be achieved with one plugin and the discussion for all of it is best to be kept in one place.

That makes sense, I hope that the feature can be merged into that plugin!
