### ISSUE TITLE
InAppNotifications

### ISSUE THREAD

**Issue by XotiicGTX** [Vencord/plugin-requests#490]
### Plugin Description

Can y'all add this Plugin in Vencord please. I would appreciate that a lot. 
Plugin is called: InAppNotifications

I used it a long time ago when I was using BetterDiscord, but since I found Vencord better and easier to use I decided to switch. I got all my plugins that I used with BetterDiscord except this one.

### Existing Plugin for other mod

https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/InAppNotifications

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by PATXS** [comment]
#22
