### ISSUE TITLE
Ownership transfer/scammer banning prevention plugin

### ISSUE THREAD

**Issue by flattio** [Vencord/plugin-requests#491]
### Plugin Description

Recently, the youtuber, NTTS released a video titled "Your Discord Account is in Danger!" (https://www.youtube.com/watch?v=a9rOLaH5dJs), in this video, close to the end he explains how a user could transfer ownership of a server to you, in attempt to get your discord account instantly terminated, so my suggestion is, a plugin, similar to "Relationship notifier" where it instead notifies you if you are transferred ownership to a server, or even staff roles, though this might not be helpful for everyone, it could help people have peace of mind about their discord account being spontaneously deleted.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by NeonGamerBot-QK** [comment]
possible but i dont think its going to be added.
![image](https://github.com/Vencord/plugin-requests/assets/58448036/4f31e4b8-e2fd-4914-8c3a-68256881062f)

**Comment by Vendicated** [comment]
just don't be in weird guilds like that
