### ISSUE TITLE
Scheduled Status

### ISSUE THREAD

**Issue by kaushik-kyle** [Vencord/plugin-requests#499]
### Plugin Description

Scheduled Status such as set DND from 11P.M. to 8A.M. (applicable for all predefined as well as custom status) with possibility to maybe set multiple status'es based on different times, time to be obtained from system time.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
I think this would be considered selfbotting, so likely won't be added
