### ISSUE TITLE
edit other people's messages on the client / rotate someone's camera by 45/90 degrees

### ISSUE THREAD

**Issue by Noorly** [Vencord/plugin-requests#506]
### Plugin Description

the ability to rotate someone's camera by 45/90 degrees (for landscape phone views)

and the ability to edit other people's messages on the client (only for you, and shouldn't show for anyone else using the plugin)

### Existing Plugin for other mod

noop

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by ImLvna** [comment]
editing other peoples messages will never be done. it is a huge concern for abuse

**Comment by leon01288** [comment]
the ability to rotate someone's camera by 90 degrees  someone's cam would be really nice i was just thinking this should be a feature.

**Comment by Noorly** [comment]
> editing other peoples messages will never be done. it is a huge concern for abuse

how is changing someone's messages locally a concern for abuse but the ability to see deleted messages, see what device they're using, automatic link suppressors and a ton of other privacy invading features not?

**Comment by leon01288** [comment]
> > editing other peoples messages will never be done. it is a huge concern for abuse
> 
> how is changing someone's messages locally a concern for abuse but the ability to see deleted messages, see what device they're using, automatic link suppressors and a ton of other privacy invading features not? its not like i like anal or anything baka!

Faking someone else's messages as real is on reason i guessing.

**Comment by PATXS** [comment]
you can already edit messages locally using the devtools. just ctrl+shift+i and then use the element picker to pick a message on the screen

**Comment by Vendicated** [comment]
one request per issue.
