### ISSUE TITLE
Change Discord's sounds!

### ISSUE THREAD

**Issue by MozaicoTheHuman** [Vencord/plugin-requests#507]
### Plugin Description

It would be cool if you guys add a plugin that lets you change Discord's sounds! Like the notification, call, VC join/leave, etc.

### Existing Plugin for other mod

There's a plugin named NotificationSounds! I can't find a link to the original one so here's the one i had on BetterDiscord (It has some custom sounds set i think) https://cdn.discordapp.com/attachments/1164927554323484704/1238012658767102094/NotificationSounds.config.json?ex=663dbca3&is=663c6b23&hm=3ceb78be328811f654174bb64f5ed082b9a75909fac2eab88a1872e27e76b20f&

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
#21
