### ISSUE TITLE
WiderUserArea

### ISSUE THREAD

**Issue by Zelechka** [Vencord/plugin-requests#509]
### Plugin Description

This is a plugin that makes the user area at the bottom left of the screen expand left into the server list.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/WiderUserArea

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Zelechka** [comment]
how can I do this using css?

**Comment by Vendicated** [comment]
you can get help with css in our discord community
