### ISSUE TITLE
infinite message search 

### ISSUE THREAD

**Issue by Ebrehe** [Vencord/plugin-requests#51]
### Plugin Description

Changing pages while searching is very annoying.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by D3SOX** [comment]
A possible workaround would be to implement some kind of overscroll that clicks the next/previous button or better yet make it emulate like an infinite scrollable list which loads when scrolling (I'm sure there's already a library for that)
