### ISSUE TITLE
Teamspeak sounds

### ISSUE THREAD

**Issue by kabovmaniscool** [Vencord/plugin-requests#512]
### Plugin Description

Could there be a plugin to include the Teamspeak sounds (Ex. user disconnected from your channel, welcome to teamspeak, ETC).

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
https://vencord.dev/plugins/VcNarrator

**Comment by ThomasYoussef-Business** [comment]
I'd also like this to be a plugin, either by allowing you to add custom sounds to each notification type, or by replacing it with TeamSpeak's audios directly, though I hardly believe the latter is legal for copyright reasons.
