### ISSUE TITLE
Apple Music user panel support

### ISSUE THREAD

**Issue by Dev-Frog-uk** [Vencord/plugin-requests#515]
### Plugin Description

Plugin request: Apple Music support for user panel (see Spotify version screenshot below)
Please follow up if more info required.

![image](https://github.com/Vencord/plugin-requests/assets/145220575/791c6196-1591-4373-9f50-a7437f435925)

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
closing in favour of of #198
