### ISSUE TITLE
Uncensored Screenshare transmisions

### ISSUE THREAD

**Issue by ItsTony04** [Vencord/plugin-requests#517]
### Plugin Description

When you are looking a serie in Crunchyroll or Netflix and you screenshare they viwers usually see a black screen instead of the video so, Is it really possible to make this plugin? Or is just impossible? I think it would be a pretty useful plugin if doesn't exist already.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment]
I think you can do it if you dis/enabled hardware acceleration + this issue is related to the sites not wanting you to stream a (paid) series/movie

**Comment by Vendicated** [comment]
you need to do this in your browser. vencord cant do anything
