### ISSUE TITLE
Message "secret"

### ISSUE THREAD

**Issue by Lopzinc** [Vencord/plugin-requests#519]
### Plugin Description

Make it possible to form a "secret" with someone and you can each make a dictionary so if either of you send for example, 🐷 it would turn it into whatever translation you put in the dictionary, example below:

🐷- Hello

User: 🐷
Anyone who has the "secret" will see "Hello" whereas people who dont will just see 🐷

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
honestly you can just exchange TextReplace rules, or use https://vencord.dev/plugins/InvisibleChat
