### ISSUE TITLE
Favorite Media (Images, Gifs, Video, and audio in addition to gifs)

### ISSUE THREAD

**Issue by gwenily** [Vencord/plugin-requests#521]
### Plugin Description

basically i'd like functionality to "star" all types of media, not just gifs. This is one of my favorite BetterDiscord plugins which still doesn't have a vencord alternative
Ideally each kind of media would have its own tab in the gif picker. Attatched is the betterdiscord plugin

### Existing Plugin for other mod

https://github.com/Dastan21/BDAddons/tree/main/plugins/FavoriteMedia

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
https://github.com/Vencord/plugin-requests/issues/13
