### ISSUE TITLE
Show GitHub/source code links in Plugins menu

### ISSUE THREAD

**Issue by pumpkinhasapatch** [Vencord/plugin-requests#522]
### Plugin Description

We should add a View Source Code button for each Plugin in Vencord that lets users easily review source code.

Currently you can go to https://vencord.dev/plugins, [click the Plugin](https://vencord.dev/plugins/AlwaysAnimate), then click the GitHub icon in the top-right to see the actual JS/TS files. It would be nice to have this functionality built into Vencord so anyone can find the source code for each Plugin without digging through the website, browser console or GitHub repos.

Here are some mockup designs where you could place the source code link to make it more accessible:
![image](https://github.com/Vencord/plugin-requests/assets/113677241/21345f1b-d23e-4140-ad37-00bd24b93057)
![image](https://github.com/Vencord/plugin-requests/assets/113677241/c45cae79-75e8-4647-a0c7-256abc18c03b)

### Existing Plugin for other mod

-

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
yep, i was thinking about adding this as well (but definitely not in the plugin card, only the modal)

anyway since this isnt a plugin request, please open this in the vencord repo instead
