### ISSUE TITLE
Perm Logs

### ISSUE THREAD

**Issue by ChaChaSlideLeader** [Vencord/plugin-requests#523]
### Plugin Description

Make a option in the message logger permanent and a option to make it for every channel your in, not just the one your viewing.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
this is never getting added natively

but there's a third party plugin for this in the third-party-plugins channel on our discord

(+ multiple duplicates exist)
