### ISSUE TITLE
InAppNotifications plugin

### ISSUE THREAD

**Issue by pataz1k** [Vencord/plugin-requests#526]
### Plugin Description

Displays notifications such as new messages, friends added in Discord. 
Like a RelationshipNotifier but only display dm messages and mentions in channels

### Existing Plugin for other mod

https://github.com/QWERTxD/BetterDiscordPlugins/tree/main/InAppNotifications

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AftmostSeeker80** [comment]
#462
