### ISSUE TITLE
Tabs and favorite bar! 

### ISSUE THREAD

**Issue by Accentaro** [Vencord/plugin-requests#528]
### Plugin Description

Tabs/Favourites bar(Like in browsers)

This is the only plug in I need to make the change to vencord! On all devices 

### Existing Plugin for other mod

Betterdiscord.app/plugin/channeltabs

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
#6
