### ISSUE TITLE
arRPC Support for the normal Discord App

### ISSUE THREAD

**Issue by darkpixlz** [Vencord/plugin-requests#529]
### Plugin Description

arRPC is really nice to have from a dev standpoint and some things I use only support it instead of Discord's normal one. It should be possible to have it as a plugin so using vesktop isn't required. Discord's RPC is picky with what it will do without rejecting it so this would be great to have.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
> some things I use only support it instead of Discord's normal one

huh? if something supports arrpc, it should automatically support discord as well

anyway this plugin already exists

**Comment by darkpixlz** [comment]
discord likes to complain if you sent the name field through (so it can be "Playing {x}" not "Playing Application Title")

also what's its name? i only see customrpc and norpc
