### ISSUE TITLE
Exclusive Search

### ISSUE THREAD

**Issue by fldried** [Vencord/plugin-requests#53]
### Plugin Description

[E,g](https://support.discord.com/hc/en-us/community/posts/360057840551-Excluding-Search-Button)
Sometimes searching for specific things inside of chats and channels is a hassle. For example searching for has:video will show both urls and directly attached videos such as mp4s
It'd be cool to be able to exclude urls.
Same with images etc.
Also improving the logic behind multiple "has" statements could be improved.
has:file and has:video for example will show not only videofiles as one would probably assume but videos and other files

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
![Screenshot_2024-02-16-07-52-11-63_4d38fce200f96aeac5e860e739312e76](https://github.com/Vencord/plugin-requests/assets/45497981/4298a1df-87ab-40e6-9034-72b5a0b0f69e)
