### ISSUE TITLE
Disable Hidden Links using Markdown

### ISSUE THREAD

**Issue by simonwoegerb** [Vencord/plugin-requests#531]
### Plugin Description

A simple plugin to disable the newly added markdown syntax for hidden links.
In its current form things like `[steamcommunity.com/gift/4289](https://scammer.com)` are possible and hard to identify by default. 
Replacing the rendered part with merely the text representation might be a good option. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
Newly added? Has something changed?  
Anyway, there are multiple css solutions for this, to either completely replace the text with the link, do it on hover, color any markdown link text differently, or whatever you prefer.

The snippet I've been using is this, which adds the url with a smaller font following any markdown link:
```CSS
[class^=anchor_][title$=")"]::after
 { font-size: .7rem;
   content: " (" attr(href) ")";
   filter: grayscale(.4); }
```
![image](https://github.com/Vencord/plugin-requests/assets/34724502/4d57243d-9bc4-405d-b656-1eaa2f3b89f7)

CSS allows a lot more freedom than what a plugin could reasonably offer.

**Comment by simonwoegerb** [comment]
Hey, thanks! I did not know about that possibility... Sorry if i wasted your time!
