### ISSUE TITLE
[Additional setting - MessageLatency] - Show milliseconds

### ISSUE THREAD

**Issue by ar065** [Vencord/plugin-requests#535]
### Plugin Description

**The important bit:** 
The title pretty much explains the entire thing I want, just a setting added to the `MessageLatency` plugin to allow the user to toggle between seeing the actual milliseconds in the tooltip, and the default behavior of just seeing seconds in the tooltip. 

Disclaimer: Not particularly sure if this was the right place to request this, but on the main repository I was under the impression that I'd be banned/blocked for doing so.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
this was also merged /shrug
