### ISSUE TITLE
Disable/reduce Image Compression

### ISSUE THREAD

**Issue by sryanttza** [Vencord/plugin-requests#536]
### Plugin Description

If possible, a plugin that could disable or reduce image compression would be nice. They supposedly added that as a nitro feature a while ago, but then disabled it.

I believe this could be done one of two ways:
1. Straight up disabling/reducing the compression by finding a way to just turn off the feature
2. Upscaling the image when sent, so that when it compresses the image, the compressed result is closer to the original image quality.

Either way, I believe this would be very useful and could certainly be possible, one way or another.

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
discord does not compress uploads

**Comment by Vendicated** [comment]
duplicate of https://github.com/Vencord/plugin-requests/issues/164
