### ISSUE TITLE
Square Profile Pictures

### ISSUE THREAD

**Issue by iluvpidgeons** [Vencord/plugin-requests#537]
### Plugin Description

Square profile pictures, getting rid of the circular crop. I'm not a programmer but I think it should be possible because discord sends and revives the raw image (pretty sure).
![Screenshot 2024-05-13 033530](https://github.com/Vencord/plugin-requests/assets/152823406/1e4bfb3c-306e-45cf-b240-eb0ef4eb1342)

![Screenshot 2024-05-13 032444](https://github.com/Vencord/plugin-requests/assets/152823406/ccb5662c-f918-4a4c-b662-dacc0df2903a)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
Easily doable in css. Here's my snippet for square avatars and servericons, adjust as you want. Other such snippets also exist.
https://github.com/nvhhr/discordcss/blob/main/snippets/squareicons.theme.css
