### ISSUE TITLE
ublock/vencord plugin

### ISSUE THREAD

**Issue by Golonchy** [Vencord/plugin-requests#539]
### Plugin Description

Ublock blocks hidden trackers for websites so would it be possible/make sense to embed ublock into vesktop? Bcs vesktop is running discord web. 
Idk if this'll do anything but whenever I have ublock turned on and visit the discord website ublock blocks hundreds of trackers by the time I finish using discord.

### Existing Plugin for other mod

most certainly not

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
the vencord NoTrack plugin does this
