### ISSUE TITLE
Password System Plugin

### ISSUE THREAD

**Issue by rotutoss** [Vencord/plugin-requests#54]
### Plugin Description

 the plugin could be a "Password" system, for example, if you have the app discord version and you turn on your pc discord always opens, well you could add like a thing to put your own password to acess discord (not you account password, another type of password you could put in the settings of the plugin) like in whatsapp, and also be able to put passwords to DM's and Servers.
In the settings of the plugin you could put your password and etc etc.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by cheesesamwich** [comment]
can you not just log out of discord or lock your pc

**Comment by cheesesamwich** [comment]
skill issue i cant lie

**Comment by jedenastka** [comment]
> [...] or lock your pc

That part still applies if you don't want to log out (I personally wouldn't want to either as it's a hassle).

The solution you propose is inherently insecure. You can't stop somebody from getting into your Discord account when they are already logged into your OS account (if you don't have FDE then just having physical access is enough, though then it requires more skill).

Just lock your OS account. It's more secure (if you have FDE it's very secure), it's simple and doesn't need a plugin.

**Comment by rotutoss** [comment]
b-but mine is more quality and is more explained 😭😭

> > [...] or lock your pc
> 
> That part still applies if you don't want to log out (I personally wouldn't want to either as it's a hassle).
> 
> The solution you propose is inherently insecure. You can't stop somebody from getting into your Discord account when they are already logged into your OS account (if you don't have FDE then just having physical access is enough, though then it requires more skill).
> 
> Just lock your OS account. It's more secure (if you have FDE it's very secure), it's simple and doesn't need a plugin.
> 
> Also I just checked, and it's a duplicate of #10.

b-but mine is more explained and better 😭😭

**Comment by jedenastka** [comment]
It asks for the same thing, and the thing it asks for is dumb - the reason for that one getting closed is because it's dumb, not because it's not explained well.

**Comment by rotutoss** [comment]
> It asks for the same thing, and the thing it asks for is dumb - the reason for that one getting closed is because it's dumb, not because it's not explained well.
"low quality"

**Comment by jedenastka** [comment]
Low quality feature, not low quality description of the feature.

**Comment by rotutoss** [comment]
where it says its the feautre dawg 💀💀 

> Low quality feature, not low quality description of the feature.

**Comment by jedenastka** [comment]
It's what the tag is for. Have you even read what the person who closed the request wrote?

> I do not think plugins that give a false sense of security should be in the mod; the idea of PasscodeLock as an actual lock is misleading at best and dangerous at worst.

**Comment by DalinFrazier** [comment]
> > can you not just log out of discord or lock your pc
> > imagine log out of Discord every damn time

What if you have multi-factor authentication enabled?
Image having to go to your messages, email, or authenticator app every time you leave you computer.
