### ISSUE TITLE
OldTitleBar (Classic support)

### ISSUE THREAD

**Issue by fraxgut** [Vencord/plugin-requests#540]
### Plugin Description

A Plugin that allows the user to use the native Windows TitleBar while running the Classic or Basic theme (Win98, Win2K, fallback themes, etc).

Should look like this:

![image](https://github.com/Vencord/plugin-requests/assets/88363070/52d32e1d-f375-4331-9a85-31fce80d0b0c)

### Existing Plugin for other mod

https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/OldTitleBar

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
you can change look of the discord titlebar with css

if you want to use the native os titlebar, there's a setting for it in vencord settings
