### ISSUE TITLE
FavoriteMedia

### ISSUE THREAD

**Issue by Beikkn** [Vencord/plugin-requests#544]
### Plugin Description

![Screenshot 2024-05-13 211131](https://github.com/Vencord/plugin-requests/assets/169714560/836283b4-7909-4c16-868f-296cb9b4f227)
Favorite media, probably one of my favorite plugins.
It just allows you to favorite images and videos.
*Field*

### Existing Plugin for other mod

https://betterdiscord.app/plugin/FavoriteMedia

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by PATXS** [comment]
#13
