### ISSUE TITLE
TextReply addon

### ISSUE THREAD

**Issue by IsRvHere** [Vencord/plugin-requests#545]
### Plugin Description

Suggestion: For the "TextReplace" Plugin y'all should add so you can have for example:

!testmsg @rv2_ 

and in the replace message it sends for example:

Hello there @rv2_! How's your day today?

(And in the settings you put it as Hello there <user>! How's your day today?)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by ImLvna** [comment]
already possible. use regex

[tutorial](https://regexone.com/)
