### ISSUE TITLE
Channel Message History

### ISSUE THREAD

**Issue by basicallyelite** [Vencord/plugin-requests#55]
### Plugin Description

Add a plugin to view the message history in channels, even if you don't have the permission
![Screenshot 2024-02-16 095113](https://github.com/Vencord/plugin-requests/assets/136079990/856360e6-ebe8-42f4-9fd1-01dbbd9a7585)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by jedenastka** [comment]
This is not possible.

**Comment by theprocrastarnator** [comment]
it wouldve been so cool if it was possible
