### ISSUE TITLE
No Message Requests

### ISSUE THREAD

**Issue by radishcatish** [Vencord/plugin-requests#554]
### Plugin Description

the message requests thing kind of sucks, so i was wondering if there could be a plugin to just replace them with normal messages? iLoveSpam does this, but not for regular message requests, so not sure if this is a duplicate, but i dunno, i don't like just. not receiving dm notifications just because the person's never dmed me before. i might be just a people pleaser but id prefer to answer messages quicker, yknow?

formal apologies if my dumbass made an issue that was bad

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
already a discord feature

![Sqaaakoi-15-05-2024-10-31-16](https://github.com/Vencord/plugin-requests/assets/37475903/e83a426e-4969-4cd6-9f74-a16fcb9deedd)
![Sqaaakoi-15-05-2024-10-31-44](https://github.com/Vencord/plugin-requests/assets/37475903/b6cad576-4b85-4488-ac2c-1cbae4209820)

**Comment by radishcatish** [comment]
i have had that on for since it was out and it does not work

**Comment by Sqaaakoi** [comment]
i mean disable it

**Comment by radishcatish** [comment]
IM ACTUALLY FUCKING STUPID
