### ISSUE TITLE
Custom Status Presets

### ISSUE THREAD

**Issue by Stonedtaco** [Vencord/plugin-requests#557]
### Plugin Description

i think the name says for its self
Pretty much Have it Where you can have multiple Presets for Your Statuses

### Existing Plugin for other mod

https://betterdiscord.app/plugin/CustomStatusPresets

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by PATXS** [comment]
#127
