### ISSUE TITLE
remove discord feedback

### ISSUE THREAD

**Issue by VillainsRule** [Vencord/plugin-requests#558]
### Plugin Description

when you leave a guild or report a message, it sometimes pops up with a "can you tell us more" or "tell us about your reporting experience". these are annoying, and i'd like a plugin to disable them.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
there's a "do not show again" switch

**Comment by VillainsRule** [comment]
> there's a "do not show again" switch
> 
> ![image](https://private-user-images.githubusercontent.com/45497981/330648312-5f66ba65-b6e7-48c1-8957-d6c6aa222dea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM1MjYsIm5iZiI6MTcxNTc4MzIyNiwicGF0aCI6Ii80NTQ5Nzk4MS8zMzA2NDgzMTItNWY2NmJhNjUtYjZlNy00OGMxLTg5NTctZDZjNmFhMjIyZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE0MjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YjM4OGQzMTI4MGM3Yjc0ZmM3ZmQyMzYwM2NiNzQyZjJmYzk2MTExMzZhMDNiNTQ0NDc1ZTk3Mjk1Y2ZlZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z5VYatZvhOTyl8O1LETlEm5tzTjj8dvaLEbdE4DsgTw)

aware; and it doesn't persist across accounts
