### ISSUE TITLE
Show Hidden Channels

### ISSUE THREAD

**Issue by freeutka-cmd** [Vencord/plugin-requests#566]
### Plugin Description

Show Hidden Channels

https://raw.githubusercontent.com/JustOptimize/return-ShowHiddenChannels/main/ShowHiddenChannels.plugin.js

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by ImpishMoxxie** [comment]
its a built-in plugin ffs 
![image](https://github.com/Vencord/plugin-requests/assets/79810799/8095571e-1745-47ff-8eb6-14fbc15ac8f0)

**Comment by freeutka-cmd** [comment]
Oh, thanks

**Comment by RobinRMC** [comment]
bruh
