### ISSUE TITLE
Message deletion queue.

### ISSUE THREAD

**Issue by Xantrisse** [Vencord/plugin-requests#567]
### Plugin Description

If you delete messages too quickly, Discord limits you.

The plugin would allow you to add messages to the queue and then send a query every 2 seconds to Discord, and the messages themselves would be hidden even if they are in the queue.

If a queue is not an option, I suggest something similar to prevent Discord from limiting message deletions.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
how can you even reach the deletion ratelimit? never reached it in my entire existence on discord

also having an automated queue might be selfbotting

**Comment by Duckrinium** [comment]
> how can you even reach the deletion ratelimit? never reached it in my entire existence on discord


If you hold shift and use a quick buttons bar, you pretty much can. There are situations where you gotta do it manually and there are a lot of messages. 

But I do agree it sounds like self-botting. Maybe a cool down indicator? ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by mynameisbob1928** [comment]
Get dyno or one of the other million bots there are and use purge command
