### ISSUE TITLE
hide channels

### ISSUE THREAD

**Issue by elkapokogu** [Vencord/plugin-requests#568]
### Plugin Description

This adds a button at the top left in the tool bar to click which hides the channel list.

Additionally there is also a keybind option (default: Ctrl + H) you can use and rebind. like https://betterdiscord.app/plugin/Hide%20Channels

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sakuhaku** [comment]
It would be very nice to have this since watching a stream in VC with a smaller window is really cluttered with the channel list, the CSS things I saw didn't seem to work either
