### ISSUE TITLE
Plugin from better discord - Display Servers As Channels

### ISSUE THREAD

**Issue by SilverGamez** [Vencord/plugin-requests#57]
### Plugin Description

This plugin turns the server list to a channel list looking thing. This is already a plugin on better discord but I think that it would be a great plugin for vencord. The plugin can be found [here.](https://betterdiscord.app/plugin/DisplayServersAsChannels) Not much more to say but wondering if this could be added in the near future.
   
![image](https://github.com/Vencord/plugin-requests/assets/79312009/bd51bd38-463e-4780-9aee-4ffaccf149c2)

### Existing Plugin for other mod

https://betterdiscord.app/plugin/DisplayServersAsChannels
https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/DisplayServersAsChannels

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sasson100** [comment]
Honestly the fact Vencord doesn't have this plugin is the only thing keeping me from switching

**Comment by Inbestigator** [comment]
Seems more like a CSS problem
