### ISSUE TITLE
notifications on alt accounts

### ISSUE THREAD

**Issue by laelaps01** [Vencord/plugin-requests#571]
### Plugin Description

a plugin to still get notifications from other accounts you are signed in to but not actively on at the moment

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
almost certainly a risk trying to build another gateway connection into the client without extreme hacks to discord's code which is very difficult (anti-spam might flag the accounts if the gateway code is reimplemented badly)

**Comment by Sqaaakoi** [comment]
i know this was closed (and for good reason) however I think there might be some possibility. however I just read about https://github.com/Discord-Datamining/Discord-Datamining/commit/ed48dc268c2169c852d028161639c79eac7ef81d#commitcomment-142118545 and I suspect it could be potentially used for this in a semi-legit way?

**Comment by Vendicated** [comment]
no.
