### ISSUE TITLE
Chat downloading

### ISSUE THREAD

**Issue by Antonio225t** [Vencord/plugin-requests#572]
### Plugin Description

I searched if somebody already requested a plugin like this but seems like nobody did. If this is a duplicate I apologize.
That being said, I'd like to download Discord chats to keep memories I made with friends since Discord is... Seems like they're starting to delete old users and I have a DM full of memories that I don't want to lose...

I'd appreciate if the plugin downloads the chat and converts it into an HTML document so it's extendible, and if it downloads the attachments aswell it would be even better (since Discord has the "token in the link" thing that blocks you from accessing Discord assets from other websites).

If something sounds wrong in what I describe or the plugin is impossible to make, I apologize. Thank you for your time 👍

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by PATXS** [comment]
#534

**Comment by Antonio225t** [comment]
That's API abusing!? I'm sorry I didn't realize such...
Thank you anyways for reading my request.
