### ISSUE TITLE
AllCallTimeCounter from BetterDiscord

### ISSUE THREAD

**Issue by BLACK4585** [Vencord/plugin-requests#573]
### Plugin Description

A port of this plugin would be nice. Or add this to the existing CallTimeCounter Plugin as an extension.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/AllCallTimeCounter

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by D3SOX** [comment]
Already has a PR: https://github.com/Vendicated/Vencord/pull/2132

**Comment by BLACK4585** [comment]
Ah okay thank you!
