### ISSUE TITLE
multi reaction upload

### ISSUE THREAD

**Issue by Jess1246** [Vencord/plugin-requests#574]
### Plugin Description

uploads multiple emojis, stickers, soundboard sounds at the same time. like you just select the ones from your gallery that you want to upload, and it just uploads them for you. its okay if it takes some time, because it needs to temporarily store them somewhere. also it cant upload it for some reason, it cancels all uploads, incase theres some less important ones the user wants

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
you can literally already upload multiple emojis at the same time, dunno about others but probably

**Comment by mynameisbob1928** [comment]
https://github.com/Vencord/plugin-requests/assets/129603125/85783a64-44b0-4723-abab-101489d31653

**Comment by Jess1246** [comment]
> emojiiiiiiiiiii.mp4

oh, thank you, this will make it so much easier, althou i wish there was a thing like this for stickers and soundboard too. i get like 25 stickers i need to add and 15 sounds
