### ISSUE TITLE
Custom Notification Sound

### ISSUE THREAD

**Issue by Dim202** [Vencord/plugin-requests#575]
### Plugin Description

Add Notification Custom Sounds 

### Existing Plugin for other mod

https://betterdiscord.app/plugin/NotificationSounds

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/129603125/412c1c50-4084-4376-a9c3-2eb11aa7df4c)
stock feature coming soon, maybe when it does come out though could be a addon to fake nitro to unlock it
