### ISSUE TITLE
Easy timestamp maker

### ISSUE THREAD

**Issue by PELLYPELLY** [Vencord/plugin-requests#577]
### Plugin Description

Helly vencord,
I was thinking that a good plugin would be that you can easily create timestamps in messages. I dont know how you could do that but it would be really useful for a lot of people

### Existing Plugin for other mod

Not sure

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
https://vencord.dev/plugins/SendTimestamps
