### ISSUE TITLE
[Request] ShowMutualServers (on profile)

### ISSUE THREAD

**Issue by icrazykola** [Vencord/plugin-requests#58]
### Plugin Description

Shows mutual servers on user profiles, similar to ShowConnections and an old BD plugin UserDetails.

Screenshot (my personal favourite is when they are grouped together like this, rather than spread out): https://i.imgur.com/MXB4Dr2.png
Screenshot 2: https://i.imgur.com/669TsJk.png

Possible addon is show mutual friends as well, seen in screenshot 2 which was also in UserDetails

### Existing Plugin for other mod

https://betterdiscord.app/plugin/UserDetails (very outdated) and ShowConnections

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by D3SOX** [comment]
Discord now has this natively so I think this is obsolete
