### ISSUE TITLE
Channel Tabs

### ISSUE THREAD

**Issue by etzKondor** [Vencord/plugin-requests#580]
### Plugin Description

Existing plugin for better discord. 
Adds tabs and bookmarks to Discord, just like in a normal web browser.

### Existing Plugin for other mod

https://github.com/samfundev/BetterDiscordStuff/tree/0356e2a59f85f68ee3c55100265e061357daa8c0/Plugins/ChannelTabs

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AftmostSeeker80** [comment]
#6 #328 #433 #528 
> I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

me when I lie
