### ISSUE TITLE
emoji blocker

### ISSUE THREAD

**Issue by aho-emi** [Vencord/plugin-requests#581]
### Plugin Description

Okay! so the plugin will hide the message which contains certain blocked emojis, or either remove the emojis from the message and only show the rest.

Personal Opinion as people send creepy emojis

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
I think this could be possible with https://github.com/Vendicated/Vencord/pull/2238? I'm thinking maybe you could add the emoji's name to your filters and it would block the message containing said emoji.

**Comment by Vendicated** [comment]
#159
