### ISSUE TITLE
Plugin ChannelTabs

### ISSUE THREAD

**Issue by pikachuska** [Vencord/plugin-requests#582]
### Plugin Description

Add new channel tab
[link](https://betterdiscord.app/plugin/ChannelTabs)
![Screenshot_4](https://github.com/Vencord/plugin-requests/assets/122621684/9421e5b4-2523-4775-8513-d1f0a1a7164c)

### Existing Plugin for other mod

https://betterdiscord.app/plugin/ChannelTabs

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AftmostSeeker80** [comment]
#6 #328 #433 #528 #580 

>I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

me when I lie

**Comment by dopefisher** [comment]
That other plugin does not work with Vencord!

**Comment by rozbrajaczpoziomow** [comment]
> That other plugin does not work with Vencord!

wha

**Comment by dopefisher** [comment]
We are looking for a channeltabs plugin that works in Vencord, if such a thing is possible.
