### ISSUE TITLE
Swear blocker

### ISSUE THREAD

**Issue by Antonio225t** [Vencord/plugin-requests#585]
### Plugin Description

I was thinking about a plugin that would replace swearings and bad words with like "\<censored\>" text in client-side, I would like this to filter chat messages, member names, status, bioses (EDIT: and also channel names. Sorry I forgot)... If this is a duplicate I'm sorry, I did search to see if it was already made but it doesn't seem so. Thank you for reading 😀

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by VillainsRule** [comment]
isn't discord doing this soon?

**Comment by Antonio225t** [comment]
> isn't discord doing this soon?

If Discord does this soon I'll thank them... The thing is, swearings kind of trigger me and my friends are on Discord (I don't think I'd like to go back on Skype lol), since the Discord servers and... Well kind of the whole internet likes to swear, so if there is a way to block a list of words I'd be thankfull.

Also there seems to be people disagreeing/disliking this idea, if there is a person that dislikes it, can you express why? After all, I guess that this is better than actually saying "plz don't swear" a 1000 times because somebody just does it, am I right?

Thanks in advance 👍

**Comment by Vendicated** [comment]
#159

**Comment by Antonio225t** [comment]
> #159

That's great! Thanks for finding it. The only thing is that it blocks only the messages (I mean, it doesn't block other things like member names or bios or others I guess) and the description says that the plugin should block the entire message, while what I wanted is just to cover the word I don't want to see.

But anyways https://github.com/Vencord/plugin-requests/issues/159 looks cool. Thanks and sorry if this sound like a duplicate.
