### ISSUE TITLE
Find a list of all your friends in a particular server/interested people

### ISSUE THREAD

**Issue by vijaypondini** [Vencord/plugin-requests#586]
### Plugin Description

Just like how for each friend you can see their mutual servers and mutual friends, make it so that in a server, we can see what friends of ours are in it. This will be useful for us to know how many/which of our friends are in the servers we are in.
Additionally, provide an option to add custom user IDs to track for anyone sharing a common server with you

So the plugin would have settings to enable "friends", and "by discord ID". Enabling each of them would show respectively who are all in that same server along with you. 

I'd find this really useful because I've always wanted to know who of my friends are in a server without needing to scroll through everyone. Hope this makes sense!

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
https://vencord.dev/plugins/ServerProfile
