### ISSUE TITLE
Mobile Phone Online Status

### ISSUE THREAD

**Issue by vorine** [Vencord/plugin-requests#588]
### Plugin Description

I'm aware that bots can do this, but I'm wondering if it's possible to include it as a plugin, similar to the streaming status feature.
 ![image](https://github.com/Vencord/plugin-requests/assets/167487479/99ebf048-d616-46e2-9fcb-5190cce3fae9)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
what

**Comment by Faf4a** [comment]
They probably mean the ability to set the status/platform to "mobile" on desktop.

**Comment by vorine** [comment]
Yes
