### ISSUE TITLE
click and copy

### ISSUE THREAD

**Issue by unclealvin123** [Vencord/plugin-requests#591]
### Plugin Description

hi, would it be possible to add a plugin that makes the user able to copy texts from images

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
use a user app with ocr command, like https://discord.com/application-directory/682654466453012553
