### ISSUE TITLE
[Request] Plugin that removes the GIFs search restrictions

### ISSUE THREAD

**Issue by elmolini** [Vencord/plugin-requests#592]
### Plugin Description

A plugin that removes the restrictions on the GIFs search engine. If you search for more, let's say "controversial" things on the GIF search bar, it'll just outright not show anything.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
That's because there aren't any gifs on [tenor](https://tenor.com/search/adolf-gifs) (or [giphy](https://giphy.com/search/adolf)) with "controversial" topics, which is where discord gets their gifs from, so naturally it's gonna be empty.

**Comment by elmolini** [comment]
maybe its js me being crazy but i remember a time where it showed controversial gifs. ive seen people posting n word gifs too 

but yeah ur right

**Comment by rozbrajaczpoziomow** [comment]
people can make their own gifs, upload them anywhere and favourite them. /shrug
