### ISSUE TITLE
More Servers

### ISSUE THREAD

**Issue by festis11** [Vencord/plugin-requests#594]
### Plugin Description

Make it so you can be in over 100 server

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
buy nitro /shrug

**Comment by Koishukaze** [comment]
you cant bypass serverside restrictions

**Comment by schoeneBiene** [comment]
> I read the above and made sure my plugin is possible and allowed

me when I lie

**Comment by radishcatish** [comment]
in all honesty who ACTUALLY fucking joins more then like, 50 servers. if you need to join MORE THEN 100 you have problems and the only exception is if they're emote servers or utility servers (like ESMbot)

**Comment by mynameisbob1928** [comment]
> in all honesty who ACTUALLY fucking joins more then like, 50 servers. if you need to join MORE THEN 100 you have problems and the only exception is if they're emote servers or utility servers (like ESMbot)

im in like 90 servers :D

**Comment by radishcatish** [comment]
![flashlight](https://github.com/Vencord/plugin-requests/assets/166326616/daf9669e-2557-43e3-b70f-3f37714966a9)

**Comment by radishcatish** [comment]
why the fuck is it ai upscaled
