### ISSUE TITLE
Pin Channel

### ISSUE THREAD

**Issue by kingy3577** [Vencord/plugin-requests#598]
### Plugin Description

**Pin Channel**
similar to pin dm where you can add specific channels as links or something to your DMs (or similar)

Not sure if this is the same as "Channel Tabs" as others have mentioned and if channel tabs save after re-opening discord (sorry if it is)

### Existing Plugin for other mod

Not Sure

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
There's this old discord experiment called 'Favourites server'. Once enabled you can right click any channel and it'll show in it's own server thing right under dms
![image](https://github.com/Vencord/plugin-requests/assets/129603125/f4fbbb83-d4e9-49c6-a3d0-2b3907f4edaf)
plus side of this is that it also works on mobile (you can only add on pc with experiment but it is still viewable on mobile and other devices)
