### ISSUE TITLE
Bring back the Old Profile Cards

### ISSUE THREAD

**Issue by GiZM059** [Vencord/plugin-requests#599]
### Plugin Description

Bring back the Old Profile Cards

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
turn off the experiment

**Comment by RathAdventures** [comment]
Turning off the experiment is only temporary. Knowing discord this will be released to everyone, and a plugin to show full profile cards would be very nice.

**Comment by nin0-dev** [comment]
> Turning off the experiment is only temporary. Knowing discord this will be released to everyone, and a plugin to show full profile cards would be very nice.

that's an experiment, which means things will likely change over time. therefore making any patch on the new profile UI isn't sustainable until it actually gets "set in stone"

**Comment by Sqaaakoi** [comment]
> Turning off the experiment is only temporary. Knowing discord this will be released to everyone, and a plugin to show full profile cards would be very nice.

They will only delete the experiment after a year, it's fine
