### ISSUE TITLE
feat(plugin request) - Unstyled Markdown in messages

### ISSUE THREAD

**Issue by aoqia194** [Vencord/plugin-requests#60]
### Plugin Description

This concept plugin should transform messages with Markdown styling into raw Markdown with no styling. An example of this would be: Instead of a h1 message displaying a header 1 style, it would rather display "# test header" to the reader.

In addition to the h1 spammers, the new addition to Markdown hyperlinks using \[text](link) format is making it easier to scam and manipulate unsuspecting victims. My thought of this concept plugin was for this exact reason. I did try to develop this plugin on my own, but not being a web developer and having no experience with Vencord plugins whatsoever proved a humbling 8-hour experience by total destruction of all neurons located inside the brain in the name of JavaScript.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
that would be a nice plugin, if it were to be made it would also be nice to have a button to toggle the markdown so it can be seen with it if wanted

**Comment by cheesesamwich** [comment]
ViewRaw kinda does this i guess? good idea tho

**Comment by nvhhr** [comment]
I'm not sure there's anything here that can't be achieved with some css.

If h1 elements are too big just change their font-size:
`.markup_a7e664 h1 { font-size: 1rem; }`
You can also do any kind of other styling this way to fit your preference, with way more flexibility than what a plugin would offer.
with ::before/::after pseudoelements you can create the characters used in the markdown too, and strip out the styling from any bold/underline/strikethrough/etc.

Neat snippet example for masked links:
```
.anchor_c8ddc0[title$=")"]::after {
    font-size: 0.7rem;
    content: " (" attr(href) ")";
    filter: grayscale(0.4);
}
```

A toggle button can't be done in css, but a workaround for that is to switch styling when hovering a specific element of your choice or whatever.
Maybe ViewRaw could have an addition to always show raw message or something if there's really a need for that?

**Comment by Vendicated** [comment]
> markdown headers take up too much space

use css
```css
.markup_a7e664 :is(h1, h2, h3, h4, h5, h6) {
    all: inherit;
}
```


> Markdown hyperlinks using [text](link) format [make] it easier to scam and manipulate unsuspecting victims

they really don't

![image](https://github.com/Vencord/plugin-requests/assets/45497981/54e5500f-3d68-4770-835e-aca41463b809)

for any other use cases, once again CSS or View Raw
