### ISSUE TITLE
Passcode lock needed for vencord 

### ISSUE THREAD

**Issue by N0tBLUE** [Vencord/plugin-requests#602]
### Plugin Description

like this [plugin](https://github.com/arg0NNY/DiscordPlugins/tree/master/PasscodeLock) can we have passcode plugin for vencord 
this is the only reason stopping me from installing vencord and stop using betterdiscord 
i hope you guys will try your best 

![image](https://github.com/Vencord/plugin-requests/assets/74755694/e8a81655-3a11-4e33-a397-07c7831fbc98)

### Existing Plugin for other mod

https://github.com/arg0NNY/DiscordPlugins/tree/master/PasscodeLock

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
> I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

#375 #360 #10 #54 #211 #226

**Comment by schoeneBiene** [comment]
#327 #245 #226 #54
> I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
me when I lie

**Comment by radishcatish** [comment]
i wish you luck hiding your porn from mom, N0tBLUE
