### ISSUE TITLE
mutual friends finder

### ISSUE THREAD

**Issue by FatalDiscovery** [Vencord/plugin-requests#604]
### Plugin Description

a plugin that can "scan" a server and find people you have mutual friends with

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by schoeneBiene** [comment]
#329 
> I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist

me when I lie

**Comment by mynameisbob1928** [comment]
wrong quote xd
