### ISSUE TITLE
Mass Channel Notifications Mute button 

### ISSUE THREAD

**Issue by RabbiPika** [Vencord/plugin-requests#606]
### Plugin Description

It would be a button like the read all messages plugin but for sever channel notifications settings and would set the setting to mute all indefinitely as it is really time consuming to do manually for any server I join with more than 12 server channels

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
1. NewGuildSettings
2. Just mute the whole server??

**Comment by RabbiPika** [comment]
no it mute each individual server channel

**Comment by MrDiamondDog** [comment]
What's the point of that

**Comment by RabbiPika** [comment]
to save time

**Comment by Vendicated** [comment]
if you want to mute every channel then just mute the entire server in server settings
