### ISSUE TITLE
fakeDeafen&mute

### ISSUE THREAD

**Issue by iWz3r** [Vencord/plugin-requests#608]
### Plugin Description

fakeDeafen&mute you can put a deafen & mute and you can talk above you put it

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
>  I read the above and made sure my plugin is possible and allowed

me when i lie

1) incredibly creepy
2) you are stalking if you use them

**Comment by ashley-graves** [comment]
>## Do not request any of the following plugins:
>- Plugins that spy on other users (like FakeDeafen)
