### ISSUE TITLE
plugins

### ISSUE THREAD

**Issue by NoobShadowMaster** [Vencord/plugin-requests#609]
### Plugin Description

хочу себе этот плагин но его нету в vencord 

### Existing Plugin for other mod

https://betterdiscord.app/plugin/EditUsers

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by PATXS** [comment]
#102 #209 #384 #476 #597

**Comment by qtlunya** [comment]
Your suggestion was not actually rejected, it was only closed because it was already suggested in #102, and there is no point in having two separate suggestions open for the same thing.
