### ISSUE TITLE
Open DM directly without friend request

### ISSUE THREAD

**Issue by danilwhale** [Vencord/plugin-requests#61]
### Plugin Description

Right now, you have to first make friend request to the user and then send DM (if this user didn't send any message before in any of server where you exist). I think it will be just easier to do this using a single button and don't annoy user with friend requests.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by D3SOX** [comment]
Literally open the profile, click on the three dots and then on message

**Comment by danilwhale** [comment]
> Literally open the profile, click on the three dots and then on message
**(if this user didn't send any message before in any of server where you exist)**

**Comment by D3SOX** [comment]
Then just tag anywhere using `<@userid>`

**Comment by danilwhale** [comment]
> Then just tag anywhere using `<@userid>`

to get id you still need user's profile

**Comment by Vendicated** [comment]
you can literally just use the quickswitcher

![image](https://github.com/Vencord/plugin-requests/assets/45497981/20d3e1a8-011d-450a-bafc-db9ebca2499a)
