### ISSUE TITLE
[Accessibility] Bionic Reading

### ISSUE THREAD

**Issue by danielah05** [Vencord/plugin-requests#62]
### Plugin Description

bionic reading for discord. this would be a great accessibility option to have if ever implemented, i personally struggle when it comes to reading, and i know other people like that as well, and bionic readers have been really helpful for that on browser using extensions, and having this as an option on discord would be genuinely great!

how i imagine it could be implemented is by making certain letters bold on the clients side (if possible that is), kinda like you can already do manually by adding * to it.

im unsure if this would be useful but there already is an open source implementation of a bionic reader on github, which could possibly used for something like this on discord? im not really sure, i dont know how stuff like this works.
https://github.com/Gumball12/text-vide

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
There is a font that somewhat does this apparently.
https://github.com/Born2Root/Fast-Font
Install the font, and put this (or serif variant) in quickcss: ``:root { --font-primary: "fast_sans"; }``

![image](https://github.com/Vencord/plugin-requests/assets/34724502/7295b131-94b7-48e7-a318-c33a5757b93a)

**Comment by danielah05** [comment]
wasnt aware that theres a font that tries doing this in a way, ill check it out for now thanks!
