### ISSUE TITLE
Destiny LFG Plugin

### ISSUE THREAD

**Issue by Riobii** [Vencord/plugin-requests#620]
### Plugin Description

It's a plugin that allows messages like "/join Riobi#9999" to be hyperlinked and with one click copy to clipboard to make it easier to paste and join others in destiny 2. I provided a link to the plugin. Thanks for reading!

### Existing Plugin for other mod

https://github.com/bodaay/DestinyLFGJoinInviteCopier

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
just use TextReplace
