### ISSUE TITLE
Plugin Request - FirstMessage

### ISSUE THREAD

**Issue by waterbufalowalking** [Vencord/plugin-requests#621]
### Plugin Description

Always opens to the first new message at the bottom of a chat. 

When reopening chats, it's often that you will be placed hundreds of messages above recent ones and you will end up spamming clicking the "back to new" button. Thanks to discord scrolling you back up for no reason you have to click 5-10 times to be brought to new chats. This plugin will help greatly.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
press esc

**Comment by waterbufalowalking** [comment]
> When reopening chats, it's often that you will be placed hundreds of messages above recent ones and you will end up spamming clicking the "back to new" button. Thanks to discord scrolling you back up for no reason you have to click 5-10 times to be brought to new chats. This plugin will help greatly.

I just explained why this doesn't work
