### ISSUE TITLE
user logs

### ISSUE THREAD

**Issue by kittenvr** [Vencord/plugin-requests#623]
### Plugin Description

a plugin that adds a rightclick option to a user show message logs which opens a popup with their message history in servers you are in

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by programminglaboratorys** [comment]
first this would need fetching messages from what I know that's self botting, second what purpose would this serve?

**Comment by kittenvr** [comment]
> first this would need fetching messages from what I know that's self botting, second what purpose would this serve?

seeing what people say

**Comment by Vendicated** [comment]
stock feature
![image](https://github.com/Vencord/plugin-requests/assets/45497981/0ab856a9-0cc6-4e1e-ab4c-4681cc7d810f)

**Comment by kittenvr** [comment]
> stock feature ![image](https://private-user-images.githubusercontent.com/45497981/333891806-0ab856a9-0cc6-4e1e-ab4c-4681cc7d810f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzgyNjEsIm5iZiI6MTcxNjczNzk2MSwicGF0aCI6Ii80NTQ5Nzk4MS8zMzM4OTE4MDYtMGFiODU2YTktMGNjNi00ZTFlLWFiNGMtNDY4MWNjN2Q4MTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE1MzkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZGQyYTY2Yzc0YjA2M2FhYTk0NmVlZGU1MGQwZjJhZTdkZDViZDI5NGJhNzcyZmRkMDBhYjI1OWU5MDk0N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GA5gfTD80cAR9MyAQ8PFwKARa8xzKkWzjSTsYsUhjkI)

thats only one server i want it to be in every mutual server
