### ISSUE TITLE
Change Settings order

### ISSUE THREAD

**Issue by User3254548** [Vencord/plugin-requests#624]
### Plugin Description

Plugin to fully Re arange and hide all settings to your own liking

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
ThemeAttributes + css can do this

**Comment by Vendicated** [comment]
you can receive help in our support channel
