### ISSUE TITLE
SplitLarheMessages

### ISSUE THREAD

**Issue by Zarak199076** [Vencord/plugin-requests#626]
### Plugin Description

So it sends your VERY LONG discord message as multiple messages instead of making it a txt file or you having to delete it entirely

### Existing Plugin for other mod

https://betterdiscord.app/plugin/SplitLargeMessages

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
Why not just do it manually instead so it makes more sense instead of the plugin splitting off at some random point (if there’s even a paragraph to begin with)
