### ISSUE TITLE
Plugin: animatedBackgrounds

### ISSUE THREAD

**Issue by soulfireneedusername** [Vencord/plugin-requests#628]
### Plugin Description

Allows you to set a YoutTube video as an animated background. I recommend using a long loop Video. A background supporting theme must be installed. Just paste any YouTube Video URL in the link Input in the plugin settings. 
<img width="960" alt="image" src="https://github.com/Vencord/plugin-requests/assets/141316485/bc57644e-752c-449a-8e6f-592a8f368dc2">
Use this for example: https://youtu.be/Q7W4JISNmQk?si=NxVreG4ZDz6zOUNs

I hope this is not against any policies. Also tried a clean code this time.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
Why did you make a plugin request for a plugin you already made

**Comment by Vendicated** [comment]
css
