### ISSUE TITLE
Plugin that fixes with AI

### ISSUE THREAD

**Issue by zykoytz** [Vencord/plugin-requests#629]
### Plugin Description

Hello, I would like to propose this idea basically to make a plugin which allows you to correct the text automatically or to translate but above all mainly to correct what we send the sentence AI corrects while trying to be a human being with the API open gpt chat ai

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
that would require paying, unless you are assuming the enduser will provide a token? (in which case, itll mean that *they* pay)

**Comment by zykoytz** [comment]
> that would require paying, unless you are assuming the enduser will provide a token? (in which case, itll mean that _they_ pay)

yeah please

**Comment by ImLvna** [comment]
vee has expressed that no plugins requiring the user to generate a token will be accepted

**Comment by Scyye** [comment]
> vee has expressed that no plugins requiring the user to generate a token will be accepted

in that case, shouldnt customRPC not be allowed?

**Comment by MrDiamondDog** [comment]
> > vee has expressed that no plugins requiring the user to generate a token will be accepted
> 
> in that case, shouldnt customRPC not be allowed?

you dont have to pay for that, i think that was implied in the original message

**Comment by Scyye** [comment]
> > > vee has expressed that no plugins requiring the user to generate a token will be accepted
> > 
> > 
> > in that case, shouldnt customRPC not be allowed?
> 
> you dont have to pay for that, i think that was implied in the original message

it really wasnt.

the only tokens used on discord usually, are completely free.

(user tokens, and bot tokens)

**Comment by zykoytz** [comment]
otherwise is it possible to pay to have this extension for just me?

**Comment by nin0-dev** [comment]
1. this entire idea is not that useful, you can use a user app for it
2. if you find someone that wants to make this plugin yes
