### ISSUE TITLE
activity page :3

### ISSUE THREAD

**Issue by starriescythe** [Vencord/plugin-requests#631]
### Plugin Description

a plugin where it makes a customizable "now playing"/"now listening" page where you can change the title, picture and description :3c

### Existing Plugin for other mod

I don't think there is one!

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
You appear to be talking about customRPC https://vencord.dev/plugins/CustomRPC

![image](https://github.com/Vencord/plugin-requests/assets/129603125/07781a9f-1d39-4c6a-b2fc-d95f9d83fd94)
![image](https://github.com/Vencord/plugin-requests/assets/129603125/bc1c59ec-2431-471b-b1f9-828939c64d04)

**Comment by schoeneBiene** [comment]
> I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist

me when I lie

**Comment by starriescythe** [comment]
i didn't know it was called a rich presence, i didn't lie i just didn't
know what i was looking for ):
