### ISSUE TITLE
Iphone emojis

### ISSUE THREAD

**Issue by MinioneQMC** [Vencord/plugin-requests#633]
### Plugin Description

it would be great if there was a plugin that replaces original discord emojis with the ones that iphone.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by ImLvna** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/44179559/37b8ccca-944c-4d81-8ac7-4582a65f82e7)

**Comment by nvhhr** [comment]
https://github.com/mwittrien/BetterDiscordAddons/blob/master/Themes/EmojiReplace/EmojiReplace.theme.css
Here's a 'theme' that does it.
