### ISSUE TITLE
Better formating

### ISSUE THREAD

**Issue by BlueMoonTR** [Vencord/plugin-requests#637]
### Plugin Description

Betterdiscord plugin. 

### Existing Plugin for other mod

https://betterdiscord.app/plugin/BetterFormattingRedux

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
accessibility nightmare

**Comment by AftmostSeeker80** [comment]
#8
