### ISSUE TITLE
auto encrypt / auto decrypt

### ISSUE THREAD

**Issue by coolrack** [Vencord/plugin-requests#640]
### Plugin Description

a plugin which you can choose different text encryption methods, with cypher modes, and output types. options to toggle encryption, and toggle decryption if recipient is also using this.

i managed to find something related to what i was looking for, i've provided a link below, although i haven't used it before, i'm unaware if it matches with my description.

### Existing Plugin for other mod

https://noirth.com/threads/betterdiscord-encrypted-text.2008/

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Inbestigator** [comment]
Check out Encryptcord

**Comment by Thandeka0** [comment]
Just use invisiblechat.

**Comment by Inbestigator** [comment]
> Just use invisiblechat.

Not actually encrypted

**Comment by coolrack** [comment]
> Check out Encryptcord

i couldn't find what you're mentioning here, but i found a extremley simillar plugin on bd (although not official).

https://github.com/hmerritt/discord-encryption

this has mostly what i mentioned, other that different cypher modes, and output types.

**Comment by Inbestigator** [comment]
> i couldn't find what you're mentioning here, but i found a extremley simillar plugin on bd (although not official).

Check out #third-party-plugins in the Vencord Discord server

**Comment by Vendicated** [comment]
encryption inside discord makes no sense. use a proper encrypted messenger like signal, matrix, xmpp, etc
