### ISSUE TITLE
KeywordMatch/NotificationHistory Plugins

### ISSUE THREAD

**Issue by randoomdude** [Vencord/plugin-requests#641]
### Plugin Description

The two most important plugins from BetterDiscord, basically any way to keep a log/display notifications and keywords or user id match, because whats the point of having a dozen servers that have the notif sound going off if there's no way to check what it is or check after you come back from a break.

Note: NotificationHistory stopped working on BetterDiscord a couple months ago and hasn't been maintained

![image](https://github.com/Vencord/plugin-requests/assets/6027132/307d68e4-7cc1-4575-9237-a3cfc3c5f018)
![image](https://github.com/Vencord/plugin-requests/assets/6027132/22a77456-c99f-438e-9a06-2f2841627e7d)
![image](https://github.com/Vencord/plugin-requests/assets/6027132/ab0ed30c-4a8d-49fc-8f05-740c74f7c2b3)
![image](https://github.com/Vencord/plugin-requests/assets/6027132/f28cb5b4-1d26-4254-a6e5-9d1024be902d)

### Existing Plugin for other mod

https://github.com/sarahkittyy/KeywordTracker
https://github.com/BrandonXLF/BetterDiscordPlugins/tree/main/src/NotificationHistory

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
I believe https://github.com/Vendicated/Vencord/pull/1960 would satisfy this request?

**Comment by Vendicated** [comment]
follow the request rules or you will be blocked from opening further requests.
