### ISSUE TITLE
Red Notification Post Checker

### ISSUE THREAD

**Issue by randoomdude** [Vencord/plugin-requests#642]
### Plugin Description

This would be similar to NotificationHistory, but just for checking what posts the red notifications dots are referencing in a channel when you have too many to know, or got one but it was too far up and you can't find it, might be easier to implement than full NotificationHistory but I would prioritize just general history, but using both would cover all instances of confusing notifications
![image](https://github.com/Vencord/plugin-requests/assets/6027132/2f1ff736-edbc-40e1-9414-d29180e2415f)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/45497981/902d3626-b52e-4f28-affc-189a36c5dbf1)
