### ISSUE TITLE
Add the auto capitalizer, from BetterDiscord

### ISSUE THREAD

**Issue by Zagmeeboi** [Vencord/plugin-requests#647]
### Plugin Description

Maybe some people are just too lazy to write capitals in their text so they would like a auto capitalizer so they dont have to capitalize their text when texting!

### Existing Plugin for other mod

https://betterdiscord.app/plugin/WriteUppercase

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
#170
