### ISSUE TITLE
Favorite Images and videos to custom "GIF" categorizes

### ISSUE THREAD

**Issue by Linkus12** [Vencord/plugin-requests#648]
### Plugin Description

Basically allows you to make new categorizes in the "GIF" button section, you can right click on image/video and save it into that category to basically save the image/video for a later use similar to favoriting GIFs (Basically just save the link of the image/video when choosing them in the category, for example: You have the favorite category, videos category and images category that you can open and choose what you're looking for, similar to GIFs)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
Requests already exist see #44 #13
