### ISSUE TITLE
low bandwidth mode

### ISSUE THREAD

**Issue by EmeraldSnorlax** [Vencord/plugin-requests#650]
### Plugin Description

discord is extremely greedy with bandwidth and does not behave well with unreliable connections, which is not great for my incredibly slow and spotty internet connection (goes as low as 30kb/s). 

it would be very much appreciated if:
- things like custom emojis, gifs, images, etc were replaced with their alt text and a link to download (by opening a web browser. firefox's download queue is infinitely more robust to adverse conditions than discord is. downloading a 14mb image takes several minutes and may fail several times.)
- prevent client updates entirely (discord is already in my distro's package repositories, so at worst my discord version will be maybe a few days out of date between repository updates. this is infinitely preferable over burning several hundred mb for essentially nothing)
- retry message sending when connection is restored, both red messages and vanished messages -- discord will just eat the message if enough time passes (it doesn't turn red, it just completely *vanishes*).
- generally just cut down on heavy network requests. there's probably more that can be done but click to load media, better handling of dropped messages, and killing the client autoupdater are all i can think of right now

this article is tangentially related and you may or may not find it useful https://brr.fyi/posts/engineering-for-slow-internet

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
> things like custom emojis, gifs, images, etc were replaced with their alt text and a link to download (by opening a web browser. firefox's download queue is infinitely more robust to adverse conditions than discord is. downloading a 14mb image takes several minutes and may fail several times.)

emojis are cached and are small, for images you can turn off embedding in discord settings (stock feature)

> prevent client updates entirely (discord is already in my distro's package repositories, so at worst my discord version will be maybe a few days out of date between repository updates. this is infinitely preferable over burning several hundred mb for essentially nothing)

actual app js is cached, for the native stuff isn't that downloaded on startup? and it's totally separate to the stuff in the package? there is a secret setting you can set in settings.json to turn off that updater check though iirc
(also obligatory running "discord desktop" on linux is a bad idea if you use wayland btw; use Vesktop)

> retry message sending when connection is restored, both red messages and vanished messages -- discord will just eat the message if enough time passes (it doesn't turn red, it just completely vanishes).

this would actually be very useful

> generally just cut down on heavy network requests. there's probably more that can be done but click to load media, better handling of dropped messages, and killing the client autoupdater are all i can think of right now

honestly idk if vencord can do cut down on heavy network requests; you would be surprised how much useless junk the Discord gateway sends to clients (though it is small and compressed)
regarding click to load media, that would actually be useful and discord doesn't provide this when disabling embedded media like I mentioned earlier

**Comment by EmeraldSnorlax** [comment]
vesktop is not suitable for me as it lacks push to talk. otherwise, thank you, i'll try the things youve mentioned :)

**Comment by Sqaaakoi** [comment]
> vesktop is not suitable for me as it lacks push to talk. otherwise, thank you, i'll try the things youve mentioned :)

sounds like you are an x11 user in which case vesktop probably cant fix a whole load anyway

**Comment by EmeraldSnorlax** [comment]
im on wayland

**Comment by Sqaaakoi** [comment]
must be using discord in xwayland then with a compositor sending all events to xwayland apps then

**Comment by Vendicated** [comment]
This isn't realistically possible from a plugin, since most of those requests are necessary for proper functioning of the client and stopping specific requests would be a lot of effort. And it's way too niche

Either use the stock options (eg disabling embeds in settings, like sqakoi mentioned) or consider using a lighter third party discord app like https://github.com/diamondburned/dissent

**Comment by EmeraldSnorlax** [comment]
would you not be able to register a service worker to blackhole those requests as a naive solution?

**Comment by Sqaaakoi** [comment]
blackholing them is not useful just accept what is cached already or is small and don't load what isn't cached
