### ISSUE TITLE
Disable Call Keybind

### ISSUE THREAD

**Issue by 4Bakers** [Vencord/plugin-requests#651]
### Plugin Description

Disables `CTRL '` keybind for Start Call in Private Message Or Group because I keep hitting it on accident and it's really annoying.
I meant to type a quotation mark but *oops*, now a call's started...

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by skullriot** [comment]
You can disable the keybind by binding Ctrl ' to unassigned in the keybind menu.

**Comment by 4Bakers** [comment]
I already tried that but apparently I didn't try hard enough.
I got it working!
(that is really unintuitive btw, damn.)
