### ISSUE TITLE
AI sniffer

### ISSUE THREAD

**Issue by discordnekoli** [Vencord/plugin-requests#652]
### Plugin Description

plugin that shows if a discord account is being controlled/ handled by AI (API or BOT)
_I'm sure anything is possible if you know how to do it._

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by discordnekoli** [comment]
we have users starting create accounts and let bots/AI handle them for the user. we want to stop this in our server and need a leg up on this. please help.

**Comment by programminglaboratorys** [comment]
man, discord themselves have difficulty detecting selfbots and you wanna a client-side plugin to tell? will there is for sure some factors to guess how much this user is close to being a bot but it won't be a accurate. taking your request word by word its impossible

**Comment by discordnekoli** [comment]
> man, discord themselves have difficulty detecting selfbots and you wanna a client-side plugin to tell? will there is for sure some factors to guess how much this user is close to being a bot but it won't be a accurate, taking your request word by word its impossible

im sure it's possible.

**Comment by mynameisbob1928** [comment]
Selfbots are hard to detect (unless the creator is stupid). Accounts that just sit in a server and collect messages and other similar data are impossible to distinguish to an inactive member. If there was an easy/reliable way to detect these type of accounts then I’d hope discord would already be doing it. 
An alternative solution would be to implement some form of verification in your server and if the member does not complete the verification within x amount of time you can kick the user. This would have to be done with a custom bot and not onboarding or some other public bot as more advanced selfbots are able to autocomplete simple verification.

**Comment by Vendicated** [comment]
just use a normal Discord bot for this
