### ISSUE TITLE
NotificationSounds

### ISSUE THREAD

**Issue by HetDays** [Vencord/plugin-requests#654]
### Plugin Description

Allows you to replace the native Sounds with custom Sounds.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/NotificationSounds

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by danielah05** [comment]
https://github.com/Vendicated/Vencord/pull/1765

**Comment by nvhhr** [comment]
#21
