### ISSUE TITLE
betterdiscord to vencord

### ISSUE THREAD

**Issue by hamzamake** [Vencord/plugin-requests#655]
### Plugin Description

A plugin where you get plugins from a different Discord mod like BetterDiscord and put the plugin there, and then use BetterDiscord plugins on Vencord. Please, there are so many cool ones on BetterDiscord, and I used to use BetterDiscord until I found Vencord because it doesn't crash. If the plugin does make Vencord crash, you can check if it will crash before you install it.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
it seems that you do not know how bd/vencord plugins work, and that's okay! that's why I will teach you this today.

betterdiscord monkeypatches webpack. you do not have to know what this means, idk too.

vencord, meanwhile, uses regular expressions to directly edit discord's clientside code.

these two are not compatible in any way. this means betterdiscord support will likely never come to vencord

**Comment by hamzamake** [comment]
Then change how vencord works or is that too far just for one plugin

Sent from the all new AOL app for iOS


On Saturday, June 1, 2024, 4:20 PM, nin0dev ***@***.***> wrote:




it seems that you do not know how bd/vencord plugins work, and that's okay! that's why I will teach you this today.

betterdiscord monkeypatches webpack. you do not have to know what this means, idk too.

vencord, meanwhile, uses regular expressions to directly edit discord's clientside code.

these two are not compatible in any way. this means betterdiscord support will likely never come to vencord

**Comment by nin0-dev** [comment]
bd hooks into your discord app in a specific way that only allows monkeypatching.

also bd plugins will likely never be supported into vencord since its plugin ecosystem is extremely bloated.

if there's one specific plugin you want request it
