### ISSUE TITLE
DMsOrganzier

### ISSUE THREAD

**Issue by karimawi** [Vencord/plugin-requests#656]
## Description:
Adds a filter and a sort button on top of the DM list to get easy and quick access to important DMs

Here's a scuffed demo done in Figma to demonstrate the feature:

### Default
![Default](https://github.com/Vencord/plugin-requests/assets/69881381/e0fd0c7e-c1d3-482a-a6e0-bc7f1c7ef148)

### Create DM Hovered (Control)
![Create DM Hovered](https://github.com/Vencord/plugin-requests/assets/69881381/3983bbd5-a944-42a3-9d24-0f929bffbd6d)

### Filter DMs Hovered
![Filter DMs Hovered](https://github.com/Vencord/plugin-requests/assets/69881381/3c9911a3-1d24-440f-a540-5aa53844209c)

### Sort DMs Hovered
![Sort DMs Hovered](https://github.com/Vencord/plugin-requests/assets/69881381/821501a8-28f5-4c96-8c8d-76100646b4b9)

### Filter DMs Open (scaling and spacing might be off, but you get the idea)
> These are just the filter ideas that I had in mind and found would be useful for me, there might be other useful ones that didn't come to mind

![Filter DMs Open](https://github.com/Vencord/plugin-requests/assets/69881381/a03f104c-280c-431c-b207-f1483455565f)

### Sort DMs Open
> These are just the sorting ideas that I had in mind and found would be useful for me, there might be other useful ones that didn't come to mind

![Sort DMs Open](https://github.com/Vencord/plugin-requests/assets/69881381/7c281020-0abc-475a-89c0-6d79f2c2c528)

### Filter & Sort Active
![Filter & Sort Active](https://github.com/Vencord/plugin-requests/assets/69881381/fce6464c-6ad3-4472-ad61-a0d685b21017)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
https://vencord.dev/plugins/PinDMs

**Comment by karimawi** [comment]
Wll, PinDMs doesn't do filtering or sorting, I'll try to manage something myself and mention it here when I'm free, thanks for checking the issue out though, appreciate all the hard work that you do 🫡
