### ISSUE TITLE
UrgentNotifications

### ISSUE THREAD

**Issue by LunRos** [Vencord/plugin-requests#657]
### Plugin Description

A plugin that allows messages to bypass do not disturb and streamer mode.

### Existing Plugin for other mod

https://github.com/YuzuZensai/UrgentNotification

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
https://github.com/Vencord/plugin-requests/issues/131
