### ISSUE TITLE
Automatically enable streaming mode, while streaming in Discord.

### ISSUE THREAD

**Issue by frosthuuund** [Vencord/plugin-requests#659]
### Plugin Description

In the title.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
Correct me if I'm wrong, but, isn't that already a thing? I'm thinking of the plugin called "StreamerModeOnStream".

**Comment by fily-gif** [comment]
afaik impossible to check without connecting through websockets. Discord automatically turns on steaming mode when you **open** obs/etc.

To show the streaming status, you have to enable it and start streaming on a connected account.

**Comment by schoeneBiene** [comment]
https://vencord.dev/plugins/StreamerModeOnStream

**Comment by fily-gif** [comment]
> https://vencord.dev/plugins/StreamerModeOnStream

Ah, should've checked the plugins list before commenting lol
