### ISSUE TITLE
Discord Away Status

### ISSUE THREAD

**Issue by ImMrJakob** [Vencord/plugin-requests#66]
### Plugin Description

ik this is a bad suggestion but i think it would be cool if we had the og moon away status instead of the plain orange circle as our status

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by danielah05** [comment]
im on latest canary and its still a moon for me, do u maybe just have a theme on or something thats replacing it?

**Comment by EdVraz** [comment]
It's still a moon. If discord would change it, you can change it via css either way (or just disable the experiment for it if there is one), but there would be no need to make this a plugin.
