### ISSUE TITLE
Tupperbox message log clean up

### ISSUE THREAD

**Issue by HyperRaccoon13** [Vencord/plugin-requests#660]
### Plugin Description

Currently in a server that has the tupperbox bot, which is kinda hard to explain, but it deletes the users messages and sends it as some other character. see: [plural](<https://morethanone.info/>) and [tupperbox](<https://tupperbox.app/guide/basics>).

With the message logger plugin enabled, when the bot deleted and sends the message, you seee 2 of the same message, which quickly fills up the screen and is hard to read, see: 
![image](https://github.com/Vencord/plugin-requests/assets/68512889/d06c2ed1-0b8e-4560-8ff9-e9e686040c71)

is it possable for a plugin to be made to not include the message after its been deleted, if it was deleted by a bot of x ID

Feel free to contact me on discord: theoverlycaffeinatedtrashpanda

### Existing Plugin for other mod

MessageLogger

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by tuta-amb** [comment]
use the "COMMA-SEPARATED LIST OF USER IDS TO IGNORE" option, just put the bot id there, as bot users are still users

https://cdn.typescript.love/file/boo5uglas7brplh1rx.png

**Comment by Feathers8** [comment]
You may have misread his request. Or maybe I did (I don't think so though).

**Comment by fily-gif** [comment]
> use the "COMMA-SEPARATED LIST OF USER IDS TO IGNORE" option, just put the bot id there, as bot users are still users
> 
> https://cdn.typescript.love/file/boo5uglas7brplh1rx.png

User's message gets deleted, this field is for ignoring deleted messages __that were sent by the user__, so you would have to put the entire server in there which is
1. Husk
2. Makes it global for every single server

**Comment by Feathers8** [comment]
Actually, I just remembered there is a PR that could address this request https://github.com/Vendicated/Vencord/pull/2201

**Comment by Vendicated** [comment]
just use the plugin's ignore options. you can ignore specific users, channels or entire servers

**Comment by Vendicated** [comment]
also it's impossible to know who deleted the message without audit log access
