### ISSUE TITLE
DoubleClickToEdit Plugin

### ISSUE THREAD

**Issue by bearwilliam2** [Vencord/plugin-requests#664]
### Plugin Description

Double clicking on your message that you typed with automatically edit it you can also double click on another user's message to instantly reply to it

### Existing Plugin for other mod

https://betterdiscord.app/plugin/Double%20Click%20To%20Edit#google_vignette

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
ermmm... https://vencord.dev/plugins/MessageClickActions
