### ISSUE TITLE
Server Count

### ISSUE THREAD

**Issue by echoless3484** [Vencord/plugin-requests#665]
### Plugin Description

A counter above the server list that displays the amount of servers you're in.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/ServerCounter

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
Already a thing. The name of the plugin is "ServerListIndicators".
