### ISSUE TITLE
pls delete this issue i was just stupid featrue alreaddy exists vanilla

### ISSUE THREAD

**Issue by TheSmileModder** [Vencord/plugin-requests#67]
### Plugin Description

Lets you Fullscreen Screenshare's like in youtube.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by cheesesamwich** [comment]
mf that has existed since the dinosaurs went extinct

**Comment by TheSmileModder** [comment]
> mf that has existed since the dinosaurs went extinct

![Screenshot 2024-02-16 232035](https://github.com/Vencord/plugin-requests/assets/126444681/91c23500-45a7-49c8-8154-a830512d3f86)

this isnt fullscreen

**Comment by cheesesamwich** [comment]
it is if you press the fullscreen button 💀

**Comment by TheSmileModder** [comment]
> it is if you press the fullscreen button 💀

where tf is it

**Comment by danielah05** [comment]
click on the small arrow in the middle to get rid of the icons of the people in the vc, then its completely fullscreened

**Comment by TheSmileModder** [comment]
> click on the small arrow in the middle to get rid of the icons of the people in the vc, then its completely fullscreened

we dont talk about this

**Comment by TheSmileModder** [comment]
can i delete an issue and thanks
