### ISSUE TITLE
Video Mirroring Plugin

### ISSUE THREAD

**Issue by ShashvatMalik** [Vencord/plugin-requests#670]
### Plugin Description

So whenver you join a voice channel in discord and turn on your video it mirrors your video for others, is it possible to have a plugin where the video shown to others is same as shown to us by dc without mirroring

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
The video stream of yourself is the flipped one; this is done through CSS

If you want to revert it to what other people see, you can use ```css
video[class*="mirror"] {
    transform: none !important;
}
```

I don't know if it's possible to flip the camera stream for other people, if not you can use a virtual camera from OBS and set your real camera as a source in OBS
