### ISSUE TITLE
Server History/Statistics

### ISSUE THREAD

**Issue by JT02GitHub** [Vencord/plugin-requests#671]
### Plugin Description

**Server:**
When hovering over the server with your mouse, you may view the server owner, the date it was created, how many roles, channels, etc. You can also view what the server looked like over time. 

**Channels:**
When right clicking on a channel/category, you may view the history of the channel. When it was first created, changes of the name and what category it has been moved to, etc. You can also view the history of categories from all of the above.

**Roles:**
You can view what the role was before, when it was created, how many have had the role over time, etc. (You can also view the list of server roles and see how many people have the role). 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
> You can also view what the server looked like over time.
> changes of the name and what category it has been moved to, etc.
> You can view what the role was before [...] how many have had the role over time, etc.

impossible.

> (You can also view the list of server roles and see how many people have the role).

PermissionsViewer plugin

**Comment by JT02GitHub** [comment]
How would you through the permissions viewer plugin? Like view how many people have a role?

**Comment by rozbrajaczpoziomow** [comment]
right, that was suggested (because it's possible iirc) but wasn't added, sowwy

**Comment by JT02GitHub** [comment]
What do you mean by "role list"

**Comment by rozbrajaczpoziomow** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/58668179/2a1d13b1-cd42-45d4-9862-4cfae952edca)

**Comment by JT02GitHub** [comment]
Ohhhh ok thanks!

**Comment by JT02GitHub** [comment]
What happens if it just shows a role id? ex. <@&928393830393093930203>

**Comment by rozbrajaczpoziomow** [comment]
whar

**Comment by Vendicated** [comment]
https://vencord.dev/plugins/ServerProfile
https://vencord.dev/plugins/PermissionViewer

rest is impossible
