### ISSUE TITLE
GOOL

### ISSUE THREAD

**Issue by FantZarYT** [Vencord/plugin-requests#673]
### Plugin Description

When :ETC_GOOOOOL: is sent, a GOOOOOL sound will be played and so too when reacting to the message. 

### Existing Plugin for other mod

https://github.com/Vendicated/Vencord/tree/main/src/plugins/moyai

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
tbh this should be generalised as a soundtriggers plugin if it's added
