### ISSUE TITLE
Oneko cat SKINS

### ISSUE THREAD

**Issue by CantDrawist** [Vencord/plugin-requests#676]
### Plugin Description

Can there be more skins for the oneko cat that follows the cursor? I just thought of this the other day and would love it if we could customize the little buddy 🦆✨

### Existing Plugin for other mod

Oneko Cat Plugi - https://vencord.dev/plugins/oneko

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
Someone made a collection of Oneko stuff, and there is a folder with skins there - https://github.com/coolesding/onekocord
Also, this Css Snippet can be used to change the skin, just change the link to the one you want - https://canary.discord.com/channels/1015060230222131221/1028106818368589824/1238897574166003773
