### ISSUE TITLE
File size hint.

### ISSUE THREAD

**Issue by nikolaaafunn** [Vencord/plugin-requests#677]
### Plugin Description

Please add file size hint, just like in Telegram, if its not possible without API abuse, at least add this on downloading files.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
If you want to see the sizes of downloadable files, yeah that's stock discord?

**Comment by rozbrajaczpoziomow** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/58668179/fb1edc14-9912-406b-9209-10651b9cffb6)
