### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by TheServerit** [Vencord/plugin-requests#678]
### Plugin Description

A button for cancelling friend request would be lovely. Currently it is only on mobile. Like when you send a request, on mobile you'd be able to cancel it.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
You can cancel friend requests on mobile though

**Comment by nin0-dev** [comment]
> A button for cancelling friend request would be lovely. 
![image](https://github.com/Vencord/plugin-requests/assets/75569739/c5424750-ce84-4dc5-9dac-fa7f9168c0fd)

**Comment by Scyye** [comment]
> You can cancel friend requests on mobile though
> You > Your Friends > Friend Requests

> Currently it is only on mobile.

**Comment by rozbrajaczpoziomow** [comment]
> > You can cancel friend requests on mobile though
> > You > Your Friends > Friend Requests
> 
> > Currently it is only on mobile.

reading comprehension is hard, either way, as nin0 correctly screenshotted, you *can* cancel friend requests, so what the point Scyye?
![image](https://github.com/Vencord/plugin-requests/assets/58668179/280fac33-6d9c-42e1-be20-09c3b8571490)

**Comment by Scyye** [comment]
> reading comprehension is hard, either way, as nin0 correctly screenshotted, you can cancel friend requests on non-mobile, so what's the point Scyye?

well that aggression is a tad not-needed.
my point was simply that they *said* that its on mobile, and the response they got was "its on mobile"
I can see, and am aware that its possible on non-mobile, that wasnt my point.

**Comment by TheServerit** [comment]
Ok ty y'all (: I forgot it has to be in that friends menu instead of being in the 3 dots like it is on mobile.
