### ISSUE TITLE
Hide Channels

### ISSUE THREAD

**Issue by jirholi** [Vencord/plugin-requests#68]
### Plugin Description

Allow for channels to be hidden without hiding all muted channels. 

### Existing Plugin for other mod

https://betterdiscord.app/plugin/HideUtils

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by cheesesamwich** [comment]
that is a stock discord feature

**Comment by MrDiamondDog** [comment]
me when

![image](https://github.com/Vencord/plugin-requests/assets/84212701/5ed7dd43-097a-4c30-bd35-eac94829ea55)

**Comment by nvhhr** [comment]
Hit 'channels and roles' or 'browse channels' in your channellist and you can tick/untick channels that you want to see/hide.
On some servers this might not be available (when you have certain permissions I think), you can hide a channel with css if you really need to:
`.containerDefault__3187b[data-dnd-name="shiggy"] {display:none;}`

**Comment by jirholi** [comment]
thank you very much for the css snippet

**Comment by nvhhr** [comment]
Oh and if you need the snippet to be server specific (some other server has same channelname you don't want hidden), use this;
`.container__590e2[aria-label^="Vendor"] .containerDefault__3187b[data-dnd-name="shiggy"] {display:none;}`
