### ISSUE TITLE
Marquee Everywhere

### ISSUE THREAD

**Issue by moe-rs** [Vencord/plugin-requests#683]
### Plugin Description

Cause overflowing text (_text that does not fit the width of it's container_) to [marquee](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee) (_scroll LTR/RTL_) for:
- Channel names (including names of DMs)
- Member names
- User status

Each of the the above can be toggled from the plugin settings.

Bonus:
- RTL text scrolls right-to-left (default/fallback to left-to-right)

### Existing Plugin for other mod

https://github.com/terabyte25/plugins/tree/main/MarqueeEverywhere

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
css can do this
