### ISSUE TITLE
Disable Auth App Plugin

### ISSUE THREAD

**Issue by FarzadHZZ** [Vencord/plugin-requests#686]
### Plugin Description

i want to disable message like this anyone can create the plugin?
![Image](https://github.com/Vencord/plugin-requests/assets/44641593/d11de859-c092-4ddf-bb72-1177d23d27bc)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
what do you mean? if you click on authorize knowing it's malicious then that's on your fault

if you want to auto authorize that's a security risk and will never be added

**Comment by FarzadHZZ** [comment]
I want it to stop sending messages like this and automatically cancel any app that requires auth

**Comment by schoeneBiene** [comment]
That would cause a lot of confusion - oauth2 is used for more than just scams.

**Comment by FarzadHZZ** [comment]
@nin0-dev I just want a plugin that will stop showing this message

**Comment by MrDiamondDog** [comment]
This pop up should absolutely not be disabled. It tells you what the app you're about to add is allowed to do on your account. If this pop up is disabled, the likelihood of you allowing malicious apps onto your account increases drastically. Either way it's literally one button press to make this go away so it's not a big issue in the first place

**Comment by Vendicated** [comment]
what? this popup will only show if you click "Add bot" or click a bot invite link

just.. don't click any of that?
