### ISSUE TITLE
Fake Defean

### ISSUE THREAD

**Issue by Pkp107** [Vencord/plugin-requests#688]
### Plugin Description

Make it look like you are deafen to other people!

(Dont Include) JS: 

//META{"name":"ExampleLibraryPlugin", "authorId":"575933571186032641", "invite":"TQ2dePQ", "website":"https://github.com/ali0sam"}*//
//import {DiscordModules as Modules} from "modules";
class ExampleLibraryPlugin {
    
getName() {return "Fake Mute&Deafen";}
getDescription() {return "Join voice channel, mute and deafen yourself, start and stop plugin, now you can Un-mute and Listen and speak!";}
getVersion() {return "0.0.1";}
getAuthor() {return "ali_s";}
    

start() {
if (!global.ZeresPluginLibrary) return window.BdApi.alert("Library Missing",`The library plugin needed for ${this.getName()} is missing.<br /><br /> <a href="https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js" target="_blank">Click here to download the library!</a>`);
ZLibrary.PluginUpdater.checkForUpdate(this.getName(), this.getVersion(), "LINK_TO_RAW_CODE");
        
var text = new TextDecoder("utf-8");

WebSocket.prototype.original = WebSocket.prototype.send;
WebSocket.prototype.send = function(data) {
if (Object.prototype.toString.call(data) === "[object ArrayBuffer]") {
if (text.decode(data).includes("self_deaf")) {
console.log("found mute/deafen");
data = data.replace('"self_mute":false', 'NiceOneDiscord');
console.log("Activated");
}
}
WebSocket.prototype.original.apply(this, [data]);
}
window.BdApi.alert("success",`now you can stop plugin!, After you turned ON the plugin , you cant join any other voice channels , for this you have to Reload discord!`);

 

stop() {

}
}

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
![Screenshot_20240607-123416](https://github.com/Vencord/plugin-requests/assets/75569739/b610df38-344e-49cd-9b94-56f3d6992b40)

not to be rude but please try to read next time
