### ISSUE TITLE
YouTube Music Rich Presence 

### ISSUE THREAD

**Issue by DezBirdss** [Vencord/plugin-requests#689]
### Plugin Description

Use YouTube music oauth2 to display what music you are playing.

### Existing Plugin for other mod

Yes the Apple Music Rich Presence.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by ImLvna** [comment]
use the last.fm youtube scrobbler extension combined with last.fm rich presence

**Comment by ImLvna** [comment]
https://chromewebstore.google.com/detail/lastfm-scrobbler-for-yout/kjhnjfldmodoikafpfhfehngokaiegok

**Comment by Feathers8** [comment]
I thought about suggesting that Premid thing but I wasn't sure if that counts as off-topic.

**Comment by DezBirdss** [comment]
I don't use YouTube music on my PC I use it on my phone it would be nice if it just used YouTube musics oauth2

**Comment by nin0-dev** [comment]
> I don't use YouTube music on my PC I use it on my phone it would be nice if it just used YouTube musics oauth2

not possible.

**Comment by DezBirdss** [comment]
Does YouTube Music not have a oauth2?

**Comment by nin0-dev** [comment]
it doesn't, at least not to see what's playing

**Comment by Vendicated** [comment]
> I don't use YouTube music on my PC I use it on my phone it would be nice if it just used YouTube musics oauth2

Use https://play.google.com/store/apps/details?id=com.arn.scrobble to scrobble the Youtube Music app and then use the LastFMRichPresence plugin
