### ISSUE TITLE
be able to add extensions on kruker game when playing it in vc

### ISSUE THREAD

**Issue by the-hidden-desert** [Vencord/plugin-requests#691]
### Plugin Description

be able to add extensions on kruker game when playing it in vc

like tampermonkey or any others we can use 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
you can already achieve this by making a custom plugin for it, much similar to the WatchTogetherAdblock plugin
