### ISSUE TITLE
[Req] Better NSFW Tag

### ISSUE THREAD

**Issue by Setnour6** [Vencord/plugin-requests#693]
### Plugin Description

BetterNsfwTag places a label or tag next to channels that are marked as NSFW. This is useful for people who do not easily notice the warning/caution icon just on the channel hashtag when a channel does not directly mention any NSFW content or when the users forget that a particular channel does have NSFW (the verification happens only once, last I remember).
![image](https://github.com/Vencord/plugin-requests/assets/70764728/97b44886-798e-4114-9f98-9acea8cf649a)
_The warning/caution channel icon above_.

This is also a thing on BetterDiscord.

### Existing Plugin for other mod

BetterDiscord: https://betterdiscord.app/plugin/BetterNsfwTag

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
possible with a css snippet, look in the css snippets channel of the [Vencord Server](https://discord.gg/vencord)

**Comment by KrstlSkll69** [comment]
Hello, i actually created two css snippets for exactly this -

NSFW channel tag/marker (also recolors the small triangle):
https://canary.discord.com/channels/1015060230222131221/1028106818368589824/1191265782315888640

Just recolors the triangle:
https://canary.discord.com/channels/1015060230222131221/1028106818368589824/1226666307630403665

**Comment by Setnour6** [comment]
Thank you for letting me know. Can any of you please post the CSS here?

**Comment by KrstlSkll69** [comment]
The css snippets can be seen by joining the discord server

**Comment by Setnour6** [comment]
> The css snippets can be seen by joining the discord server

It just makes it easier for people who don't have discord or don't plan to use it to get the answer without the need to even use discord in the first place. I'll assume that posting CSS here is not allowed according to the Vencord administration.

**Comment by Vendicated** [comment]
there's nothing against posting css here, but this is the plugin request repo so it should stay on topic (as in, talk about actual requests)

plus, you are asking for people to go look for the snippet for you and spoonfeed it to you. just go look for it yourself, we're not your servants 🤷🏻

**Comment by KrstlSkll69** [comment]
> > The css snippets can be seen by joining the discord server
> 
> 
> 
> It just makes it easier for people who don't have discord or don't plan to use it to get the answer without the need to even use discord in the first place. I'll assume that posting CSS here is not allowed according to the Vencord administration.
> 
> I'll try it out anyways

if you dont have discord then want are you doing on the github for a discord client mod
