### ISSUE TITLE
Request on a Plugin. "Mute Bypass"

### ISSUE THREAD

**Issue by dawdawdd32e23** [Vencord/plugin-requests#695]
### Plugin Description

Generated by AI. Not garaunted functinoal.

The plugins bypasses someones muted button. For an example. If they muted me i can just click on a button and then they can still here me even if they muted me. So i haved tried to do a code and make it functional and i dont even know if it is, But yeah let me know if you can help me do it. And ofc also tell me if you are not avaible to do it or not. Its should be a really fun plugin. I am not good at coding btw.  Sorry for my bad English.

```
// MuteBypass.ts
import { Vencord } from 'vencord';
import { Discord } from 'discord.js';
import { VoiceChannel } from 'discord.js';
import { Guild } from 'discord.js';

class MuteBypassPlugin {
  name: string = 'MuteBypass';
  description: string = 'Bypasses mutes for others';

  async onVoiceStateUpdate(user: Vencord.User, oldState: Vencord.VoiceState, newState: Vencord.VoiceState) {
    if (newState.mute && oldState.mute !== newState.mute) {
      // Check if the user who muted you is in the same voice channel as you
      const voiceChannel = await Vencord.getVoiceChannel(user.id);
      if (voiceChannel && voiceChannel.members.has(user.id)) {
        // Get the guild ID and the voice channel ID
        const guildId = voiceChannel.guild.id;
        const voiceChannelId = voiceChannel.id;

        // Unmute yourself in the voice channel
        await Vencord.unmute(user.id, voiceChannelId, guildId);
      }
    }
  }
}

Vencord.registerPlugin(new MuteBypassPlugin());
```

### Existing Plugin for other mod

No it does not already exist.

### Request Agreement

- [Prob] I read the above and made sure my plugin is possible and allowed
- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
do you really expect ai to generate functioning code? this entire code is broken and stupid lol

**Comment by KrystalSkullOfficial** [comment]
> do you really expect ai to generate functioning code? this entire code you sent is broken and stupid lol

Yes they did expect it(prolly will try to say that they wrote it themselves)

**Comment by nin0-dev** [comment]
oh and that wouldn't even be possible. mutes are handled clientside

**Comment by dawdawdd32e23** [comment]
> oh and that wouldn't even be possible. mutes are handled clientside

Ok

**Comment by dawdawdd32e23** [comment]
> do you really expect ai to generate functioning code? this entire code you sent is broken and stupid lol

Do it better self to make a mute bypass. Instead of searching for every freaking request and say your stupid.

**Comment by MrDiamondDog** [comment]
1. This is really creepy
2. It's not possible
3. AI can't generate vencord plugins

**Comment by dawdawdd32e23** [comment]
> 1. This is really creepy
> 2. It's not possible
> 3. AI can't generate vencord plugins

Creepy?

**Comment by dawdawdd32e23** [comment]
And btw. Its not _

> impossible

_. Its just really hard to make one beacuse of the server side i guess. If they now even have one.

**Comment by MrDiamondDog** [comment]
> Creepy?

Your original request states that you want a button that makes it so people who have muted you can hear you anyway. There is a reason people mute other people, and it shouldn't be bypassed. It's the other person's decision, not your own.

> btw. Its not impossible

yes, it is.

**Comment by dawdawdd32e23** [comment]
> > Creepy?
> 
> Your original request states that you want a button that makes it so people who have muted you can hear you anyway. There is a reason people mute other people, and it shouldn't be bypassed. It's the other person's decision, not your own.
> 
> > btw. Its not impossible
> 
> yes, it is. you cant change what happens on other people's clients or the server.

Then explain the fake deafen plugin.

**Comment by MrDiamondDog** [comment]
> Then explain the fake deafen plugin.

That's not the same thing as this. That plugin just says to the server "show me as deafened", but doesn't actually deafen yourself. What you requested still isn't possible.

**Comment by nin0-dev** [comment]
fakedeafen doesn't even work. its either malware or explodes your vc ability until reload

**Comment by dawdawdd32e23** [comment]
> > Then explain the fake deafen plugin.
> 
> That's not the same thing as this. That plugin just says to the server "show me as deafened", but doesn't actually deafen yourself. What you requested still isn't possible.

But it is possible. For example. This is how hard it could be 0.0009. You could say it like that.

**Comment by MrDiamondDog** [comment]
> But it is possible. For example. This is how hard it could be 0.0009. You could say it like that.

what???

you have no proof this is possible as it literally isnt

**Comment by nin0-dev** [comment]
mutes are handled clientside. aka no vencord plugin will be able to change what happens on someone else's **computer**.

a mute bypass plugin would be **impossible**.

**Comment by dawdawdd32e23** [comment]
> fakedeafen doesn't even work. its either malware or explodes your vc ability until reload

It works perfectly. Its really fun playing with.

**Comment by dawdawdd32e23** [comment]
> > But it is possible. For example. This is how hard it could be 0.0009. You could say it like that.
> 
> what???
> 
> you have no proof this is possible as it literally isnt

Oh man you have no "idea!"

**Comment by MrDiamondDog** [comment]
> > fakedeafen doesn't even work. its either malware or explodes your vc ability until reload
> 
> It works perfectly. Its really fun playing with.

it isn't "fun", its a complete invasion of other people's privacy. even if it did work, other people would see you deafened and would know that you couldn't hear them when you actually can.

**Comment by KrystalSkullOfficial** [comment]
@Vendicated can we please close and lock this

**Comment by dawdawdd32e23** [comment]
> > > fakedeafen doesn't even work. its either malware or explodes your vc ability until reload
> > 
> > 
> > It works perfectly. Its really fun playing with.
> 
> it isn't "fun", its a complete invasion of other people's privacy. even if it did work, other people would see you deafened and would know that you couldn't hear them when you actually can.

It is















💀


Fun

**Comment by dawdawdd32e23** [comment]
ITS still possible. I wondering get someone one time hacked nasa base just to look into some documents without harm. If you even knowed this already.💀

**Comment by Sqaaakoi** [comment]
> ITS still possible. I wondering get someone one time hacked nasa base just to look into some documents without harm. If you even knowed this already.💀

![image](https://github.com/Vencord/plugin-requests/assets/37475903/b9cdc2ce-b16b-4d80-861c-3fe7bd7cb37a)

also like everyone said, this just isnt possible. these mutes are handled on other people's clients. also stop being a silly kid about fakedeafen and accept it's weird

**Comment by MrDiamondDog** [comment]
Since you KNOW it's possible, why don't you tell us how to do it and why it's possible?

**Comment by dawdawdd32e23** [comment]
> > ITS still possible. I wondering get someone one time hacked nasa base just to look into some documents without harm. If you even knowed this already.💀
> 
> ![image](https://private-user-images.githubusercontent.com/37475903/337937916-b9cdc2ce-b16b-4d80-861c-3fe7bd7cb37a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4OTE4NTQsIm5iZiI6MTcxNzg5MTU1NCwicGF0aCI6Ii8zNzQ3NTkwMy8zMzc5Mzc5MTYtYjljZGMyY2UtYjE2Yi00ZDgwLTg2MWMtM2ZlN2JkN2NiMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDAwMDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YzJkY2Q0NWRlODcyMjdiOTMyZTc1NGJiYWIxN2VhYzA5Y2YyYTQ0YzhjMTcwNWU5Yzg3OTdjYjk5MTEwYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PV16C5uSobR2eAmAEt7hbT-irK2dm5e2LBp-7tF1rHY)
> 
> also like everyone said, this just isnt possible. these mutes are handled on other people's clients. also stop being a silly kid about fakedeafen and accept it's weird

You heard me skid. Not shut your mouth. 🤐👌
