### ISSUE TITLE
Improved file sending (file splitter)

### ISSUE THREAD

**Issue by melvazmelvazeoll19** [Vencord/plugin-requests#698]
### Plugin Description

WinRAR and other file archivers can split 1 file into files of a certain size, you can create a plugin that will split the file, if it is larger than 25 MB, into several files of 25 MB each.
![image](https://github.com/Vencord/plugin-requests/assets/169545100/fdf440d0-9537-4543-8723-bbd811196ced)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by cheesesamwich** [comment]
This is an interesting idea but theres a lot of edge cases, the file limit at one time is 10 (iirc) so you wouldn't achieve a higher file size limit with this plugin method over just uploading it to a file host like catbox (less than half the file size actually)

**Comment by schoeneBiene** [comment]
#408
