### ISSUE TITLE
XSOverlay

### ISSUE THREAD

**Issue by Smol-Hanako** [Vencord/plugin-requests#699]
### Plugin Description

There is already a Better Discord version but because Vencord is x Times better I wanted to ask if its possible to port the plugin

### Existing Plugin for other mod

https://github.com/Eidenz/XSOverlay-BetterDiscord

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
... ? https://vencord.dev/plugins/XSOverlay
