### ISSUE TITLE
ShowAllChannels

### ISSUE THREAD

**Issue by JustLeader69420** [Vencord/plugin-requests#70]
### Plugin Description

Show all channels because the "Channels & Roles" stuff is annoying to turn on all the categories, or even still does not show all channels.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
Cant you just

![image](https://github.com/Vencord/plugin-requests/assets/47912135/550919bb-2865-4973-87a7-aac63b66dec9)

**Comment by JustLeader69420** [comment]
> Cant you just
> 
> ![image](https://private-user-images.githubusercontent.com/47912135/305649418-550919bb-2865-4973-87a7-aac63b66dec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxODAyNDMsIm5iZiI6MTcwODE3OTk0MywicGF0aCI6Ii80NzkxMjEzNS8zMDU2NDk0MTgtNTUwOTE5YmItMjg2NS00OTczLTg3YTctYWFjNjNiNjZkZWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE0MjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ODIxM2MwN2FjMzQ3Mzk0YzA1NmU0ZDI2ZTdhNzY2ZTQxYzRlN2JhMWI0MjZlMzdiM2EzOTBhZjYyOTFlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hBssMq6pySs8YJwX26eON9xbjWpyjfpOl_hdSUTeSfs)

Oh yeah, that is a thing, however, I would still have to click through a hundred servers to turn this on, still not ideal.

**Comment by danielah05** [comment]
i mean even if its not ideal, its still a built in discord feature so a plugin for it doesnt need to be made (plus genuinely, manually doing it on every server right now is much faster than waiting for someone to make a plugin for it to automate it)
