### ISSUE TITLE
Hide Webhook Messages

### ISSUE THREAD

**Issue by lilygruman** [Vencord/plugin-requests#700]
### Plugin Description

Based on the existence of [MoreUserTags](https://vencord.dev/plugins/MoreUserTags) and its ability to identify webhooks, as well as multiple plugins' abilities to [show](https://vencord.dev/plugins/MessageLogger) and [hide](https://vencord.dev/plugins/NoBlockedMessages) messages, I am betting that it's possible to make a plugin that can hide messages posted by webhooks. It would be even better if it could block specific webhooks, like those generated by PluralKit or even specific users of it, which are [infamously unblockable](https://pluralkit.me/faq/#is-it-possible-to-block-proxied-messages-like-blocking-a-user).

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
you can use that to hide all messages from a specific username

```css
li[data-author-username="USERNAME"] {
  display: none;
}
```

**Comment by Vendicated** [comment]
MoreUserTags adds data attributes to messages `data-tag="webhook"` so you can do this with css
