### ISSUE TITLE
QuickJS

### ISSUE THREAD

**Issue by Dodge100** [Vencord/plugin-requests#702]
### Plugin Description

Similar to the native Vencord QuickCSS, a button would be added. Clicking on this button would open a window (with linting) that would allow you to paste in js and ts. perhaps functionality for tsx as well

### Existing Plugin for other mod

n/a

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Inbestigator** [comment]
Scary

**Comment by programminglaboratorys** [comment]
Have you thought of the idiot children in discord before requesting this?

**Comment by Luna-devv** [comment]
if it was implemented, it should be behind some quiz which judges how stupid a user is

**Comment by Luna-devv** [comment]
> > if it was implemented, it should be behind some quiz which judges how stupid a user is
> 
> Vencord QuickJS answers 2024 [UPDATED]

Add a kernel level anti cheat to the system which makes screenshot every few seconds and use AI to analyze it

**Comment by rozbrajaczpoziomow** [comment]
Windows Recall?

**Comment by Luna-devv** [comment]
Vencord Recall

**Comment by Dodge100** [comment]
I mean you can already paste it in the console but this has the advantages of being persistent even on client reload. I think that to solve the problem of
> the idiot children in discord
we could make the feature hidden so you would have to do something weird but not inconvenient to access it.

**Comment by henmalib** [comment]
>I mean you can already paste it in the console but this has the advantages of being persistent even on client reload.

So basically it's the same as writing code in plugins start function with less possibilities

**Comment by programminglaboratorys** [comment]
> I mean you can already paste it in the console but this has the advantages of being persistent even on client reload. I think that to solve the problem of
> 
> > the idiot children in discord
> 
> we could make the feature hidden so you would have to do something weird but not inconvenient to access it.

convincing enough for me, judging how its easy to access the existing devtools, I am interested in vee opinion

**Comment by Dodge100** [comment]
> > I mean you can already paste it in the console but this has the advantages of being persistent even on client reload.
> 
> So basically it's the same as writing code in plugins start function with less possibilities

It's also faster since you don't need to constantly open your IDE.

**Comment by TetraTheta** [comment]
I'm strongly against this idea.

Contrary to CSS that only can show or remove stuff clientside only, JS can do literarily _everything_.  
Stealing a user's token is a very basic thing that can be done with JS.

No matter what we do to prevent idiot users who just blindly paste JS into the console, people will eventually find out how to mitigate it or bypass it. Making it inconvenient to access the console is an intentional design for minimum safety.

IIRC, what makes the Vencord plugin safer is that Vencord members check plugin codes before providing them to people. You can't do that with random JS.

It is easy to think that those idiots will blame Vencord for their compromised or banned account because of their stupidity. There is so little gain for so many possible vulnerabilities and disadvantages.

I would suggest making your own plugin in your fork then use it. Or you can save those JS in somewhere that you can only see and paste it into the console when you need it.

**Comment by Luna-devv** [comment]
I personally just run Vencord from source, added my own plugins to the plugins folder, whenever I update Vencord I just stash my changes, pull, and recover them, build Vencord and restart Vesktop/Discord. This way works pretty fine. You can make a simple bash script to do that automatically

**Comment by henmalib** [comment]
> I personally just run Vencord from source, added my own plugins to the plugins folder, whenever I update Vencord I just stash my changes, pull, and recover them, build Vencord and restart Vesktop/Discord. This way works pretty fine. You can make a simple bash script to do that automatically

You can use the userplugins folder for such a thing, it's in .gitignore, so you don't have to stash changes every update

**Comment by Luna-devv** [comment]
@henmalib I’m aware I just can’t be bothered to fix that, not that it takes a long time eitherway, I modify some core plugins so I would have to stash changes eitherway

**Comment by lewisakura** [comment]
Snippets like these can break all the time, and also it would lead to some people being tricked into running certain code they don't really understand.
