### ISSUE TITLE
Copy user/server info

### ISSUE THREAD

**Issue by shxd10** [Vencord/plugin-requests#703]
### Plugin Description

This plugin allows you to quick copy all the users/servers information (like name, display name, id and many other for users and same thing for servers) all in one click. also thought of adding format options (like JSON format, env format etc..).
The option to copy will be right under the "copy user/server ID" button when you right click the user or the server.
I also dont know if its best practice to separate each in 2 different plugins. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
crazy this exists https://vencord.dev/plugins/ViewRaw
additional formats you can just do manually, not that many fields
