### ISSUE TITLE
Request for a Plugin - "Quick Logout Shortcut"

### ISSUE THREAD

**Issue by T3M1N4L** [Vencord/plugin-requests#704]
### Plugin Description

# How the plugin would work

A user clicks a set shortcut that can be setup in the plugin settings ex. `Ctrl +Q`  [I know this does quits discord if enabled in settings, but it would be nice if there was an option to quick-logout]

The user then clicks their preferred shortcut, which closes discord, preferably it also quits discord.

I'm quite a newbie when it comes to this side of Vencord, and if this is impossible, or if I broke the plugin request requirements/expectations, I'm sorry. 

Thanks for taking your time to read this request, and it would be nice if this is a plugin that is implemented in the future. :smi 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
> The user then clicks their preferred shortcut, which closes discord, preferably it also quits discord.

The alt f4 button in question:

**Comment by T3M1N4L** [comment]
How do you quickly logout with the alt+f4 button?

**Comment by nin0-dev** [comment]
it closes your client.

for the average user this is more than enough, a dedicated logout keybind is too niche.

if you want this you can use a browser in private browsing mode

**Comment by PoolloverNathan** [comment]
> How do you quickly logout with the alt+f4 button?

Would logging out with DevTools open work due to Discord hiding the token?

**Comment by T3M1N4L** [comment]
> Would logging out with DevTools open work due to Discord hiding the token?

_Originally posted by @PoolloverNathan in https://github.com/Vencord/plugin-requests/issues/704#issuecomment-2164235690_

Well what javascript script would you put in there?
