### ISSUE TITLE
Add some plugins from BetterDiscord to Vencord

### ISSUE THREAD

**Issue by PJ289** [Vencord/plugin-requests#707]
### Plugin Description

Hello. I wish you could add these plugins that BetterDiscord has to Vencord. Thank you.
https://betterdiscord.app/plugin/VoiceActivity
https://betterdiscord.app/plugin/StatusEverywhere
https://betterdiscord.app/plugin/FriendNotifications

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
follow the submission rules or you will be blocked from opening further submissions.
