### ISSUE TITLE
Server cloning

### ISSUE THREAD

**Issue by fbvfbfbfbfbfhgmnbw** [Vencord/plugin-requests#71]
### Plugin Description

a plugin that allows you to copy a server into a server template for personal use

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
use a bot.

**Comment by Sqaaakoi** [comment]
discord also already has server templates if you are admin just use those
there is no good reason to clone some specific community server if you aren't admin, it isnt your community and you should build from scratch or a template

**Comment by MrDiamondDog** [comment]
They ment cloning any server into a server template
