### ISSUE TITLE
Removing ... cutoff from about me

### ISSUE THREAD

**Issue by unknown-guy-bots** [Vencord/plugin-requests#715]
### Plugin Description

<img width="254" alt="Screenshot 2024-06-12 at 10 42 25 PM" src="https://github.com/Vencord/plugin-requests/assets/100909007/55f9bad7-eaa5-4ae9-9220-9834ee54ddf6">
<img width="301" alt="Screenshot 2024-06-12 at 10 35 30 PM" src="https://github.com/Vencord/plugin-requests/assets/100909007/37a5f774-72c6-4f25-aece-b811296ff6c6">
<img width="379" alt="Screenshot 2024-06-12 at 10 35 24 PM" src="https://github.com/Vencord/plugin-requests/assets/100909007/e167a1f7-93e3-4737-ba52-aaf22d0feaa5">

There should be a plugin to remove the cutoff from the about me section. If its more than 7-8 lines, it will still cutoff the text in the about me with a ... It is really annoying when trying to see users profiles.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by fily-gif** [comment]
I feel like there was a css snippet for that in their server
