### ISSUE TITLE
Favorite Media

### ISSUE THREAD

**Issue by Em-Z23** [Vencord/plugin-requests#716]
### Plugin Description

Have a quick way to save medias like: 
- Images
- Videos
- Audio
for an easy upload of silly images and videos or memes that we can instantly share with friends.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/FavoriteMedia

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
follow the submission rules or you will be blocked from opening further requests.
![](https://github.com/Vencord/plugin-requests/assets/45497981/4d0e3409-e97a-4c29-a8ab-7cb8eb9bbff2)
