### ISSUE TITLE
Typing Sounds

### ISSUE THREAD

**Issue by PuppyProgram** [Vencord/plugin-requests#718]
### Plugin Description

A simple plugin that plays simple, customizable tactile sounds as you type in discord.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/KeyboardClick

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
There was a PR for this but it was rejected: https://github.com/Vendicated/Vencord/pull/2206

**Comment by KrstlSkll69** [comment]
it exist the third party plugins channel, 
https://canary.discord.com/channels/1015060230222131221/1032200195582197831/1077574811473150012
