### ISSUE TITLE
Local User Edit

### ISSUE THREAD

**Issue by PuppyProgram** [Vencord/plugin-requests#719]
### Plugin Description

Locally edit user's profile images, nicknames, colors, etc.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/EditUsers

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
duplicate of #102

read the request rules next time.

**Comment by PuppyProgram** [comment]
I had read the rules and I hadn't found anything under the searches I had tried. No need to be rude,

**Comment by KrstlSkll69** [comment]
![Capture](https://github.com/Vencord/plugin-requests/assets/150982280/c01b4ea4-d63b-44f6-a6ca-3b98ff79256b)

**Comment by PuppyProgram** [comment]
I had looked for "edituser" assuming it would include the content of the issue, and the link. My bad.
