### ISSUE TITLE
Different Default Page on Startup

### ISSUE THREAD

**Issue by ayyEve** [Vencord/plugin-requests#720]
### Plugin Description

Add ability to not go to friends list by default. 
Option to go to the first dm channel, or go to the last channel in the last server you were in before Vencord was closed.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
> go to the last channel in the last server you were in before Vencord was closed.

For this part at least, there's this plugin https://vencord.dev/plugins/KeepCurrentChannel

**Comment by ayyEve** [comment]
omg thank you lmao, i missed that bc none of my searches included "loading". deleting this since it also works with the last dm channel. my apologies
