### ISSUE TITLE
Font Family Changer

### ISSUE THREAD

**Issue by JDNorman** [Vencord/plugin-requests#721]
### Plugin Description

# How would this work?
My reason for this is I want to be able to change font family for only specific messages, but I also wanna import mine own. I would imagine that users who do not have the plugin would view the text normally, but users who do have the plugin would also view the different font. Also, the font I want to use is unsupported in many applications so it would be awesome if fonts could be imported from ttf files straight into the plugin. If someone doesn't have that font they should be able to tell they don't have that font installed (maybe a hidden message only they can see or some sort of red text next to the message) that allows them to "steal" the font and install it on their client as well.

# Why am I asking this
The purpose for this is that many fan-based language font styles (Chakobsa for example - the language/writing system of the Fremen from Dune) are not supported normally, and if you want you can install the font directly to Windows Fonts folder, but Discord does not support changing fonts without plugins or retheming the UI, so it's impossible to have a font that displays globally to all users if you decide to change it somehow, it only affects your own local instance. 

# Benefits
A plugin like this could allow for many language-learning fandom servers (or just nerds in general) to be able to import the font styles and turn on the plugin (probably with a button next to the text input box at the bottom) so they would be able to use whatever keyboard they have to speak to one another using that font. To everyone who doesn't have the font installed (or the plugin) the words will appear to be normal characters, and to those who do have the plugin, they could steal the font and import it on their own side to use. (and ofc members should be able to select the font they want to use)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by programminglaboratorys** [comment]
very niche eh?

**Comment by JDNorman** [comment]
I mean, not really, I could also see it being used in markdown format for say, server announcements or even for gamers when they wanna use a specific font that isn't common. Also could just leave it on if you wanna make your messages stand out, I see a lot of use cases

**Comment by Vendicated** [comment]
you can change font with css

**Comment by JDNorman** [comment]
I was thinking like for specific messages, they would keep their font style even if you switch to another font style. One message you send could be one font style and a second message could be another style entirely, so you could switch between what you want, and it could be seen globally by other users which changing with css wouldn't do. But oh well
