### ISSUE TITLE
Fix UserVoiceShow in new ui profiles

### ISSUE THREAD

**Issue by eternalyoshino** [Vencord/plugin-requests#722]
### Plugin Description

Please fix the plugin for the new ui profiles, the plugin is very useful and it is sorely missed

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
from known-issues in vencord support

![image](https://github.com/Vencord/plugin-requests/assets/75569739/5f599a83-1257-4242-9f0d-e5db9576e827)
