### ISSUE TITLE
Automatic Friend Request Handling

### ISSUE THREAD

**Issue by Woolyenough** [Vencord/plugin-requests#727]
### Automatic handling of friend requests based on a set of preconfigured conditions
This plugin would be able to automatically handle friend requests based on a set of predefined conditions. This would allow for more customisation compared to Discord's current server privacy options.

For example, one condition could be to automatically ignore/deny friend requests from users who share a specific server with you. This feature would be particularly beneficial for staff members of large communities who'd prefer to keep their DMs open, but wish not to receive unsolicited friend requests.

Other conditions could potentially involve:
- sharing x amount of servers/friends with the user;
- sharing a specific mutual friend or server.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by programminglaboratorys** [comment]
this won't be possible without self botting

**Comment by Vendicated** [comment]
![Screenshot_2024-06-16-00-01-09-43_572064f74bd5f9fa804b05334aa4f912](https://github.com/Vencord/plugin-requests/assets/45497981/2417c3dc-fb83-4baf-8aff-ef45dcb65be0)
