### ISSUE TITLE
fakeserverboosts

### ISSUE THREAD

**Issue by wierd-discowd-vids** [Vencord/plugin-requests#729]
### Plugin Description

idk if this is meant for fakenitro or not, but i was wondering if you could make one for free boosts so i can boost my server :) thx if made.  pls email me if its in or not at noob12345761@hotmail.com

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
boosts are server side gated. get nitro

**Comment by wierd-discowd-vids** [comment]
> boosts are server side gated. get nitro

i have fakenitro plugin on, but i still cant boost my server, this plugin would be great

**Comment by ImLvna** [comment]
nuh uh

**Comment by wierd-discowd-vids** [comment]
y

**Comment by ImLvna** [comment]
as we have said, not possible

**Comment by wierd-discowd-vids** [comment]
any other way?

**Comment by ImLvna** [comment]
**no. not possible.**

**Comment by wierd-discowd-vids** [comment]
what makes it not possible

**Comment by ImLvna** [comment]
> boosts are server side gated.

**Comment by wierd-discowd-vids** [comment]
wdtm
What does that mean

**Comment by wierd-discowd-vids** [comment]
im not very good with code and stuff like that

**Comment by AushevAhmad** [comment]
> wdtm What does that mean

it means that plugin won't do anything since plugins work locally on whatever device you use.

**Comment by wierd-discowd-vids** [comment]
and servers arent local, their online

**Comment by wierd-discowd-vids** [comment]
now i get it
kk sry for the trouble

**Comment by AushevAhmad** [comment]
> and servers arent local, their online

yes, they are, quite shocking 😱

**Comment by Luna-devv** [comment]
what about selfhosting discord servers????

**Comment by wierd-discowd-vids** [comment]
???

**Comment by wierd-discowd-vids** [comment]
wdym
