### ISSUE TITLE
Add camera mirror (flip/reverse) toggle setting to client

### ISSUE THREAD

**Issue by devxan** [Vencord/plugin-requests#73]
### Plugin Description

Add a toggle located somewhere in Discord's settings that allows the user to disable the automatic mirroring of the camera on the client, or enable it if they want it. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
what?

**Comment by devxan** [comment]
Oops, forgot to mention what was mirroring. I edited my description.

**Comment by Vendicated** [comment]
use css

**Comment by Tottogrin** [comment]
> use css

how?
