### ISSUE TITLE
RoleIcons

### ISSUE THREAD

**Issue by Peps3000** [Vencord/plugin-requests#730]
### Plugin Description

Are you thinking about adding images to your roles without nitro? Well, thats what this plugin do!

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sadan4** [comment]
Not possible
