### ISSUE TITLE
PersonByPersonTheme

### ISSUE THREAD

**Issue by Boeing-F-15-EX-Eagle-II** [Vencord/plugin-requests#731]
### Plugin Description

More or less, a plugin designed to work with BD's themes that enable the custom user-per-user theme switching. Say, if I enter a private message with person A, the plugin recognizes the user and changes the theme to theme A. Change the PM to person B, now it changes to theme B. Outside of PMs, it goes to a default.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AushevAhmad** [comment]
Why do you even need that lol? Just get one cool theme or create one and use it, that plugin is useless

**Comment by Vendicated** [comment]
can be done with pure css
