### ISSUE TITLE
Anti Effect (No profile effect)

### ISSUE THREAD

**Issue by KaneSucks** [Vencord/plugin-requests#732]
### Plugin Description

A plugin that simply removes profile effects (the things attached in the image) so you cant see them on other peoples profiles, cuz they are annoying. 
![image_2024-06-16_232406394](https://github.com/Vencord/plugin-requests/assets/84256640/4a425c13-cb95-450a-87f7-ec4f1b0b945a)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AushevAhmad** [comment]
There's no need for a plugin, this can be done with css
```css
[class^="profileEffects"]
{
  display: none;
}
```
