### ISSUE TITLE
auto removing from friends list

### ISSUE THREAD

**Issue by uq6c** [Vencord/plugin-requests#737]
### Plugin Description

a plugin that will prompt you to add a time or date at which it will remove a user from your friends list after adding them, its useful for people that add a lot of random people to play with for a day or two and then dont play with them again. when you accept a friend request or when someone accepts yours it will make a pop up appear that lets you either not set a timer or set a time or day at which it will remove that person from your friends list

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by uq6c** [comment]
> that's a selfbot so against tos

:(

**Comment by Scyye** [comment]
just... set a reminder to remove them..
