### ISSUE TITLE
Clean up chat channel names 

### ISSUE THREAD

**Issue by HippiePlayerOne** [Vencord/plugin-requests#738]
### Plugin Description

A way to Improve chat names by automatically capitalising them, and removing dashes + underscores

![IMG_3297](https://github.com/Vencord/plugin-requests/assets/173175588/1173c933-4125-4f5b-812d-28e12dc8db4c)

### Existing Plugin for other mod

https://betterdiscord.app/plugin/BetterChatNames

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
this can be done with css, look in the css snippets channel of the vencord server

**Comment by HippiePlayerOne** [comment]
Thank you 🙏🏽
