### ISSUE TITLE
Message Logger Addition + Addition to PauseInvitesIndefinitely plugin

### ISSUE THREAD

**Issue by rithcodes** [Vencord/plugin-requests#740]
### Plugin Description

Addition to the Message Logger plugin I'd like to see is similar to how it works on BetterDiscord, it saves the deleted messages to a cache/file so even if you restart Discord the messages will still be there.

Addition to the PauseInvitesIndefinitely, I'd like to see Pause DMs Indefinitely added to this snice it'll be a great pause for DM advertisement instead of redoing it every 24 hours.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by jamesbt365** [comment]
For the half part, #385.

**Comment by Vendicated** [comment]
no. not possible. one request per issue.
