### ISSUE TITLE
Relative Timestamps 

### ISSUE THREAD

**Issue by Kendric223** [Vencord/plugin-requests#741]
### Plugin Description

Basically When you or someone sends a message, it Shows how long the message has been there Seconds, Minutes, Hours, Days, Months, Years, Such as this from betterdiscord - https://betterdiscord.app/plugin/RelativeTimestamps

### Existing Plugin for other mod

Dont think so

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
Probably counts as a duplicate. You can show your support by 👍 this one https://github.com/Vencord/plugin-requests/issues/1
