### ISSUE TITLE
5 account switch limit breaker

### ISSUE THREAD

**Issue by maggot2e1** [Vencord/plugin-requests#742]
### Plugin Description

A plugin that simply lets you have more then 5 accounts in the switch tab
for niche testing purposes for things like discord rollout or just to be funny and have a bunch of accounts

### Existing Plugin for other mod

na

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by HAHALOSAH** [comment]
https://github.com/Vendicated/Vencord/pull/2600
