### ISSUE TITLE
vencord plugin idea

### ISSUE THREAD

**Issue by cooldan1211** [Vencord/plugin-requests#743]
### Plugin Description

so i don't know if this is possible but can you guys (the amazing vencord crew) make it possible to look in channels you don't have access to I'm just very curious if it is thank you for reading this and i appreciate your time

### Existing Plugin for other mod

https://vencord.dev/plugins/ShowHiddenChannels and https://vencord.dev/plugins/ShowHiddenThings are very close to what i want

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
No, it's not.

**Comment by cooldan1211** [comment]
dang well thanks for telling me sir
