### ISSUE TITLE
Display friends messages from all mutual servers

### ISSUE THREAD

**Issue by jihading** [Vencord/plugin-requests#745]
### Plugin Description

Instead of searching each server you share with the user, there could be a menu on their profile where it gathers their messages from each server and displays them to you.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
This sounds like API spam/abuse
