### ISSUE TITLE
File viewer

### ISSUE THREAD

**Issue by ramadityo** [Vencord/plugin-requests#747]
### Plugin Description

A plugin that shows content preview inside of the file such as pdf, docx, xlsx or csv etc.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/FileViewer

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
> - [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

me when i don't read 

https://github.com/Vencord/plugin-requests/issues/3
