### ISSUE TITLE
Fake offline indicator

### ISSUE THREAD

**Issue by charslize** [Vencord/plugin-requests#748]
### Plugin Description

A plugin that allows the user to tell if somebody has set their status to 'offline' basically a fake offline detector. this can be shown with a little logo beside the users profile where the badges sit and when the user hovers over this logo, it has the text "this user has a fake offline status"

<img width="411" alt="Screenshot 2024-06-19 at 10 33 52 pm" src="https://github.com/Vencord/plugin-requests/assets/129347344/cc4f64cc-078a-4369-b205-d36eca8ea930">

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
not possible please read the request guidelines
