### ISSUE TITLE
Suggestion For Already Existing Plugin

### ISSUE THREAD

**Issue by kamsucks** [Vencord/plugin-requests#749]
### Plugin Description

For the oneko plugin, maybe there should be like a button that you can press and then the lil kitty runs to that button and sleeps on it. Kinda like a quick toggle on and off button for the plugin

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sadan4** [comment]
a version of oneko that i use on spotify has it where if you double click it it will go to the corner and sleep there, maybe it could be on double click instead of a button.
