### ISSUE TITLE
Emojify Text

### ISSUE THREAD

**Issue by Kanibal02** [Vencord/plugin-requests#756]
### Plugin Description

The plugin would work like this
You have a slash command '/emojify text' which would check for any text inside the text box, and would change it to the emoji text
for example, instead of
Hello World
it would be
:regional_indicator_h: :regional_indicator_e: (and this continues)

It would be a funny way of trolling friends, and I think it wouldn't be hard to code too.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
annoying, useless, and poor/no accessibility
#483

**Comment by nin0-dev** [comment]
also this can be done using textreplace with enough determination

**Comment by Kanibal02** [comment]
i already did a python gui for it
