### ISSUE TITLE
TypeReactions

### ISSUE THREAD

**Issue by UltbeeNOTFAKE** [Vencord/plugin-requests#759]
### Plugin Description

You know how people like to spell out words in reactions to messages? Like in announcements and stuff? It's usually a pain to do so, having to find each letter in the reactions and sometimes people put something inbetween your reactions. Well the idea for the plugin I had would make it so you can just type in what word you want to spell, and the plugin would automatically put every emoji immediately as a reaction.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
Api spam

**Comment by sadan4** [comment]
A similar form of this plug-in was also declined
