### ISSUE TITLE
Change Stream Quality (client-side)

### ISSUE THREAD

**Issue by AmirTheWeirdo** [Vencord/plugin-requests#76]
### Plugin Description

Not sure how much it's possible to implement this, but there have been many times where I'd join a stream and it's at a ridiculously high quality that I don't wanna watch, and it's too awkward to always ask the other person to lower it themselves
A plugin where you can change the other person's stream quality and frames for your own side, that's the whole request.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by fily-gif** [comment]
Fakenitro exists btw, afaik it already has that

**Comment by Sqaaakoi** [comment]
i don't think discord transcodes streams at their end (to keep latency low) so this probably isn't possible
