### ISSUE TITLE
Plugin Request

### ISSUE THREAD

**Issue by ZaxSky** [Vencord/plugin-requests#764]
### Plugin Description

Custom Notifications Sound!

I mean there is a plugin on BetterDiscord, why not on Vencord too

### Existing Plugin for other mod

https://github.com/mwittrien/BetterDiscordAddons/tree/56f17c06ea1338af7d69ba70e6bcdf809a2a7acb/Plugins/NotificationSounds

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
#21
