### ISSUE TITLE
Family Tree 

### ISSUE THREAD

**Issue by HollyDaCoder** [Vencord/plugin-requests#765]
### Plugin Description

A plugin that lets multiple users make a **"family tree"** using a relationship feature, you can use a command to **propose, adopt, abandon, divorce, leave a family and customise the tree** (like in design terms, almost like how _**Marriage Bot**_ does the marriage system but _cross-server and fancier_ and no needing to pay **MONEY** just to be _polyamorous!!!!_)

also a little icon/badge beside **related users**, a different icon for **friends/best friends** that aren't related and a blank icon for **strangers"**    

**![image_2024-06-22_023626639](https://github.com/Vencord/plugin-requests/assets/173518386/8e15a883-c1c0-4a81-aa32-933a5419b705)**

### Existing Plugin for other mod

nope!

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by PoolloverNathan** [comment]
what the fuck

**Comment by HollyDaCoder** [comment]
> what the fuck

fuck you too >:/

**Comment by PoolloverNathan** [comment]
> > what the fuck
> fuck you too >:/
please don't…
Sent from Proton Mail Android
-------- Original Message -------- 
On 6/21/24 9:47 PM, Holly wrote: 
what the fuck
fuck you too >:/

**Comment by Feathers8** [comment]
Dat Proton Mail plug though.

**Comment by Vendicated** [comment]
better done by a discord bot
