### ISSUE TITLE
Force Embedding MP4's as GIFs from the client.

### ISSUE THREAD

**Issue by gelcord** [Vencord/plugin-requests#767]
### Plugin Description

Discord embeds imgur mp4s as gifs. Could you do this locally such as upload a mp4 and embed it as a gif. Does anyone know the intricacies of Discord to know if this could be done?
<https://imgur.com/a/n3ABvMi> turns to <https://images-ext-1.discordapp.net/external/IXOAsKvz8jdRD_QYT7vE2A-I76frB5eahbh0QylpCt4/https/i.imgur.com/vXNHMCa.mp4>
![image](https://github.com/Vencord/plugin-requests/assets/173118026/375140c0-0475-4007-984f-b75c9e0377d4)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
ofc it can be done, but why? it won't work for others

**Comment by gelcord** [comment]
Whoops sorry, I didn't explain it well tbh. I'm not sure if such plugins still exist, but I remember a quote plugin for BD that used to post embeds, but I was thinking there'd be some sort of way to post a special kind of message with whatever embed parameters it needs to classify a file as a gif. I think whatever I'm suggesting may be entirely server side on Discord's end.

**Comment by Vendicated** [comment]
it's not possible to do that. only locally

**Comment by gelcord** [comment]
Thank you for letting me know! Sorry for wasting your time
