### ISSUE TITLE
Fake SoundBoard

### ISSUE THREAD

**Issue by lucasdaweb95** [Vencord/plugin-requests#768]
### Plugin Description

You can preview any soundboard sound even without nitro, so my idea is to grab the link for that sound from the preview request and play it into the vc (if thats impossible use [VB-CABLE](https://vb-audio.com/Cable/))

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
use an external soundboard

**Comment by lucasdaweb95** [comment]
> use an external soundboard

can there at least be a download feature to download the sounds?

**Comment by RobinRMC** [comment]
https://codeberg.org/Lunaa/userPlugins/src/branch/main/soundboard.web.ts
