### ISSUE TITLE
Split Long Messages

### ISSUE THREAD

**Issue by Ermageeerd** [Vencord/plugin-requests#77]
### Plugin Description

At the 2k character limit or higher, send 2k text chunks of the message instead of not allowing you to send it at all.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/SplitLargeMessages

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
This would technically be API spam/selfbotting and thus is not allowed

**Comment by Ermageeerd** [comment]
> This would technically be API spam/selfbotting and thus is not allowed

Oh, Ok! I understand and will close this.

**Comment by e1ectricdog** [comment]
Please!!

**Comment by Ermageeerd** [comment]
> Please!!

No, this will never get added, use BD if you want this :P
