### ISSUE TITLE
Being rich

### ISSUE THREAD

**Issue by SpentTrike** [Vencord/plugin-requests#771]
### Plugin Description

Being rich game activity where it says being rich and shows money

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Luna-devv** [comment]
Can you.. please.. take an IQ test and send the outcome here.. I beg you..

**Comment by SpentTrike** [comment]
Same for rich thing my IQ is over 9 billion

**Comment by Feathers8** [comment]
Can't you already do that with that CustomRPC plugin? I'm not sure.

**Comment by Luna-devv** [comment]
1.  I checked every box, despite not reading any
2. There is a custom RPC plugin already.
3. This plugin is stupid/too niche.
You have successfully failed all requirements in order to make a plugin request.

**Comment by SpentTrike** [comment]
Awwwww

**Comment by SpentTrike** [comment]
But I'm smart like that

**Comment by AushevAhmad** [comment]
If you are, then close this issue and get off of Github.
