### ISSUE TITLE
See how many times an attachment you've posted on Discord has been download/maybe also be able to see what users have downloaded your attachment?

### ISSUE THREAD

**Issue by DomaYahaha** [Vencord/plugin-requests#775]
### Plugin Description

I'm not 100% if it's something that can be done, but it'd be cool if you could get a small number on your attachment, or in some little pop up when hovering over the attachment, of how many people have downloaded it (maybe even if they've been linked shared too?). Something to add to that, it could be cool of there was another screen that you could open when going over the message options of the attachment to see the Discord users who did download the attachment. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
not possible afaik

**Comment by DomaYahaha** [comment]
Worst day of my life

**Comment by Scyye** [comment]
you must have a pretty damn good life then

> Worst day of my life

**Comment by DomaYahaha** [comment]
When bad things happen to me, it's instantly the worst day of my life :(
