### ISSUE TITLE
permission helper

### ISSUE THREAD

**Issue by szumi6760** [Vencord/plugin-requests#776]
### Plugin Description

so basically the plugin would add a button on top of all permissions, which would check or uncheck all the boxes

### Existing Plugin for other mod

-

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
Checking all is just the Administrator permission, and unchecking all is the default?

**Comment by Vendicated** [comment]
uncheck already exists! uncheck doesn't seem useful considering you can just check admin

![image](https://github.com/Vencord/plugin-requests/assets/45497981/a211bd8e-e844-4968-a509-6158d294f812)
