### ISSUE TITLE
Parroting / CopyCat plugin

### ISSUE THREAD

**Issue by Cherif107** [Vencord/plugin-requests#778]
### Plugin Description

so basically this plugin instantly repeats the exact same message that a specific person (and that person cannot be you to avoid constant spamming) has sent,
so its basically a button that's gonna be somewhere in the window or in the message bar thing, when you click it it sends you to an option list which has a "User ID" parameter, a begin button and a stop button.

for example:
person A: i want a cookie
person B: i want a cookie
person B copied person A and person B's message is sent instantly after person A's message

i have made a js script that i could paste into console to do the same (which im gonna send here) but i wanted a plugin for it so i wanted to try and ask for it here!

i would be more than happy if my plugin suggestion was accepted :D
[the copycat aka message mirroring script](https://github.com/user-attachments/files/15946455/mirroring.txt)

### Existing Plugin for other mod

most likely not

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
that's a selfbot, which is against TOS

**Comment by Cherif107** [comment]
> that's a selfbot, which is against TOS
> 
> likely won't be added to the main mod

omg i didnt know that, should i close this issue?
