### ISSUE TITLE
Screenshare with audio on Linux client

### ISSUE THREAD

**Issue by jadedcaffeinated** [Vencord/plugin-requests#78]
### Plugin Description

Allow for streaming with audio on Linux client as discord does not normally support it (for some reason)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by jedenastka** [comment]
[Vesktop](https://github.com/Vencord/Vesktop) supports this. I imagine it would be a pain to do it as a plugin for the regular client, as it'd require changing quite some native code.

**Comment by jadedcaffeinated** [comment]
> [Vesktop](https://github.com/Vencord/Vesktop) supports this. I imagine it would be a pain to do it as a plugin for the regular client, as it'd require changing quite some native code.

will check this out thanks

**Comment by lewisakura** [comment]
use vesktop
