### ISSUE TITLE
Better Friends List Plugin (BetterFriendsList)

### ISSUE THREAD

**Issue by Cattrag** [Vencord/plugin-requests#780]
### Plugin Description

It allows you to search through your friends list, favorite friends, search by status, etc.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/BetterFriendList

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
>     * [ ]  I checked every box, despite not reading any
> 
>     * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

Ermm... i think you lied or didnt actually read
https://github.com/Vencord/plugin-requests/issues/238

**Comment by Cattrag** [comment]
no, i searched "betterfriendslist" and "better friends list" and nothing came up
![plugin](https://github.com/Vencord/plugin-requests/assets/173649548/02e0e840-b031-4785-894a-e6e615a11d31)

i see it listed under "betterfriendlist", though, which is the actual name of the plugin. that's my bad
