### ISSUE TITLE
hide nsfw servers link

### ISSUE THREAD

**Issue by Restrated** [Vencord/plugin-requests#781]
### Plugin Description

you know how people send those nsfw server links or those 50$ steam links? make a plugin to hide them. would be very nice for me or atleast blacklist them from message logger

### Existing Plugin for other mod

nah

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [ ] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AushevAhmad** [comment]
![IMG_1629](https://github.com/Vencord/plugin-requests/assets/113457231/d4076926-8b21-45a2-8297-26561f4238d9)
+ There's no need in plugin, just block people who are sending this shit

**Comment by Feathers8** [comment]
I think it would be possible to at least filter those $50 steam link messages using the BlockKeywords plugin, but I'm not sure.
