### ISSUE TITLE
FNaF phone ringtone

### ISSUE THREAD

**Issue by catluizfilipi** [Vencord/plugin-requests#783]
### Plugin Description

A plugin that replaces the default discord call sound for the FNaF 1 phone guy call sound

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Luna-devv** [comment]
Please read again and edit or close your issue.

**Comment by Scyye** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/97131358/a23a35f7-ece9-4667-a647-383cd1663ed3)
nice x3

**Comment by nvhhr** [comment]
Falls under #21
