### ISSUE TITLE
Hi!!!

### ISSUE THREAD

**Issue by nothillyheights** [Vencord/plugin-requests#785]
### Plugin Description

Hi!!!

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nothillyheights** [comment]
why did you guys ban me!?!?!

**Comment by nothillyheights** [comment]
lowkey NOT tuff

**Comment by nothillyheights** [comment]
+ there was no point.....

**Comment by AushevAhmad** [comment]
Get off of Github HERE. AND. NOW!!!!

**Comment by nothillyheights** [comment]
why!!!

**Comment by nothillyheights** [comment]
i love you guys though!!!!
