### ISSUE TITLE
Quick disable all feature

### ISSUE THREAD

**Issue by AlexDiego123** [Vencord/plugin-requests#786]
### Plugin Description

A new feature to quickly disable everything like themes and plugins to make it look like you don't have Vencord for when you have to send screenshots in public servers where you can get banned or reported and then re-enable the themes and plugins that were enabled previously. It would be cool to have this feature inside the VencordToolbox plugin so you can quickly disable everything from the toolbox icon.

### Existing Plugin for other mod

Didn't find any

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
Seems like someone else suggested it before, but it got rejected.
https://github.com/Vencord/plugin-requests/issues/221

**Comment by AlexDiego123** [comment]
> Seems like someone else suggested it before, but it got rejected. #221

I think it would be really useful..
