### ISSUE TITLE
OLD PROFILE

### ISSUE THREAD

**Issue by SlookiaCP0** [Vencord/plugin-requests#787]
### Plugin Description

i want old profile not like this because it's ugly
![Capture d'écran 2024-06-24 215809](https://github.com/Vencord/plugin-requests/assets/83918529/e36fe14e-51b8-49db-b56f-94cc2217a3e5)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Luna-devv** [comment]
Use the experiments plugin to set the experiment “simplified profiles” to “not eligible”

**Comment by KrstlSkll69** [comment]
Can be done with Experiments, set both of these to "Not Eligible"
![Capture](https://github.com/Vencord/plugin-requests/assets/150982280/c5a54072-fb70-4a8a-a1f2-5a55f7301ac1)

**Comment by SlookiaCP0** [comment]
ty

**Comment by DozerUnknown** [comment]
> Can be done with Experiments, set both of these to "Not Eligible" ![Capture](https://private-user-images.githubusercontent.com/150982280/342477984-c5a54072-fb70-4a8a-a1f2-5a55f7301ac1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MjQ1NTIsIm5iZiI6MTcxOTQyNDI1MiwicGF0aCI6Ii8xNTA5ODIyODAvMzQyNDc3OTg0LWM1YTU0MDcyLWZiNzAtNGE4YS1hMWYyLTVhNTVmNzMwMWFjMS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxNzUwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGQ4YzhiMjhmNGY1OGU0ODQwYTc3NWExYjZlYWEyZWVmOWJjZDdiM2M0ZDlhMTU2ZGQwZTkyNDg1NzM3ODdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nJ1_rh8Zc_vkqHqcfCzT8asm6s0PU5Vhdbrz0Whdbro)

this was removed.

**Comment by KrstlSkll69** [comment]
> > Can be done with Experiments, set both of these to "Not Eligible" ![Capture](https://private-user-images.githubusercontent.com/150982280/342477984-c5a54072-fb70-4a8a-a1f2-5a55f7301ac1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MjQ1NTIsIm5iZiI6MTcxOTQyNDI1MiwicGF0aCI6Ii8xNTA5ODIyODAvMzQyNDc3OTg0LWM1YTU0MDcyLWZiNzAtNGE4YS1hMWYyLTVhNTVmNzMwMWFjMS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxNzUwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGQ4YzhiMjhmNGY1OGU0ODQwYTc3NWExYjZlYWEyZWVmOWJjZDdiM2M0ZDlhMTU2ZGQwZTkyNDg1NzM3ODdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nJ1_rh8Zc_vkqHqcfCzT8asm6s0PU5Vhdbrz0Whdbro)
> 
> this was removed.

Everything to-do with the old profiles was removed by discord and doesnt work anymore
now can someone please lock this
