### ISSUE TITLE
larger profile pictures next to peoples messages

### ISSUE THREAD

**Issue by IncompetentMoron** [Vencord/plugin-requests#790]
### Plugin Description

it bothers me that whenever i see peoples messages i can never really see their profile pictures cause theyre too small, ive searched thoroughly but cant find any option for something that specifically resizes the profile picture icon, nor have i found anyone else requesting such a thing.

so it would be a small but cool gimmick to have a plugin that makes peoples profile pictures larger so we can see everyones profile picture in their full beautiful glory

i even made a mockup on how it could look like!

![instead of this](https://github.com/Vencord/plugin-requests/assets/111074029/4106b9d1-4a1a-4b5d-a84f-386b9da68be4)
so instead of this small pfp, you could resize the icon to be bigger instead
![this](https://github.com/Vencord/plugin-requests/assets/111074029/2447d794-bf2f-4e08-881b-7ccd4b7c2100)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by AushevAhmad** [comment]
Probably can be done with CSS, also, try looking in Accessibility settings, maybe there is something..

**Comment by IncompetentMoron** [comment]
> Probably can be done with CSS, also, try looking in Accessibility settings, maybe there is something..

found nothing, theres this zoom option but it makes everything bigger

**Comment by IncompetentMoron** [comment]
i would try to do it myself but i have absolutely no knowledge about programming

**Comment by Vendicated** [comment]
css + ThemeAttributes can do this https://vencord.dev/plugins/ThemeAttributes#Avatars
