### ISSUE TITLE
Jump To Ping

### ISSUE THREAD

**Issue by OfficalCloud-Codes** [Vencord/plugin-requests#791]
### Plugin Description

Jump To Ping. Right-click on a channel with a ping, if there is only one ping jump to it, if there are multiple pings open a mini menu to select which ping to jump to OR make it so you can see all pings in a server in 1 menu.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
already exists
![image](https://github.com/Vencord/plugin-requests/assets/97131358/dd8eb73b-8439-49d5-94e1-41eea2c74bb3)

**Comment by OfficalCloud-Codes** [comment]
> already exists ![image](https://private-user-images.githubusercontent.com/97131358/342756478-dd8eb73b-8439-49d5-94e1-41eea2c74bb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNjE0OTIsIm5iZiI6MTcxOTM2MTE5MiwicGF0aCI6Ii85NzEzMTM1OC8zNDI3NTY0NzgtZGQ4ZWI3M2ItODQzOS00OWQ1LTk0ZTEtNDFlZWEyYzc0YmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDAwMTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZjFkMmU5ZDU5MWVjNDljN2VlODg4ODczYjhmZGUwMDAwYjA0NjY0OTliN2E4OWMyZTMyMDZiNzk4ZjhlNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-HR0sQ7U4XtRJPrSTo0dRcdYLR3CD6S2Q5XdyWGDQh8)

What plugin is it though

**Comment by OfficalCloud-Codes** [comment]
@Scyye If it exists, what plugin is it?

**Comment by Feathers8** [comment]
It's not a plugin, it's a feature Discord itself has. It's the inbox button at the top right.
