### ISSUE TITLE
vencord module that allows me to see the original link cuz of the steam scam

### ISSUE THREAD

**Issue by Agent-Turtle** [Vencord/plugin-requests#793]
### Plugin Description

This would show the actual link instead of the masked link scammers are using 

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
can be done with css + there's a giant popup when you click the link maybe read where it takes you

**Comment by AushevAhmad** [comment]
![IMG_1656](https://github.com/Vencord/plugin-requests/assets/113457231/aaf2b14c-2c98-4a2b-9c53-bbe959923fc4)
Nice... Also, you can just... not click on those links and report them to Discord.
