### ISSUE TITLE
Server Banner?

### ISSUE THREAD

**Issue by bandgz** [Vencord/plugin-requests#799]
### Plugin Description

the ability to add and change server banners, to venchord users without the need to boost the server? is that even possible? :) just purely for smaller channels of people who like the aesthetic of them!

### Request Agreement

- [x] I checked every box, despite not reading any
- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
Not possible, banners are server-sided which means we cannot change that. You can change it locally to be only for you but that's it.

**Comment by rozbrajaczpoziomow** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/58668179/05c6d95a-0f7d-485b-bd7c-dc1008f52f14)

**Comment by Scyye** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/97131358/c707d186-4eb5-4535-8c51-e129f3bc57aa)
nice


> Not possible

it.. most certainly is...

**Comment by rozbrajaczpoziomow** [comment]
(but does anyone actually care enough for this to implement it)

**Comment by bandgz** [comment]
> ![image](https://private-user-images.githubusercontent.com/58668179/343302128-05c6d95a-0f7d-485b-bd7c-dc1008f52f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTA5NDgsIm5iZiI6MTcxOTQ1MDY0OCwicGF0aCI6Ii81ODY2ODE3OS8zNDMzMDIxMjgtMDVjNmQ5NWEtMGY3ZC00ODViLWJkN2MtZGMxMDA4ZjUyZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAxMTA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZWU2MGQwZWNjMjM4MTVhMjJkN2NkMmMzNmUzOTBjYTEwYzUzMWNjZjQzYmQ3Y2M5OWY0MTczY2YwZjc0ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hoap_Y801cXIjdbbqZ9K8bAMm59IW67J9BNk-nRcD7s)

was i not meant to click the retard option?
if its possible to do for an individual to see that's cool, i guess that's pretty much what i was hoping for, but im confused if its doable or not, one guy says no one guy says yes?
