### ISSUE TITLE
Formating Plugin

### ISSUE THREAD

**Issue by junusdenised** [Vencord/plugin-requests#8]
### Plugin Description

A plugin that adds a menu to the message box that makes it easy to add fomating, similar to [BetterFormattingRedux](https://betterdiscord.app/plugin/BetterFormattingRedux). Preferably customizable so you can choose what fomatting options will be shown within the menu.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/BetterFormattingRedux

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by HeartX94** [comment]
+1 here I need that !

**Comment by ABritishLass** [comment]
was just about to make a post about this, agreed wholeheartedly i used that plugin daily and find my self to be missing it's functionality 

+1

**Comment by DannyPt** [comment]
@sunnniee can we please have an update for this request?
over a year has past and this is a very useful one

**Comment by Gauvino** [comment]
This plugin was so important on betterdiscord and I didn't see anyone implemented it in vencord and since I don't know how to make I hope someone will see this and make it because I really love the usage of it, if I could keep one plugin in vencord it would be this one.

**Comment by programminglaboratorys** [comment]
I believe currently, this isn't possible but could be in the future. the reason behind it is long, I have yapped enough

**Comment by programminglaboratorys** [comment]
> > I believe currently, this isn't possible but could be in the future. the reason behind it is long, I have yapped enough
> 
> Any reason on why it's not possible ?

long story short, discord loads the formatting rules so early that vencord has no chance to modify them making it impossible

**Comment by Vendicated** [comment]
this plugin is easily possible

however it is also very useless and just annoying

**Comment by Zexerif** [comment]
I think its very useful, and what do you mean by annoying? If it's a plugin people can just disable it if they find it annoying.

**Comment by Zexerif** [comment]
> this plugin is easily possible
> 
> however it is also very useless and just annoying

I think its very useful, and what do you mean by annoying? If it's a plugin people can just disable it if they find it annoying.
You yourself said it was easily possible, so what do you really have to lose?

I know I'm basically fighting a losing battle here but like, I don't see how it could be useless. I used it all the time when I used BetterDiscord!

Even looking at the reactions to this request you can see that there is demand for it!
