### ISSUE TITLE
A plugin that goes back to the old profile

### ISSUE THREAD

**Issue by NoviTheQT** [Vencord/plugin-requests#802]
### Plugin Description

There should be a plugin that shows the old profile instead of the new ugly profile. Since it's no longer an experiment, it can't be disabled there.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
https://github.com/Vencord/plugin-requests/issues/787
https://github.com/Vencord/plugin-requests/issues/798

**Comment by sadan4** [comment]
you somehow managed to not check this box
![image](https://github.com/Vencord/plugin-requests/assets/117494111/05d2db78-d821-4988-ba23-10d5630ca612)
and yet you missed the two other times this has been posted
