### ISSUE TITLE
MessageTags option for saving formatted text

### ISSUE THREAD

**Issue by ghost** [Vencord/plugin-requests#804]
### Plugin Description

**MessageTags** store messages but doesn't let you store _**formatted**_. Important because you **cant save formatted text** like code-blocks of code and non-formatted code isn't usable (from what i've tested)

A new option for `/tag create` in [Message Tags](https://vencord.dev/plugins/MessageTags) to select what type of method to use for saving text. 

Lets you save formatted text via putting the **Message Link** of a message you need the formatted text from to save, because **you cant type formatted text with built-in commands, like not being able to create a new line in the text.**

Useful for people who usually use code and not just plugins for thingys on cord or just saving advanced formatted text.

Usage:

- `/tags create tag-name: N/A type: message/Message Link value: Text/Message Link`

- Two options while creating a tag, one Message and one MessageLink

![Example picture](https://github.com/Vencord/plugin-requests/assets/129940833/1b1286a8-4193-4e35-9069-043a9ea83f18)

### Existing Plugin for other mod

https://vencord.dev/plugins/MessageTags

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/97131358/6cb0d733-c549-43ec-9391-2e4c571bcd66)
nice

**Comment by Scyye** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/97131358/e6b725b1-9566-478b-bccb-7ca66709536c)
![image](https://github.com/Vencord/plugin-requests/assets/97131358/0e7aa07c-95c7-4d9f-9c3e-3676f6b6567f)

also, you can already use formatting.

**Comment by Luna-devv** [comment]
And for new lines, just throw in a classic `\n` (I made the plugin fyi)

**Comment by Scyye** [comment]
> > ![image](https://private-user-images.githubusercontent.com/97131358/343754825-e6b725b1-9566-478b-bccb-7ca66709536c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODg1NDUsIm5iZiI6MTcxOTQ4ODI0NSwicGF0aCI6Ii85NzEzMTM1OC8zNDM3NTQ4MjUtZTZiNzI1YjEtOTU2Ni00NzhiLWJjY2ItN2NhNjY3MDk1MzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDExMzcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MzIzZTUxYzU2ZjlkMzU4NTIyNGZkYjViZjE1ZGI1NGMwMmMxYTg2MjFlNzQxZGQ2YTIwZmFjMWI0Nzg5MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Czy7U_Phh7Ni7iY11dM0F4AHlOGlE620EjtJ9WlnvU) ![image](https://private-user-images.githubusercontent.com/97131358/343754786-0e7aa07c-95c7-4d9f-9c3e-3676f6b6567f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODg1NDUsIm5iZiI6MTcxOTQ4ODI0NSwicGF0aCI6Ii85NzEzMTM1OC8zNDM3NTQ3ODYtMGU3YWEwN2MtOTVjNy00ZDlmLTljM2UtMzY3NmY2YjY1NjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDExMzcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMmE4MmFhNjRhMjQ1ZDBiYmU4NjY1MGU3YzM1OTc3YjNlYjdiNmIwNjY4MmYyMTY5ZWE0MmE4OGU0NmM0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QbhjlogrZu_BFePDQkiM3F71MbyBj83KComNhkpVgpY)
> > also, you can already use formatting.
> 
> i meant formatting like seperating with spaces
> 
> like this ok
> 
> try getting some js snippet and try formatting it with that

![image](https://github.com/Vencord/plugin-requests/assets/97131358/69532561-6eed-4296-939f-f8b2bb79ea28)
![image](https://github.com/Vencord/plugin-requests/assets/97131358/867747ad-bc24-402a-bffb-1de8b265c11d)

**Comment by Luna-devv** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/71079641/fc4fcc09-5251-483d-85cb-0ff0cf19a219)

**Comment by Luna-devv** [comment]
just add newlines using `\n` or copy the raw original message and paste it
> Become schizophrenic\n\nrun `stop()` to stop\n```js\n(() => {\n    const { GuildMemberStore, FluxDispatcher, SelectedChannelStore } = Vencord.Webpack.Common;\n    \n    const i = setInterval(() => FluxDispatcher.dispatch({\n        type: \"TYPING_START\",\n        channelId: SelectedChannelStore.getChannelId(),\n        userId: GuildMemberStore.getMemberIds(Vencord.Util.getCurrentGuild().id).sort(() => Math.random() - 0.5)[0]\n    }), 5000)\n    return window.stop = () => clearInterval(i)\n})()\n```
