### ISSUE TITLE
Plugin request: alerting if somebody joins the voice call

### ISSUE THREAD

**Issue by HussamXGamerYT** [Vencord/plugin-requests#805]
### Plugin Description

A plugin that alerts me when somebody joins the voice call in the boys discord server. I do not know if it's a plugin spamming discord, I'm not a computer person.
I apologize in advance if this was already requested, I'm autistic.
Thank you for reading.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
> I'm autistic.

uhhh... thanks for sharing?

**Comment by KrstlSkll69** [comment]
Also is this just
https://vencord.dev/plugins/VcNarrator
