### ISSUE TITLE
Every User in Member List

### ISSUE THREAD

**Issue by Space4gamer** [Vencord/plugin-requests#806]
### Plugin Description

see every user in the member list on large servers, regardless of whether they are online or not.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
not possible
