### ISSUE TITLE
Plugin Request: Can someone recreate or import the BD plugin "BetterAudioPlayer" into Vencord?

### ISSUE THREAD

**Issue by zake2002v2** [Vencord/plugin-requests#808]
### Plugin Description

There was a BetterDiscord plugin that made music files (.mp3, .ogg, .wav, etc.) in desktop show an audio visualizer while playing in discord, I can't find such a plugin in Vencord, can someone recreate it?

### Existing Plugin for other mod

https://betterdiscord.app/plugin/BetterAudioPlayer

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
?
![image](https://github.com/Vencord/plugin-requests/assets/45497981/64442c3d-78ee-4c54-b415-b17116d3e4aa)

![image](https://github.com/Vencord/plugin-requests/assets/45497981/8f0654d7-7a44-4df5-940a-a753dad9c141)
