### ISSUE TITLE
Write Uppercase

### ISSUE THREAD

**Issue by paylorddd** [Vencord/plugin-requests#809]
### Plugin Description

A plugin that automatically writes the first letter of a sentence in uppercase.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/WriteUppercase

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/58668179/7f22ec94-4022-4fea-93d9-e67f3c29bfc4)
### If you were to actually follow the request agreement you'd find:
![image](https://github.com/Vencord/plugin-requests/assets/58668179/f754edee-7b56-4c9f-8399-4389a9512afe)
