### ISSUE TITLE
Better Volume control plug-in

### ISSUE THREAD

**Issue by 5wi5wi** [Vencord/plugin-requests#810]
### Plugin Description

Set user volume values manually instead of using a slider. Allows setting volumes higher than 200%.
![image](https://github.com/Vencord/plugin-requests/assets/92057330/b3293ad5-2e6c-4884-8c98-728c6782e03c)

### Existing Plugin for other mod

https://betterdiscord.app/plugin/BetterVolume

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
Already exists, it's called VolumeBooster.
Only works on the desktop client, not web clients.
