### ISSUE TITLE
Hide the new quest thing on the friendlist bar.

### ISSUE THREAD

**Issue by Xiarno** [Vencord/plugin-requests#816]
### Plugin Description

Simply hide the new quest thing that is in the friendlist bar.
![15639_DiscordCanary_pf4Et1zRqF](https://github.com/Vencord/plugin-requests/assets/24660485/7699a8ce-467d-41b1-96f3-8fc0b3fbd3e8)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
That can be easily hidden with css, and so a plugin won't be added for this.
