### ISSUE TITLE
API or CLI Interface for Vesktop & Desktop

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [Vencord/plugin-requests#817]
### Plugin Description

I want to suggest an plugin that allows to control discord from a local API or using a CLI application.

Great use-cases:
- Use with [streamdeck-ui](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui) to control discord with your streamdeck on linux systems
- Use with another application to create custom keybinds, or keybinds at all for vesktop users

Ideas for controllable things:
- Mute status
- Deaf status
- Game activity status
- Send message to specific channel id (useful for (non-slash) music bot commands, for example)
- Set online status
- Soundboard, when in voice
- Start / Stop stream (starting might be harder to realize)
- Voice volume of users
- Join and leave VCs (by ID)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
too niche. some of these can be done with RPC or ekybinds
