### ISSUE TITLE
Timezone plugin for adding timezone in utc next to friend name

### ISSUE THREAD

**Issue by mishalhossin** [Vencord/plugin-requests#818]
### Plugin Description

A plugin that shows time in another timezone next to target user.

### Existing Plugin for other mod

I saw some discord bots have it

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by schoeneBiene** [comment]
#555 #364 #155

> I checked every box, despite not reading any
