### ISSUE TITLE
PlatformEmulator

### ISSUE THREAD

**Issue by FireStacks** [Vencord/plugin-requests#820]
### Plugin Description

it will be great to have a plugin for changing platform on discord and the **PlatformEmulator** plugin will be great to have for that here is the betterdiscord - https://betterdiscord.app/plugin/PlatformEmulator
and github link - https://github.com/Kyza/BetterDiscordPlugins/blob/49e352459b772c1528df591f3708a5af86b0784c/builds/PlatformEmulator.plugin.js

### Existing Plugin for other mod

https://betterdiscord.app/plugin/PlatformEmulator

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by PATXS** [comment]
this is a duplicate sadly
#280 #588
