### ISSUE TITLE
Make ImageZoom lens bigger

### ISSUE THREAD

**Issue by zUkrainak47** [Vencord/plugin-requests#823]
### Plugin Description

or remove it entirely and just let us zoom into the picture itself, like, actually zoom into it, like in a phone gallery or in telegram. the lens is annoying and not big enough, just obstructing the view

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
shift + scroll wheel, you can close this now :p

**Comment by Sqaaakoi** [comment]
shift + scroll allows you to make the lens bigger. there's also settings to change the default size

**Comment by zUkrainak47** [comment]
tysm, didnt know about the shortcut :)
