### ISSUE TITLE
spatial navigation

### ISSUE THREAD

**Issue by i-Igor-i** [Vencord/plugin-requests#824]
### Plugin Description

plugin that allow to jump between UI elements using keyboard hotkeys.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
![image](https://github.com/Vencord/plugin-requests/assets/45497981/eecd0331-09d0-4eef-982d-171f3c796a10)
![image](https://github.com/Vencord/plugin-requests/assets/45497981/b1480b48-0b27-47ad-9abc-85b98f0362ca)
