### ISSUE TITLE
Netflix rich presence plugin

### ISSUE THREAD

**Issue by Wanneshey** [Vencord/plugin-requests#825]
### Plugin Description

Like the Apple Music plugin that is based on the Spotify RPC feature, I would love to have a plugin that displays what I'm watching on Netflix.

### Existing Plugin for other mod

Apple Music RPC

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
https://github.com/Vencord/plugin-requests/issues/243

**Comment by Vendicated** [comment]
you can use premid i think
