### ISSUE TITLE
Plugin Request: Custom Call Ringer

### ISSUE THREAD

**Issue by Boombox17556** [Vencord/plugin-requests#832]
### Plugin Description

ability to have a different call sound with client.
could utilize upload or a redirect to a file location on users system.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
Falls under #21
