### ISSUE TITLE
Easy Dragging for Sorting Categories and Channels in Discord

### ISSUE THREAD

**Issue by Htbatmann** [Vencord/plugin-requests#833]
### Plugin Description

The plugin ideas is an easier dragging mechanism for sorting categories and channels in Discord. Similar to dragging items on some websites, users can grab a handle or dot on a category or channel and easily move it up or down the list. This intuitive and efficient feature simplifies the organization process, making it quicker and more convenient to rearrange channels and categories within a server.

I know Discord currently has drag-and-drop functionality for channels and categories, but this would address the issue where a category or channel gets stuck at the top and can't be moved again. Sometimes, users have to switch to mobile to fix this, which shouldn't be necessary. This is a current issue I am facing, and many other server owners have reported the same problem. The existing "fixes" provided do not work effectively.

https://github.com/Vencord/plugin-requests/assets/100452271/a2b6bbfd-1b4c-424e-aaa0-2f48b2d7f29d

heres an example of the issue (ik its not your discord but still I have had this happen a couple of times) and a plugin to help fix would be really really helpful

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
> this would address the issue where a category or channel gets stuck at the top and can't be moved again

Sounds like _THE_ typical ShowHiddenChannels bug
