### ISSUE TITLE
Better folders are getting on my nerves

### ISSUE THREAD

**Issue by salt-y-lemons** [Vencord/plugin-requests#837]
### Plugin Description

The plugin better folders is doing this weird thing when I scroll down to see the ones lower down, I get automatically taken to the top again and it's really quite annoying since it's been happening for like 10 days now. Just thought I'd notify you guys about it.

### Existing Plugin for other mod

this is an issue about a plugin not a request

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
> this is an issue about a plugin not a request

soo... whyd you make an issue here?

**Comment by Luna-devv** [comment]
me when [`Vencord/plugin-requests`](https://github.com/Vencord/plugin-requests)
