### ISSUE TITLE
ShowMeYourName: Option to Replace Nickname in Voicechat or displaying it next to the nick

### ISSUE THREAD

**Issue by gedropptesitems** [Vencord/plugin-requests#842]
### Plugin Description

Currently, if you have ShowMeYourName enabled, the nick name will remain in a voice channel, where it could cause confusion, when the whole server appearance is different.

My request is to:
- Being able to replace the nick in a voice channel with the actual username
- Being able to show the username next to the nick

### Existing Plugin for other mod

https://vencord.dev/plugins/ShowMeYourName

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by skullriot** [comment]
I believe this would fall under my improvement request #434 yes?
