### ISSUE TITLE
Local + Unlimited User Notes

### ISSUE THREAD

**Issue by IncandescenceSy** [Vencord/plugin-requests#844]
### Plugin Description

Makes user notes stored locally, which also allows bypassing of the 1,500 note limit. Ideally also add a way to look through all of your notes

### Existing Plugin for other mod

https://betterdiscord.app/plugin/UserNotes

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
Someone was working on [making notes unlimited](https://github.com/Vendicated/Vencord/pull/2573), but it seems like that PR got rejected.
Making them searchable was accepted though at least. So the author opened a [separate PR](https://github.com/Vendicated/Vencord/pull/2607) for it.

**Comment by IncandescenceSy** [comment]
I'm currently using that myself with my own build of Vencord. However, it has some flaws, mainly the fact that it doesn't work with existing standard notes

**Comment by vishnyanetchereshnya** [comment]
> I'm currently using that myself with my own build of Vencord. However, it has some flaws, mainly the fact that it doesn't work with existing standard notes

if u using my first plugin version with local notes then u can transfer all standart notes into plugin notes data by button in plugin settings

**Comment by IncandescenceSy** [comment]
oh, thank you! I'm not sure how I missed that haha
