### ISSUE TITLE
Application Command

### ISSUE THREAD

**Issue by Rainbowcrash231** [Vencord/plugin-requests#845]
### Plugin Description

Can used a command on any app bots like Dyno, MEE6, etc

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
what?

**Comment by Rainbowcrash231** [comment]
i mean I can't use any application commands like Dyno while using vencord

**Comment by MrDiamondDog** [comment]
So this is a bug report, not a plugin request?

Please use our [support channel](https://vencord.dev/discord) for this

**Comment by Rainbowcrash231** [comment]
I'll try but I'm using vencord but when I gonna use some Dyno or mee6 or etc commands I can't use it

**Comment by MrDiamondDog** [comment]
> I'll try but I'm using vencord but when I gonna use some Dyno or mee6 or etc commands I can't use it

This is unintended behavior on Vencord's part, please use our [vencord support channel](https://vencord.dev/discord) for further assistance
