### ISSUE TITLE
4:3 to 16"9 for CS2/VAL

### ISSUE THREAD

**Issue by burdenss** [Vencord/plugin-requests#846]
### Plugin Description

It would give you a toggle to make a 4:3 to 16:9 to stretch like the game on your monitor.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
not possible, just use OBS and virtual camera

**Comment by burdenss** [comment]
> not possible, just use OBS and virtual camera

ty
