### ISSUE TITLE
PlatformSwitch

### ISSUE THREAD

**Issue by lua5-1** [Vencord/plugin-requests#856]
## **PlatformSwitch**
This plugin enables individuals to switch their platform. With this plugin, users have the flexibility to change their platform to a range of options, including **PS5, Mobile, Web, and Desktop**.

If you choose the **PS5** platform, each time you launch an application with a presence, your profile will show "Playing on PS5," accompanied by a PS5 logo and a "Connect to PlayStation Network" button below. 

Users equipped with the **PlatformIndicator** plugin will have the capability to view the platform designated by this plugin.

## **Contact Information**
As the contributor of this plugin, I have played a key role in its creation and development.

Writer: 973926908276400198 (@ordinary_binary) / https://github.com/AggelosAst
Contributor: 1093609255623475270 (@lua5.1) / https://github.com/lua5-1
Source Code: https://github.com/lua5-1/PlatformSwitch

## **Review**
I have reviewed the list of functionalities that the plugin is unable to perform, and I can confirm that the plugin does not contravene any items on the list.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by rozbrajaczpoziomow** [comment]
see https://github.com/Vendicated/Vencord/pull/1548#issuecomment-1665994016

**Comment by lua5-1** [comment]
> see [Vendicated/Vencord#1548 (comment)](https://github.com/Vendicated/Vencord/pull/1548#issuecomment-1665994016)

Thank you for making me aware. I weren't able to find a plugin request like that!
