### ISSUE TITLE
Image checker plugin

### ISSUE THREAD

**Issue by Magma-Dev17** [Vencord/plugin-requests#858]
### Plugin Description

A plugin which checks if an image comes from google to check if users like fake there gaming-setup on an event in an discord server.
Example for the Engines:
const Engines = {
    Google: "https://lens.google.com/uploadbyurl?url=",
    Yandex: "https://yandex.com/images/search?rpt=imageview&url=",
    SauceNAO: "https://saucenao.com/search.php?url=",
    IQDB: "https://iqdb.org/?url=",
    TinEye: "https://www.tineye.com/search?url=",
    ImgOps: "https://imgops.com/start?url="
}

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment]
you can already use the reverse image search plugin to do that

**Comment by Luna-devv** [comment]
https://vencord.dev/plugins/ReverseImageSearch

**Comment by Magma-Dev17** [comment]
Omg thx

Luna ***@***.***> schrieb am So. 7. Juli 2024 um 15:10:
