### ISSUE TITLE
AutoResults

### ISSUE THREAD

**Issue by Aexure** [Vencord/plugin-requests#859]
### Plugin Description

You go into a channel and see yourself a poll infront of you, too lazy to vote and too lazy to click "Show Results", that's where AutoResults comes in, go into a channel and AutoResults will automatically show results for the poll in the selected channel you have entered/joined.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
This seems incredibly niche.

**Comment by Sqaaakoi** [comment]
How about an option to show results and still allow voting?

**Comment by Aexure** [comment]
Yeah, that's what I meant, but too bad am terrible at English. (English is
not my main language)

**Comment by Scyye** [comment]
> How about an option to show results and still allow voting?

wouldnt that just be "either have the plugin enabled, or dont"

**Comment by Sqaaakoi** [comment]
> > How about an option to show results and still allow voting?
> 
> wouldnt that just be "either have the plugin enabled, or dont"

i mean at the same time, without having to switch between voting/show results
