### ISSUE TITLE
Remove Account Limit in Discord Built-In account switcher

### ISSUE THREAD

**Issue by Ritanium** [Vencord/plugin-requests#860]
### Plugin Description

Discord Limit us to add only 5 accounts in account switcher so add a plugin that remove this limit and make it add infinity amount of accounts
![Screenshot 2024-07-07 195100](https://github.com/Vencord/plugin-requests/assets/144973099/c84a3e41-2e3d-49db-ab91-716d6f1ea497)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Luna-devv** [comment]
please learn to read, https://github.com/Vendicated/Vencord/pull/1353

**Comment by schoeneBiene** [comment]
and #742 #35
