### ISSUE TITLE
Random Theme Selector

### ISSUE THREAD

**Issue by LaWron-byte** [Vencord/plugin-requests#861]
### Plugin Description

Please, can someone make a plugin, that randomly will choose any of your installed themes, so when you launch your Discord app, they will change everytime, bc i found some cool themes, and dont want manually change them everytime.

Thx.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
Sounds way too niche.

**Comment by LaWron-byte** [comment]
> Sounds way too niche.

![image](https://github.com/Vencord/plugin-requests/assets/59113222/8ad98aa8-3bf4-403f-9f22-e02f5ddb787d)

Sounds like ctrl+c ctrl+v

**Comment by Scyye** [comment]
> Sounds like ctrl+c ctrl+v

2 very niche plugins, 2 comments calling those plugins niche.

**Comment by LaWron-byte** [comment]
> > Sounds like ctrl+c ctrl+v
> 
> 2 very niche plugins, 2 comments calling those plugins niche.

If you recently watched or readed Berserk, it doesnt mean, that all QoL features are niche

**Comment by Luna-devv** [comment]
Too niche.

**Comment by fily-gif** [comment]
very niche.

**Comment by LaWron-byte** [comment]
Niche died from the cringe in his coffin

**Comment by Vendicated** [comment]
#772
