### ISSUE TITLE
AutoResponder to specified keywords

### ISSUE THREAD

**Issue by Bluejutzu** [Vencord/plugin-requests#868]
### Plugin Description

The plugin would automatically respond to certain keywords, with a certain cooldown so you don't spam a channel or get rate-limited by discord. Already worked on this and it worked pretty fine.
(The plugin doesn't auto respond to any user, you have to first give the User IDs of the people you want to automatically respond to so you don't spam random servers suddenly)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
blatant selfbotting
