### ISSUE TITLE
Hide Channel plugin

### ISSUE THREAD

**Issue by ghosnon** [Vencord/plugin-requests#87]
### Plugin Description

Button to hide channel tab

### Existing Plugin for other mod

https://betterdiscord.app/plugin/Hide%20Channels

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
There's some css solutions for this that you can find on the discord but depending on how you want it to function they might not exactly be what you're after.
For a plugin approach let's have this merged to #79.
