### ISSUE TITLE
Voice join sound

### ISSUE THREAD

**Issue by MarkLeague** [Vencord/plugin-requests#870]
### Plugin Description

Can we have the "choose a sound" setting in the "Voice & Video" settings? It doesn't work with FakeNitro

### Existing Plugin for other mod

nope

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
soundboard is blocked server side, and this includes entrance/exit sounds. FakeNitro can't do anything to unlock it

**Comment by mynameisbob1928** [comment]
You could use something to autoplay one of the free sounds on joining but that's about it

**Comment by Sqaaakoi** [comment]
> soundboard is blocked server side, and this includes entrance/exit sounds. FakeNitro can't do anything to unlock it

This is partially misinformation. You can absolutely recreate entrance sounds, provided they are from the same server or are the default sounds
