### ISSUE TITLE
Math parser

### ISSUE THREAD

**Issue by DarkblooM-IO** [Vencord/plugin-requests#871]
### Plugin Description

Parses math expressions upon sending message.  
Examples:
- `$1 + 1$` -> `2`
- `$(86 − 32) × 5/9$` -> `30`

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
use case?
