### ISSUE TITLE
ChannelTabs

### ISSUE THREAD

**Issue by PandoeSandoe** [Vencord/plugin-requests#872]
### Plugin Description

ChannelTabs is a plugin where you have tabs on Discord. You can open and close them, and even favorite them.
![tabs](https://github.com/Vencord/plugin-requests/assets/143614699/cc81411c-263c-4291-816b-4d118c30e4f9)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
https://github.com/Vencord/plugin-requests/issues/6

**Comment by Luna-devv** [comment]
Already covered in https://github.com/Vendicated/Vencord/pull/499
