### ISSUE TITLE
Feature request for existing plugin MaskedLinkPaste: an option to put the link between <>

### ISSUE THREAD

**Issue by thismoon** [Vencord/plugin-requests#876]
### Plugin Description

add an option to MaskedLinkPaste to make pasted links between <> so it doesn't make an embed
original behavior:
[selected text]\(link)
new behavior (with the option enabled):
[selected text]\(\<link>)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
You can use textreplace plugin to achieve this.
REGEX:
find `(https?:\/\/\S+)`
replace `<$1>`

This could probably be improved I don't know regex very well.
I use something similar to disable embeds for specific sites.

**Comment by Jazza-231** [comment]
> You can use textreplace plugin to achieve this. REGEX: find `(https?:\/\/\S+)` replace `<$1>`
> 
> This could probably be improved I don't know regex very well. I use something similar to disable embeds for specific sites.

This is a good solution for now, but it would be nice to add it as a setting to the original plugin.

**Comment by thismoon** [comment]
update: the MaskedLinkPaste plugin is now deleted since its functionality is a discord built in feature now (https://github.com/Vendicated/Vencord/commit/5160f906f408aaadf8b10b507eb1a8f823b5b528).
and the feature i suggested [was going to get implemented in that plugin](https://github.com/Vendicated/Vencord/pull/2741). but since the plugin got deleted, the pr was closed.
however automatically adding `<>` isn't a part of the built in feature. that's why i am going to keep my request open.
i'm not sure how this should be implemented. a part of NoMaskedLinkPaste? a standalone plugin (that could have the extra functionality or putting non masked pasted links in between `<>`)?
also editing the message with regex (which happens after it's sent to my understanding) wouldn't be a good solution in some cases. what if i have a message with 5 links and i want to unmask one important link to show it's embed? editing the message wouldn't be so convenient. although this is a specific use case it would be nice to have a good solution.

**Comment by Vendicated** [comment]
use textreplace
