### ISSUE TITLE
Aisable Automatic Super Reactions

### ISSUE THREAD

**Issue by JumJumCZ** [Vencord/plugin-requests#877]
### Plugin Description

Discord loves pushing towards their Super Reactions, and it is Super annoying. especially when others cannot react with the emoji because they do not got nitro, and when i want to try to react fast and i just got to switch to normal reactions, and it is annoying, and slowing me down. i tried to look up some mod or plugin, but i could not find any, neither in Vencord or searching web was helpful, and i was surprised that there is not request of this already. I sincerely believe that this could be useful as Discord is trying to push their annoying rubbish forward. thank you for reading this, have a great day.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by ImLvna** [comment]
Disable [SuperReactionTweaks](https://vencord.dev/plugins/SuperReactionTweaks)

**Comment by JumJumCZ** [comment]
oh, that worked. thank you!
