### ISSUE TITLE
no (edited) thing at the end of your message

### ISSUE THREAD

**Issue by Snytexm0ds** [Vencord/plugin-requests#88]
### Plugin Description

basically when you edit a message you sent it will say _(edited)_ but i would like to have a plugin that makes it so it doesnt say that.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by EdVraz** [comment]
Pretty sure you should be able to hide that with css

**Comment by cheesesamwich** [comment]
.edited_b20dd9
{
    display: none;
}

**Comment by TeemoCell** [comment]
This hides only the `(edited)` content.
There is still the empty space, if you have a edited embed.

### Without CSS:
![JnN2w7o](https://github.com/Vencord/plugin-requests/assets/11705513/3679e346-d5ec-4390-a752-03b3796b3b81)

### With CSS:
![bsXfYeT](https://github.com/Vencord/plugin-requests/assets/11705513/2eb361d5-9031-476e-b7e4-9ceb19a94200)

**Comment by rozbrajaczpoziomow** [comment]
this request is only 4 months old

**Comment by Scyye** [comment]
*and* has been closed and rejected

**Comment by TeemoCell** [comment]
If I had opened a new request, one of you would have had something to complain about. So I preferred to comment here.
It was closed because it was said that this can only be done with CSS. Which is correct, but doesn't look neat or isn't a permanent solution.

**Comment by Scyye** [comment]
its good enough. its also insanely niche.

> If I had opened a new request, one of you would have had something to complain about. So I preferred to comment here. It was closed because it was said that this can only be done with CSS. Which is correct, but doesn't look neat or isn't a permanent solution.
