### ISSUE TITLE
Signatures

### ISSUE THREAD

**Issue by Packjackisback** [Vencord/plugin-requests#883]
### Plugin Description

Very simple plugin, add a toggle-able button that enables having a customizable signature to the end of each message.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by fily-gif** [comment]
I feel like there was a plugin for that, but it seems like it was deleted/lost and I cant find it now.

**Comment by MrDiamondDog** [comment]
TextReplace can probably do this
