### ISSUE TITLE
Vencord Identifier

### ISSUE THREAD

**Issue by ProjectCrytos** [Vencord/plugin-requests#884]
### Plugin Description

So if someone is using Vencord give them a badge with the Vencord icon and when you hover over it have it say "Vencord User"
When you click it it says "This is a Vencord User" Thanks for your time.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
What's the use case though? I don't see this being very useful

**Comment by sadan4** [comment]
you do not need a plugin, it's builtin to discord
it's called asking them
