### ISSUE TITLE
Role holder

### ISSUE THREAD

**Issue by sawanami** [Vencord/plugin-requests#885]
### Plugin Description

I'd like the ability to list roles and the usernames who hold those roles.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by sunnniee** [comment]
#118
