### ISSUE TITLE
Fix "Messages Failed To Load"

### ISSUE THREAD

**Issue by bangalu1** [Vencord/plugin-requests#886]
### Plugin Description

Fix the messages fail to load, this issue has started to happen because of another user getting banned on the same IP so the messages do not load for everyone else in the same server on the same IP
![image](https://github.com/user-attachments/assets/79f16be4-5be9-4c39-bed0-414a9f57838c)

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Luna-devv** [comment]
thats... thats.. api side...

**Comment by bangalu1** [comment]
Is there any workaround then

**Comment by Luna-devv** [comment]
how is a **client** mod supposed to change what runs on discords' servers?

**Comment by bangalu1** [comment]
telling me to touch grass is ironic but alr
