### ISSUE TITLE
can yall add the communitytabs plugin on vencord please?

### ISSUE THREAD

**Issue by DomaEatsSouls** [Vencord/plugin-requests#888]
### Plugin Description

yo can yall add the communitytabs plugin on vencord please?

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
what?

**Comment by DomaEatsSouls** [comment]
ok so community tabs is a plugin that adds tabs to your discord just like google.

**Comment by Scyye** [comment]
#872 
#733
#582  
#580 
#528 
#433 
#328 
#6
