### ISSUE TITLE
A simple Change in Relationship Notifier 

### ISSUE THREAD

**Issue by RoopakShukla** [Vencord/plugin-requests#891]
### Plugin Description

erm i'm not here to ask for a new plug-in but i waned some change in Relationship notifier i.e the pop up that appears in bottom right side of your screen whenever you come online to tell that someone has unfriended / kicked you from server

Just wanted to remove that timer thingy and want it to stay coz sometimes i'm afk and someone unfriends me so its hard for me to recall who that person is and that pop-up helps me lead to that person's ID.
The green bar helps with nothing. So maybe it would be good it you add a option in plug-in settings to make that pop-up stay
Thanks

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [ ] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
click this button inside of vencord settings for a log of these notifications
![Notification Log button](https://github.com/user-attachments/assets/003378dd-73d1-48ef-9f13-fc5f84a6fe06)

**Comment by MrDiamondDog** [comment]
![image](https://github.com/user-attachments/assets/753ff1bb-5a70-40f5-907d-8a0c918f81b6)
![image](https://github.com/user-attachments/assets/c160f528-caf8-49b1-9a92-48335615651a)

you can also change the settings here so that the notifications dont go away

**Comment by RoopakShukla** [comment]
thank you @Sqaaakoi @MrDiamondDog
