### ISSUE TITLE
Hide Channels

### ISSUE THREAD

**Issue by talkouki89** [Vencord/plugin-requests#892]
### Plugin Description

Hide channel list from view. This also works for DM list.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/Hide%20Channels

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
i think this is possible with css
https://discord.com/channels/1015060230222131221/1191809103677378631/1258059750499946548

**Comment by sadan4** [comment]
#724

**Comment by Vendicated** [comment]
stop being lazy

![image](https://github.com/user-attachments/assets/78588a02-5c8c-4a1c-a65b-6add7761ca9b)
