### ISSUE TITLE
Moving favorite gifs/emojis/stickers etc

### ISSUE THREAD

**Issue by SERAPHIGATO** [Vencord/plugin-requests#895]
### Plugin Description

often times i find myself having an overflow on stickers that i really like but some i rarely use.. the moment i want to add a new one that i want to commonly use, id have to scroll all the way down for awhile until i can find said sticker, this is the same for gifs and emojis (sometimes)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Faf4a** [comment]
#440

**Comment by SERAPHIGATO** [comment]
for stickers and gifs tho
