### ISSUE TITLE
Block the download button on Google Chrome, for example

### ISSUE THREAD

**Issue by Pierre2004** [Vencord/plugin-requests#896]
### Plugin Description

I think it would be nice to have a plugin that removes the button to download Discord because it's useless.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
css

**Comment by Pierre2004** [comment]
It must be complicated to create CSS and then just for that, it's useless I think.
