### ISSUE TITLE
Adding KeyboardClick Sound

### ISSUE THREAD

**Issue by Massachusettss** [Vencord/plugin-requests#897]
### Plugin Description

Plugin that make keyboard click sound like in opera gx

### Existing Plugin for other mod

https://betterdiscord.app/plugin/KeyboardClick

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
> * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Lie buzzer**
https://github.com/Vencord/plugin-requests/issues/718
