### ISSUE TITLE
Image Folder

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [Vencord/plugin-requests#898]
### Plugin Description

basically this plugin allows you to have a folder that stores images inside discord
imo this makes sending images more convenient, specially when you need to send a meme or something similar quickly
this is similar to a plugin that exists in better discord
https://betterdiscord.app/plugin/ImageFolder

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
#716 and some other issues

**Comment by Scyye** [comment]
![image](https://github.com/user-attachments/assets/032996c4-79e2-43cd-8fd1-71e123ca6f74)
stock... computer feature...

also,
#13, #14, #284, #521, #544, #716, https://github.com/Vendicated/Vencord/pull/2091

**Comment by Pierre2004** [comment]
Source : https://github.com/TheLazySquid/DiscordImageFolder/blob/09f7f391e034548a9d2c04a0632ca015a793237b/build/ImageFolder.plugin.js

**Comment by Scyye** [comment]
*Huh?*

> Source : https://github.com/TheLazySquid/DiscordImageFolder/blob/09f7f391e034548a9d2c04a0632ca015a793237b/build/ImageFolder.plugin.js

**Comment by Pierre2004** [comment]
> _Huh?_
> 
> > Source : https://github.com/TheLazySquid/DiscordImageFolder/blob/09f7f391e034548a9d2c04a0632ca015a793237b/build/ImageFolder.plugin.js

Low what? They can use this to make the plugin

**Comment by HAHALOSAH** [comment]
Why not just... make a folder on your desktop

**Comment by Sqaaakoi** [comment]
> ![image](https://private-user-images.githubusercontent.com/97131358/348502392-032996c4-79e2-43cd-8fd1-71e123ca6f74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MTc3MzcsIm5iZiI6MTcyMDkxNzQzNywicGF0aCI6Ii85NzEzMTM1OC8zNDg1MDIzOTItMDMyOTk2YzQtNzllMi00M2NkLThmZDEtNzFlMTIzY2E2Zjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDAwMzcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMWNkMjQyZDZmOWE0N2MxZWY4YjhkODI2ODZjYmUwMjgwZmM0NTAwYmJjYWEwMTJlMTU5YmJmY2UwMmNiNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7nyzHOnI_kgNtPOl1RSeAJNLuKH5iY0489R7iFfLy9A) stock... computer feature...
> 
> also, #13, #14, #284, #521, #544, #716, [Vendicated/Vencord#2091](https://github.com/Vendicated/Vencord/pull/2091)


> Why not just... make a folder on your desktop

@Scyye @HAHALOSAH Too inconvenient. FavouriteMedia with folders (someone's definitely made a request or PR for it) is a better solution

**Comment by InfectedGriffon** [comment]
If you don't like using your own computer to store images, you could use a file hosting site like imageclipboard or catbox

**Comment by Scyye** [comment]
> Too inconvenient.

How so?

**Comment by Vendicated** [comment]
useless just use system folders
