### ISSUE TITLE
Upgrading messagelogger

### ISSUE THREAD

**Issue by proboy125** [Vencord/plugin-requests#9]
### Plugin Description

Could the messagelogger save edited, deleted and purged messages/images and ghost pings into a modal/icon that appears on the top beside the "start voice call" icon. It would be able to save messages even after restarting Discord or having it closed (maybe?) and u are able to delete them from the modal/log if you wish to.

### Existing Plugin for other mod

https://1lighty.github.io/BetterDiscordStuff/?plugin=MessageLoggerV2

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by junusdenised** [comment]
[MessageLoggerEnhanced](https://github.com/Syncxv/vc-message-logger-enhanced) can safe messages and images between restarts, and i think there is a button with it (might already be a feature with the normal one) that shows all the deleted/edited messages and can clear the logs.

**Comment by Vendicated** [comment]
no
