### ISSUE TITLE
MessageTextAdd

### ISSUE THREAD

**Issue by KenvaidGT** [Vencord/plugin-requests#900]
### Plugin Description

A plugin that adds automatic addition of text to messages, 
for example, in the plugin settings, 
set the text to be displayed on the next line and 
configure the text itself that is needed.

### **Example of settings:**

Shift+Enter:  [+]
Text: TeXt69

### **Example of usage:**

**Your message:** 
-

> HelloWorld!

**Output:**
-

> HelloWorld!
>   TeXt69

====================
 

### **Example of settings:**

Shift+Enter: [ ]
Text: TeXt69

### **Example of usage:**

**Your message:**
-

> HelloWorld!

**Output:**
-

> HelloWorld!TeXt69

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
You can accomplish this with textreplace plugin but I'm not sure how to set that up.

**Comment by Blackilykat** [comment]
You can use textreplace with regex using `$` as find (or `^` to put it in front of the message instead) and putting the text to add in Replace. You can write `\n` to add a newline
![image](https://github.com/user-attachments/assets/3403b61f-869b-43b7-93ad-8e6ac0f7ba9c)
![image](https://github.com/user-attachments/assets/b8a0d88d-3918-4d42-938d-281abc38060e)
