### ISSUE TITLE
JoinedSince

### ISSUE THREAD

**Issue by JT02GitHub** [Vencord/plugin-requests#904]
### Plugin Description

So basically, you can see when someone joined a server even if they've left the server. "Even if they've left" is the **modification** to what Discord shows. (Discord only shows when they've joined if they're **still** in the server, which is annoying).

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
Discord doesn't retain that data, the closest possible result is when the user sent their first message

**Comment by seriousfact** [comment]
> Discord doesn't retain that data, the closest possible result is when the user sent their first message
What if they weren't active in the server at all, and just acted as a spectator?

**Comment by Mm2PL** [comment]
Discord sends these welcome messages:
![image](https://github.com/user-attachments/assets/61163a9f-de00-4eaf-b6da-549cf33b1519)
They show up when looking up `from:user` (order by oldest first). They can be deleted by the user but not faked afaik.

**Comment by Luna-devv** [comment]
They could also be disabled server wide, be in a private channel, or as you said deleted.
