### ISSUE TITLE
channeltab

### ISSUE THREAD

**Issue by WhyWKey** [Vencord/plugin-requests#905]
### Plugin Description

PLEASE I NEED CHANNELTABS PLEASE 

### Existing Plugin for other mod

https://betterdiscord.app/plugin/ChannelTabs

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [ ] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by maddie480** [comment]
<img width="401" alt="Capture d’écran 2024-07-16 à 09 56 30" src="https://github.com/user-attachments/assets/2f4c1569-afdb-43cf-af5b-d8a2162dfc9e">

**Comment by KrstlSkll69** [comment]
_Pr Pending Version_
https://github.com/Vencord/plugin-requests/issues/6

**Comment by Scyye** [comment]
> ![image](https://github.com/user-attachments/assets/662a97b1-d1a1-4432-9d7d-5c9118a6c5f0)

well, i mean... they didnt check it tbf lol
