### ISSUE TITLE
Message to Base64

### ISSUE THREAD

**Issue by TxcToxic** [Vencord/plugin-requests#907]
### Plugin Description

A plugin which replaces the current message to base64 that converts received base64 strings

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Koishukaze** [comment]
But why?

**Comment by Luna-devv** [comment]
It’s not even that that this was e2ee or anything, that’s just entirely useless. I’d say just make a userplugin if you really need that.
