### ISSUE TITLE
Override DND Plugin

### ISSUE THREAD

**Issue by remsterrr** [Vencord/plugin-requests#914]
### Plugin Description

This plugin is designed for use in Do Not Disturb (DND) mode. It allows you to prioritize certain DMs so they can bypass DND. To use it, simply right-click on the DM and check the "Override DND" option, which will be located under "Mute DM." You will then hear notifications from that DM as if your status were set to online.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment]
> [x] I searched the existing issues and made sure a similar request doesn't already exist

https://github.com/Vencord/plugin-requests/issues/639
https://github.com/Vencord/plugin-requests/issues/131
