### ISSUE TITLE
PGP Encryption and Decryption plugin.

### ISSUE THREAD

**Issue by T0BAA** [Vencord/plugin-requests#919]
### Plugin Description

A plugin for client-side PGP encryption and decryption, allowing users to input and save their private and public keys. With this plugin, messages can be automatically encrypted using a button. Additionally, the plugin's popup window includes a tab for entering the recipient's public key, ensuring all messages are automatically encrypted and decrypted when configured correctly. Non-plugin users will only see a PGP scrambled key.

### Existing Plugin for other mod

By "a popup window" im thinking about something similar to the window that pops up when using the translate function. https://vencord.dev/plugins/Translate

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrystalSkullOfficial** [comment]
isn't this just 
https://discord.com/channels/1015060230222131221/1032200195582197831/1245882235283046410
