### ISSUE TITLE
PlatformIndicators - Add more color options and formatting

### ISSUE THREAD

**Issue by Saud-97** [Vencord/plugin-requests#925]
### Plugin Description

I suggest adding an option similar to Color Mobile Indicator but applicable to all icons such as web or desktop with more color options. I would really love having the option to make the platform icons as grey for aesthetics purposes.
![image](https://github.com/user-attachments/assets/827ba4e8-363f-4344-a000-c46b0e6f9afc)

Also please add option to make the alignment of the platform icons to the far right.

![image](https://github.com/user-attachments/assets/42c045e4-74ad-43e9-b61a-342c9379f83b)

Latest suggestion is perhaps is it possible to make the primary platform icon of status to be similarly positioned just like the phone symbol status that is on top of the user profile pic?
![image](https://github.com/user-attachments/assets/1ead7410-9351-4846-8b79-f20faa9cd480)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
css
