### ISSUE TITLE
Color Message Logger

### ISSUE THREAD

**Issue by Grimfoxy19883** [Vencord/plugin-requests#928]
### Plugin Description

I'd like to have the ability in the message logger to change the color style of deleted messages to any color, such as green or orange using hex codes. Additionally, it would be great to include a chroma option that makes the deleted text change colors like a rainbow.

### Existing Plugin for other mod

Message Logger 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Fripe070** [comment]
This can be done trivially with custom css. See [messageLogger/deleteStyleText.css](https://github.com/Vendicated/Vencord/blob/main/src/plugins/messageLogger/deleteStyleText.css)
