### ISSUE TITLE
Higher quality profile pictures

### ISSUE THREAD

**Issue by equmaq** [Vencord/plugin-requests#932]
### Plugin Description

The plugin would change the size variable in the URLs of all profile pictures to 320 or whatever the highest value possible is.

At startup and when a mutation is observed the plugin would go through all the HTML and look for img tags, if it finds an image tag it checks if the url set as its source matches one of an avatar url (https://cdn.discordapp.com/avatars/*), if it is the url of an avatar the size variable at the end of the url is changed to 320. (sorry for the lack of punctuation, I was feeling too lazy for that)

This would be useful not only because profile pictures would look noticeably better (sometimes), but it would also make development of themes that change the size of profile pictures for some reason possible/easier.

If someone makes this I'll be like super grateful frfr

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
ThemeAttributes plugin + css can do this.
![image](https://github.com/user-attachments/assets/c3975b44-158a-4ed2-b985-e0a3d9acc1ef)
