### ISSUE TITLE
Profile picture on Compact mode

### ISSUE THREAD

**Issue by Malanao** [Vencord/plugin-requests#935]
### Plugin Description

Basically, as it says, I think it would be nice if Compact mode had profile pictures. As small as they might be, I still think it's neat and crucial to have profile pictures.

![concept](https://github.com/user-attachments/assets/91559d73-e2af-4e93-8bfa-32c4a07d04c6)

Additionally, there could also be more padding between the timestamp to make it more thorough to understand and visualise. And an option to tweak the message break between a person's sequence of messages and another, where the gap between two different people would be larger than the gap between messages from the same person.

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
You're looking for this?
![image](https://github.com/user-attachments/assets/9467b721-c00a-4bf7-940d-351e12cb21a6)

**Comment by Vendicated** [comment]
stock feature + css can do all this
