### ISSUE TITLE
WiderUserArea

### ISSUE THREAD

**Issue by burdenss** [Vencord/plugin-requests#936]
### Plugin Description

Add this please

### Existing Plugin for other mod

https://betterdiscord.app/plugin/WiderUserArea

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
This can be done easily in CSS, but also it's part of Discord's new theme which you can enable via the visual refresh experiment.
