### ISSUE TITLE
Wave infinitely

### ISSUE THREAD

**Issue by kittenvr** [Vencord/plugin-requests#937]
### Plugin Description

A plugin that uses https://vencord.dev/plugins/GreetStickerPicker to allow you to wave infinitely

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Blackilykat** [comment]
is this not the same as directly using stickers?
![image](https://github.com/user-attachments/assets/1e6b5de3-c58d-4c08-8535-5c2859f61ba8)

**Comment by kittenvr** [comment]
> is this not the same as directly using stickers? ![image](https://private-user-images.githubusercontent.com/66535696/351268361-1e6b5de3-c58d-4c08-8535-5c2859f61ba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3Mjk3MzgsIm5iZiI6MTcyMTcyOTQzOCwicGF0aCI6Ii82NjUzNTY5Ni8zNTEyNjgzNjEtMWU2YjVkZTMtYzU4ZC00YzA4LTg1MzUtNWMyODU5ZjYxYmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDEwMTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMDYxZmUwZGM2NGQ2MTg4Zjc1ZGE5YjNiY2Y2OGU5MTFiOTgwNzM0MTBiZjdjZGExMTdmZDE4NmU4YWVmMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NCiULxr9G6yRqJV12nhjuIyacizdDN4JMntG591EZXM)

no you the suggestion is easier
