### ISSUE TITLE
InfiniteInvites

### ISSUE THREAD

**Issue by MrBlueTopHat** [Vencord/plugin-requests#939]
### Plugin Description

Makes it so invites last forever by default instead of the usual default of 7 days.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by clevernt** [comment]
https://github.com/Vencord/plugin-requests/issues/563 https://github.com/Vendicated/Vencord/pull/2672
