### ISSUE TITLE
ShowAllMembers

### ISSUE THREAD

**Issue by elos12223** [Vencord/plugin-requests#940]
### Plugin Description

make a plugin that shows you all members on the member list even if they are offline
idk if its possible but it would be usefull 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Golonchy** [comment]
thats impossible, yes
