### ISSUE TITLE
Better Volume from BetterDiscord

### ISSUE THREAD

**Issue by PhoenixllGames** [Vencord/plugin-requests#943]
### Plugin Description

Set user volume values manually instead of using a slider. Allows setting volumes higher than 200%.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/BetterVolume

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
plugin already exists... also blatant duplicate
