### ISSUE TITLE
Always show spoilers

### ISSUE THREAD

**Issue by etotspia5** [Vencord/plugin-requests#946]
### Plugin Description

Always Shows The spoilers message  and images and etc 

### Existing Plugin for other mod

No

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by etotspia5** [comment]
is this possible i think this is possible tho.

**Comment by Feathers8** [comment]
![image](https://github.com/user-attachments/assets/bc7a61c7-f090-46a1-8151-7b4145547cd0)

**Comment by etotspia5** [comment]
ohhh my bad
