### ISSUE TITLE
 turns typed words in reactions into emojis

### ISSUE THREAD

**Issue by etotspia5** [Vencord/plugin-requests#947]
### Plugin Description

Adds a option to quickly type words in reaction 
![image](https://github.com/user-attachments/assets/3e14b0c0-d7ee-420a-8c9b-d7612e0213ad)

### Existing Plugin for other mod

Aliucord Has it but i want it on pc 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by etotspia5** [comment]
simply adds an option, then if you type hi it puts the letter emoji

**Comment by etotspia5** [comment]
@nvhhr is this good plugin?

**Comment by etotspia5** [comment]
i mean yall need to try this its really really tho.

**Comment by Feathers8** [comment]
It was denied before.
https://github.com/Vencord/plugin-requests/issues/759

**Comment by etotspia5** [comment]
BROO WTF

**Comment by etotspia5** [comment]
its impossible to get a new plugin

**Comment by etotspia5** [comment]
thats why theres no new plugins

**Comment by etotspia5** [comment]
Also how do i add my own plugin like putting betterdiscord plugins into vencord

**Comment by mynameisbob1928** [comment]
Adding your own plugins is not officially supported but is possible. There is a short guide on how to do it [here](https://ptb.discord.com/channels/1015060230222131221/1257038407503446176). Do note though that you cannot just use a betterdiscord plugin on vencord as they use different libraries and methods.
