### ISSUE TITLE
SplitLargeMessages

### ISSUE THREAD

**Issue by etotspia5** [Vencord/plugin-requests#948]
### Plugin Description

Allows you to enter larger Messages, which will automatically split into several smaller Messages

### Existing Plugin for other mod

https://betterdiscord.app/plugin/SplitLargeMessages

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [ ] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by mynameisbob1928** [comment]
Already denied

**Comment by etotspia5** [comment]
BRUH WHY  ITS GOOD THO.

**Comment by etotspia5** [comment]
man
