### ISSUE TITLE
Send Timestamps Enhancements (Allow highlighted text like '6pm' or '6:00pm' or a date supllied to turn into a timestamp) 

### ISSUE THREAD

**Issue by ColynOrg** [Vencord/plugin-requests#950]
### Plugin Description

Similar to how MaskedLinkPaste works where it adds Parentheses and Square Bracket around the link and such when you paste on a highlighted text. with this you can be able to turn time that is highlighted into timestamps. 

here are some examples:
6pm / 6:00pm: <t:1721944800:t>
Thursday, July 25th, 6:00pm: <t:1721944800>

im sure this would be a great addition so people aren't just having to go back and forward to the timestamps menu if they want to select a time thats an hour ahead of what they already selected, saving much needed time.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by jakjakob** [comment]
Is SendTimestamps what you are searching?
![image](https://github.com/user-attachments/assets/a14918cb-1869-4618-a165-c729893375c1)

**Comment by ColynOrg** [comment]
> Is SendTimestamps what you are searching?
Correct it is, i notice i got the plugin name wrong but i also applied the word 'enhancements'.

>From your description I quite not entirely understand what is the exact functionality you are searching
if you have used the MaskedLinkPaste plugin, you would notice that when you highlight the text and pasted a link, it would turn those highlighted text into a masked link with the highlighted text being the header. what this enhancements plugin request is suggesting is that the same behavior can apply to this plugin making it a timestamp instead of having to go back and forward adding more timestamps which is wasting time, especially when you're just trying to insert a time an hour forward from the previous one.

**Comment by Vendicated** [comment]
![image](https://github.com/user-attachments/assets/56d23cff-e9a4-416e-986c-ab13df019d09)
