### ISSUE TITLE
picture in picture for vc livestreams

### ISSUE THREAD

**Issue by ImMrJakob** [Vencord/plugin-requests#951]
### Plugin Description

picture in picture livestreams

so when someone goes live in a vc, allow us to put that live into picture in picture

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by fily-gif** [comment]
already somewhat exists, it even allows you to put it on top of other programms:
![Ziw83qBdak](https://github.com/user-attachments/assets/47cdc061-66d2-4714-9694-d81eec712d3c)

**Comment by Vendicated** [comment]
there's really no need to add pinning to top cause your window manager should handle it. on mac and linux it's a stock feature, on windows you can install powertools always on top

rest of the request already exists sooo
