### ISSUE TITLE
YouTube Music Player in Discord

### ISSUE THREAD

**Issue by Pierre2004** [Vencord/plugin-requests#952]
### Plugin Description

A plugin that allows you to have a player on Discord just like Spotify

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue+is%3Aopen+YouTube+Music
