### ISSUE TITLE
Markdown/Message formatting plugin

### ISSUE THREAD

**Issue by Zexerif** [Vencord/plugin-requests#954]
### Plugin Description

A message formatter so i dont have to go to the dreaded [White page](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline) every time i want to remember how to use markdowns. It can just be above the chatbox. Something like what ive linked below.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/BetterFormattingRedux
https://github.com/rauenzi/BetterDiscordAddons/tree/c85066eac5758acba004651a593a21820283f6dd/Plugins/BetterFormattingRedux
### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
https://github.com/Vencord/plugin-requests/issues/8

**Comment by Zexerif** [comment]
How is it not useful? I used it all the time when I used betterdiscord

**Comment by Gauvino** [comment]
> How is it not useful? I used it all the time when I used betterdiscord

Same for me really

**Comment by Zexerif** [comment]
and they just locked the original one lol

**Comment by nin0-dev** [comment]
1. don't create deliberate duplicates
2. select text and you should see formatting options
3. all that betterformattingredux seems to add is 1337 speak, and some other annoying unicode fonts. so yeah I'd agree that this plugin is annoying
