### ISSUE TITLE
FileViewer

### ISSUE THREAD

**Issue by shenwandev** [Vencord/plugin-requests#955]
### Plugin Description

File Viewer lets you view files like pdf, doc, xlsx etc. directly in discord.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
#3
