### ISSUE TITLE
Opening request for a cool and easy to use plugin - FavoriteMedia

### ISSUE THREAD

**Issue by Domicele** [Vencord/plugin-requests#957]
### Plugin Description

the plugin allows to favorite GIFs, images, videos and audios and no need to download them so its very easy to use (it exists in betterdiscord mod)

### Existing Plugin for other mod

https://betterdiscord.app/plugin/FavoriteMedia

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by clevernt** [comment]
> I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

![image](https://github.com/user-attachments/assets/a01615cd-2e97-40be-9738-4cf9bcf0b6fa)

**Comment by Domicele** [comment]
oh so it will be not added:(
