### ISSUE TITLE
Folder Icons

### ISSUE THREAD

**Issue by multiaudacity** [Vencord/plugin-requests#963]
### Plugin Description

Folder/Group Icons. Would like to be able to put icons or just normal emoji for folders/groups on vencord

### Existing Plugin for other mod

https://vencord.dev/plugins/BetterFolders

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrystalSkullOfficial** [comment]
>     * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

_Lie Sound Effect_
https://github.com/Vencord/plugin-requests/issues/638

**Comment by Scyye** [comment]
(this is a blatant dupe, literally searching "Folder Icons" yields results.)
