### ISSUE TITLE
Profile saving and loading

### ISSUE THREAD

**Issue by Shenlmao** [Vencord/plugin-requests#966]
### Plugin Description

It would allow you to make a profile on discord (banner, profile picture, profile effect, avatar effect, about me, etc.) and then save it to some kind of GUI. In that same GUI you will be able to load a profile, which will automatically set ur banner, pfp, etc. to whatever you have saved.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Shenlmao** [comment]
this is ofcours kind of a big thing, but it would be extremely nice to have and saves a lot of time and effort. i did my best to try and find a simular suggestion like this, but i couldnt find one so i hope i was right and its original.

**Comment by Krammeth** [comment]
Sounds similar to #137

**Comment by Shenlmao** [comment]
let me look that one up

**Comment by Shenlmao** [comment]
i see now, i appologise. i was not aware.

**Comment by Krammeth** [comment]
Np, you can show your support for the original plugin request by reacting with a 👍
