### ISSUE TITLE
Lock DM's with PIN-Code

### ISSUE THREAD

**Issue by Allerek** [Vencord/plugin-requests#968]
### Plugin Description

Simple plugin - lock DM's with PIN code. So other's can't read it while you're away from your PC while sharing a room with someone. 
You could set different PIN for every DM chat

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
turn your computer off/lock it
close discord
dont give people access to your computer that you dont want having access to your computer

Blatant dupe.

https://github.com/Vendicated/Vencord/pull/2637
https://github.com/Vencord/plugin-requests/issues/375
https://github.com/Vencord/plugin-requests/issues/360
https://github.com/Vencord/plugin-requests/issues/245
https://github.com/Vencord/plugin-requests/issues/211
https://github.com/Vencord/plugin-requests/issues/54
https://github.com/Vencord/plugin-requests/issues/10
