### ISSUE TITLE
Custom RPC “saves”

### ISSUE THREAD

**Issue by bruhIDFK** [Vencord/plugin-requests#969]
### Plugin Description

I would really appreciate a brand new plugin or an update to Custom RPC that let you save the ones you’ve made! I get tired of having to edit everything every time I wanna swap it and then having to edit it back when I wanna swap back, so if you made them work like files so you could export all the values to like a text file, and import as well! Would be way easier to swap between different ones you’ve made  

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by DeViL5292** [comment]
Why this feature is rejected??
it will be really helpful
