### ISSUE TITLE
UserAffinity

### ISSUE THREAD

**Issue by 42chompii** [Vencord/plugin-requests#97]
### Plugin Description

A plugin that allows you to see who you interact with the most either by DM or direct @ messages in servers.

This plugin allows you to view who you talk to the most, through DMs or through directly interacting with them in servers by @ing them. Screenshots below of what to expect it to look like.

Totally didn't copy this from Sarah's bd plugin page.
Idk if she'd mind it being on VC as well as BD, unless that's not something you guys care about

If it exists already then I'm blind, couldn't find it on the website

### Existing Plugin for other mod

https://betterdiscord.app/plugin/UserAffinities

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment]
you can see this in the discord devtools. they're enabled by activating `isStaff` in the `Experiments` plugin

**Comment by Vendicated** [comment]
https://vencord.dev/plugins/ImplicitRelationships
