### ISSUE TITLE
AvatarSettingsButton - Moves the User Settings button to clicking on the user avatar

### ISSUE THREAD

**Issue by Aracnoss** [Vencord/plugin-requests#970]
### Plugin Description

Removes the settings button and moves the User Settings button to left clicking on the user avatar, with the status picker and context menu still available on configurable actions.

### Existing Plugin for other mod

https://github.com/Neodymium7/BetterDiscordStuff/tree/main/AvatarSettingsButton

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [x] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [x] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
Very niche, and can be mostly done in css by moving the settings button on top of the avatar with 0 opacity, or make settings button appear under specific criteria; This is much more a theming type of customization than something there should be a plugin for.
