### ISSUE TITLE
Afk In voice room

### ISSUE THREAD

**Issue by ifzpmM4** [Vencord/plugin-requests#971]
### Plugin Description

When you enter a voice room and go AFK, and then click on shutdown mode or sleep mode, Discord will not kick you out of the voice room

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
You want to stay connected to a voice channel when you shut down your computer?

**Comment by ifzpmM4** [comment]
> You want to stay connected to a voice channel when you shut down your computer?

Yes

**Comment by Scyye** [comment]
lol
