### ISSUE TITLE
UAE VOICE ROOM

### ISSUE THREAD

**Issue by ifzpmM4** [Vencord/plugin-requests#972]
### Plugin Description

When I enter a voice room with my friend, I'm unable to hear them or see the screen because I'm in the UAE and need VIP access to do so. If you could add a plugin to help with this, it would be greatly appreciated and would make a big difference for me.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by skullriot** [comment]
Based on a few google searches this is a block put in place by the government. You will need to use a VPN to get around it. 

I'm not really finding any info other than that that's newer than 2 years old but I expect that it hasn't changed much since then. 

Related:  #437 #383

**Comment by zLost32** [comment]
> Based on a few google searches this is a block put in place by the government. You will need to use a VPN to get around it.
> 
> I'm not really finding any info other than that that's newer than 2 years old but I expect that it hasn't changed much since then.
> 
> Related: #437 #383

would it be possible to change the region of the voice call for yourself like you can in DMs? I live in the UAE and I can bypass the ban by changing the region of the call in DMs but this doesn't work in servers where I don't have admin so if theres anyway I can change the region for a call for myself, it would be great

**Comment by Vendicated** [comment]
use a VPN
