### ISSUE TITLE
Change discord hour format display

### ISSUE THREAD

**Issue by ChazmerW** [Vencord/plugin-requests#973]
### Plugin Description

I'd like a Discord setting to choose between 12-hour and 24-hour time format display, for example, if you're using EN language you'll see 12 hours format without the plugin but 24 hours format if ES language

Example:
![image](https://github.com/user-attachments/assets/6611e638-a533-45a5-b87e-679525036d18)
![image](https://github.com/user-attachments/assets/c9d6f436-4c44-4b68-8ca1-38f01ad1b8c8)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by KrstlSkll69** [comment]
>     * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

_LIE SOUND EFFECT_
https://github.com/Vencord/plugin-requests/issues/1

**Comment by ChazmerW** [comment]
> > ```
> > * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist
> > ```
> 
> _LIE SOUND EFFECT_ #1

Oh bruh, I didn't saw that one when I searched 💀
