### ISSUE TITLE
Youtube AD block

### ISSUE THREAD

**Issue by Sazoji** [Vencord/plugin-requests#974]
### Problem: 
Very recently, youtube has begun to implement ads within discord embeds

### Solutions:
- Embedding via text replacement, looking at options, but most normal users probably dont want a fxyoutube-like or Invidious to watch memes, livestreams wouldn't work either AFAIK.
- Plugin to right-click and open in your video player (honestly, if there was a way to do this with any link/text to "execute with app" or "send URL to MPV" instead of the default browser that'd save quite a few clicks, let you set up a command arg and where to insert the URL (Title: `Open in MPV` args: `/*/*/mpv.exe [URL] --no-terminal` Send to clipboard or execute new app? `app`), would be nice for ytdlp command forwarding
- UBO ported to the client, or similar ad blocking ability embedded into the default or custom vencord client, there's already the watchtogether plugin with adguard, so this could be feasible, but considerably more effort 

I do have concerns with editing embeds as the client is then interacting potentially with URL grabbers without interacting with the embed, and the URL redirect could be obfuscated with blue text, so you'd never know that a 3rd party grabbed your ip after clicking a play button that embeds an ad-free version of youtube.
The top 2 solutions are ideal for security IMO, but something similar to or built within FixYoutubeEmbeds would be what I expect most people would think it'd work.

### Existing Plugin for other mod

[OpenInApp](https://vencord.dev/plugins/OpenInApp) exists, but to translate URLs for apps, not executing a command with custom args to launch something like MPV or ytdlp/ffmpeg
[FixYoutubeEmbeds](https://vencord.dev/plugins/FixYoutubeEmbeds) functions similarly but not for ads in the embed
[WatchTogetherAdblock](https://vencord.dev/plugins/WatchTogetherAdblock) does the expected for watch together sessions

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by prototype464** [comment]
Yes please. Absolutely. I've blocked ads on everything everywhere else I can. Screw Alphabet, Google, and YouTube. Screw them. This is stupid. Ads are awful. Sick of them. They are so damn loud and obnoxious.

**Comment by Sazoji** [comment]
I've worked around this by setting up the discord webapp in firefox with the tampermonkey extension, UBO also works and blocks ads on the embeds as intended. Theme support seems to work despite the warning.
If you open up edge (with extensions enabled for webapps) you could make your own standalone webapp with Vencord and UBO/SponsorBlock/etc in a few clicks. Would save some ram too if you keep your microsoft default browser open (ew)

I'm off the main vencord server for now, so any feedback in this thread for suggestions on the best execution for removing ads from youtube embeds would be appreciated here!

**Comment by TheLonelyGuy1234** [comment]
Literrally had the same idea not long ago

**Comment by nvhhr** [comment]
This was just added today with version 1.9.7 https://github.com/Vendicated/Vencord/commit/0f8d21a8461b716d9aac9a5f58c18c9a4d64dd27
