### ISSUE TITLE
Black outline on names

### ISSUE THREAD

**Issue by EarwaxGames** [Vencord/plugin-requests#976]
### Plugin Description

This plugin would be usefull beacuse there are many servers that color their roles in a color thats unseeable in lightmode

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment]
Alternatively, you could use this. It's in user settings > accessibility.
(I'm also guessing this request is possible with CSS but idk.)
![image](https://github.com/user-attachments/assets/dc51d570-8010-4522-838d-911ab39c879e)

**Comment by nvhhr** [comment]
I've tried making outlines with [-webkit-text-stroke](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke) and multiple [text-shadow](https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow)s and at least in my experience and in my eyes it looked horrible, so I came up with another solution that I much prefer.
https://github.com/nvhhr/discordcss/blob/main/snippets/namebrightener.theme.css
Check my [readme](https://github.com/nvhhr/discordcss/blob/main/snippets/README.md) for namebrightener for screenshot and additional info.

In any case, I'm closing this in favor of #758.
