### ISSUE TITLE
ChannelTabs 

### ISSUE THREAD

**Issue by sdfsdf3edsf** [Vencord/plugin-requests#979]
### Plugin Description

он добовляет вкладки как в браузере,и можно переключаться с одного канала на другой

### Existing Plugin for other mod

ChannelTabs (ВettaryDiscord)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
1- duplicate, please use the search bar
2- please use english
