### ISSUE TITLE
ChannelTabs

### ISSUE THREAD

**Issue by JohannKili** [Vencord/plugin-requests#980]
### Plugin Description

A working ChannelTabs so its looking like this:
![image](https://github.com/user-attachments/assets/e98e7010-3a6a-4973-8808-44906f6820b0)

Warning! the plugin dont work on _(psst.. betterdiscord)_

### Existing Plugin for other mod

https://betterdiscord.app/plugin/ChannelTabs

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment]
#6 #328 #433 #528 #580 #582 #733 #872 #905 #979
