### ISSUE TITLE
An Addition to an CustomRPC plugin

### ISSUE THREAD

**Issue by DeViL5292** [Vencord/plugin-requests#982]
### Plugin Description

Hi,

I have a suggestion for the CustomRPC plugin. It would be great to add a feature for presets. For example, users could set preset 1 for Netflix, preset 2 for YouTube, and so on. This way, they can quickly switch between different RPC statuses without having to change the details every time. This would make it more convenient for users to manage their RPC statuses.

Thanks!

### Existing Plugin for other mod

https://github.com/Vendicated/Vencord/tree/main/src/plugins/customRPC

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
> I checked the existing issues and made sure a similar request doesn't already exist

The #206 #969 in question:
