### ISSUE TITLE
Cloud Sync

### ISSUE THREAD

**Issue by arkzok** [Vencord/plugin-requests#983]
### Plugin Description

A plugin that saves you plugins to cloud

### Existing Plugin for other mod

https://bunny.nexpid.xyz/cloud-sync/
https://github.com/nexpid/BunnyPlugins/tree/main/plugins/cloud-sync

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
Liter

**Comment by arkzok** [comment]
oh lmfao

**Comment by arkzok** [comment]
im blind
