### ISSUE TITLE
Read message history

### ISSUE THREAD

**Issue by TsardomRussland** [Vencord/plugin-requests#984]
### Plugin Description

Basically be able to see message history, even if read message history is off in that channel

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
#55 #890
