### ISSUE TITLE
Disable Markdown link pasting (i.e. inverse of former MaskedLinkPaste plugin)

### ISSUE THREAD

**Issue by leo60228** [Vencord/plugin-requests#987]
### Plugin Description

I would appreciate the ability to disable Discord's newly added functionality of pasting a link from the clipboard while having text highlighted resulting in that text being turned into a link rather than replaced. This would effectively be the inverse of the removed MaskedLinkPaste plugin.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Scyye** [comment]
Why though? just backspace + paste.
it makes more sense to have it turn it into a hyperlink.

**Comment by leo60228** [comment]
8+ years of muscle memory in Discord, and longer in almost every other application with text input?

I don't necessarily disagree with Discord enabling it by default, but I think it should be an option (as it was previously in Vencord).

**Comment by 6c0-o** [comment]
I've made an `userplugins` shitty code and that use MaskedLinkPaste code but work

https://github.com/6c0-o/UnMaskedLinkPaste

![unmasked](https://github.com/user-attachments/assets/f6e15a39-c205-4661-84dc-191ef324e697)

**Comment by leo60228** [comment]
Closed by https://github.com/Vendicated/Vencord/pull/2782
