### ISSUE TITLE
AI-Powered Sentence Formatter for Discord

### ISSUE THREAD

**Issue by olluolen** [Vencord/plugin-requests#989]
### Plugin Description

This plugin uses AI to automatically capitalize the first letter and add the right punctuation at the end of your messages. Keep your chats clean and professional effortlessly.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
#170 #338 #647
