### ISSUE TITLE
Confirm Server Invites.

### ISSUE THREAD

**Issue by Acrohh** [Vencord/plugin-requests#99]
### Plugin Description

When right clicking someone's profile on the sever list, there is a funny button called "Invite to Server >" which is surprisingly easy to miss click, this is awkward for you, and annoying for the person receiving the invite, especially if its someone you dont know.
If there is anyway to make you confirm the invite via this method, that would be greatly appreciated.
~~I'd prefer not to send a friend my hentai stash again.~~

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MadelineMaid** [comment]
This doesn’t need to be a plugin, as this can EASILY be accomplished via QuickCSS.
