### ISSUE TITLE
ShowHiddenThings minor addition

### ISSUE THREAD

**Issue by aloshTM** [Vencord/plugin-requests#993]
### Plugin Description

When opening a user in Mod View using ShowHiddenThings, their username/display name/profile picture should be clickable to open up their discord profile. 

**I know it kinda defeats the purpose** as you can just find their profile manually but it would be a nice and quick shortcut

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
out of scope of the plugin. it merely unlocks it. the mod view ui is by discord.
