### ISSUE TITLE
Extended Volume Sliders Compatible with Vesktop/Discord Web

### ISSUE THREAD

**Issue by solonovamax** [Vencord/plugin-requests#995]
### Plugin Description

A plugin that allows you to increase the volume of users past 100%, **which is compatible with vesktop.**

Currently, discord does not allow you to increase the volume of a user past 100%. This is annoying in cases where you're talking with someone who is very quiet and cannot hear them.

It would be nice to have a plugin that instead makes it so you can increase the volume up to, say, 300%.

This is similar to #931 and #815.

### Existing Plugin for other mod

There is currently a plugin compatible only with the desktop version of discord but not vesktop/discord web.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by 6c0-o** [comment]
https://github.com/Vendicated/Vencord/tree/main/src/plugins/volumeBooster.discordDesktop

You can increase up to 1000%
![image](https://github.com/user-attachments/assets/5b5a03ac-ae59-4bd0-a5bc-ba1265e57c83)

**Comment by solonovamax** [comment]
huh, I searched for it and didn't see it?? gimme a few mins to search again

**Comment by Scyye** [comment]
no need to search again, they linked it.

**Comment by Vendicated** [comment]
alresdy tracked in other places and in the works
