### ISSUE TITLE
Custom Discord Sounds

### ISSUE THREAD

**Issue by mmdanda** [Vencord/plugin-requests#997]
### Plugin Description

Pretty simple, a plugin that can change your discord sounds to something custom from your computer

E.G: making your discord call sound be the Brooklyn 99 intro theme, making your notification sound a kirby sound effect, making the open discord sound effect a vine boom, etc.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/NotificationSounds

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment]
I genuinely lost count of the duplicates for this 😔
